import type { Concept } from "../types"

export const clientlibsAdvancedConcepts: Concept[] = [
  {
    id: "tmpl-089",
    category: "Client Libraries — Advanced Features",
    title: "HTL, via the helper template at libs/granite/sightly/templates/clientlib.html — the only method current AEMaaCS docs describe",
    reference: "How are client libraries loaded in AEM as a Cloud Service?",
    explanation:
      "In AEM as a Cloud Service, client libraries are loaded through HTL, using the helper template at libs/granite/sightly/templates/clientlib.html, accessed via data-sly-use and invoked with data-sly-call, passing the desired categories. Current Cloud Service documentation only covers this approach.",
  },
  {
    id: "tmpl-090",
    category: "Client Libraries — Advanced Features",
    title: "data-sly-use.clientlib=\"libs/granite/sightly/templates/clientlib.html\", then data-sly-call passing categories",
    reference: "What is the HTL syntax pattern for loading a client library by category?",
    explanation:
      "The pattern is: use data-sly-use to instantiate the clientlib helper template, then data-sly-call to invoke it (e.g. clientlib.css or clientlib.all), passing the desired categories as an array or comma-separated string.",
  },
  {
    id: "tmpl-091",
    category: "Client Libraries — Advanced Features",
    title: "It's a legacy, on-premise-era pattern — current AEMaaCS Cloud Service documentation doesn't reference it, and cloud component scripting is HTL-only",
    reference: "Is the older JSP taglib approach (ui:includeClientLib) still a current, valid way to load clientlibs in AEMaaCS?",
    explanation:
      "The JSP taglib pattern using ui:includeClientLib is legacy, historical context from on-premise AEM. AEM as a Cloud Service component development is HTL-only, and the current Cloud Service documentation for client libraries doesn't reference the JSP approach at all.",
  },
  {
    id: "tmpl-092",
    category: "Client Libraries — Advanced Features",
    title: "A String[] property listing the categories of other client library folders that the current one depends on",
    reference: "What does the dependencies property on a cq:ClientLibraryFolder node do?",
    explanation:
      "The dependencies property is a String[] listing other client library categories that the current library folder depends on — useful when code in one folder requires a file in another to function properly.",
  },
  {
    id: "tmpl-093",
    category: "Client Libraries — Advanced Features",
    title: "It generates HTML that includes a link to your library file as well as links to its declared dependencies",
    reference: "What effect does the dependencies property have on the HTML generated by ui:includeClientLib (or its HTL equivalent)?",
    explanation:
      "When you link a client library folder that declares dependencies, the generated HTML includes a link to your generated library file as well as links to its dependencies, ensuring all required resources load together.",
  },
  {
    id: "tmpl-094",
    category: "Client Libraries — Advanced Features",
    title: "The embedding library's generated JS/CSS files include the code from the embedded library at runtime",
    reference: "What does the embed property on a client library folder do?",
    explanation:
      "The embed property lets you embed code from one client library into another — at runtime, the generated JS and CSS files of the embedding library will include the code from the embedded library.",
  },
  {
    id: "tmpl-095",
    category: "Client Libraries — Advanced Features",
    title: "Creating a client library folder under /etc that embeds the library located under /apps",
    reference: "How do you expose an /apps-restricted client library to visitors while keeping /apps access-restricted?",
    explanation:
      "To keep /apps restricted from website visitors while still delivering its client library code, you create a client library folder under /etc that embeds the /apps client library, using the embed property with the value of the target's categories property.",
  },
  {
    id: "tmpl-096",
    category: "Client Libraries — Advanced Features",
    title: "It combines all necessary client library code into a single file, reducing the number of <script> requests during page load",
    reference: "How does embedding help minimize requests on a page with many client libraries?",
    explanation:
      "Embedding lets you combine all necessary client library code into a single file via the embed property, consolidating multiple libraries and reducing the number of separate requests made during page load.",
  },
  {
    id: "tmpl-097",
    category: "Client Libraries — Advanced Features",
    title: "Relative to the embedding library's location, not the original embedded library's location",
    reference: "When CSS is embedded from one client library into another, how are relative resource paths (like background images) resolved?",
    explanation:
      "When you embed CSS files from one client library into another, the generated CSS code contains paths relative to the embedding library's location, not the original library's — so a rule like background: url(images/bg.jpg) resolves relative to where the embedding library lives.",
  },
  {
    id: "tmpl-098",
    category: "Client Libraries — Advanced Features",
    title: "Append ?debugClientLibs=true to the URL — it shows @import statements instead of the merged, embedded code",
    reference: "How do you inspect exactly which files are being embedded at runtime in a client library?",
    explanation:
      "Enable debug mode by appending ?debugClientLibs=true to the page URL. This displays the names of embedded files as @import statements in the generated library, instead of the actual embedded code, letting you verify dependencies.",
  },
  {
    id: "tmpl-099",
    category: "Client Libraries — Advanced Features",
    title: "YUI Compressor is the default; Google Closure Compiler (GCC) for JavaScript is available as a pluggable alternative",
    reference: "What are AEM's built-in CSS/JS preprocessors, and which is the default?",
    explanation:
      "AEM ships with built-in support for YUI Compressor (CSS and JavaScript) and Google Closure Compiler (JavaScript), with YUI set as the default preprocessor. Preprocessors can be configured per-library or system-wide.",
  },
  {
    id: "tmpl-100",
    category: "Client Libraries — Advanced Features",
    title: "The /libs/cq/granite/components/dumplibs/dumplibs component, via the dumplibs.html/.test.html URLs",
    reference: "What tool lets you discover all client library folders and preview the generated output for a category?",
    explanation:
      "The /libs/cq/granite/components/dumplibs/dumplibs component generates a page listing all client library folders, their categories and dependencies, accessible at dumplibs.html (with a Test Output page for previewing generated code per category).",
  },
]
