import type { Concept } from "../types"

export const jcrRepositoryConcepts: Concept[] = [
  {
    id: "intro-017",
    category: "JCR Repository",
    title: "Java Content Repository",
    reference: "What does JCR stand for in the AEM technology stack?",
    explanation:
      "JCR stands for Java Content Repository. It is a standardized API (defined by JSR-170 and JSR-283) for storing and accessing content in a hierarchical, tree-structured repository. AEM uses Apache Jackrabbit Oak as its JCR implementation.",
  },
  {
    id: "intro-018",
    category: "JCR Repository",
    title: "The JCR implementation used by AEM as its content repository",
    reference: "What is Apache Jackrabbit Oak in relation to AEM?",
    explanation:
      "Apache Jackrabbit Oak is the specific open-source implementation of the Java Content Repository (JCR) specification used by AEM. It provides hierarchical content storage with support for versioning, access control, and full-text search.",
  },
  {
    id: "intro-019",
    category: "JCR Repository",
    title: "Under /content in the JCR tree",
    reference: "Where is AEM page content stored in the JCR repository?",
    explanation:
      "AEM page content is stored under /content in the JCR repository. For example, a page at /content/mysite/en/home. Other important paths: /apps (application code), /libs (AEM core), /conf (configurations), /var (variable data).",
  },
  {
    id: "intro-020",
    category: "JCR Repository",
    title: "/apps",
    reference: "What JCR path stores AEM application code such as components and templates?",
    explanation:
      "Custom application code including components, templates, OSGi configurations, and scripts is stored under /apps. The /libs path contains AEM's own core code, which should not be modified — instead override by creating overlays under /apps.",
  },
  {
    id: "intro-021",
    category: "JCR Repository",
    title: "Representing an AEM page node in the content repository",
    reference: "What is the node type 'cq:Page' used for in the JCR?",
    explanation:
      "cq:Page is the JCR primary node type used for AEM pages. A page node typically has a child node jcr:content (of type cq:PageContent) that holds the page's actual properties and content.",
  },
  {
    id: "intro-022",
    category: "JCR Repository",
    title: "The special child node under a page that holds the actual content properties",
    reference: "What is a 'jcr:content' node in AEM?",
    explanation:
      "The jcr:content node is a standard child node of AEM page (cq:Page) nodes. It holds the actual content properties of the page, such as jcr:title, sling:resourceType (the template), and all the component instances placed on the page.",
  },
  {
    id: "intro-023",
    category: "JCR Repository",
    title: "nt:unstructured",
    reference: "What node type is used for flexible nodes without structural constraints in JCR?",
    explanation:
      "nt:unstructured is a JCR node type that imposes no constraints — any property or child node can be added. It is commonly used for component content storage under jcr:content nodes because AEM components often store varied properties.",
  },
  {
    id: "intro-024",
    category: "JCR Repository",
    title: "Storing configurations such as editable template definitions and content policies",
    reference: "In the JCR, what is the path '/conf' used for?",
    explanation:
      "The /conf path stores configuration data in AEM, particularly editable template definitions (/conf/<site>/settings/wcm/templates), content policies, and cloud service configurations. It replaced the older /etc path for many configurations.",
  },
  {
    id: "intro-025",
    category: "JCR Repository",
    title: "JCR-SQL2",
    reference: "What AEM query language uses SQL-like syntax for JCR queries?",
    explanation:
      "JCR-SQL2 is the SQL-like query language for querying the JCR content repository, defined in the JSR-283 specification. AEM also supports XPath queries. Example: SELECT * FROM [cq:Page] WHERE ISDESCENDANTNODE('/content/mysite').",
  },
  {
    id: "intro-026",
    category: "JCR Repository",
    title: "Storing variable, runtime-generated data like workflow instances and reports",
    reference: "What is the purpose of the '/var' path in the AEM JCR repository?",
    explanation:
      "The /var path stores variable, runtime-generated data in AEM, including workflow instances, audit logs, replication queue data, package manager data, and reports. Unlike /content or /apps, /var data is generated by AEM at runtime.",
  },
  {
    id: "intro-027",
    category: "JCR Repository",
    title: "A digital asset stored in the AEM DAM (Digital Asset Manager)",
    reference: "What does the 'dam:Asset' node type represent in the JCR?",
    explanation:
      "dam:Asset is the JCR node type for digital assets stored in the AEM DAM. Assets are typically stored under /content/dam and include images, videos, PDFs, and other binary files, each with metadata stored in their jcr:content child.",
  },
  {
    id: "intro-028",
    category: "JCR Repository",
    title: "Under /home in the JCR repository",
    reference: "Where are user and group definitions stored in the AEM JCR?",
    explanation:
      "User and group definitions are stored under /home in the JCR. Specifically, users are at /home/users/<path> and groups at /home/groups/<path>. This is managed by AEM's User Administration module backed by Apache Oak.",
  },
]
