import type { TriviaQuestion } from "./trivia-types"

export const componentsQuestionsPartB: TriviaQuestion[] = [
  {
    id: "comp-051",
    topic: "Sling Models Fundamentals",
    question: "What are Sling Models in AEM?",
    correctAnswers: [
      "Annotation-driven Java POJOs mapped automatically from Sling objects",
      "Annotation-based Java POJOs that map from Sling resources or requests",
      "Java POJOs automatically mapped from Sling objects through annotations",
      "Annotation-driven POJOs used to map Sling objects like resources and requests",
    ],
    incorrectAnswers: [
      "Granite UI dialogs stored under /libs",
      "Dispatcher rules for cache invalidation",
      "OSGi bundles used only for replication",
      "JCR node types that replace cq:Component",
      "Workflow launchers for content approval",
      "Client library categories for authoring UI",
      "SAML handlers for external identity providers",
      "Cloud Manager pipeline definitions",
    ],
    explanation:
      "The speech defines Sling Models as annotation-driven Java POJOs mapped automatically from Sling objects such as resources and requests, and notes that they can also receive OSGi services.",
  },
  {
    id: "comp-052",
    topic: "Sling Models Fundamentals",
    question: "According to the speech, what is the recommended way to implement component logic in AEM?",
    correctAnswers: [
      "Use Sling Models to implement component logic",
      "Implement component logic with Sling Models",
      "Sling Models are the recommended approach for component logic",
      "Component logic should be implemented in Sling Models",
    ],
    incorrectAnswers: [
      "Put all logic directly in HTL expressions",
      "Implement component logic inside Dispatcher configs",
      "Write component logic only in client-side JavaScript",
      "Use cq:dialog nodes as the main logic layer",
      "Store component logic in content policies",
      "Embed all logic in Cloud Manager variables",
      "Implement component logic only in servlets",
      "Move component logic into editable templates",
    ],
    explanation:
      "The speech explicitly says Sling Models are the recommended way to implement component logic.",
  },
  {
    id: "comp-053",
    topic: "Sling Models Fundamentals",
    question: "Given a scenario where a model only needs resource data and no request-specific bindings, which adaptable does Adobe advise using where possible?",
    correctAnswers: [
      "Resource",
      "Use Resource as the adaptable where possible",
      "Prefer Resource as the adaptable",
      "The adaptable should be Resource when request-specific injectors are not needed",
    ],
    incorrectAnswers: [
      "SlingHttpServletResponse",
      "PageManager",
      "ValueMap",
      "Session",
      "ServletResolver",
      "ComponentContext",
      "TagManager",
      "Designer",
    ],
    explanation:
      "The speech says the common adaptables are Resource and SlingHttpServletRequest, and Adobe advises using Resource where possible because the model can then be used inside and outside a request context.",
  },
  {
    id: "comp-054",
    topic: "Sling Models Fundamentals",
    question: "When must the adaptable be SlingHttpServletRequest instead of Resource?",
    correctAnswers: [
      "When the model uses injectors that need the request, such as request attributes or script bindings",
      "Use SlingHttpServletRequest when request-specific injectors are required",
      "If you need request attributes or script bindings, the adaptable must be the request",
      "Request-based injectors require SlingHttpServletRequest as the adaptable",
    ],
    incorrectAnswers: [
      "When the model reads only ValueMap properties",
      "When the model is exported only to XML",
      "When the component has no dialog",
      "When the bundle lacks the Sling-Model-Packages header",
      "When the model implements ComponentExporter",
      "When the resource is stored under /conf",
      "When the servlet is path-bound",
      "When the page uses editable templates",
    ],
    explanation:
      "The speech states that if you use injectors needing the request, such as request attributes or script bindings, the adaptable must be SlingHttpServletRequest.",
  },
  {
    id: "comp-055",
    topic: "Sling Models Fundamentals",
    question: "How are Sling Models registered so AEM can discover them?",
    correctAnswers: [
      "Through the Sling-Model-Packages or Sling-Model-Classes manifest headers",
      "By manifest headers such as Sling-Model-Packages or Sling-Model-Classes",
      "They are registered using Sling Models manifest headers generated at build time",
      "AEM discovers them through Sling-Model-Packages or Sling-Model-Classes",
    ],
    incorrectAnswers: [
      "Through Dispatcher farm files",
      "By adding entries to cq:dialog",
      "Through Cloud Manager environment variables only",
      "By creating nodes under /content/models",
      "Through editable template policies",
      "By publishing them to CRX package manager",
      "Through Granite UI showhide attributes",
      "By registering them in Apache Felix Web Console manually",
    ],
    explanation:
      "The speech says models are registered through the Sling-Model-Packages header or the Sling-Model-Classes header, and that the Sling Models bnd plugin generates those headers at build time.",
  },
  {
    id: "comp-056",
    topic: "Sling Models Fundamentals",
    question: "What is the difference between using adaptTo and using the ModelFactory service to obtain a model?",
    correctAnswers: [
      "adaptTo returns null on failure, while ModelFactory.createModel throws an explanatory exception",
      "adaptTo fails with null, but ModelFactory.createModel throws an exception explaining the failure",
      "ModelFactory.createModel gives an exception instead of the null returned by adaptTo",
      "If instantiation fails, adaptTo returns null whereas ModelFactory.createModel throws",
    ],
    incorrectAnswers: [
      "adaptTo always throws checked exceptions, while ModelFactory returns false",
      "Both methods always return a default empty model on failure",
      "ModelFactory works only for dialogs, not Sling Models",
      "adaptTo requires OSGi configuration, while ModelFactory does not",
      "ModelFactory can only adapt requests, never resources",
      "adaptTo is for Publish only, and ModelFactory is for Author only",
      "ModelFactory returns JSON instead of Java objects",
      "adaptTo can instantiate only interfaces, never classes",
    ],
    explanation:
      "The speech explains that client code commonly uses adaptTo, which returns null if adaptation cannot be made, while the ModelFactory OSGi service offers createModel, which throws an exception explaining the failure.",
  },
  {
    id: "comp-057",
    topic: "Sling Models Fundamentals",
    question: "Given a model with required injection by default, what happens if one required injection fails and the field was not marked optional?",
    correctAnswers: [
      "The model cannot be instantiated and adaptTo returns null",
      "Instantiation fails, so adaptTo returns null",
      "The model is not created because required injection failed",
      "A required injection failure prevents model creation and causes adaptTo to return null",
    ],
    incorrectAnswers: [
      "AEM silently writes an empty string to the field and continues",
      "The failed field is automatically populated from cq:dialog defaults",
      "The model is created and the field is always set to the string 'undefined'",
      "AEM converts the model into a path-bound servlet instead",
      "The model becomes an OSGi service automatically",
      "The request is retried with SlingHttpServletResponse as adaptable",
      "The field is read from the Style System policy",
      "The component switches to JSP rendering",
    ],
    explanation:
      "The speech says the default injection strategy is required, so if an injection fails the model cannot be instantiated and adaptTo returns null. Marking a field optional allows creation with a null or default value.",
  },
  {
    id: "comp-058",
    topic: "Sling Models Injectors",
    question: "Which annotation injects a property from the resource's ValueMap?",
    correctAnswers: [
      "@ValueMapValue",
      "Use @ValueMapValue",
      "The correct injector annotation is @ValueMapValue",
      "@ValueMapValue injects a property from the resource's ValueMap",
    ],
    incorrectAnswers: [
      "@ChildResource",
      "@RequestAttribute",
      "@ScriptVariable",
      "@OSGiService",
      "@SlingObject",
      "@Via",
      "@PostConstruct",
      "@Exporter",
    ],
    explanation:
      "The speech explicitly says @ValueMapValue injects a property from the resource's ValueMap.",
  },
  {
    id: "comp-059",
    topic: "Sling Models Injectors",
    question: "Which annotation injects a child resource or a list of child resources?",
    correctAnswers: [
      "@ChildResource",
      "Use @ChildResource",
      "The injector for a child resource or list of child resources is @ChildResource",
      "@ChildResource injects child resources",
    ],
    incorrectAnswers: [
      "@ValueMapValue",
      "@Named",
      "@Default",
      "@OSGiService",
      "@SlingObject",
      "@ScriptVariable",
      "@Self",
      "@Exporter",
    ],
    explanation:
      "The speech states that @ChildResource injects a child resource or a list of child resources.",
  },
  {
    id: "comp-060",
    topic: "Sling Models Injectors",
    question: "Given a scenario where a model needs currentPage or properties from HTL bindings, which annotation is used and what adaptable is required?",
    correctAnswers: [
      "@ScriptVariable, and the adaptable must be the request",
      "Use @ScriptVariable and adapt from SlingHttpServletRequest",
      "@ScriptVariable injects script bindings, so the model needs the request as adaptable",
      "The answer is @ScriptVariable with a request adaptable",
    ],
    incorrectAnswers: [
      "@ValueMapValue with a ResourceResolver adaptable",
      "@ChildResource with a Session adaptable",
      "@OSGiService with a ValueMap adaptable",
      "@Named with a Page adaptable",
      "@Default with a Resource adaptable",
      "@Exporter with a SlingHttpServletResponse adaptable",
      "@PostConstruct with a TagManager adaptable",
      "@Inject with a Dialog adaptable only",
    ],
    explanation:
      "The speech says @ScriptVariable injects an HTL and scripting binding such as currentPage, resource, or properties, and that it needs the request as adaptable.",
  },
  {
    id: "comp-061",
    topic: "Sling Models Injectors",
    question: "Which annotation injects Sling objects such as the ResourceResolver, Resource, request, or response?",
    correctAnswers: [
      "@SlingObject",
      "Use @SlingObject",
      "The injector for Sling objects like ResourceResolver or request is @SlingObject",
      "@SlingObject injects Sling objects",
    ],
    incorrectAnswers: [
      "@RequestAttribute",
      "@Named",
      "@JsonProperty",
      "@Designate",
      "@ValueMapValue",
      "@Default",
      "@ChildResource",
      "@Exporter",
    ],
    explanation:
      "The speech lists @SlingObject as the injector for Sling objects like the ResourceResolver, the Resource, or the request and response.",
  },
  {
    id: "comp-062",
    topic: "Sling Models Injectors",
    question: "Which annotation injects an OSGi service into a Sling Model?",
    correctAnswers: [
      "@OSGiService",
      "Use @OSGiService",
      "The injector annotation for an OSGi service is @OSGiService",
      "@OSGiService injects an OSGi service",
    ],
    incorrectAnswers: [
      "@Reference",
      "@Exporter",
      "@ScriptVariable",
      "@JsonIgnore",
      "@Named",
      "@RequestAttribute",
      "@ChildResource",
      "@Via",
    ],
    explanation:
      "The speech explicitly says @OSGiService injects an OSGi service.",
  },
  {
    id: "comp-063",
    topic: "Sling Models Injectors",
    question: "What does the @Via annotation do in Sling Models?",
    correctAnswers: [
      "It changes the object from which the value is read",
      "@Via changes the source object used for reading the value",
      "It tells Sling Models to read from a different object, such as the resource or resource super type",
      "The purpose of @Via is to switch where the injected value comes from",
    ],
    incorrectAnswers: [
      "It marks a method to run after injection completes",
      "It renames a JSON property in the exporter",
      "It registers the model in the bundle manifest",
      "It makes every injection optional automatically",
      "It converts a model into a servlet endpoint",
      "It hides a Granite UI field conditionally",
      "It writes values back into the JCR repository",
      "It enables path-bound servlet access control",
    ],
    explanation:
      "The speech says @Via changes the object from which the value is read, for example @Via(\"resource\") or @Via(type = ResourceSuperType.class).",
  },
  {
    id: "comp-064",
    topic: "Sling Models Injectors",
    question: "Why does the speech discourage using the generic @Inject annotation when a specific injector annotation exists?",
    correctAnswers: [
      "Because specific annotations are faster, clearer, and fix which injector is used",
      "Use the specific annotation because it is faster and clearer than generic @Inject",
      "The speech discourages @Inject since specific injectors make the chosen injector explicit",
      "Specific injector annotations are preferred because they are faster, clearer, and deterministic",
    ],
    incorrectAnswers: [
      "Because @Inject works only on Publish and not on Author",
      "Because @Inject can inject only JSON exporters",
      "Because @Inject is supported only in JSP components",
      "Because @Inject forces all fields to be path-bound servlets",
      "Because @Inject disables resource adaptation entirely",
      "Because @Inject always writes values back to the repository",
      "Because @Inject requires manual registration in /libs",
      "Because @Inject can be used only inside OSGi services, never models",
    ],
    explanation:
      "The speech says @Inject is the generic annotation and is discouraged because the specific annotations are faster and clearer, and they fix which injector is used.",
  },
  {
    id: "comp-065",
    topic: "Sling Models Injectors",
    question: "In an interface-only model, what is true according to the speech?",
    correctAnswers: [
      "Sling Models creates interface-only models with dynamic proxies, and default interface methods are not executed",
      "Interface-only models use method injection via dynamic proxies, and default methods do not run",
      "Sling Models backs interface-only models with dynamic proxies, so default interface methods are not executed",
      "The speech says interface-only models are proxied and their default methods are not executed",
    ],
    incorrectAnswers: [
      "They require constructor injection only",
      "They can be registered only with Sling-Model-Classes, never Sling-Model-Packages",
      "They always execute Java default methods before field injection",
      "They can adapt only from SlingHttpServletResponse",
      "They must extend Core Component implementation classes",
      "They can be exported only as XML",
      "They cannot use method-based injection",
      "They are supported only in Classic UI",
    ],
    explanation:
      "The speech says interface-only models use methods for injection, Sling Models creates them with dynamic proxies, and default interface methods are not executed.",
  },
  {
    id: "comp-066",
    topic: "Delegation & Model Interfaces",
    question: "Why must you never extend the Core Components' implementation classes directly?",
    correctAnswers: [
      "Because their implementation classes are private and can change",
      "Never extend them because the Core Components implement their models privately and those classes may change",
      "The implementations are private and unstable for inheritance, so you should not extend them",
      "You must avoid extending Core Component model implementations since they are private and can change",
    ],
    incorrectAnswers: [
      "Because they are stored only in /content policies",
      "Because extending them automatically disables HTL",
      "Because they are Classic UI widgets, not Java classes",
      "Because they can be inherited only by servlets",
      "Because Cloud Manager deletes subclasses during deployment",
      "Because they are path-bound resources instead of classes",
      "Because they are registered only through cq:dialog",
      "Because they require SlingAllMethodsServlet inheritance",
    ],
    explanation:
      "The speech says the Core Components implement their models privately. Because the implementation classes are private and can change, you must never extend them.",
  },
  {
    id: "comp-067",
    topic: "Delegation & Model Interfaces",
    question: "What pattern should you use to extend or customize a Core Component model?",
    correctAnswers: [
      "Use the delegation pattern",
      "The correct pattern is delegation",
      "Customize Core Component models through the delegation pattern",
      "You should extend behavior by delegating to the original model implementation",
    ],
    incorrectAnswers: [
      "Use JSP inheritance",
      "Use path-bound servlet chaining",
      "Use direct modification of /libs",
      "Use repository overlays under /content",
      "Use Classic UI design mode inheritance",
      "Use Dispatcher rewrite rules",
      "Use only cq:design_dialog overrides",
      "Use static utility classes instead of models",
    ],
    explanation:
      "The speech says you must never extend the private Core Component implementation classes and should use the delegation pattern instead.",
  },
  {
    id: "comp-068",
    topic: "Delegation & Model Interfaces",
    question: "In the Model Interfaces pattern, what does your custom model implement?",
    correctAnswers: [
      "The public Core Component model interface",
      "It implements the exposed public interface, such as the Title interface",
      "Your model should implement the Core Component's public interface",
      "The custom model implements the public model interface rather than the private implementation",
    ],
    incorrectAnswers: [
      "The private Core Component implementation class",
      "The ComponentExporter class only",
      "The cq:Component node type",
      "The Granite UI field interface",
      "The Sling Model bnd plugin interface",
      "The Page JSON serializer directly",
      "The Author run mode interface",
      "The resource super type annotation class",
    ],
    explanation:
      "The speech gives com.adobe.cq.wcm.core.components.models.Title as an example and says your own model implements that public interface.",
  },
  {
    id: "comp-069",
    topic: "Delegation & Model Interfaces",
    question: "What is the purpose of the adapters parameter in @Model for a proxy model implementation?",
    correctAnswers: [
      "It registers your class as an implementation of the interface",
      "The adapters parameter tells Sling Models that your class implements the public interface",
      "Its purpose is to register the model class as the interface implementation",
      "adapters binds the model to the exposed interface type",
    ],
    incorrectAnswers: [
      "It defines the JSON extension for the exporter",
      "It enables Sling Resource Merger for dialogs",
      "It changes the field name used by @ValueMapValue",
      "It creates the cq:design_dialog automatically",
      "It stores the model under /conf",
      "It makes all injections optional",
      "It grants servlet path permissions",
      "It selects the Cloud Manager environment",
    ],
    explanation:
      "The speech says that in @Model(... adapters = Title.class ...), the adapters parameter registers your class as an implementation of the interface.",
  },
  {
    id: "comp-070",
    topic: "Delegation & Model Interfaces",
    question: "What does the resourceType parameter do in a delegated proxy model?",
    correctAnswers: [
      "It binds the model to your proxy component's resource type",
      "The resourceType parameter associates the model with the proxy resource type",
      "It tells Sling Models which proxy component resource type should use the implementation",
      "resourceType binds the custom model to the proxy component",
    ],
    incorrectAnswers: [
      "It renames exported JSON properties",
      "It registers the service PID for OSGi configuration",
      "It turns the model into a design dialog",
      "It forces path-bound servlet resolution",
      "It hides inherited Granite tabs",
      "It enables POST handling in the model",
      "It creates a new run mode folder automatically",
      "It disables delegation to the parent model",
    ],
    explanation:
      "The speech says the resourceType parameter binds the model to your proxy component's resource type.",
  },
  {
    id: "comp-071",
    topic: "Delegation & Model Interfaces",
    question: "Given a scenario where you need the parent Core Component's model inside your proxy model, how does the speech say to inject it?",
    correctAnswers: [
      "Use @Self @Via(type = ResourceSuperType.class) on the interface field",
      "Inject the parent implementation with @Self and @Via(type = ResourceSuperType.class)",
      "The parent model is obtained through @Self @Via(type = ResourceSuperType.class)",
      "Use a field like @Self @Via(type = ResourceSuperType.class) private Title title",
    ],
    incorrectAnswers: [
      "Use @ValueMapValue on a String field named superType",
      "Use @SlingServletPaths on the model class",
      "Use @JsonProperty on the interface field",
      "Use @Designate on the proxy component",
      "Use @ChildResource on cq:dialog/items",
      "Use @Named(\"resourceSuperType\") on a servlet",
      "Use @PostConstruct on the interface type only",
      "Use @RequestAttribute on the policy node",
    ],
    explanation:
      "The speech gives the exact pattern: @Self @Via(type = ResourceSuperType.class) private Title title.",
  },
  {
    id: "comp-072",
    topic: "Delegation & Model Interfaces",
    question: "Because of resourceType binding, what happens when the Title interface is adapted for the proxy resource?",
    correctAnswers: [
      "Sling Models picks your implementation instead of the Core Component's",
      "The proxy resource resolves to your model implementation, not the Core Component implementation",
      "Your implementation is selected for the proxy resource because of the resourceType binding",
      "Adapting the interface for the proxy resource returns your model, which is the double binding behavior",
    ],
    incorrectAnswers: [
      "AEM always bypasses Sling Models and uses only HTL",
      "The Core Component implementation always wins, so proxy models are ignored",
      "The interface adaptation returns the cq:dialog node tree",
      "The adaptation works only on Author and never on Publish",
      "AEM converts the model into JSON automatically without an exporter",
      "The resource is rebound to /libs at runtime",
      "The proxy component can no longer use the Core Component HTL",
      "The request is forced to adapt to ResourceResolver instead",
    ],
    explanation:
      "The speech says that because of the resourceType binding, Sling Models picks your implementation for the proxy resource, not the Core Component's. It calls this double binding in the Model Interfaces pattern.",
  },
  {
    id: "comp-073",
    topic: "Exporting Models as JSON",
    question: "How do you annotate a Sling Model so it can be exported as JSON?",
    correctAnswers: [
      "Add @Exporter(name = \"jackson\", extensions = \"json\")",
      "Use the Sling Model Exporter annotation @Exporter(name = \"jackson\", extensions = \"json\")",
      "Annotate the model with @Exporter using the jackson exporter and json extension",
      "The model needs @Exporter(name = \"jackson\", extensions = \"json\")",
    ],
    incorrectAnswers: [
      "Add @JsonExport(type = \"model\")",
      "Use @SlingServletPaths(path = \"/model.json\")",
      "Add @ComponentExporterOnly",
      "Use @Designate(ocd = JsonConfig.class)",
      "Add @ScriptVariable(name = \"json\")",
      "Use @ValueMapValue(extensions = \"json\")",
      "Add @PostConstruct(export = true)",
      "Use @Named(\"model.json\") on the class",
    ],
    explanation:
      "The speech says Sling Models can be exported as JSON with the Sling Model Exporter by annotating the model with @Exporter(name = \"jackson\", extensions = \"json\").",
  },
  {
    id: "comp-074",
    topic: "Exporting Models as JSON",
    question: "What request pattern returns the serialized Sling Model JSON for a resource?",
    correctAnswers: [
      "Request the resource with the .model.json selector and extension",
      "Use the .model.json selector and extension on the resource path",
      "The serialized model is returned from a URL ending in .model.json",
      "Requesting /path/to/resource.model.json returns the serialized model",
    ],
    incorrectAnswers: [
      "Request the resource with .dialog.html",
      "Call the resource with .export.xml",
      "Append .policy.css to the resource path",
      "Request the resource with .cfg.json",
      "Use only the .json extension with no selector",
      "Append /model/exporter/jackson to the path",
      "Request the path through /system/console/models",
      "Use .contentfragment.json for all Sling Models",
    ],
    explanation:
      "The speech says requesting the resource with the .model.json selector and extension returns the serialized model, such as /content/wknd/page/jcr:content/root/title.model.json.",
  },
  {
    id: "comp-075",
    topic: "Exporting Models as JSON",
    question: "Why do Core Components implement ComponentExporter and ContainerExporter?",
    correctAnswers: [
      "So components can be exported as part of the page JSON, which underpins SPA Editor and headless consumption",
      "Those interfaces allow Core Components to participate in page JSON export for SPA and headless use",
      "They let components be exported in the page model JSON used by SPA Editor and headless consumers",
      "ComponentExporter and ContainerExporter make page JSON export possible for Core Components",
    ],
    incorrectAnswers: [
      "So dialogs can inherit tabs through Sling Resource Merger",
      "So servlets can bind to repository paths",
      "So OSGi configurations can be stored under /apps",
      "So default interface methods execute in Sling Models",
      "So HTL can compile into JavaScript bundles",
      "So Dispatcher rules can be generated from components",
      "So cq:design_dialog nodes can become policies automatically",
      "So Cloud Manager can infer run modes from page content",
    ],
    explanation:
      "The speech says Core Components implement ComponentExporter and ContainerExporter so components can be exported as part of the page JSON. It adds that this is the base of the SPA editor and headless consumption of component content.",
  },
  {
    id: "comp-076",
    topic: "Exporting Models as JSON",
    question: "Which library does the Sling Model Exporter use according to the speech?",
    correctAnswers: [
      "Jackson",
      "It uses the Jackson library",
      "The exporter is based on Jackson",
      "JSON export uses Jackson",
    ],
    incorrectAnswers: [
      "Gson",
      "Granite UI",
      "JAXB",
      "Apache POI",
      "Sling Resource Merger",
      "Felix SCR annotations",
      "Dispatcher SDK",
      "Coral 3",
    ],
    explanation:
      "The speech explicitly says the exporter uses the Jackson library.",
  },
  {
    id: "comp-077",
    topic: "Exporting Models as JSON",
    question: "How do you exclude or rename properties in exported model JSON?",
    correctAnswers: [
      "Use @JsonIgnore to exclude properties and @JsonProperty to rename them",
      "@JsonIgnore hides a property, and @JsonProperty renames it",
      "Exclude with @JsonIgnore and rename with @JsonProperty",
      "The speech says to use Jackson annotations: @JsonIgnore for exclusion and @JsonProperty for renaming",
    ],
    incorrectAnswers: [
      "Use @ValueMapValue to exclude and @Named to rename",
      "Use @Via to exclude and @Self to rename",
      "Use sling:hideResource to exclude and sling:orderBefore to rename",
      "Use @Reference to exclude and @Designate to rename",
      "Use cq:dialog hidden fields to exclude and Granite UI labels to rename",
      "Use @SlingObject to exclude and @Exporter to rename",
      "Use path-bound servlet annotations to exclude and rename",
      "Use run mode folders to exclude and rename properties",
    ],
    explanation:
      "The speech says the exporter uses Jackson and specifically calls out @JsonIgnore for excluding properties and @JsonProperty for renaming them.",
  },
  {
    id: "comp-078",
    topic: "Exporting Models as JSON",
    question: "Given a scenario where a model is exported as part of the page model, what else does the speech say the model needs besides the exporter annotation?",
    correctAnswers: [
      "It needs the resourceType parameter and a ComponentExporter implementation",
      "For page model export, include resourceType and implement ComponentExporter",
      "The speech says page-model export requires resourceType plus ComponentExporter",
      "A page-exported model needs resourceType binding and ComponentExporter",
    ],
    incorrectAnswers: [
      "It needs only a cq:design_dialog and nothing else",
      "It needs a path-bound servlet registered to /model",
      "It needs @ObjectClassDefinition on the model",
      "It needs a config.publish folder beside the component",
      "It needs @SlingServletPaths and POST support",
      "It needs a multifield named ./model",
      "It needs @Reference on every getter method",
      "It needs the bundle to skip Sling-Model-Packages generation",
    ],
    explanation:
      "The speech says to remember that the model needs the resourceType parameter and the ComponentExporter implementation when it is exported with the page model.",
  },
  {
    id: "comp-079",
    topic: "Exporting Models as JSON",
    question: "When should you add an exporter to a Sling Model?",
    correctAnswers: [
      "Only when the data is consumed as JSON",
      "Add the exporter only if the model's data will be consumed as JSON",
      "A model used only for HTL needs no exporter; add one only for JSON consumption",
      "Use an exporter when the model must be consumed as JSON, not for HTL-only models",
    ],
    incorrectAnswers: [
      "Always add an exporter to every Sling Model",
      "Only add an exporter to models adapted from ResourceResolver",
      "Add an exporter whenever a design dialog exists",
      "Add an exporter only for POST servlets",
      "Add an exporter when the model has optional injection",
      "Add an exporter only for path-bound components",
      "Add an exporter to replace ComponentExporter",
      "Add an exporter whenever the model uses @PostConstruct",
    ],
    explanation:
      "The speech clearly says a model that is only for HTL needs no exporter, and that you add the exporter only when the data is consumed as JSON.",
  },
  {
    id: "comp-080",
    topic: "Component Dialogs",
    question: "What is the difference between cq:dialog and cq:design_dialog?",
    correctAnswers: [
      "cq:dialog is the edit dialog for page authors, while cq:design_dialog is the design dialog for template authors to set policies",
      "The edit dialog is cq:dialog, and the design dialog for policies is cq:design_dialog",
      "cq:dialog lets page authors set component content; cq:design_dialog lets template authors set policies",
      "cq:dialog is for content editing, whereas cq:design_dialog is for policy configuration",
    ],
    incorrectAnswers: [
      "cq:dialog is for Publish only, and cq:design_dialog is for Author only",
      "cq:dialog defines OSGi configurations, and cq:design_dialog defines servlets",
      "cq:dialog stores page JSON, and cq:design_dialog stores model exporters",
      "cq:dialog is a Classic UI dialog, and cq:design_dialog is a Dispatcher rule set",
      "cq:dialog is for Sling Models, and cq:design_dialog is for HTL scripts",
      "cq:dialog is for component code, and cq:design_dialog is for client libraries",
      "cq:dialog is a path-bound servlet registration, and cq:design_dialog is a resource type binding",
      "cq:dialog is for env vars, and cq:design_dialog is for secrets",
    ],
    explanation:
      "The speech says AEM components have two kinds of dialogs: the edit dialog named cq:dialog for page authors to set content, and the design dialog named cq:design_dialog for template authors to set policies.",
  },
  {
    id: "comp-081",
    topic: "Component Dialogs",
    question: "What UI framework and node type are used for these component dialogs?",
    correctAnswers: [
      "They are built with Granite UI, the Coral 3 based Touch UI framework, and stored as nt:unstructured nodes",
      "Dialogs use Granite UI on Coral 3 Touch UI and are stored as nt:unstructured",
      "The speech says component dialogs are Granite UI dialogs stored as nt:unstructured nodes",
      "AEM component dialogs are Granite UI/Coral 3 Touch UI structures of type nt:unstructured",
    ],
    incorrectAnswers: [
      "They are built with Classic UI ExtJS and stored as cq:Page nodes",
      "They use React and are stored as sling:Folder nodes",
      "They are JSP forms stored as oak:QueryIndexDefinition nodes",
      "They are Dispatcher configs stored as nt:file nodes",
      "They use Adobe I/O Runtime and are stored as rep:User nodes",
      "They are SPA Editor JSON files stored as dam:Asset nodes",
      "They are OSGi Metatype forms stored as cq:Component nodes",
      "They are GraphQL schemas stored as nt:hierarchyNode nodes",
    ],
    explanation:
      "The speech states that both dialogs are built with Granite UI, the Coral 3 based Touch UI framework, and both are stored as nodes of type nt:unstructured.",
  },
  {
    id: "comp-082",
    topic: "Component Dialogs",
    question: "In a Granite UI dialog field, what does the name property represent?",
    correctAnswers: [
      "The JCR property where the field value is saved",
      "It is the JCR property path used to store the field's value",
      "The name property tells AEM which JCR property receives the field value",
      "It identifies the repository property where the dialog writes the value",
    ],
    incorrectAnswers: [
      "The CSS class used by the Style System",
      "The servlet extension that handles the dialog",
      "The OSGi PID of the component",
      "The manifest header that registers the model",
      "The resource super type of the component",
      "The path to the client library category",
      "The policy name in ui.config",
      "The Dispatcher cache directory",
    ],
    explanation:
      "The speech says the name property of a field is the JCR property where the value is saved, for example ./jcr:title.",
  },
  {
    id: "comp-083",
    topic: "Component Dialogs",
    question: "What does the ./ prefix mean in a dialog field name like ./jcr:title?",
    correctAnswers: [
      "It means the property is relative to the component's content resource",
      "The ./ prefix makes the property path relative to the component content resource",
      "It indicates a relative path on the component's content resource",
      "In dialog field names, ./ means relative to the component content resource",
    ],
    incorrectAnswers: [
      "It means the field is stored under /libs",
      "It marks the property as an OSGi configuration value",
      "It targets the resource super type dialog automatically",
      "It sends the value to the page policy instead of content",
      "It indicates a path-bound servlet endpoint",
      "It stores the value only in memory for the request",
      "It creates a child resource list automatically",
      "It points to the component's client library folder",
    ],
    explanation:
      "The speech explicitly says the path prefix ./ means relative to the component's content resource.",
  },
  {
    id: "comp-084",
    topic: "Component Dialogs",
    question: "How are dialogs inherited and customized in proxy components?",
    correctAnswers: [
      "They are inherited through sling:resourceSuperType and merged with Sling Resource Merger",
      "Dialog inheritance comes from sling:resourceSuperType, and customization uses Sling Resource Merger",
      "A proxy merges its dialog with the parent dialog through Sling Resource Merger and resource super type inheritance",
      "The speech says dialogs inherit via sling:resourceSuperType and are customized through the Sling Resource Merger",
    ],
    incorrectAnswers: [
      "They are inherited only through Dispatcher farm inheritance",
      "They are copied from /libs into /content automatically",
      "They are merged only through Cloud Manager pipeline variables",
      "They are inherited by registering the same servlet path",
      "They are customized only through editable template policies, not dialogs",
      "They are inherited through the Sling-Model-Packages header",
      "They are merged only when @Exporter is present",
      "They are inherited through OSGi factory PID naming",
    ],
    explanation:
      "The speech says dialogs are inherited through sling:resourceSuperType and that the Sling Resource Merger lets a proxy merge its dialog with the parent's dialog.",
  },
  {
    id: "comp-085",
    topic: "Component Dialogs",
    question: "Given a scenario where you need to remove an inherited tab from a dialog, what should you do?",
    correctAnswers: [
      "Create a node with the same name and set sling:hideResource to true",
      "Hide the inherited tab by creating a same-named node with sling:hideResource = true",
      "To remove an inherited tab, add a matching node and set sling:hideResource true",
      "Use sling:hideResource on a same-name node to remove the inherited tab",
    ],
    incorrectAnswers: [
      "Delete the parent tab directly under /libs",
      "Rename the tab with @JsonProperty",
      "Add @Named(\"hide\") to the Sling Model",
      "Register a path-bound servlet for the tab name",
      "Move the tab into ui.config/config.publish",
      "Change the field name prefix from ./ to ../",
      "Add @PostConstruct to the dialog root node",
      "Remove the component's resourceType binding",
    ],
    explanation:
      "The speech says to remove an inherited tab, create a node with the same name and set the property sling:hideResource to true.",
  },
  {
    id: "comp-086",
    topic: "Component Dialogs",
    question: "What customization guideline does Adobe give for dialog inheritance below the tab item level?",
    correctAnswers: [
      "Replicate the parent structure only up to the tab item level and never touch structures below a tab item; hide the whole tab and add your own instead",
      "Do not edit below a tab item; hide the tab and add a replacement tab instead",
      "Keep compatibility by mirroring the parent structure to the tab item level and replacing entire tabs rather than editing inside them",
      "Adobe's guideline is to avoid touching structures below a tab item and replace whole tabs when needed",
    ],
    incorrectAnswers: [
      "Always edit the deepest inherited field nodes directly under the parent tab",
      "Flatten the parent dialog into a single fixedcolumns node and remove tabs",
      "Convert inherited tabs into OSGi configurations",
      "Replace the parent dialog with a path-bound servlet definition",
      "Store all custom fields under /apps/settings/wcm/policies only",
      "Remove sling:resourceSuperType before changing any inherited field",
      "Move all tab customizations into the model's @PostConstruct method",
      "Use default interface methods to override tab internals",
    ],
    explanation:
      "The speech says to replicate the parent dialog structure up to the tab item level and never touch structures below a tab item. Instead, hide the whole tab and add your own tab to stay compatible with Core Component updates.",
  },
  {
    id: "comp-087",
    topic: "OSGi Services & Configurations",
    question: "What role do OSGi services play in AEM according to the speech?",
    correctAnswers: [
      "They provide reusable logic, such as search or integrations with external systems",
      "OSGi services are reusable logic units for things like search and external integrations",
      "They encapsulate reusable logic that Sling Models can consume",
      "The speech describes OSGi services as reusable logic, for example search or external system integration",
    ],
    incorrectAnswers: [
      "They are the node type used for dialogs",
      "They are the only way to write HTL markup",
      "They define Granite UI field ordering",
      "They replace content policies in editable templates",
      "They are immutable copies of /libs components",
      "They are author-only servlet selectors",
      "They store CSS classes for the Style System",
      "They are the manifest headers for Sling Models",
    ],
    explanation:
      "The speech says AEM is built on OSGi and that services provide reusable logic, such as search or integration with external systems.",
  },
  {
    id: "comp-088",
    topic: "OSGi Services & Configurations",
    question: "How is a basic OSGi service class declared in the speech's example?",
    correctAnswers: [
      "As a class annotated with @Component(service = MyService.class) that implements an interface",
      "Use Declarative Services annotations and declare @Component(service = MyService.class) on a class implementing an interface",
      "The service is a class implementing an interface and annotated with @Component(service = MyService.class)",
      "Declare the service with DS annotations, specifically @Component(service = MyService.class), on the implementation class",
    ],
    incorrectAnswers: [
      "As a cq:dialog node with sling:resourceType fixedcolumns",
      "As a class annotated only with @Model(adaptables = Resource.class)",
      "As a servlet registered through @SlingServletPaths",
      "As a JSON file inside ui.apps/components",
      "As a client library category with embed dependencies",
      "As a content policy under /conf",
      "As a Sling Resource Merger overlay in /libs",
      "As a default method on a model interface",
    ],
    explanation:
      "The speech says a service is a class annotated with @Component(service = MyService.class), using Declarative Services annotations, and that it implements an interface.",
  },
  {
    id: "comp-089",
    topic: "OSGi Services & Configurations",
    question: "Which annotation is used to inject one OSGi service into another service?",
    correctAnswers: [
      "@Reference",
      "Use @Reference",
      "Services are injected with @Reference",
      "The Declarative Services injection annotation is @Reference",
    ],
    incorrectAnswers: [
      "@OSGiService",
      "@ValueMapValue",
      "@JsonIgnore",
      "@Via",
      "@PostConstruct",
      "@Named",
      "@Exporter",
      "@SlingServletResourceTypes",
    ],
    explanation:
      "The speech says services are injected with @Reference. It separately notes that Sling Models get services with @OSGiService.",
  },
  {
    id: "comp-090",
    topic: "OSGi Services & Configurations",
    question: "Given a configurable service, which annotations and method does the speech say to use for its OSGi configuration?",
    correctAnswers: [
      "Define @ObjectClassDefinition with @AttributeDefinition entries, add @Designate on the service, and receive the config in the @Activate method",
      "Use OSGi Metatype annotations: @ObjectClassDefinition, @AttributeDefinition, @Designate, and read config in @Activate",
      "A configurable service uses @ObjectClassDefinition and @AttributeDefinition on the config type, @Designate on the service, and @Activate to receive values",
      "The speech says to model config with OSGi Metatype annotations and consume it in @Activate",
    ],
    incorrectAnswers: [
      "Use only @Model and @Exporter on the service class",
      "Store config fields in cq:design_dialog and inject them with @ScriptVariable",
      "Use @SlingServletPaths and @PostConstruct to load configuration",
      "Use sling:hideResource and sling:orderBefore on ui.config files",
      "Use only @Reference on a ValueMap field",
      "Use path-bound servlet extensions to declare the PID",
      "Use @JsonProperty on the config interface instead of Metatype annotations",
      "Use a client library category named after the PID",
    ],
    explanation:
      "The speech says configurable services use OSGi Metatype annotations: define an @ObjectClassDefinition on an annotation type with @AttributeDefinition for each property, then add @Designate(ocd = Config.class) on the service and receive the config in @Activate.",
  },
  {
    id: "comp-091",
    topic: "OSGi Services & Configurations",
    question: "Where are OSGi configurations stored in an AEM project?",
    correctAnswers: [
      "As .cfg.json files in config folders of the ui.config module",
      "They belong in the repository as .cfg.json files under ui.config config folders",
      "Store configurations as .cfg.json files in ui.config",
      "The speech says OSGi configs are repository .cfg.json files inside ui.config run-mode folders",
    ],
    incorrectAnswers: [
      "As editable template policies under /conf only",
      "As Java constants inside Sling Models",
      "As servlet path registrations under /bin",
      "As nodes under /apps that authors edit in production",
      "As dialog fields saved below component content",
      "As Dispatcher YAML files in the frontend module",
      "As Cloud Manager pipeline variables only, with no repo files",
      "As client library .content.xml files",
    ],
    explanation:
      "The speech says configurations are stored as .cfg.json files in the repository in a config folder of ui.config.",
  },
  {
    id: "comp-092",
    topic: "OSGi Services & Configurations",
    question: "How should environment-specific values and secrets be referenced in AEM as a Cloud Service configurations?",
    correctAnswers: [
      "Use Cloud Manager environment variables with $[env:VARIABLE_NAME] and secrets with $[secret:SECRET_NAME], and never commit secrets to Git",
      "Reference environment variables as $[env:VARIABLE_NAME] and secrets as $[secret:SECRET_NAME]",
      "The speech says to use Cloud Manager env vars and secret placeholders instead of hard-coding values",
      "Environment-specific values should come from $[env:...] and secrets from $[secret:...], not from committed literals",
    ],
    incorrectAnswers: [
      "Hard-code them directly in Java classes for faster access",
      "Store all secrets in cq:dialog hidden fields",
      "Put secrets in /libs because /libs is immutable",
      "Save environment values only in content policies under /conf",
      "Register each secret as a path-bound servlet",
      "Expose secrets through .model.json and consume them in HTL",
      "Write secrets into client library categories",
      "Commit separate plaintext secret files into ui.apps",
    ],
    explanation:
      "The speech says secrets and environment-specific values should not be hard-coded. In AEM as a Cloud Service, use Cloud Manager environment variables referenced as $[env:VARIABLE_NAME] and secrets as $[secret:SECRET_NAME], and never commit secrets to Git.",
  },
  {
    id: "comp-093",
    topic: "OSGi Services & Configurations",
    question: "Why do configurations belong in code rather than being changed through the web console in a deployed AEM as a Cloud Service environment?",
    correctAnswers: [
      "Because AEM as a Cloud Service has an immutable /apps, so deployed environments cannot rely on web console config changes",
      "Configurations belong in code because /apps is immutable in AEM as a Cloud Service",
      "The speech says you cannot change deployed configuration through the web console since /apps is immutable",
      "In AEM as a Cloud Service, immutable /apps means configuration must be managed as code",
    ],
    incorrectAnswers: [
      "Because the web console exists only on Publish and not on Author",
      "Because OSGi configurations are stored only in /content",
      "Because Cloud Manager deletes every PID at startup",
      "Because Sling Models cannot read configured services",
      "Because Granite UI dialogs overwrite all OSGi settings automatically",
      "Because only Dispatcher can apply run modes in Cloud Service",
      "Because design dialogs replace OSGi configuration entirely",
      "Because resource type servlets cannot run with configured services",
    ],
    explanation:
      "The speech says that because AEM as a Cloud Service has an immutable /apps, you cannot change configuration through the web console in a deployed environment. Configurations belong in code.",
  },
  {
    id: "comp-094",
    topic: "Servlets, Style System & Best Practices",
    question: "Which servlet base class should you use for a read-only GET endpoint?",
    correctAnswers: [
      "SlingSafeMethodsServlet",
      "Use SlingSafeMethodsServlet for a read-only GET servlet",
      "A read-only GET servlet should extend SlingSafeMethodsServlet",
      "The speech says GET-only servlets extend SlingSafeMethodsServlet",
    ],
    incorrectAnswers: [
      "SlingAllMethodsServlet only",
      "ResourceResolverFactoryServlet",
      "GraniteFixedColumnsServlet",
      "ComponentExporterServlet",
      "ModelFactoryServlet",
      "TouchUIDialogServlet",
      "DispatcherSafeMethodsServlet",
      "ContainerExporterServlet",
    ],
    explanation:
      "The speech says servlets are OSGi components that extend SlingSafeMethodsServlet for read-only GET, or SlingAllMethodsServlet for GET and POST.",
  },
  {
    id: "comp-095",
    topic: "Servlets, Style System & Best Practices",
    question: "How does the speech say to register a servlet by resource type?",
    correctAnswers: [
      "Use @Component(service = Servlet.class) together with @SlingServletResourceTypes specifying resourceTypes, methods, and extensions",
      "Register it as an OSGi Servlet component and annotate it with @SlingServletResourceTypes",
      "The servlet should use @Component(service = Servlet.class) and @SlingServletResourceTypes(...)",
      "Resource-type servlet registration uses @Component plus @SlingServletResourceTypes",
    ],
    incorrectAnswers: [
      "Use only @SlingServletPaths with no OSGi component annotation",
      "Register it through cq:design_dialog and a Granite field",
      "Add it to Sling-Model-Packages in the bundle manifest",
      "Declare it in ui.config as a .cfg.json file",
      "Create a node under /content/servlets and let AEM scan it",
      "Annotate the HTL file with @SlingServletResourceTypes",
      "Use @ObjectClassDefinition on the servlet instead of @Component",
      "Register it by adding a client library category named servlet",
    ],
    explanation:
      "The speech provides the exact pattern: @Component(service = Servlet.class) and @SlingServletResourceTypes(resourceTypes = \"wknd/components/search\", methods = \"GET\", extensions = \"json\").",
  },
  {
    id: "comp-096",
    topic: "Servlets, Style System & Best Practices",
    question: "What is the recommended binding approach for Sling servlets in AEM?",
    correctAnswers: [
      "Bind servlets to resource types, not to paths",
      "Resource type binding is the best practice, not path binding",
      "The speech recommends resource-type servlets instead of path-bound servlets",
      "Servlets should be registered by resource type rather than by path",
    ],
    incorrectAnswers: [
      "Bind all servlets only to /bin paths",
      "Register every servlet through Dispatcher rules instead of annotations",
      "Bind servlets only to cq:dialog node names",
      "Use path binding for security and resource type binding only for development",
      "Bind servlets to Cloud Manager environment names",
      "Use Sling-Model-Packages for servlet routing",
      "Bind servlets to Style System policy names",
      "Use only POST path bindings for headless delivery",
    ],
    explanation:
      "The speech says the best practice is to bind servlets to resource types and not to paths.",
  },
  {
    id: "comp-097",
    topic: "Servlets, Style System & Best Practices",
    question: "Why are path-bound servlets discouraged according to the speech?",
    correctAnswers: [
      "Because they cannot be access-controlled through the repository and are harder to secure",
      "Path-bound servlets are discouraged since repository permissions cannot control them and they are harder to secure",
      "They are harder to secure because repository access control does not apply the same way as with resource-type binding",
      "The speech says path-bound servlets are discouraged due to weaker repository-based access control and security",
    ],
    incorrectAnswers: [
      "Because they can handle only POST and never GET",
      "Because they are incompatible with OSGi components",
      "Because they always require Classic UI dialogs",
      "Because they disable the Style System",
      "Because they can never return JSON",
      "Because they automatically modify /libs",
      "Because they are stored only in ui.config",
      "Because they force Sling Models to adapt from response objects",
    ],
    explanation:
      "The speech says path-bound servlets with @SlingServletPaths are discouraged because they cannot be access-controlled through the repository and are harder to secure.",
  },
  {
    id: "comp-098",
    topic: "Servlets, Style System & Best Practices",
    question: "What does the Style System let template authors do?",
    correctAnswers: [
      "Define CSS classes in a policy that content authors can apply to a component without code changes",
      "It lets template authors define policy-based CSS classes for content authors to apply",
      "The Style System provides policy-defined CSS classes that authors can apply without changing code",
      "Template authors can offer visual styles through policies instead of code changes",
    ],
    incorrectAnswers: [
      "Register GET servlets by path automatically",
      "Generate Sling Model manifest headers at build time",
      "Store OSGi secrets directly in content policies",
      "Replace Granite UI dialogs with React forms",
      "Execute default methods in interface-only models",
      "Bind models to resource super types without annotations",
      "Convert cq:dialog fields into Dispatcher filters",
      "Publish content directly from HTL files",
    ],
    explanation:
      "The speech says the Style System lets template authors define CSS classes in a policy that content authors then apply to a component, without any code change.",
  },
  {
    id: "comp-099",
    topic: "Servlets, Style System & Best Practices",
    question: "Given a scenario where authors need multiple visual variants of the same component, what does the speech recommend instead of creating many near-duplicate components?",
    correctAnswers: [
      "Prefer the Style System and configurable components over copies of nearly identical components",
      "Use the Style System rather than creating extra near-duplicate components",
      "Offer visual variants through the Style System instead of cloning components",
      "The recommended approach is to use styles and configurability instead of many similar component copies",
    ],
    incorrectAnswers: [
      "Create one new component for every CSS class variation",
      "Put all visual variants into separate path-bound servlets",
      "Duplicate the Core Component under /libs for each variant",
      "Encode each variant as an OSGi PID",
      "Store every variant in a separate Sling Model adaptable",
      "Replace the component with multiple editable templates",
      "Hard-code a variant switch in Cloud Manager environment variables",
      "Use only cq:design_dialog inheritance without policies or styles",
    ],
    explanation:
      "The speech says the Style System is a preferred way to offer visual variants rather than creating additional components, and summarizes that configurable components are preferred over copies of nearly identical ones.",
  },
  {
    id: "comp-100",
    topic: "Servlets, Style System & Best Practices",
    question: "Which best-practice summary matches the speech?",
    correctAnswers: [
      "Put logic in Sling Models and markup in HTL; use proxy components; never modify /libs; prefer specific injectors, Resource adaptables where possible, delegation, compatible dialogs, resource-type servlets, code-based config, and the Style System",
      "Use Sling Models for logic and HTL for markup, extend Core Components through proxy-plus-delegation, keep dialogs compatible, bind servlets to resource types, avoid hard-coded config, and prefer the Style System",
      "The speech's best practices are Sling Models for logic, HTL for markup, proxy components instead of versioned content targets, no /libs changes, specific injectors, Resource when possible, delegation, compatible dialogs, resource-type servlet binding, and configurable styling",
      "Follow the summary: logic in models, markup in HTL, proxies not versioned components, never /libs, specific injectors over @Inject, Resource adaptable when possible, delegation for Core Components, compatible dialogs, resource-type servlets, no hard-coded config, and styles over duplicates",
    ],
    incorrectAnswers: [
      "Put most logic in HTL, point content directly to versioned components, and modify /libs when customization is needed",
      "Use generic @Inject everywhere, prefer path-bound servlets, and hard-code environment values for reliability",
      "Duplicate Core Components for every style variant and keep model logic inside cq:design_dialog nodes",
      "Bind servlets to paths, avoid proxy components, and store secrets in Git so all environments stay in sync",
      "Use request adaptables exclusively, extend private Core Component implementations, and edit inherited dialog fields deep inside parent tabs",
      "Replace HTL with OSGi configs, expose all models as JSON by default, and manage production configuration from the web console",
      "Store component logic in policies, keep markup in servlets, and define visual variants by cloning components under /libs",
      "Prefer path-bound endpoints, Classic UI dialogs, and manual production config edits over code-based configuration",
    ],
    explanation:
      "The speech closes with a summary of best practices: keep logic in Sling Models and markup in HTL; use proxy components; never modify /libs; use specific injector annotations; use Resource as adaptable when possible; use model interfaces and delegation; keep dialogs structurally compatible; bind servlets to resource types; do not hard-code configuration; and prefer the Style System and configurable components over near-duplicate copies.",
  },
]
