import type { TriviaQuestion } from "./trivia-types"

export const dispatcherQuestionsPartA: TriviaQuestion[] = [

  // ── INTRODUCTION (8) ─────────────────────────────────────────────────────

  {
    id: "disp-001",
    topic: "Introduction",
    question: "This Dispatcher lesson maps mainly to which exam area, and about what percentage of the exam does it represent?",
    correctAnswers: [
      "This lesson maps to Configurations, about 15 percent of the exam",
      "It maps to the Configurations part of the exam at roughly 15%",
      "The main exam area is Configurations, which is about fifteen percent",
      "The speech says the lesson belongs to Configurations, around 15 percent of the exam",
    ],
    incorrectAnswers: [
      "This lesson maps to AEM Development, about 37 percent of the exam",
      "It maps to Build and Deployment, about 50 percent of the exam",
      "The main exam area is Authoring, which is about 15 percent",
      "It belongs to Security Administration, around 25 percent of the exam",
      "The lesson maps to Components, about 10 percent of the exam",
      "It maps to Workflows, around 30 percent of the exam",
      "The main exam area is Templates, which is about 20 percent",
      "It belongs to Content Fragments, about 5 percent of the exam",
    ],
    explanation:
      "The introduction says this lesson maps to the Configurations part of the exam, about 15 percent.",
  },
  {
    id: "disp-002",
    topic: "Introduction",
    question: "Besides Configurations, which two exam-support areas does the lesson explicitly say this topic helps with?",
    correctAnswers: [
      "The lesson also supports Build and Deployment and Analyzing and Debugging",
      "It supports Build and Deployment plus Analyzing and Debugging",
      "The two supporting areas are Build and Deployment and Analyzing and Debugging",
      "The speech says Dispatcher also supports Build and Deployment and Analyzing and Debugging",
    ],
    incorrectAnswers: [
      "The lesson also supports Authoring and Translation",
      "It supports Commerce Integration and SPA Editor",
      "The two supporting areas are MSM and Launches",
      "It supports Accessibility and Content Governance",
      "The speech says Dispatcher supports Forms and Assets Microservices",
      "The two supporting areas are User Administration and IMS setup",
      "It supports Editable Templates and Content Policies",
      "The speech says Dispatcher supports Sling Models and HTL",
    ],
    explanation:
      "The introduction states that this lesson supports Build and Deployment and Analyzing and Debugging.",
  },
  {
    id: "disp-003",
    topic: "Introduction",
    question: "What kind of exam questions does the speech tell you to expect for Dispatcher topics?",
    correctAnswers: [
      "Expect scenario questions such as why a page was not cached, which file holds a rule, and how cache invalidation works",
      "The speech says to expect scenario-based questions like why a page was not cached, where a rule lives, and how invalidation works",
      "You should expect scenarios about why a page missed cache, which file contains the rule, and how Dispatcher invalidates cache",
      "The lesson warns that Dispatcher questions are scenario questions about cache misses, rule locations, invalidation, and validation failures",
    ],
    incorrectAnswers: [
      "Expect only Java syntax questions about writing Sling Models",
      "Expect only authoring UI questions about page editor shortcuts",
      "Expect only memorization questions about package manager buttons",
      "Expect only OSGi PID naming questions with no scenarios",
      "Expect only network questions about SSL certificates",
      "Expect only repository compaction questions for TarMK",
      "Expect only fragment model questions unrelated to Dispatcher",
      "Expect only Cloud Manager pricing questions",
    ],
    explanation:
      "The introduction explicitly says to expect scenario questions such as why a page was not cached, which file holds a rule, how the cache is invalidated, and what fails validation.",
  },
  {
    id: "disp-004",
    topic: "Introduction",
    question: "In AEM as a Cloud Service, what path does traffic follow before it reaches the publish nodes?",
    correctAnswers: [
      "Traffic passes through the CDN to an Apache web server layer that supports Dispatcher before reaching publish",
      "In Cloud Service, requests go through the CDN and then the Apache web server layer with Dispatcher",
      "The speech says traffic reaches publish after passing through the CDN and the Apache layer that includes Dispatcher",
      "The request path is CDN first, then the Apache web server layer with Dispatcher, then publish nodes",
    ],
    incorrectAnswers: [
      "Traffic goes directly from the browser to publish, and Dispatcher runs only on author",
      "Requests pass through author first, then CDN, then publish",
      "Traffic reaches publish through Cloud Manager and then through workflow models",
      "The path is browser to dispatcher.any to author and then to publish",
      "Requests go first to a package manager endpoint and then to publish",
      "Traffic passes through the translation framework before the web server",
      "The path is CDN to author only, because publish does not receive internet traffic",
      "Requests must go through /system/console before entering publish",
    ],
    explanation:
      "The introduction says that in AEM as a Cloud Service, traffic passes through the CDN to an Apache web server layer that supports Dispatcher.",
  },
  {
    id: "disp-005",
    topic: "Introduction",
    question: "What is Dispatcher used for primarily in the architecture described by the speech?",
    correctAnswers: [
      "Dispatcher is used primarily as a cache to limit processing on the publish nodes",
      "Its primary role is caching so the publish instances do less processing",
      "The main use of Dispatcher is as a cache that reduces publish-node processing",
      "The speech says Dispatcher is primarily a cache for limiting work on publish nodes",
    ],
    incorrectAnswers: [
      "Dispatcher is used primarily as a workflow engine for publish nodes",
      "Its main role is storing content fragments in the repository",
      "Dispatcher is primarily a replication agent from author to publish",
      "The main use of Dispatcher is compiling client libraries on demand",
      "It is primarily an editable template manager for websites",
      "Dispatcher mainly replaces the CDN in Cloud Service",
      "Its primary role is creating users and groups for publish access",
      "Dispatcher is mainly an authoring dialog renderer",
    ],
    explanation:
      "The speech says Dispatcher is used primarily as a cache to limit processing on the publish nodes.",
  },
  {
    id: "disp-006",
    topic: "Introduction",
    question: "Why does the speech also describe Dispatcher as a security layer?",
    correctAnswers: [
      "Dispatcher is also a security layer because filters control which requests reach AEM",
      "It acts as a security layer since filter rules decide which requests can reach AEM",
      "The speech says Dispatcher provides security because its filters control access to AEM",
      "Dispatcher is described as a security layer because filters determine what reaches AEM",
    ],
    incorrectAnswers: [
      "Dispatcher is a security layer because it encrypts repository nodes at rest",
      "It provides security by replacing ACLs inside the JCR",
      "The speech says Dispatcher secures AEM by compiling Java code before requests run",
      "Dispatcher is a security layer because it turns every request into basic authentication",
      "It provides security by disabling all virtual hosts automatically",
      "Dispatcher secures AEM by converting pages into content fragments",
      "The speech says Dispatcher is secure because it blocks all GET requests by default",
      "Dispatcher is a security layer because it replicates permissions from author to CDN",
    ],
    explanation:
      "The introduction states that Dispatcher is also a security layer because filters control which requests reach AEM.",
  },
  {
    id: "disp-007",
    topic: "Introduction",
    question: "A mock exam asks, \"Why was this page not cached?\" Which section of the certification blueprint is this lesson said to reinforce beyond Configurations?",
    correctAnswers: [
      "That scenario also reinforces Analyzing and Debugging",
      "Questions like that support the Analyzing and Debugging area",
      "The speech says such cache-troubleshooting scenarios support Analyzing and Debugging",
      "Beyond Configurations, that style of question reinforces Analyzing and Debugging",
    ],
    incorrectAnswers: [
      "That scenario mainly reinforces Translation Rules",
      "Questions like that support only Content Fragment authoring",
      "The speech says it reinforces only Launches administration",
      "Beyond Configurations, it reinforces only Editable Templates",
      "That style of question belongs only to Assets processing",
      "Questions like that support only workflow participant steps",
      "The speech says it reinforces only package installation",
      "Beyond Configurations, it reinforces only IMS user mapping",
    ],
    explanation:
      "The introduction says this topic supports Analyzing and Debugging as well as Build and Deployment.",
  },
  {
    id: "disp-008",
    topic: "Introduction",
    question: "What content-delivery layer does the lesson say it is about when it shifts from components, Maven, workflows, and fragments?",
    correctAnswers: [
      "The lesson shifts to the Apache web server layer with the Dispatcher module and its caching",
      "It turns to the Apache web server layer, the Dispatcher module, and the caching around it",
      "The speech says the focus moves to the Apache layer with Dispatcher and cache behavior",
      "This lesson is about the Apache web server layer with Dispatcher and the cache surrounding it",
    ],
    incorrectAnswers: [
      "The lesson shifts to the page editor toolbar and authoring overlays",
      "It turns to the Granite UI widget library and dialog inheritance",
      "The speech says the focus moves to content fragment models and GraphQL schemas",
      "This lesson is about workflow inbox delegation and participant steps",
      "It turns to editable templates, style systems, and responsive grids",
      "The focus moves to package filters, Repo Init, and service users",
      "The lesson is about MSM blueprints and live copies",
      "It turns to Sling Models exporters and JSON serialization only",
    ],
    explanation:
      "The introduction says the lesson looks at how content is delivered: the Apache web server layer with Dispatcher and the caching around it.",
  },

  // ── DISPATCHER.ANY, FARMS AND INCLUDES (7) ───────────────────────────────

  {
    id: "disp-009",
    topic: "dispatcher.any, Farms and Includes",
    question: "What is the default text file name that stores the Dispatcher configuration?",
    correctAnswers: [
      "The default Dispatcher configuration file is named dispatcher.any",
      "Dispatcher configuration is stored by default in dispatcher.any",
      "The speech says the default file name is dispatcher.any",
      "By default, the Dispatcher config lives in a text file called dispatcher.any",
    ],
    incorrectAnswers: [
      "The default Dispatcher configuration file is named default.vhost",
      "Dispatcher configuration is stored by default in filters.any",
      "The speech says the default file name is renders.any",
      "By default, the config lives in a text file called cache.any",
      "The default Dispatcher configuration file is named httpd.conf",
      "Dispatcher configuration is stored by default in vanityUrls.html",
      "The speech says the default file name is dispatcher.yaml",
      "By default, the config lives in a text file called virtualhosts.any",
    ],
    explanation:
      "Section 2 says the Dispatcher configuration is stored by default in a text file named dispatcher.any.",
  },
  {
    id: "disp-010",
    topic: "dispatcher.any, Farms and Includes",
    question: "How are Dispatcher property names written in dispatcher.any?",
    correctAnswers: [
      "Dispatcher property names are prefixed with a forward slash",
      "Each property name starts with a forward slash",
      "The speech says property names use a leading slash",
      "In dispatcher.any, property names are written with a slash prefix",
    ],
    incorrectAnswers: [
      "Dispatcher property names are prefixed with a dollar sign",
      "Each property name starts with a hash symbol",
      "The speech says property names use XML attributes instead of slashes",
      "In dispatcher.any, property names are written in JSON keys with quotes only",
      "Dispatcher property names are prefixed with an at sign",
      "Each property name starts with a backslash",
      "The speech says property names use no prefix at all",
      "In dispatcher.any, property names are written only as YAML list items",
    ],
    explanation:
      "Section 2 says property names are prefixed with a forward slash.",
  },
  {
    id: "disp-011",
    topic: "dispatcher.any, Farms and Includes",
    question: "How are multi-valued properties represented in dispatcher.any?",
    correctAnswers: [
      "Multi-valued properties enclose their child items in braces",
      "Child items of a multi-valued property are placed inside braces",
      "The speech says multi-valued properties use braces around their children",
      "Dispatcher.any represents multi-valued properties with child items in braces",
    ],
    incorrectAnswers: [
      "Multi-valued properties must be written as comma-separated values on one line",
      "They are represented only as XML child tags",
      "The speech says multi-valued properties require square brackets only",
      "Dispatcher.any represents them as semicolon-delimited strings",
      "They must be stored in separate .json files",
      "Multi-valued properties are represented only with repeated comments",
      "The speech says they use parentheses around child items",
      "Dispatcher.any requires them to be encoded as query parameters",
    ],
    explanation:
      "Section 2 explains that multi-valued properties enclose their child items in braces.",
  },
  {
    id: "disp-012",
    topic: "dispatcher.any, Farms and Includes",
    question: "Which two top-level properties does the speech name in dispatcher.any?",
    correctAnswers: [
      "The top-level properties named are /name and /farms",
      "Dispatcher.any names /name and /farms at the top level",
      "The speech identifies /name and /farms as the top-level properties",
      "At the top level, the file uses /name and /farms",
    ],
    incorrectAnswers: [
      "The top-level properties named are /docroot and /rules",
      "Dispatcher.any names /filter and /cache at the top level only",
      "The speech identifies /hostname and /port as the top-level properties",
      "At the top level, the file uses /statfile and /invalidate",
      "The top-level properties named are /virtualhosts and /clientheaders only",
      "Dispatcher.any names /url and /delay at the top level",
      "The speech identifies /secure and /receiveTimeout as the top-level properties",
      "At the top level, the file uses /path and /selectors only",
    ],
    explanation:
      "Section 2 says the top-level properties are /name and /farms.",
  },
  {
    id: "disp-013",
    topic: "dispatcher.any, Farms and Includes",
    question: "When should you use a single farm instead of several farms?",
    correctAnswers: [
      "Use a single farm when all pages should be handled the same way",
      "A single farm is appropriate if all pages share the same Dispatcher behavior",
      "The speech says to use one farm when all pages are handled the same way",
      "Choose one farm if the whole site or URL set should follow the same behavior",
    ],
    incorrectAnswers: [
      "Use a single farm only when each area needs different behavior",
      "A single farm is required whenever virtual hosts differ by scheme",
      "The speech says to use one farm only for author instances",
      "Choose one farm if you want each site area to have different cache rules",
      "Use a single farm only when you need multiple document roots",
      "A single farm is appropriate only when no filters are defined",
      "The speech says one farm is mandatory for vanity URLs",
      "Choose one farm only to disable caching everywhere",
    ],
    explanation:
      "Section 2 says to use a single farm when all pages should be handled the same way.",
  },
  {
    id: "disp-014",
    topic: "dispatcher.any, Farms and Includes",
    question: "Why would you use several farms in a Dispatcher configuration?",
    correctAnswers: [
      "Use several farms when different sites or URL areas need different behavior",
      "Several farms are used when different sites or sections require different Dispatcher behavior",
      "The speech says multiple farms are for sites or URL groups that need different behavior",
      "Choose several farms if different areas need different rules or handling",
    ],
    incorrectAnswers: [
      "Use several farms only to define several publish ports for the same rule set",
      "Several farms are required whenever the cache is enabled",
      "The speech says multiple farms are only for authoring workflows",
      "Choose several farms only when you want one hostname and one URI",
      "Use several farms only to turn off virtual host matching",
      "Several farms are required for all Cloud Service environments",
      "The speech says multiple farms exist only to store client headers",
      "Choose several farms only when no includes are used",
    ],
    explanation:
      "Section 2 says to use several farms when different sites or areas need different behavior.",
  },
  {
    id: "disp-015",
    topic: "dispatcher.any, Farms and Includes",
    question: "How can a large Dispatcher configuration be split and made environment-aware?",
    correctAnswers: [
      "Use $include to split files, wildcards such as farm_*.any to include ranges, and ${variable_name} for environment variables",
      "The speech says large configs use $include, wildcard includes like farm_*.any, and environment variables in the form ${variable_name}",
      "Dispatcher splits large configs with $include, can include a file range with a wildcard, and can use ${variable_name} values",
      "You make it modular with $include, optional wildcard includes, and string values that reference environment variables",
    ],
    incorrectAnswers: [
      "Use only Java annotations and OSGi configs to split Dispatcher configuration",
      "Large configs must be split only by creating additional publish instances",
      "The speech says modular configs require XML entities and JSP includes",
      "Dispatcher uses package filters and Repo Init scripts instead of includes",
      "You make it environment-aware only by changing the page component path",
      "The speech says wildcards are forbidden in include statements",
      "Dispatcher splits configs only through CRX package dependencies",
      "Environment values can be inserted only with query parameters on requests",
    ],
    explanation:
      "Section 2 explains that $include splits a large configuration, wildcards can include a range of files, and string values can use environment variables like ${variable_name}.",
  },

  // ── VIRTUAL HOSTS (7) ────────────────────────────────────────────────────

  {
    id: "disp-016",
    topic: "Virtual Hosts",
    question: "What does the /virtualhosts property list for a farm?",
    correctAnswers: [
      "The /virtualhosts property lists every hostname and URI combination the farm accepts",
      "It lists the hostname and URI combinations accepted for that farm",
      "The speech says /virtualhosts contains all accepted host-and-URI combinations",
      "For a farm, /virtualhosts defines every accepted hostname and URI combination",
    ],
    incorrectAnswers: [
      "The /virtualhosts property lists every render hostname and port",
      "It lists the HTTP headers passed to AEM",
      "The speech says /virtualhosts contains all cache invalidation IP addresses",
      "For a farm, /virtualhosts defines every allowed response header",
      "The /virtualhosts property lists only file extensions that can be cached",
      "It lists the document root and statfile path",
      "The speech says /virtualhosts contains only selector and suffix rules",
      "For a farm, /virtualhosts defines all workflow launchers",
    ],
    explanation:
      "Section 3 says /virtualhosts lists every hostname and URI combination that Dispatcher accepts for the farm.",
  },
  {
    id: "disp-017",
    topic: "Virtual Hosts",
    question: "What is the effect of using a single asterisk in /virtualhosts?",
    correctAnswers: [
      "A single asterisk handles all requests",
      "Using one * means every request is handled",
      "The speech says a single wildcard accepts all requests",
      "In /virtualhosts, one asterisk is a catch-all for all requests",
    ],
    incorrectAnswers: [
      "A single asterisk limits the farm to HTTPS only",
      "Using one * allows only requests with selectors",
      "The speech says a single wildcard blocks all requests",
      "In /virtualhosts, one asterisk matches only localhost",
      "A single asterisk means only client headers are passed through",
      "Using one * caches every response regardless of rules",
      "The speech says a single wildcard enables render failover only",
      "In /virtualhosts, one asterisk matches only the URI but never the host",
    ],
    explanation:
      "Section 3 states that a single asterisk handles all requests.",
  },
  {
    id: "disp-018",
    topic: "Virtual Hosts",
    question: "When a request arrives, in what overall order does Dispatcher evaluate farms and virtual host entries?",
    correctAnswers: [
      "Dispatcher evaluates farms from the bottom up, and within a farm it checks virtual host entries from top to bottom",
      "It starts at the lowest farm and works upward, while each farm's virtual hosts are checked from the top down",
      "The speech says request matching is bottom-up across farms and top-down inside each farm",
      "Farm order is bottom-up, but the values inside a farm are matched from first to last",
    ],
    incorrectAnswers: [
      "Dispatcher evaluates farms from the top down, and each farm from the bottom up",
      "It starts with renders, then filters, then virtual hosts only if caching fails",
      "The speech says request matching is random across farms for load balancing",
      "Farm order is alphabetical by farm name and host order is alphabetical by host string",
      "Dispatcher evaluates only the topmost farm and ignores the rest",
      "It starts with the last virtual host in the topmost farm and never checks others",
      "The speech says matching order depends only on file timestamps",
      "Farm order is based only on the /port value of each render",
    ],
    explanation:
      "Section 3 says Dispatcher starts at the lowest farm and works upward, and within each farm it starts at the top value and works down.",
  },
  {
    id: "disp-019",
    topic: "Virtual Hosts",
    question: "Which matching rule has first priority when Dispatcher chooses a virtual host?",
    correctAnswers: [
      "The first priority is the first virtual host that matches the host, the scheme, and the URI",
      "Dispatcher first looks for the first entry matching host, scheme, and URI together",
      "The speech says the best match is the first virtual host that matches host, scheme, and URI",
      "The highest-priority rule is a match on host plus scheme plus URI",
    ],
    incorrectAnswers: [
      "The first priority is the entry with the shortest URI only",
      "Dispatcher first chooses the farm with the most renders",
      "The speech says the best match is the first host that matches only the port",
      "The highest-priority rule is the newest farm file on disk",
      "The first priority is any farm that defines /cache first",
      "Dispatcher first chooses the host with the most wildcard characters",
      "The speech says the best match is always the topmost virtual host of the topmost farm",
      "The highest-priority rule is the first rule that matches only the HTTP method",
    ],
    explanation:
      "Section 3 says the first virtual host that matches the host, the scheme, and the URI is used.",
  },
  {
    id: "disp-020",
    topic: "Virtual Hosts",
    question: "If no virtual host matches both scheme and URI, what fallback does Dispatcher use next?",
    correctAnswers: [
      "It uses the first virtual host that matches the host",
      "The next fallback is the first entry that matches the host only",
      "The speech says Dispatcher then picks the first virtual host matching the host",
      "If scheme and URI do not both match, Dispatcher falls back to a host match",
    ],
    incorrectAnswers: [
      "It uses the first virtual host that matches only the query string",
      "The next fallback is the render with the lowest timeout",
      "The speech says Dispatcher then rejects the request immediately with 403",
      "If scheme and URI do not both match, Dispatcher disables the farm",
      "It uses the first rule that matches only the selector",
      "The next fallback is the first host that matches the port number",
      "The speech says Dispatcher then flushes the cache and retries",
      "If scheme and URI do not both match, Dispatcher always uses author",
    ],
    explanation:
      "Section 3 says that if none match both scheme and URI, the first virtual host that matches the host is used.",
  },
  {
    id: "disp-021",
    topic: "Virtual Hosts",
    question: "If no host matches at all, what does Dispatcher use?",
    correctAnswers: [
      "Dispatcher uses the topmost virtual host of the topmost farm",
      "The ultimate fallback is the topmost virtual host in the topmost farm",
      "The speech says that with no host match, Dispatcher uses the topmost host entry of the topmost farm",
      "If no host matches, Dispatcher falls back to the first virtual host in the topmost farm",
    ],
    incorrectAnswers: [
      "Dispatcher uses the bottommost virtual host of the bottommost farm",
      "The ultimate fallback is the first render in /renders",
      "The speech says that with no host match, Dispatcher returns 504",
      "If no host matches, Dispatcher falls back to /dispatcher/invalidate.cache",
      "Dispatcher uses the last matching filter rule only",
      "The ultimate fallback is whichever farm has /secure set to 1",
      "The speech says that with no host match, Dispatcher switches to author",
      "If no host matches, Dispatcher ignores the request body and retries",
    ],
    explanation:
      "Section 3 says that if no host matches, the topmost virtual host of the topmost farm is used.",
  },
  {
    id: "disp-022",
    topic: "Virtual Hosts",
    question: "Why should the default virtual host be placed at the top of the virtualhosts property in the topmost farm?",
    correctAnswers: [
      "The default virtual host should be there because the final fallback uses the topmost virtual host of the topmost farm",
      "You put it there because if nothing else matches, Dispatcher falls back to the topmost entry of the topmost farm",
      "The speech says the default host belongs at the top because that is the no-match fallback",
      "It should be placed first in the topmost farm so the fallback behavior lands on the default host",
    ],
    incorrectAnswers: [
      "The default virtual host should be there because Dispatcher reads farms alphabetically",
      "You put it there because only the top entry can use HTTPS",
      "The speech says the default host belongs at the top to disable CDN routing",
      "It should be placed first so filters are skipped for that host",
      "The default virtual host should be there because only the top farm can define /cache",
      "You put it there because bottom farms cannot contain wildcards",
      "The speech says the default host belongs at the top to enable author replication",
      "It should be placed first because renders are chosen before hosts",
    ],
    explanation:
      "Section 3 explicitly says to put the default virtual host at the top of the virtualhosts property in the topmost farm because of the fallback behavior.",
  },

  // ── RENDERS AND CLIENT HEADERS (7) ───────────────────────────────────────

  {
    id: "disp-023",
    topic: "Renders and Client Headers",
    question: "What does the /renders property define in Dispatcher?",
    correctAnswers: [
      "The /renders property defines where Dispatcher sends requests to render a document",
      "It defines the render targets that receive requests for document rendering",
      "The speech says /renders specifies where Dispatcher forwards requests to render content",
      "In Dispatcher, /renders identifies where requests are sent for rendering",
    ],
    incorrectAnswers: [
      "The /renders property defines which URLs are cached by path",
      "It defines which filter rules deny requests",
      "The speech says /renders specifies the vanity URL lookup file",
      "In Dispatcher, /renders identifies which client headers are stored on disk",
      "The /renders property defines every accepted hostname and URI combination",
      "It defines the IPs allowed to flush the cache",
      "The speech says /renders specifies only the statfile path",
      "In Dispatcher, /renders identifies the query parameters ignored for caching",
    ],
    explanation:
      "Section 4 says the /renders property defines where Dispatcher sends requests to render a document.",
  },
  {
    id: "disp-024",
    topic: "Renders and Client Headers",
    question: "Which two child properties does each render have according to the speech?",
    correctAnswers: [
      "Each render has a /hostname and a /port",
      "The required child properties named are /hostname and /port",
      "The speech says every render uses /hostname plus /port",
      "A render is defined with a hostname and a port",
    ],
    incorrectAnswers: [
      "Each render has a /docroot and a /statfile",
      "The required child properties named are /url and /delay",
      "The speech says every render uses /method plus /query",
      "A render is defined with a selector and an extension",
      "Each render has a /clientheaders and a /filter",
      "The required child properties named are /allowedClients and /rules",
      "The speech says every render uses /glob plus /type",
      "A render is defined with a /suffix and a /path",
    ],
    explanation:
      "Section 4 says each render has a /hostname and a /port.",
  },
  {
    id: "disp-025",
    topic: "Renders and Client Headers",
    question: "When a farm contains several renders, how does Dispatcher handle requests?",
    correctAnswers: [
      "When there are several renders, Dispatcher distributes requests among them",
      "Multiple renders cause Dispatcher to distribute requests across them",
      "The speech says requests are distributed among several renders",
      "With several renders configured, Dispatcher spreads requests among the render instances",
    ],
    incorrectAnswers: [
      "When there are several renders, Dispatcher always sends every request to the first one only",
      "Multiple renders cause Dispatcher to disable caching automatically",
      "The speech says requests are mirrored to every render for each page view",
      "With several renders configured, Dispatcher sends traffic to author first",
      "When there are several renders, Dispatcher ignores host matching",
      "Multiple renders cause Dispatcher to flush the cache after every response",
      "The speech says requests are queued until every render becomes idle",
      "With several renders configured, Dispatcher serves only stale content",
    ],
    explanation:
      "Section 4 says that when there are several renders, requests are distributed among them.",
  },
  {
    id: "disp-026",
    topic: "Renders and Client Headers",
    question: "What does /timeout control, and what do 0 and the default mean?",
    correctAnswers: [
      "The /timeout property is the connection timeout in milliseconds, and 0 means wait indefinitely, which is the default",
      "It controls the connection timeout in milliseconds; a value of 0 means wait indefinitely and that is the default",
      "The speech says /timeout defines the connection timeout, with 0 meaning indefinite wait by default",
      "Dispatcher uses /timeout for connection timeout in milliseconds, and zero means no timeout by default",
    ],
    incorrectAnswers: [
      "The /timeout property is the cache TTL in seconds, and 0 disables caching by default",
      "It controls the number of allowed retries, and 0 means fail immediately",
      "The speech says /timeout defines the response body size limit, with 0 meaning empty responses",
      "Dispatcher uses /timeout for the vanity URL refresh interval, and zero reloads every request",
      "The /timeout property is the flush IP list length, and 0 means all clients are denied",
      "It controls the document root depth, and 0 means no folders are cached",
      "The speech says /timeout defines selector matching, with 0 meaning exact matches only",
      "Dispatcher uses /timeout for browser cache minutes, and zero means five minutes",
    ],
    explanation:
      "Section 4 says /timeout is the connection timeout in milliseconds, where 0 means wait indefinitely, and that is the default.",
  },
  {
    id: "disp-027",
    topic: "Renders and Client Headers",
    question: "A request hangs while Dispatcher is parsing response headers and then returns 504. Which setting from the speech is most directly involved, and what is its default?",
    correctAnswers: [
      "The relevant setting is /receiveTimeout, whose default is 600000 milliseconds, or ten minutes",
      "That points to /receiveTimeout; the default is 600000 ms, which is ten minutes",
      "The speech says a 504 during response-header parsing is tied to /receiveTimeout, defaulting to 600000 milliseconds",
      "The directly involved property is /receiveTimeout, with a default of ten minutes",
    ],
    incorrectAnswers: [
      "The relevant setting is /statfileslevel, whose default is 600000 milliseconds",
      "That points to /gracePeriod; the default is ten minutes",
      "The speech says a 504 during response-header parsing is tied to /allowedClients, defaulting to 600000 milliseconds",
      "The directly involved property is /virtualhosts, with a default of ten minutes",
      "The relevant setting is /cache, whose default is 504 milliseconds",
      "That points to /filter; the default is ten minutes",
      "The speech says a 504 during response-header parsing is tied to /docroot, defaulting to 600000 milliseconds",
      "The directly involved property is /query, with a default of ten minutes",
    ],
    explanation:
      "Section 4 says /receiveTimeout is the time a response may take, its default is 600000 milliseconds or ten minutes, and hitting that timeout while parsing response headers returns 504.",
  },
  {
    id: "disp-028",
    topic: "Renders and Client Headers",
    question: "What does setting /secure to 1 do for a render?",
    correctAnswers: [
      "Setting /secure to 1 makes Dispatcher use HTTPS to reach AEM",
      "A /secure value of 1 tells Dispatcher to contact AEM over HTTPS",
      "The speech says /secure set to 1 uses HTTPS for render communication",
      "With /secure equal to 1, Dispatcher reaches the render over HTTPS",
    ],
    incorrectAnswers: [
      "Setting /secure to 1 makes Dispatcher cache authenticated pages automatically",
      "A /secure value of 1 tells Dispatcher to deny all HTTP methods except HEAD",
      "The speech says /secure set to 1 uses SSH for cache invalidation",
      "With /secure equal to 1, Dispatcher switches traffic to author",
      "Setting /secure to 1 makes Dispatcher store headers in the cache",
      "A /secure value of 1 tells Dispatcher to disable virtual host matching",
      "The speech says /secure set to 1 enables vanity URL loading at startup",
      "With /secure equal to 1, Dispatcher bypasses all filters",
    ],
    explanation:
      "Section 4 says that /secure set to 1 makes Dispatcher use HTTPS to reach AEM.",
  },
  {
    id: "disp-029",
    topic: "Renders and Client Headers",
    question: "Why is customizing /clientheaders risky if you forget a default header, and which header does the speech call out for page activation requests?",
    correctAnswers: [
      "The /clientheaders list must be exhaustive, including default headers, and page activation requests need the PATH header",
      "Customizing /clientheaders is risky because you must restate the full default list, and activation needs PATH",
      "The speech says /clientheaders must be exhaustive and specifically mentions the PATH header for page activation",
      "If you customize /clientheaders, you must include all default headers, including PATH for activation handling",
    ],
    incorrectAnswers: [
      "The /clientheaders list can be partial, and page activation requests mainly need ETag",
      "Customizing /clientheaders is safe because Dispatcher automatically adds any missing headers, especially CQ-Action",
      "The speech says /clientheaders should contain only custom headers, and activation needs Expires",
      "If you customize /clientheaders, you should remove defaults and keep only Content-Type for activation",
      "The /clientheaders list must contain only Cache-Control, and activation needs Last-Modified",
      "Customizing /clientheaders is risky only because it disables HTTPS, and activation needs ServerAlias",
      "The speech says /clientheaders should contain only Host and Port, and activation needs Surrogate-Control",
      "If you customize /clientheaders, you must remove PATH because it prevents activation",
    ],
    explanation:
      "Section 4 says that /clientheaders is the list of headers passed to the render, and if you customize it, you must specify an exhaustive list including the defaults. It also gives PATH as an example needed for page activation requests.",
  },

  // ── FILTERS (7) ──────────────────────────────────────────────────────────

  {
    id: "disp-030",
    topic: "Filters",
    question: "What does the /filter section specify in Dispatcher?",
    correctAnswers: [
      "The /filter section specifies which HTTP requests Dispatcher accepts",
      "It defines which HTTP requests are accepted by Dispatcher",
      "The speech says /filter controls acceptance of HTTP requests",
      "In Dispatcher, /filter determines which requests are allowed through",
    ],
    incorrectAnswers: [
      "The /filter section specifies which documents are cached by path",
      "It defines which renders receive HTTPS traffic",
      "The speech says /filter controls document root selection",
      "In Dispatcher, /filter determines which response headers are stored",
      "The /filter section specifies which IPs can flush the cache",
      "It defines which vanity URLs are downloaded to a file",
      "The speech says /filter controls how .stat files are touched",
      "In Dispatcher, /filter determines which farms are evaluated first",
    ],
    explanation:
      "Section 5 says the /filter section specifies which HTTP requests Dispatcher accepts.",
  },
  {
    id: "disp-031",
    topic: "Filters",
    question: "What happens to requests that are not accepted by the /filter section?",
    correctAnswers: [
      "Requests that are not accepted are sent back to the web server with a 404 status",
      "Rejected filter requests are returned to the web server as 404",
      "The speech says an unaccepted request is sent back with HTTP 404",
      "If the filter does not accept the request, Dispatcher returns it to the web server with status 404",
    ],
    incorrectAnswers: [
      "Requests that are not accepted are cached and served stale with status 111",
      "Rejected filter requests are returned to the web server as 403 only",
      "The speech says an unaccepted request is retried on author with HTTP 302",
      "If the filter does not accept the request, Dispatcher forwards it to publish anyway",
      "Requests that are not accepted are automatically added to vanity URL storage",
      "Rejected filter requests are returned to the web server as 504 only",
      "The speech says an unaccepted request becomes a render timeout",
      "If the filter does not accept the request, Dispatcher deletes the cache immediately",
    ],
    explanation:
      "Section 5 says requests that are not accepted are sent back to the web server with a 404 status.",
  },
  {
    id: "disp-032",
    topic: "Filters",
    question: "If there is no /filter section at all, how does Dispatcher behave?",
    correctAnswers: [
      "If there is no /filter section, all requests are accepted",
      "Without /filter, Dispatcher accepts every request",
      "The speech says the absence of /filter means all requests are accepted",
      "No /filter section means Dispatcher allows all requests through",
    ],
    incorrectAnswers: [
      "If there is no /filter section, all requests are denied",
      "Without /filter, Dispatcher accepts only GET and HEAD",
      "The speech says the absence of /filter means only cached requests are accepted",
      "No /filter section means Dispatcher forwards only vanity URLs",
      "If there is no /filter section, only localhost requests are accepted",
      "Without /filter, Dispatcher returns 403 for every request",
      "The speech says the absence of /filter means only author traffic is accepted",
      "No /filter section means Dispatcher automatically creates a deny-all rule",
    ],
    explanation:
      "Section 5 says that if there is no /filter section, all requests are accepted.",
  },
  {
    id: "disp-033",
    topic: "Filters",
    question: "What allowlist strategy does the speech recommend for /filter rules?",
    correctAnswers: [
      "Use an allowlist strategy: first deny everything, then allow only what is needed",
      "The recommended pattern is deny all first and then allow only necessary requests",
      "The speech says to start by denying everything and then allow just the needed cases",
      "Dispatcher filter rules should follow a deny-all first, allow-needed-later approach",
    ],
    incorrectAnswers: [
      "Use a blocklist strategy: allow everything first, then deny a few dangerous cases",
      "The recommended pattern is allow all first and never add deny rules",
      "The speech says to start by caching everything and use filters later only for admin traffic",
      "Dispatcher filter rules should follow a wildcard-allow-only approach",
      "Use a strategy that denies only POST and allows every other request",
      "The recommended pattern is to match only query strings and ignore the URL",
      "The speech says to start with vanity URL rules and skip deny rules entirely",
      "Dispatcher filter rules should follow a per-render timeout strategy",
    ],
    explanation:
      "Section 5 recommends an allowlist strategy: first deny everything, then allow only what is needed.",
  },
  {
    id: "disp-034",
    topic: "Filters",
    question: "What is the classic first deny-all rule described in the speech?",
    correctAnswers: [
      "The first deny-all rule is type deny with url asterisk",
      "A deny-all rule uses /type deny and /url *",
      "The speech says the initial blanket deny rule is deny plus url wildcard",
      "To deny everything first, use a rule with type deny and url *",
    ],
    incorrectAnswers: [
      "The first deny-all rule is type allow with url asterisk",
      "A deny-all rule uses /type deny and /query * only",
      "The speech says the initial blanket deny rule is deny plus extension html",
      "To deny everything first, use a rule with type allow and host wildcard",
      "The first deny-all rule is type render with hostname asterisk",
      "A deny-all rule uses /type secure and /url *",
      "The speech says the initial blanket deny rule is deny plus protocol https only",
      "To deny everything first, use a rule with type cache and glob *",
    ],
    explanation:
      "Section 5 explicitly gives the first deny-all rule as type deny and url asterisk.",
  },
  {
    id: "disp-035",
    topic: "Filters",
    question: "Which request-line elements are preferred for filtering instead of matching the whole line?",
    correctAnswers: [
      "The preferred request-line elements are /method, /url, /query, /protocol, /path, /selectors, /extension, and /suffix",
      "Dispatcher prefers filtering by request-line elements such as method, url, query, protocol, path, selectors, extension, and suffix",
      "The speech says to filter on request-line elements, specifically /method, /url, /query, /protocol, /path, /selectors, /extension, and /suffix",
      "Rather than matching the whole line, the preferred approach uses request-line parts including method, URL, query, protocol, path, selectors, extension, and suffix",
    ],
    incorrectAnswers: [
      "The preferred request-line elements are /hostname, /port, /docroot, and /rules only",
      "Dispatcher prefers filtering by /glob because it matches the entire request line best",
      "The speech says to filter only by response headers such as Cache-Control and Expires",
      "Rather than matching the whole line, the preferred approach uses only /statfile and /invalidate",
      "The preferred request-line elements are /farm, /render, /cache, and /secure only",
      "Dispatcher prefers filtering only by browser cookies and never by path parts",
      "The speech says to filter only by virtual host order and not by request-line parts",
      "Rather than matching the whole line, the preferred approach uses only /hostname and /receiveTimeout",
    ],
    explanation:
      "Section 5 says filtering on elements of the request line is preferred, naming /method, /url, /query, /protocol, and from Dispatcher 4.2.0 also /path, /selectors, /extension, and /suffix.",
  },
  {
    id: "disp-036",
    topic: "Filters",
    question: "Why should you avoid the older /glob property in filters?",
    correctAnswers: [
      "The older /glob should be avoided because it matches the entire request line, is deprecated, and can lead to security issues",
      "Avoid /glob because it filters the whole request line, is deprecated, and may create security problems",
      "The speech says /glob is deprecated and can lead to security issues because it matches the entire request line",
      "You should not rely on /glob since it matches the full request line and is considered unsafe and deprecated",
    ],
    incorrectAnswers: [
      "The older /glob should be avoided because it works only for client headers",
      "Avoid /glob because it disables all cache invalidation automatically",
      "The speech says /glob is preferred over request-line elements starting with Dispatcher 4.2.0",
      "You should not rely on /glob because it is required only for renders and never for filters",
      "The older /glob should be avoided because it matches only the host and nothing else",
      "Avoid /glob because it prevents HTTPS connections to the render",
      "The speech says /glob is mandatory for vanity URL support",
      "You should not rely on /glob because it is only for browser cache headers",
    ],
    explanation:
      "Section 5 says the older /glob property matches the entire request line, is deprecated, and can lead to security issues.",
  },

  // ── FILTER SAFETY AND VANITY URLS (7) ────────────────────────────────────

  {
    id: "disp-037",
    topic: "Filter Safety and Vanity URLs",
    question: "Why does the Dispatcher validator fail a filter rule that uses a glob to allow requests in AEM as a Cloud Service?",
    correctAnswers: [
      "The validator fails glob-based allow rules because of CVE-2016-0957",
      "In Cloud Service, an allow rule using a glob fails validation due to CVE-2016-0957",
      "The speech says the validator rejects glob allow rules because of CVE-2016-0957",
      "A glob used to allow requests is invalid because of the CVE-2016-0957 security risk",
    ],
    incorrectAnswers: [
      "The validator fails glob-based allow rules because globs cannot match the URL at all",
      "In Cloud Service, an allow rule using a glob fails because only author can use filters",
      "The speech says the validator rejects glob allow rules because they are slower than regex",
      "A glob used to allow requests is invalid because it prevents cache invalidation",
      "The validator fails glob-based allow rules because globs are allowed only in virtual hosts",
      "In Cloud Service, an allow rule using a glob fails because it requires HTTPS",
      "The speech says the validator rejects glob allow rules because they hide document roots",
      "A glob used to allow requests is invalid because it removes all client headers",
    ],
    explanation:
      "Section 6 says the Dispatcher validator fails a filter rule that uses a glob to allow requests because of CVE-2016-0957.",
  },
  {
    id: "disp-038",
    topic: "Filter Safety and Vanity URLs",
    question: "What makes an allow rule like GET *.css* dangerous according to the speech?",
    correctAnswers: [
      "It could also allow any resource followed by a query string such as ?a=.css",
      "That rule is dangerous because it can match a resource plus a query string like ?a=.css",
      "The speech says GET *.css* could allow any resource followed by a query string containing .css",
      "The problem is that a glob like GET *.css* can allow more than CSS files, including crafted query strings",
    ],
    incorrectAnswers: [
      "It is dangerous only because CSS files can never be cached",
      "That rule is dangerous because it blocks every static resource request",
      "The speech says GET *.css* is dangerous only because it requires HTTPS",
      "The problem is that a glob like GET *.css* matches only HEAD requests",
      "It is dangerous only because it disables /clientheaders",
      "That rule is dangerous because it flushes the cache on each CSS request",
      "The speech says GET *.css* is dangerous only on author instances",
      "The problem is that a glob like GET *.css* prevents vanity URL lookup",
    ],
    explanation:
      "Section 6 explains that allowing GET *.css* would also allow any resource followed by a query string such as ?a=.css.",
  },
  {
    id: "disp-039",
    topic: "Filter Safety and Vanity URLs",
    question: "What other validation failure does the speech call out besides unsafe glob allow rules?",
    correctAnswers: [
      "The validator also fails if an admin feature such as /crx/de or /system/console is exposed",
      "Another validation failure is exposing admin features like /crx/de or /system/console",
      "The speech says validation also fails when an admin feature is exposed",
      "Besides unsafe globs, exposing /crx/de or /system/console will fail validation",
    ],
    incorrectAnswers: [
      "The validator also fails if /docroot matches the web server document root",
      "Another validation failure is having more than one render",
      "The speech says validation also fails when /timeout is set to 0",
      "Besides unsafe globs, using HTTPS to reach AEM will fail validation",
      "The validator also fails if filters deny admin paths",
      "Another validation failure is setting /receiveTimeout to ten minutes",
      "The speech says validation also fails when the top farm has a default host",
      "Besides unsafe globs, allowing only GET and HEAD will fail validation",
    ],
    explanation:
      "Section 6 says the validator also fails if an admin feature is exposed, such as /crx/de or /system/console.",
  },
  {
    id: "disp-040",
    topic: "Filter Safety and Vanity URLs",
    question: "Which security checklist item explains why an unauthorized request to /dispatcher/invalidate.cache should return 403?",
    correctAnswers: [
      "You must restrict who can flush the cache",
      "The reason is that cache flushing must be restricted to authorized clients",
      "The speech says the security checklist requires restricting who can flush the cache",
      "An unauthorized invalidation request should get 403 because cache flush access must be restricted",
    ],
    incorrectAnswers: [
      "You must allow everyone to flush the cache for freshness",
      "The reason is that only query strings may trigger invalidation",
      "The speech says the security checklist requires blocking only HTTPS invalidations",
      "An unauthorized invalidation request should get 403 because publish never supports POST",
      "You must expose all admin features to verify deployment",
      "The reason is that invalidation works only from browser cookies",
      "The speech says the security checklist requires denying only HEAD requests",
      "An unauthorized invalidation request should get 403 because Dispatcher cannot handle IP matching",
    ],
    explanation:
      "Section 6 says the security checklist includes restricting who can flush the cache, and that an unauthorized request to /dispatcher/invalidate.cache should return 403.",
  },
  {
    id: "disp-041",
    topic: "Filter Safety and Vanity URLs",
    question: "If a page request is denied by a filter, what does Dispatcher do next for vanity URL handling?",
    correctAnswers: [
      "If a page request is denied by a filter, Dispatcher consults its list of vanity URLs",
      "After the filter denies a page request, Dispatcher checks the vanity URL list",
      "The speech says Dispatcher consults the vanity URL list when a page request is denied",
      "The next step after a denied page request is a lookup in the configured vanity URL list",
    ],
    incorrectAnswers: [
      "If a page request is denied by a filter, Dispatcher immediately caches the page anyway",
      "After the filter denies a page request, Dispatcher checks only the render timeout",
      "The speech says Dispatcher restarts Apache when a page request is denied",
      "The next step after a denied page request is to bypass all filters permanently",
      "If a page request is denied by a filter, Dispatcher deletes the vanity URL file",
      "After the filter denies a page request, Dispatcher checks only /allowedClients",
      "The speech says Dispatcher forwards the request to author when a page request is denied",
      "The next step after a denied page request is to disable caching for the farm",
    ],
    explanation:
      "Section 6 says that if a page request is denied by a filter, Dispatcher consults its list of vanity URLs.",
  },
  {
    id: "disp-042",
    topic: "Filter Safety and Vanity URLs",
    question: "Which /vanity_urls settings does the speech name, and what must /url be set to?",
    correctAnswers: [
      "The /vanity_urls section uses /url, /file, and /delay, and /url must be /libs/granite/dispatcher/content/vanityUrls.html",
      "The speech names /url, /file, and /delay, with /url set to /libs/granite/dispatcher/content/vanityUrls.html",
      "Vanity URL configuration includes /url, /file, and /delay, and the required service URL is /libs/granite/dispatcher/content/vanityUrls.html",
      "Dispatcher vanity URL setup uses /url, /file, and /delay, with /url pointing to /libs/granite/dispatcher/content/vanityUrls.html",
    ],
    incorrectAnswers: [
      "The /vanity_urls section uses /hostname, /port, and /secure, and /url must be /dispatcher/invalidate.cache",
      "The speech names /method, /query, and /suffix, with /url set to /system/console",
      "Vanity URL configuration includes /headers, /rules, and /mode, and the required service URL is /etc/map",
      "Dispatcher vanity URL setup uses /path, /selectors, and /extension, with /url pointing to /crx/de",
      "The /vanity_urls section uses /docroot, /statfile, and /invalidate, and /url must be /content",
      "The speech names /cache, /filter, and /clientheaders, with /url set to /libs/cq/core/content/login",
      "Vanity URL configuration includes /allowAuthorized, /gracePeriod, and /enableTTL, and the required service URL is /bin/querybuilder.json",
      "Dispatcher vanity URL setup uses /virtualhosts, /renders, and /farms, with /url pointing to /content/dam",
    ],
    explanation:
      "Section 6 says the /vanity_urls section has /url, /file, and /delay, and that /url must be /libs/granite/dispatcher/content/vanityUrls.html.",
  },
  {
    id: "disp-043",
    topic: "Filter Safety and Vanity URLs",
    question: "Even when vanity URL support is configured, what must still be true of the filter rule for the vanity URL?",
    correctAnswers: [
      "A filter must still deny the vanity URL",
      "The vanity URL still has to be denied by the filter",
      "The speech says the filter must continue to deny the vanity URL",
      "Configured vanity URL support does not remove the need for a deny filter on the vanity URL",
    ],
    incorrectAnswers: [
      "A filter must always allow the vanity URL directly",
      "The vanity URL still has to be converted into a render hostname",
      "The speech says the filter must continue to allow admin features for the vanity URL",
      "Configured vanity URL support removes all filter requirements for that URL",
      "A filter must always rewrite the vanity URL to /dispatcher/invalidate.cache",
      "The vanity URL still has to be cached even when denied",
      "The speech says the filter must continue to add the vanity URL to client headers",
      "Configured vanity URL support requires /secure set to 1 on the vanity URL",
    ],
    explanation:
      "Section 6 explicitly says that a filter must still deny the vanity URL.",
  },

  // ── CACHE BASICS (7) ─────────────────────────────────────────────────────

  {
    id: "disp-044",
    topic: "Cache Basics",
    question: "What does the /cache section control in Dispatcher?",
    correctAnswers: [
      "The /cache section controls how Dispatcher caches documents",
      "It defines how document caching works in Dispatcher",
      "The speech says /cache governs the way Dispatcher caches documents",
      "In Dispatcher, the /cache section controls document caching behavior",
    ],
    incorrectAnswers: [
      "The /cache section controls which HTTP requests are accepted",
      "It defines how virtual host matching works",
      "The speech says /cache governs how PATH headers are forwarded",
      "In Dispatcher, the /cache section controls only render hostnames",
      "The /cache section controls which vanity URLs are downloaded",
      "It defines how author replication agents authenticate",
      "The speech says /cache governs the page component hierarchy",
      "In Dispatcher, the /cache section controls only workflow payload routing",
    ],
    explanation:
      "Section 7 says the /cache section controls how Dispatcher caches documents.",
  },
  {
    id: "disp-045",
    topic: "Cache Basics",
    question: "What requirement does the speech place on /docroot, and what changes when multiple farms are used?",
    correctAnswers: [
      "The /docroot must match the web server document root, and with multiple farms each farm needs a different document root",
      "The speech says /docroot must be the same as the web server document root, and each farm needs its own docroot when several farms exist",
      "Dispatcher requires /docroot to equal the web server document root, while multiple farms require different docroots",
      "The cache document root must match the web server document root, and it cannot be shared across multiple farms",
    ],
    incorrectAnswers: [
      "The /docroot must always be different from the web server document root, and all farms should share one path",
      "The speech says /docroot should point to author, and multiple farms must reuse it",
      "Dispatcher requires /docroot only for vanity URLs, while multiple farms ignore it",
      "The cache document root must match the render hostname, and every farm should reuse the same one",
      "The /docroot must always be /content, and all farms must point to that path",
      "The speech says /docroot is optional if /rules exist, and multiple farms use the same cache folder",
      "Dispatcher requires /docroot to equal /dispatcher/invalidate.cache, while multiple farms set only /statfile",
      "The cache document root must match the CDN endpoint, and multiple farms are not allowed",
    ],
    explanation:
      "Section 7 says /docroot is the directory where cached files are stored, it must be the same path as the web server document root, and with multiple farms each farm needs a different document root.",
  },
  {
    id: "disp-046",
    topic: "Cache Basics",
    question: "What does the /rules property control, and what do its rule types mean?",
    correctAnswers: [
      "The /rules property controls which documents are cached by path, where allow means cache and deny means render every time",
      "It controls path-based document caching, with allow meaning cache and deny meaning always render",
      "The speech says /rules decides which paths are cached, and its types mean cache for allow and render every time for deny",
      "Dispatcher uses /rules for path-based caching decisions, where allow caches and deny bypasses cache",
    ],
    incorrectAnswers: [
      "The /rules property controls only which client headers are passed through, where allow means HTTPS and deny means HTTP",
      "It controls virtual host selection, with allow meaning top farm and deny meaning bottom farm",
      "The speech says /rules decides which users can log in, and its types mean author and publish",
      "Dispatcher uses /rules for response headers only, where allow stores ETag and deny removes it",
      "The /rules property controls render failover only, where allow means retry and deny means stop",
      "It controls vanity URL downloads, with allow meaning load at startup and deny meaning load on demand",
      "The speech says /rules decides filter tracing, and its types mean debug and info",
      "Dispatcher uses /rules for replication agents, where allow means activate and deny means deactivate",
    ],
    explanation:
      "Section 7 says /rules controls which documents are cached by path. Each rule has a glob pattern and a type: allow means cache, while deny means render every time.",
  },
  {
    id: "disp-047",
    topic: "Cache Basics",
    question: "According to the speech, how do you configure Dispatcher to cache everything except dynamic sections?",
    correctAnswers: [
      "Use a rule with glob asterisk and type allow, then add deny exceptions for the dynamic sections",
      "To cache everything, allow glob * and then deny the paths that must stay dynamic",
      "The speech says to use an allow-all cache rule and add deny exceptions for dynamic areas",
      "You cache everything by allowing * in /rules and then denying the dynamic sections",
    ],
    incorrectAnswers: [
      "Use a rule with glob asterisk and type deny, then add allow exceptions for everything else",
      "To cache everything, disable /rules and rely only on virtual hosts",
      "The speech says to use only /invalidate because it determines caching",
      "You cache everything by allowing only HTML and denying every other extension",
      "Use a rule with glob asterisk and type secure, then add timeout exceptions",
      "To cache everything, enable /allowAuthorized and skip deny rules",
      "The speech says to use only /clientheaders because it determines caching",
      "You cache everything by denying GET and allowing POST",
    ],
    explanation:
      "Section 7 says that to cache everything, use glob asterisk with type allow, then add deny exceptions for dynamic sections.",
  },
  {
    id: "disp-048",
    topic: "Cache Basics",
    question: "Which request characteristic alone is enough to stop caching regardless of the configured cache rules?",
    correctAnswers: [
      "A request URI that contains a question mark is not cached regardless of the cache rules",
      "If the request URI contains ?, Dispatcher will not cache the document regardless of rules",
      "The speech says a question mark in the request URI prevents caching even if rules allow it",
      "One built-in no-cache condition is a request URI containing a question mark",
    ],
    incorrectAnswers: [
      "A request URI containing a slash is never cached regardless of rules",
      "If the request URI contains html, Dispatcher will not cache the document regardless of rules",
      "The speech says a hostname match prevents caching even if rules allow it",
      "One built-in no-cache condition is using the GET method",
      "A request URI containing localhost is never cached regardless of rules",
      "If the request URI contains a selector, Dispatcher will not cache the document regardless of rules",
      "The speech says an allowed filter rule prevents caching even if rules allow it",
      "One built-in no-cache condition is having a valid document root",
    ],
    explanation:
      "Section 7 says Dispatcher never caches a document when the request URI contains a question mark, regardless of the cache rules.",
  },
  {
    id: "disp-049",
    topic: "Cache Basics",
    question: "Besides a question mark in the URI, which other built-in conditions prevent Dispatcher from caching a document?",
    correctAnswers: [
      "Dispatcher also will not cache when the file extension is missing, when the authentication header is set, or when AEM responds with no-cache, no-store, or must-revalidate headers",
      "Other built-in no-cache conditions are a missing file extension, an authentication header, or backend no-cache, no-store, or must-revalidate headers",
      "The speech says no caching occurs if the extension is missing, authentication is present, or AEM sends no-cache, no-store, or must-revalidate",
      "Missing extension, authentication information, or no-cache-style response headers from AEM all stop caching",
    ],
    incorrectAnswers: [
      "Dispatcher also will not cache when the host matches, when PATH is present, or when AEM responds with Last-Modified",
      "Other built-in no-cache conditions are a valid extension, a HEAD request, or backend Content-Type headers",
      "The speech says no caching occurs if the extension is html, authentication is absent, or AEM sends Expires",
      "Missing extension, anonymous access, or Cache-Control public from AEM all stop caching",
      "Dispatcher also will not cache when the farm has several renders, when PATH is absent, or when AEM responds with ETag",
      "Other built-in no-cache conditions are a GET request, a docroot match, or backend 200 status",
      "The speech says no caching occurs if the extension is css, HTTPS is used, or AEM sends Content-Disposition",
      "Missing extension, one virtual host, or Cache-Control max-age from AEM all stop caching",
    ],
    explanation:
      "Section 7 says Dispatcher also does not cache when the file extension is missing, when the authentication header is set, or when AEM responds with no-cache, no-store, or must-revalidate headers.",
  },
  {
    id: "disp-050",
    topic: "Cache Basics",
    question: "Which HTTP methods are cacheable, and why should closed user groups not be cached?",
    correctAnswers: [
      "Only GET and HEAD requests are cacheable, and closed user groups should not be cached because user rights are not checked for cached pages",
      "Dispatcher caches only GET and HEAD, and closed user groups are unsafe to cache because cached pages do not check user rights",
      "The speech says only GET and HEAD are cacheable, and CUG content should not be cached since user rights are not checked",
      "Cacheability is limited to GET and HEAD, and closed user groups must not be cached because cached pages bypass user-right checks",
    ],
    incorrectAnswers: [
      "Only POST and PUT requests are cacheable, and closed user groups should be cached to improve login speed",
      "Dispatcher caches only DELETE and OPTIONS, and closed user groups are safe because user rights are always rechecked on cached pages",
      "The speech says only GET and POST are cacheable, and CUG content should be cached if filters are strict",
      "Cacheability is limited to HEAD only, and closed user groups must be cached for vanity URL support",
      "Only PATCH and TRACE requests are cacheable, and closed user groups are safe because client headers store permissions",
      "Dispatcher caches only authenticated requests, and closed user groups should be cached after invalidation",
      "The speech says every HTTP method is cacheable, and CUG content is safe if the extension is html",
      "Cacheability is limited to PUT and HEAD, and closed user groups must be cached because docroot is shared",
    ],
    explanation:
      "Section 7 says only GET and HEAD requests are cacheable, and closed user groups should not be cached because user rights are not checked for cached pages.",
  },
]
