import type { TriviaQuestion } from "./trivia-types"

export const workflowsQuestionsPartA: TriviaQuestion[] = [

  // ── INTRODUCTION (7) ─────────────────────────────────────────────────────

  {
    id: "wf-001",
    topic: "Introduction",
    question: "After components and the Maven project structure, which three features does this lesson turn to?",
    correctAnswers: [
      "The lesson covers Workflows, Content Fragments, and Experience Fragments",
      "It turns to Workflows, Content Fragments, and Experience Fragments",
      "The three features are Workflows, Content Fragments, and Experience Fragments",
      "After Maven structure, the lesson focuses on Workflows, Content Fragments, and Experience Fragments",
    ],
    incorrectAnswers: [
      "The lesson covers Dispatcher rules, CDN headers, and cache invalidation",
      "It turns to editable templates, policies, and responsive grids",
      "The three features are MSM, Translation Projects, and Launches",
      "It focuses on Sling Models, HTL Use-API, and client libraries",
      "The lesson covers package filters, Repo Init, and service users",
      "It turns to GraphQL persisted queries, CIF, and SPA Editor routing",
      "The three features are workflows, tags, and user administration",
      "It focuses on replication agents, Dispatcher flush, and IMS setup",
    ],
    explanation:
      "The introduction says that after components and Maven project structure, the lesson looks at Workflows, Content Fragments, and Experience Fragments.",
  },
  {
    id: "wf-002",
    topic: "Introduction",
    question: "Which exam domain does this lesson support, and about how much of the exam is it?",
    correctAnswers: [
      "It supports the AEM Development domain at about 37 percent",
      "This lesson maps to the AEM Development part of the exam, about 37%",
      "The exam domain is AEM Development, which is roughly 37 percent",
      "It supports AEM Development, the largest domain at about thirty-seven percent",
    ],
    incorrectAnswers: [
      "It supports Build and Deployment at about 17 percent",
      "It supports Dispatcher and CDN at about 25 percent",
      "It supports Security Administration at about 10 percent",
      "It supports Authoring Features at about 50 percent",
      "It supports Assets Microservices at about 12 percent",
      "It supports Forms Integration at about 30 percent",
      "It supports Cloud Manager Pipelines at about 5 percent",
      "It supports Commerce Integration at about 20 percent",
    ],
    explanation:
      'The speech says this lesson supports the AEM Development part of the exam, the largest domain at about 37 percent.',
  },
  {
    id: "wf-003",
    topic: "Introduction",
    question: "How are workflows characterized in the introduction?",
    correctAnswers: [
      "Workflows move a payload through steps",
      "A workflow is automation that moves a payload through steps",
      "Workflows are automation that advance a payload through steps",
      "The introduction defines workflows as moving a payload through steps",
    ],
    incorrectAnswers: [
      "Workflows are reusable page layouts for third-party channels",
      "Workflows are repository launchers that only listen for delete events",
      "Workflows are immutable configuration packages stored under /libs",
      "Workflows are authoring dialogs for editing component policies",
      "Workflows are GraphQL schemas for headless content queries",
      "Workflows are package managers for deploying AEM applications",
      "Workflows are asset renditions that rewrite HTML links",
      "Workflows are fragment models that define content element types",
    ],
    explanation:
      "The introduction summarizes workflows as automation that moves a payload through steps.",
  },
  {
    id: "wf-004",
    topic: "Introduction",
    question: "What is the lesson's definition of Content Fragments?",
    correctAnswers: [
      "Content Fragments are structured, channel-neutral content",
      "They are structured content that is channel-neutral",
      "Content Fragments are channel-neutral structured content",
      "The lesson describes Content Fragments as structured, channel-neutral content",
    ],
    incorrectAnswers: [
      "Content Fragments are reusable page layouts with components",
      "Content Fragments are workflow instances archived after completion",
      "Content Fragments are launchers that react to repository events",
      "Content Fragments are immutable code packages deployed by Cloud Manager",
      "Content Fragments are inbox assignments for human approval",
      "Content Fragments are only JCR sessions adapted from WorkflowSession",
      "Content Fragments are runtime workflow models generated under /var",
      "Content Fragments are sub-workflows started by container steps",
    ],
    explanation:
      "In the introduction, Content Fragments are defined as structured, channel-neutral content.",
  },
  {
    id: "wf-005",
    topic: "Introduction",
    question: "What is the lesson's definition of Experience Fragments?",
    correctAnswers: [
      "Experience Fragments are reusable groups of components with layout",
      "They are reusable groups of components that include layout",
      "Experience Fragments are groups of components with layout that can be reused",
      "The lesson defines Experience Fragments as reusable groups of components with layout",
    ],
    incorrectAnswers: [
      "Experience Fragments are structured data models with no layout",
      "Experience Fragments are workflow payloads serialized as Java objects",
      "Experience Fragments are node types that trigger workflow launchers",
      "Experience Fragments are OSGi services that implement WorkflowProcess",
      "Experience Fragments are transient workflow histories kept in memory",
      "Experience Fragments are technical stage labels inside a workflow model",
      "Experience Fragments are user inbox queues for participant steps",
      "Experience Fragments are workflow transitions between consecutive steps",
    ],
    explanation:
      "The introduction describes Experience Fragments as reusable groups of components with layout.",
  },
  {
    id: "wf-006",
    topic: "Introduction",
    question: "What kind of exam questions should you expect around workflow step selection and custom steps?",
    correctAnswers: [
      "Expect scenario questions about which step type fits and where a custom step is implemented",
      "The exam uses scenarios asking which step type fits a requirement and where a custom step is implemented",
      "You should expect scenario-based questions about step type choice and custom step implementation",
      "The lesson warns to expect scenarios on the right step type and the implementation location of a custom step",
    ],
    incorrectAnswers: [
      "Expect only memorization questions about exact CRXDE click paths",
      "Expect only licensing questions about Cloud Manager program tiers",
      "Expect only Java syntax questions unrelated to AEM workflows",
      "Expect only visual design questions about component spacing systems",
      "Expect only author training questions about page editor shortcuts",
      "Expect only networking questions about VPN and IP allow lists",
      "Expect only Dispatcher farm naming questions with no workflow logic",
      "Expect only package checksum questions for repository installation",
    ],
    explanation:
      "The introduction explicitly says to expect scenario questions such as which step type fits a requirement and where a custom step is implemented.",
  },
  {
    id: "wf-007",
    topic: "Introduction",
    question: "What other scenario style does the introduction call out for fragment-related exam questions?",
    correctAnswers: [
      "Expect scenario questions about which fragment type to use and how a fragment is delivered to a third party",
      "The exam also uses scenarios about fragment type choice and third-party delivery",
      "You should expect use-case questions on choosing the right fragment type and delivering it to a third party",
      "The introduction highlights scenarios on fragment selection and third-party delivery",
    ],
    incorrectAnswers: [
      "Expect only questions about Adobe Target contract terms",
      "Expect only repository compaction questions about segment stores",
      "Expect only Java heap tuning questions for author instances",
      "Expect only SSL certificate import steps for Dispatcher",
      "Expect only OSGi config syntax questions with no use cases",
      "Expect only CRX package download questions from Package Manager",
      "Expect only user permission matrix questions for Admin Console",
      "Expect only Git branching questions about release trains",
    ],
    explanation:
      "The introduction says you should expect scenario questions on which fragment type fits a use case and how a fragment is delivered to a third party.",
  },

  // ── WORKFLOW MODEL CONCEPTS (7) ──────────────────────────────────────────

  {
    id: "wf-008",
    topic: "Workflow Model Concepts",
    question: "What is a WorkflowModel in AEM?",
    correctAnswers: [
      "A WorkflowModel is the definition of a workflow",
      "It is the definition of the workflow",
      "A WorkflowModel defines the workflow",
      "In AEM, the WorkflowModel is the workflow definition",
    ],
    incorrectAnswers: [
      "A WorkflowModel is the archived history of a completed instance",
      "A WorkflowModel is the user inbox entry assigned for approval",
      "A WorkflowModel is the repository event that starts a launcher",
      "A WorkflowModel is the ECMA script used by a process step",
      "A WorkflowModel is the payload object only, without steps",
      "A WorkflowModel is the Cloud Manager pipeline definition",
      "A WorkflowModel is the JCR session adapted from WorkflowSession",
      "A WorkflowModel is the package containing multiple selected resources",
    ],
    explanation:
      "Section 2 says a WorkflowModel is the definition of a workflow, made of nodes and transitions.",
  },
  {
    id: "wf-009",
    topic: "Workflow Model Concepts",
    question: "What is a workflow transition?",
    correctAnswers: [
      "A transition is the link between two consecutive steps",
      "It links two consecutive workflow steps",
      "A workflow transition connects one step to the next consecutive step",
      "The transition is the link between consecutive steps in the flow",
    ],
    incorrectAnswers: [
      "A transition is the payload path stored on the work item",
      "A transition is the archived copy of a terminated instance",
      "A transition is the user or group assigned to a participant step",
      "A transition is the service label shown in the Process Step dialog",
      "A transition is the generated runtime model under /var",
      "A transition is the package that holds multiple selected resources",
      "A transition is the repository event type in a launcher",
      "A transition is the MetadataMap key used for process arguments",
    ],
    explanation:
      "The speech defines a transition as the link between two consecutive steps, and says rules can be applied to it.",
  },
  {
    id: "wf-010",
    topic: "Workflow Model Concepts",
    question: "What nodes must every workflow model have?",
    correctAnswers: [
      "A model always has a start node and an end node",
      "Every workflow model includes both a start node and an end node",
      "The required nodes are the start node and the end node",
      "A workflow model must contain a start node and an end node",
    ],
    incorrectAnswers: [
      "A model must always have a participant node and a container node",
      "A model must always have an AND Split and an OR Join",
      "A model must always have a launcher node and a package node",
      "A model must always have a Goto Step and a Dynamic Participant step",
      "A model must always have a video processing step and a timeout handler",
      "A model must always have two start nodes for author and publish",
      "A model must always have a workflow stage node and an archive node",
      "A model must always have a JCR session node and a resolver node",
    ],
    explanation:
      "Section 2 explicitly says a model always has a start node and an end node.",
  },
  {
    id: "wf-011",
    topic: "Workflow Model Concepts",
    question: "Which payload forms are explicitly mentioned in the speech?",
    correctAnswers: [
      "The payload can reference a repository resource by path, UUID, or URL, or be a serialized Java object",
      "It can be a repository resource identified by path, UUID, or URL, or a serialized Java object",
      "A payload may point to a resource by path, UUID, or URL, or may be a serialized Java object",
      "The speech says the payload is either a referenced repository resource by path, UUID, or URL, or a serialized Java object",
    ],
    incorrectAnswers: [
      "The payload must always be a page template and cannot be anything else",
      "The payload can only be a Content Fragment Model stored under /conf",
      "The payload must always be a workflow launcher event without repository content",
      "The payload is limited to HTML markup generated by an Experience Fragment",
      "The payload can only be an OSGi configuration PID and its properties",
      "The payload must be a package filter XML file or a ZIP archive",
      "The payload is always a Sling job created by a Goto Step",
      "The payload can only be a JCR binary asset rendition ID",
    ],
    explanation:
      "Section 2 says the payload is the resource advanced through the workflow and can be referenced by path, UUID, or URL, or be a serialized Java object.",
  },
  {
    id: "wf-012",
    topic: "Workflow Model Concepts",
    question: "What does a WorkItem contain?",
    correctAnswers: [
      "A WorkItem contains the WorkflowData and a reference to the current WorkflowNode",
      "It holds the WorkflowData the instance acts on and the current WorkflowNode reference",
      "A WorkItem includes the workflow data plus a reference to the node for the current step",
      "The WorkItem is the unit passed through the instance with WorkflowData and the current node reference",
    ],
    incorrectAnswers: [
      "A WorkItem contains only the model editor thumbnail and stage color",
      "A WorkItem contains the launcher conditions and event listener state",
      "A WorkItem contains only the process.label string and no workflow data",
      "A WorkItem contains the package manager filters used at deployment time",
      "A WorkItem contains the Allowed Templates regex for Experience Fragments",
      "A WorkItem contains the GraphQL schema and persisted query cache",
      "A WorkItem contains the Cloud Manager execution log for the deployment",
      "A WorkItem contains only archived history and never current step details",
    ],
    explanation:
      "The speech defines a WorkItem as the unit passed through a workflow instance, containing the WorkflowData and a reference to the WorkflowNode for the current step.",
  },
  {
    id: "wf-013",
    topic: "Workflow Model Concepts",
    question: "How are workflow inbox assignments described?",
    correctAnswers: [
      "Each user has a workflow inbox, and work items are assigned directly or through a group",
      "Every user account has its own workflow inbox, with items assigned either to the user or a group",
      "AEM gives each user a workflow inbox, and assignment can be direct or group-based",
      "Work items appear in each user's inbox when assigned to that user or to a group the user belongs to",
    ],
    incorrectAnswers: [
      "All work items go to a single global inbox that ignores group membership",
      "Only administrators receive workflow inboxes and standard users do not",
      "Inbox items can be assigned only to individual users, never to groups",
      "Workflow inboxes exist only for launchers and not for participant work",
      "Users receive inbox items only after the instance is archived",
      "AEM stores inbox assignments only in Cloud Manager and not in the repository",
      "Workflow inboxes are available only for transient models with Goto steps",
      "Inbox routing is based only on package filters and deployment targets",
    ],
    explanation:
      "Section 2 says each user account has its own workflow inbox, and work items are assigned either directly to a user or to a group the user belongs to.",
  },
  {
    id: "wf-014",
    topic: "Workflow Model Concepts",
    question: "Which actions are available on a workflow instance during its lifecycle?",
    correctAnswers: [
      "Terminate, suspend, resume, and restart are the available instance actions",
      "The instance actions are terminate, suspend, resume, and restart",
      "A workflow instance can be terminated, suspended, resumed, or restarted",
      "During its lifecycle, the available actions are terminate, suspend, resume, and restart",
    ],
    incorrectAnswers: [
      "Clone, replicate, publish, and rollback are the workflow instance actions",
      "Approve, reject, unlock, and merge are the standard instance actions",
      "Install, build, test, and deploy are the workflow instance actions",
      "Sync, overlay, export, and version are the instance actions",
      "Archive, externalize, invalidate, and compact are the instance actions",
      "Promote, demote, subscribe, and unsubscribe are the instance actions",
      "Render, cache, flush, and distribute are the instance actions",
      "Bootstrap, provision, snapshot, and restore are the instance actions",
    ],
    explanation:
      "The speech says an instance is created when you choose a model and define the payload, ends when the end node is processed, and offers terminate, suspend, resume, and restart.",
  },

  // ── RUNTIME MODELS AND SYNC (7) ──────────────────────────────────────────

  {
    id: "wf-015",
    topic: "Runtime Models and Sync",
    question: "How are workflow models described with respect to versioning?",
    correctAnswers: [
      "Workflow models are versioned",
      "AEM workflow models are versioned",
      "The speech says workflow models use versioning",
      "Workflow models are maintained as versioned models",
    ],
    incorrectAnswers: [
      "Workflow models are always transient and never versioned",
      "Workflow models exist only as live editor drafts with no versions",
      "Workflow models are versioned only in Cloud Manager, not in AEM",
      "Workflow models are versioned only after the instance completes",
      "Workflow models are unversioned unless they contain participant steps",
      "Workflow models are versioned only when stored under /libs",
      "Workflow models are versioned only for Legacy workflows",
      "Workflow models cannot be versioned if they use ECMA scripts",
    ],
    explanation:
      "Section 3 opens by stating that workflow models are versioned.",
  },
  {
    id: "wf-016",
    topic: "Runtime Models and Sync",
    question: "Which runtime model does a running workflow instance use?",
    correctAnswers: [
      "A running instance uses the runtime model that existed when the instance started",
      "It uses the runtime model available at the time the workflow started",
      "The instance runs against the start-time runtime model",
      "A workflow instance keeps using the runtime model that was available when it began",
    ],
    incorrectAnswers: [
      "A running instance always switches to the newest synced model immediately",
      "It uses the draft currently open in the model editor",
      "It uses the model stored under /libs even for custom workflows",
      "It uses the last ECMA script change as a full model replacement",
      "It uses the launcher definition instead of a runtime model",
      "It uses a random archived version chosen at resume time",
      "It always uses the oldest version still present in the repository",
      "It rebuilds the model on each step from the authoring nodes",
    ],
    explanation:
      "The speech says that when a workflow instance runs, it uses the runtime model that was available when that instance started.",
  },
  {
    id: "wf-017",
    topic: "Runtime Models and Sync",
    question: "What action generates a runtime model in the workflow model editor?",
    correctAnswers: [
      "Triggering Sync generates the runtime model",
      "The runtime model is generated when you click Sync",
      "Using Sync in the model editor generates the runtime model",
      "A runtime model is created by triggering Sync",
    ],
    incorrectAnswers: [
      "Saving the dialog generates the runtime model automatically",
      "Archiving a completed instance generates the runtime model",
      "Restarting the instance generates the runtime model from scratch",
      "Opening the workflow inbox generates the runtime model",
      "Installing a package always generates the runtime model instantly",
      "Starting a launcher event generates the runtime model without Sync",
      "Changing process.label generates the runtime model immediately",
      "Publishing a page generates all runtime workflow models",
    ],
    explanation:
      "Section 3 explicitly says that a runtime model is generated when you trigger Sync in the workflow model editor.",
  },
  {
    id: "wf-018",
    topic: "Runtime Models and Sync",
    question: "A developer edits a workflow model but does not trigger Sync. What is the result?",
    correctAnswers: [
      "Neither running instances nor new instances reflect the change until a new runtime model is synced",
      "Without Sync, both running and new instances keep ignoring the edit",
      "If you do not Sync, the change is not reflected for running or new instances",
      "Unsynced edits do not affect instances until a new runtime model is generated",
    ],
    incorrectAnswers: [
      "Running instances update immediately, but new instances wait for Sync",
      "New instances update immediately, but running instances archive themselves",
      "Both running and new instances automatically read the editor draft",
      "The model editor refuses to save unless the instance is terminated first",
      "Only participant steps update immediately without Sync",
      "Only Cloud Service author instances pick up the unsynced change",
      "Unsynced changes are applied only after a launcher fires twice",
      "The edit affects only Legacy workflows and no other workflow type",
    ],
    explanation:
      "The speech says that if you edit a model but do not Sync, running instances and new instances do not reflect the change.",
  },
  {
    id: "wf-019",
    topic: "Runtime Models and Sync",
    question: "What happens if a runtime model is generated after a workflow instance has already started?",
    correctAnswers: [
      "That later runtime model is not applied to the instance that already started",
      "An instance does not switch to runtime models generated after it begins",
      "Later runtime model generations do not affect an already running instance",
      "Once started, the instance keeps its original runtime model rather than adopting later synced versions",
    ],
    incorrectAnswers: [
      "The running instance pauses and migrates to the latest runtime model",
      "The instance applies later runtime models only after a participant approval",
      "The instance reloads later runtime models when it reaches an AND Split",
      "Later runtime models are applied only to terminated instances on restart",
      "The instance always merges the latest model with its archived history",
      "Later runtime models replace only the start node and end node",
      "The instance adopts later runtime models only if the payload is a URL",
      "The instance picks up later runtime models after each suspend and resume",
    ],
    explanation:
      "Section 3 says edits made, or runtime models generated, after an instance has started are not applied to that instance.",
  },
  {
    id: "wf-020",
    topic: "Runtime Models and Sync",
    question: "What is the exception to the rule that started instances do not pick up later changes?",
    correctAnswers: [
      "Changes to the underlying ECMA scripts are picked up",
      "The exception is that updated ECMA scripts are still picked up",
      "Underlying ECMA script changes are the exception and do take effect",
      "Started instances do not take later model changes, except for the shared underlying ECMA scripts",
    ],
    incorrectAnswers: [
      "Changes to transition rules are always picked up without Sync",
      "Changes to start and end nodes are always picked up at resume time",
      "Changes to participant assignees are always pushed into live instances",
      "Changes to launcher paths automatically update running instances",
      "Changes to process.label automatically migrate every active instance",
      "Changes to workflow stages replace the original model immediately",
      "Changes to Cloud Manager packages rewrite live work items automatically",
      "Changes to archived history are reapplied as live runtime updates",
    ],
    explanation:
      "The speech gives one exception: the underlying ECMA scripts are held only once, so changes to them are picked up.",
  },
  {
    id: "wf-021",
    topic: "Runtime Models and Sync",
    question: "What does the Legacy workflow type indicate in the console?",
    correctAnswers: [
      "Legacy workflows were created in a prior version of AEM",
      "The Legacy type means the workflow was created in an earlier AEM version",
      "Legacy indicates a model created in a prior version of AEM",
      "In the console, Legacy marks workflows created in an older AEM version",
    ],
    incorrectAnswers: [
      "Legacy means the model is out-of-the-box and uncustomized",
      "Legacy means the workflow has no indicator because it is custom",
      "Legacy means the model has never been synced to runtime",
      "Legacy means the workflow runs only on publish instances",
      "Legacy means the model is stored under /conf/global/settings/workflow/launcher",
      "Legacy means the workflow is transient and keeps no history",
      "Legacy means the process step is implemented only with ECMA scripts",
      "Legacy means the model cannot be started manually by a user",
    ],
    explanation:
      "Section 3 says the console types are Default, Custom, and Legacy, and that Legacy workflows were created in a prior version of AEM.",
  },

  // ── WORKFLOW STEP TYPES (7) ──────────────────────────────────────────────

  {
    id: "wf-022",
    topic: "Workflow Step Types",
    question: "Which step type should be used when a person must complete assigned work before the workflow can continue?",
    correctAnswers: [
      "A Participant step generates a work item for a user or group and waits for a person",
      "Use a Participant step because it assigns a work item to a user or group for human completion",
      "The correct step is a Participant step, which requires a person to complete the work item",
      "Choose a Participant step when the workflow must wait for a user or group assignment to be completed",
    ],
    incorrectAnswers: [
      "Use a Process step because it runs automatically with no person involved",
      "Use a Container step because it only starts a sub-workflow automatically",
      "Use an OR Split because it only chooses the next branch logically",
      "Use an AND Join because it merges simultaneous branches automatically",
      "Use a Goto Step because it skips human assignment completely",
      "Use a workflow launcher because it reacts only to repository events",
      "Use a runtime model because it is what users complete in the inbox",
      "Use a transient flag because it creates human work items faster",
    ],
    explanation:
      "Participant steps generate a work item, assign it to a user or group, and require a person to complete that item before the workflow advances.",
  },
  {
    id: "wf-023",
    topic: "Workflow Step Types",
    question: "Which step type runs automatically by the system and can be implemented in Java or ECMA script?",
    correctAnswers: [
      "A Process step runs automatically and is implemented by an ECMA script or a Java class",
      "Use a Process step for automatic execution by the system",
      "The automatic step type is the Process step, implemented in ECMA script or Java",
      "A Process step is the system-executed step type and can be backed by Java or ECMA script",
    ],
    incorrectAnswers: [
      "A Participant step runs automatically and never needs user assignment",
      "A Dynamic Participant step is only for static Java classes with no runtime choice",
      "A Container step edits the current model instead of running code",
      "An OR Join is the only step type that can execute Java logic",
      "An AND Split is used to store process arguments in MetaDataMap",
      "A workflow stage is the executable step type for Java classes",
      "A launcher is the step type for running ECMA scripts inside a model",
      "A transition is the automatic step type that replaces process steps",
    ],
    explanation:
      "Section 4 says Process steps are executed automatically by the system and are implemented either by an ECMA script or a Java class.",
  },
  {
    id: "wf-024",
    topic: "Workflow Step Types",
    question: "What does a Container step do?",
    correctAnswers: [
      "A Container step starts another workflow model as a sub-workflow",
      "It launches another workflow model as a sub-workflow",
      "A Container step is used to start a separate workflow model inside the current flow",
      "The Container step starts another workflow model as a nested sub-workflow",
    ],
    incorrectAnswers: [
      "It packages multiple selected resources for Multi Resource Support",
      "It archives terminated instances into /var/workflow/models",
      "It converts a participant step into a transient step",
      "It chooses users dynamically for inbox assignment",
      "It rewrites fragment HTML for third-party delivery",
      "It generates the runtime model when Sync is clicked",
      "It applies rules to transitions between consecutive steps only",
      "It exposes launcher conditions for repository events",
    ],
    explanation:
      "The lesson says Container steps start another workflow model as a sub-workflow.",
  },
  {
    id: "wf-025",
    topic: "Workflow Step Types",
    question: "A scenario requires logic to choose which step should execute next. Which step type fits best?",
    correctAnswers: [
      "An OR Split and Join uses logic to decide which step to execute next",
      "Use OR Split and Join because it chooses the next step through logic",
      "The correct choice is OR Split and Join for logic-based branching",
      "OR Split and Join is the step type for deciding the next step logically",
    ],
    incorrectAnswers: [
      "Use AND Split and Join because it always runs every branch simultaneously",
      "Use a Participant step because it only waits for human completion",
      "Use a Container step because it only starts a sub-workflow",
      "Use a launcher because it only reacts to repository events",
      "Use a workflow stage because it only groups steps conceptually",
      "Use a runtime model because it does not branch at step level",
      "Use a Goto Step because the speech recommends it for transient branching",
      "Use process.label because it only changes a step's display name",
    ],
    explanation:
      "Section 4 says OR Split and Join use logic to decide which step to execute next.",
  },
  {
    id: "wf-026",
    topic: "Workflow Step Types",
    question: "Which step type allows multiple steps to run simultaneously?",
    correctAnswers: [
      "AND Split and Join allow multiple steps to run simultaneously",
      "Use AND Split and Join for simultaneous execution of multiple steps",
      "The step type for parallel execution is AND Split and Join",
      "AND Split and Join are used when several steps should run at the same time",
    ],
    incorrectAnswers: [
      "OR Split and Join, because it always runs every branch in parallel",
      "Participant steps, because multiple users always work at once",
      "Process steps, because they merge all branches automatically",
      "Container steps, because sub-workflows replace parallel execution",
      "Workflow launchers, because event listeners run all steps simultaneously",
      "Workflow stages, because stage labels are concurrent execution nodes",
      "Sync, because generating a runtime model starts every step together",
      "Goto Step, because it duplicates the work item into parallel branches",
    ],
    explanation:
      "The speech states that AND Split and Join allow multiple steps to run simultaneously.",
  },
  {
    id: "wf-027",
    topic: "Workflow Step Types",
    question: "Which properties are shared by all workflow steps?",
    correctAnswers: [
      "All steps share Autoadvance and Timeout alerts, and the timeouts are scriptable",
      "The common properties are Autoadvance and Timeout alerts, with scriptable timeouts",
      "Every step has Autoadvance and Timeout alerts as shared properties",
      "Autoadvance and Timeout alerts are common to all steps, and timeout handling is scriptable",
    ],
    incorrectAnswers: [
      "All steps share process.label and Allowed Templates as common properties",
      "All steps share GraphQL queries and JSON Exporter selectors",
      "All steps share package filters and Cloud Manager pipeline IDs",
      "All steps share sling:resourceSuperType and cq:dialog inheritance",
      "All steps share replica agents and dispatcher flush settings",
      "All steps share fragment variations and social renditions",
      "All steps share Content Fragment models and element definitions",
      "All steps share only a start node and end node property",
    ],
    explanation:
      "Section 4 says all steps share the common properties Autoadvance and Timeout alerts, and that timeouts are scriptable.",
  },
  {
    id: "wf-028",
    topic: "Workflow Step Types",
    question: "How does the Dynamic Participant step determine the assignee?",
    correctAnswers: [
      "It uses a service or script to choose the user at runtime instead of a fixed user",
      "The Dynamic Participant step picks the assignee at runtime through a service or script",
      "It determines the recipient with runtime logic rather than a fixed user",
      "A Dynamic Participant step uses a service or script to select the user who receives the work item",
    ],
    incorrectAnswers: [
      "It always assigns the work item to the last user who synced the model",
      "It always assigns the work item to every member of a group at once",
      "It chooses the assignee only from workflow stages defined in the model",
      "It assigns the work item based only on Cloud Manager environment type",
      "It stores the user in /var/workflow/models and reads it from there",
      "It can assign only to launchers because participant steps do not use users",
      "It uses only a package path and cannot rely on service logic",
      "It selects the assignee by converting the payload into a serialized fragment",
    ],
    explanation:
      "The Dynamic Participant step uses a service or script to choose the user who receives the work item at runtime instead of using a fixed user.",
  },

  // ── TRANSIENT, MULTI RESOURCE AND STAGES (8) ─────────────────────────────

  {
    id: "wf-029",
    topic: "Transient, Multi Resource and Stages",
    question: "What is the key difference between a standard workflow and a transient workflow?",
    correctAnswers: [
      "A transient workflow does not persist runtime history while it runs",
      "Transient workflows are flagged so runtime history is not persisted",
      "The key difference is that transient models avoid persisting runtime history during execution",
      "Standard workflows save runtime history, but transient workflows do not persist that history while running",
    ],
    incorrectAnswers: [
      "A transient workflow can never contain process steps",
      "A transient workflow always runs only on publish instances",
      "A transient workflow stores extra history for every branch transition",
      "A transient workflow replaces the payload with a launcher definition",
      "A transient workflow is the only type that supports participant steps",
      "A transient workflow must be implemented only with Java classes",
      "A transient workflow stores models under /libs instead of /conf",
      "A transient workflow can start only one selected resource per package",
    ],
    explanation:
      "Section 5 says standard workflows save runtime history while they run, while transient workflows are flagged so that the history is not persisted.",
  },
  {
    id: "wf-030",
    topic: "Transient, Multi Resource and Stages",
    question: "Why would a developer choose a transient workflow?",
    correctAnswers: [
      "A transient workflow is a performance tuning option that saves time and resources",
      "Choose a transient workflow to save time and resources when history is not needed",
      "It is used for performance tuning when the workflow runs often and does not need persisted history",
      "Transient workflows are chosen to improve performance by avoiding unnecessary history persistence",
    ],
    incorrectAnswers: [
      "Choose a transient workflow when you need the richest audit history possible",
      "Use a transient workflow when every step must always wait for manual approval",
      "Choose a transient workflow because it is the only way to Sync a model",
      "Use a transient workflow to store custom models permanently under /libs",
      "Choose a transient workflow to force all branches into AND Join logic",
      "Use a transient workflow because it automatically creates workflow launchers",
      "Choose a transient workflow to expose fragments to third parties as HTML",
      "Use a transient workflow only to change the process.label display name",
    ],
    explanation:
      "The speech calls transient workflows a performance tuning option that saves time and resources and says they fit workflows that run often and do not need history.",
  },
  {
    id: "wf-031",
    topic: "Transient, Multi Resource and Stages",
    question: "For what kind of use case were transient workflows introduced?",
    correctAnswers: [
      "Transient workflows were introduced for loading many assets",
      "They were introduced for workflows that load many assets",
      "The speech says transient workflows first came in for loading many assets",
      "Loading many assets is the use case named for the introduction of transient workflows",
    ],
    incorrectAnswers: [
      "They were introduced for editing Experience Fragment templates",
      "They were introduced for publishing Content Fragment models",
      "They were introduced for replacing Cloud Manager pipelines",
      "They were introduced for user synchronization with Admin Console",
      "They were introduced for GraphQL persisted query generation",
      "They were introduced for creating workflow launchers under /libs",
      "They were introduced for rendering third-party HTML offers",
      "They were introduced for enforcing Allowed Templates on folders",
    ],
    explanation:
      "Section 5 explicitly says transient workflows were introduced for loading many assets.",
  },
  {
    id: "wf-032",
    topic: "Transient, Multi Resource and Stages",
    question: "When must runtime information still be persisted even if the model is marked transient because of payload processing needs?",
    correctAnswers: [
      "It must still be persisted when the payload type needs external processing steps, such as video",
      "Transient runtime information is still persisted for payload types like video that need external processing",
      "If the payload requires external processing steps, for example video, persistence is still required",
      "A transient model still persists runtime information when payload processing depends on external steps such as video",
    ],
    incorrectAnswers: [
      "It must still be persisted whenever the payload is a path instead of a UUID",
      "It must still be persisted only when the payload is a Content Fragment",
      "It must still be persisted whenever the payload is stored under /conf",
      "It must still be persisted only if the payload is a serialized Java object",
      "It must still be persisted whenever the payload belongs to a custom workflow type",
      "It must still be persisted only after the workflow instance is archived",
      "It must still be persisted whenever the payload is delivered to a third party",
      "It must still be persisted only if the payload starts in a launcher folder",
    ],
    explanation:
      "The speech lists payload types such as video that need external processing steps as one case where runtime information must still be persisted even for transient workflows.",
  },
  {
    id: "wf-033",
    topic: "Transient, Multi Resource and Stages",
    question: "What happens to persistence behavior when a transient workflow enters an AND Split?",
    correctAnswers: [
      "Runtime information must still be persisted when a transient workflow enters an AND Split",
      "Entering an AND Split is one of the cases where transient workflows still persist runtime information",
      "A transient workflow still persists runtime information at an AND Split",
      "AND Split is an exception where transient execution still requires persistence",
    ],
    incorrectAnswers: [
      "An AND Split removes the payload so no persistence is possible",
      "Entering an AND Split converts the model into a launcher definition",
      "An AND Split disables all workflow history permanently",
      "Entering an AND Split forces the model back into editor draft mode",
      "An AND Split changes the model type from Default to Legacy",
      "Entering an AND Split writes the model into /libs for faster access",
      "An AND Split is recommended specifically to avoid any persistence",
      "An AND Split can occur only in non-versioned workflows",
    ],
    explanation:
      "Section 5 names entering an AND Split as a case where runtime information must still be persisted even when the model is transient.",
  },
  {
    id: "wf-034",
    topic: "Transient, Multi Resource and Stages",
    question: "What happens when a transient workflow reaches a participant step?",
    correctAnswers: [
      "It changes at runtime to non-transient because a person is involved",
      "A transient workflow becomes non-transient at a participant step",
      "When a participant step is reached, the workflow changes to non-transient at runtime",
      "Reaching a participant step makes the transient workflow switch to non-transient because human work is involved",
    ],
    incorrectAnswers: [
      "It skips the participant step and stays fully transient",
      "It turns the participant step into an OR Split automatically",
      "It archives the instance immediately and ends the workflow",
      "It converts the assignee into a launcher path condition",
      "It removes all work items and restarts from the start node",
      "It stores the assignee only in process.label with no inbox item",
      "It changes from Custom to Default workflow type in the console",
      "It forces the payload to become a serialized Java object",
    ],
    explanation:
      "The speech says that when a transient workflow reaches a participant step, it changes at runtime to non-transient because a person is involved.",
  },
  {
    id: "wf-035",
    topic: "Transient, Multi Resource and Stages",
    question: "Why should a Goto Step not be used in a transient workflow, and what should be used instead?",
    correctAnswers: [
      "Do not use Goto Step in a transient workflow; use an OR Split instead",
      "Goto Step should be avoided because it creates a Sling job and defeats the transient purpose, so use OR Split",
      "In transient workflows, Goto Step is wrong because it generates a Sling job and log error; choose OR Split",
      "The recommended replacement for Goto Step in a transient workflow is OR Split because Goto defeats transience",
    ],
    incorrectAnswers: [
      "Do not use Goto Step in a transient workflow; use AND Split because it removes all persistence",
      "Goto Step is required in transient workflows because it keeps runtime history out of the repository",
      "Use Goto Step only with participant steps because OR Split cannot branch",
      "Replace Goto Step with a launcher because launchers are inside every workflow model",
      "Replace Goto Step with Sync because syncing decides runtime branches",
      "Replace Goto Step with process.label because labels redirect the flow",
      "Goto Step is recommended in transient workflows because it never creates Sling jobs",
      "Use a Container step because OR Split cannot make choices in a model",
    ],
    explanation:
      "Section 5 says Goto Step creates a Sling job to continue at the target step, which defeats the purpose of being transient and generates an error in the log. It recommends using an OR Split instead.",
  },
  {
    id: "wf-036",
    topic: "Transient, Multi Resource and Stages",
    question: "What does Multi Resource Support do when several resources are selected?",
    correctAnswers: [
      "Multi Resource Support starts one workflow instance and attaches each selected resource as a package",
      "It creates a single workflow instance for multiple selected resources and packages each resource with it",
      "With Multi Resource Support, one instance starts for several selected resources rather than one per resource",
      "It means multiple selected resources are handled by one workflow instance, with each attached as a package",
    ],
    incorrectAnswers: [
      "It starts one workflow instance per selected resource and disables packaging",
      "It turns several selected resources into separate runtime models",
      "It stores each selected resource as a launcher condition instead of a payload",
      "It requires every selected resource to be converted into an ECMA script",
      "It groups selected resources only for visual stages and not for execution",
      "It allows only a single resource and rejects multiple selections",
      "It runs the workflow only if every selected resource is under /libs",
      "It archives selected resources into the workflow inbox for manual pickup",
    ],
    explanation:
      "The speech says Multi Resource Support starts a single workflow instance when several resources are selected and attaches each resource as a package.",
  },
  {
    id: "wf-037",
    topic: "Custom Process Steps in Java",
    question: "What does WorkflowSession provide to a custom Java process step?",
    correctAnswers: [
      "WorkflowSession gives access to workflow operations",
      "A WorkflowSession provides access to workflow operations",
      "The WorkflowSession is the object that gives workflow operations access",
      "In a custom step, WorkflowSession is used for workflow operations",
    ],
    incorrectAnswers: [
      "WorkflowSession exists only to hold the process.label display string",
      "WorkflowSession stores custom models under /conf/global/settings/workflow/models",
      "WorkflowSession is the launcher definition that listens for repository events",
      "WorkflowSession is the ECMA variable that holds process arguments directly",
      "WorkflowSession is the stage label shown to users during workflow progress",
      "WorkflowSession is the package of selected resources used by Multi Resource Support",
      "WorkflowSession is the immutable runtime model stored under /libs",
      "WorkflowSession is the Transition object that decides the next step",
    ],
    explanation:
      "Section 7 says the WorkflowSession gives access to workflow operations in a custom Java process step.",
  },

  // ── WORKFLOWS IN CLOUD SERVICE (7) ───────────────────────────────────────

  {
    id: "wf-038",
    topic: "Workflows in Cloud Service",
    question: "In AEM as a Cloud Service, how are workflow models and launchers classified and where does that configuration live?",
    correctAnswers: [
      "Workflow models and launchers are configuration, and that configuration lives under /conf",
      "In Cloud Service, models and launchers are configuration stored under /conf",
      "They are treated as configuration, with configuration living in /conf",
      "AEM as a Cloud Service keeps workflow models and launchers as configuration under /conf",
    ],
    incorrectAnswers: [
      "Workflow models and launchers are content, and they live only under /content",
      "They are immutable binaries that must live under /libs",
      "They are author inbox entries stored only under /home",
      "They are runtime logs that belong exclusively under /var/log",
      "They are package definitions that live only in pom.xml",
      "They are cloud pipeline steps stored only in GitHub Actions",
      "They are replication agents kept under /etc/replication",
      "They are JCR sessions stored only in memory on author",
    ],
    explanation:
      "Section 6 says that in AEM as a Cloud Service, models and launchers are configuration, and configuration lives under /conf.",
  },
  {
    id: "wf-039",
    topic: "Workflows in Cloud Service",
    question: "Where are custom workflow models stored in AEM as a Cloud Service?",
    correctAnswers: [
      "Custom workflow models are stored under /conf/global/settings/workflow/models",
      "The Cloud Service path for custom models is /conf/global/settings/workflow/models",
      "Store custom workflow models in /conf/global/settings/workflow/models",
      "In Cloud Service, custom workflow models live at /conf/global/settings/workflow/models",
    ],
    incorrectAnswers: [
      "Custom workflow models are stored under /libs/settings/workflow/models",
      "Custom workflow models are stored under /apps/global/settings/workflow/models",
      "Custom workflow models are stored under /var/workflow/models as the source of truth",
      "Custom workflow models are stored under /content/workflow/models",
      "Custom workflow models are stored under /etc/workflow/models",
      "Custom workflow models are stored under /home/users/workflow/models",
      "Custom workflow models are stored under /oak:index/workflow/models",
      "Custom workflow models are stored under /conf/global/settings/launcher/models",
    ],
    explanation:
      "The speech gives the exact Cloud Service location for custom workflow models as /conf/global/settings/workflow/models.",
  },
  {
    id: "wf-040",
    topic: "Workflows in Cloud Service",
    question: "Where are workflow launchers stored in AEM as a Cloud Service?",
    correctAnswers: [
      "Workflow launchers are stored under /conf/global/settings/workflow/launcher",
      "The Cloud Service path for launchers is /conf/global/settings/workflow/launcher",
      "Store workflow launchers in /conf/global/settings/workflow/launcher",
      "In Cloud Service, workflow launchers live at /conf/global/settings/workflow/launcher",
    ],
    incorrectAnswers: [
      "Workflow launchers are stored under /var/workflow/launcher",
      "Workflow launchers are stored under /libs/workflow/launcher",
      "Workflow launchers are stored under /apps/settings/workflow/launcher",
      "Workflow launchers are stored under /content/launchers",
      "Workflow launchers are stored under /conf/global/settings/workflow/models",
      "Workflow launchers are stored under /etc/launchers/workflow",
      "Workflow launchers are stored under /home/workflow/launchers",
      "Workflow launchers are stored under /system/workflow/launcher",
    ],
    explanation:
      "Section 6 says workflow launchers are stored under /conf/global/settings/workflow/launcher.",
  },
  {
    id: "wf-041",
    topic: "Workflows in Cloud Service",
    question: "Where should custom workflow models never be placed in Cloud Service, and why?",
    correctAnswers: [
      "Never place custom workflow models in /libs because /apps and /libs are immutable",
      "Custom models must not go in /libs, since those repository areas are immutable",
      "Do not place custom workflow models under /libs because Cloud Service treats it as immutable",
      "The forbidden location is /libs, because immutable areas are not for custom workflow models",
    ],
    incorrectAnswers: [
      "Never place custom workflow models in /conf because configuration must stay empty",
      "Never place custom workflow models in /var because it is the only mutable source of truth",
      "Never place custom workflow models in /content because pages cannot reference them",
      "Never place custom workflow models in /home because users need direct edit access",
      "Never place custom workflow models in /oak:index because indexes are required for launchers",
      "Never place custom workflow models in /system because Cloud Manager stores code only there",
      "Never place custom workflow models in /etc because /etc is the required immutable root",
      "Never place custom workflow models in /conf/global because launchers only work from /apps",
    ],
    explanation:
      "The speech explicitly warns never to place custom models in /libs because /apps and /libs are immutable in Cloud Service.",
  },
  {
    id: "wf-042",
    topic: "Workflows in Cloud Service",
    question: "How are workflow models and launchers deployed in AEM as a Cloud Service?",
    correctAnswers: [
      "They are deployed as code through the Cloud Manager pipeline as part of the project packages",
      "Models and launchers are deployed as code via the Cloud Manager pipeline",
      "In Cloud Service, workflow configuration is delivered through project packages in Cloud Manager",
      "The deployment method is code-based deployment through the Cloud Manager pipeline",
    ],
    incorrectAnswers: [
      "They are deployed only by manually editing CRXDE on production author",
      "They are deployed only through the workflow inbox by administrators",
      "They are deployed only when a participant step is completed",
      "They are deployed through the Content Fragment console as assets",
      "They are deployed only by exporting a ZIP from /var/workflow/models",
      "They are deployed only by restarting the author instance",
      "They are deployed only from the Experience Fragments rewriter configuration",
      "They are deployed automatically from the launcher event without packages",
    ],
    explanation:
      "Section 6 states that models and launchers are deployed as code through the Cloud Manager pipeline, as part of the project packages.",
  },
  {
    id: "wf-043",
    topic: "Workflows in Cloud Service",
    question: "Where is the runtime model generated for running instances when the model is synced in Cloud Service?",
    correctAnswers: [
      "The runtime model is generated under /var/workflow/models when the model is synced",
      "Synced runtime models are generated in /var/workflow/models",
      "Running instances use a runtime model generated under /var/workflow/models",
      "When synced, the runtime model is created beneath /var/workflow/models",
    ],
    incorrectAnswers: [
      "The runtime model is generated under /conf/global/settings/workflow/runtime",
      "The runtime model is generated under /libs/workflow/models",
      "The runtime model is generated under /apps/workflow/models",
      "The runtime model is generated under /content/workflow/runtime",
      "The runtime model is generated under /etc/workflow/instances",
      "The runtime model is generated under /home/users/workflow/models",
      "The runtime model is generated under /system/workflow/runtime",
      "The runtime model is generated only in memory and has no repository path",
    ],
    explanation:
      "The speech says that the runtime model used by running instances is generated under /var/workflow/models when the model is synced.",
  },
  {
    id: "wf-044",
    topic: "Workflows in Cloud Service",
    question: "What does a workflow launcher do, and which conditions does it define?",
    correctAnswers: [
      "A launcher starts a workflow automatically on matching repository events and defines the event type, node type, path, and model",
      "It automatically starts a workflow when a repository event matches its conditions, including event type, node type, path, and model",
      "A workflow launcher reacts to repository events and specifies the event type, node type, path, and workflow model to start",
      "Launchers are automatic starters for workflows based on matching repository events, with conditions for event type, node type, path, and model",
    ],
    incorrectAnswers: [
      "A launcher archives completed workflow instances and defines only timeout alerts",
      "A launcher stores process arguments and defines only PROCESS_ARGS values",
      "A launcher replaces Sync and defines only the runtime model version number",
      "A launcher chooses participant users and defines only group memberships",
      "A launcher packages multiple selected resources and defines only stage names",
      "A launcher overlays /libs components and defines only sling:resourceSuperType",
      "A launcher renders Experience Fragments and defines only allowed HTML tags",
      "A launcher externalizes links and defines only protocol and host mappings",
    ],
    explanation:
      "Section 6 says a workflow launcher starts a workflow automatically when a repository event occurs on a matching path and defines the event type, node type, path, and model to start.",
  },

  // ── CUSTOM PROCESS STEPS IN JAVA (7) ─────────────────────────────────────

  {
    id: "wf-045",
    topic: "Custom Process Steps in Java",
    question: "How is a custom process step implemented in Java?",
    correctAnswers: [
      "A custom process step is implemented as an OSGi service that implements WorkflowProcess",
      "Implement it as an OSGi service implementing the WorkflowProcess interface",
      "The Java implementation is an OSGi service for the WorkflowProcess interface",
      "A custom Java process step is an OSGi service that implements WorkflowProcess",
    ],
    incorrectAnswers: [
      "A custom process step is implemented as a workflow launcher under /conf only",
      "A custom process step is implemented as a Content Fragment model",
      "A custom process step is implemented as an Experience Fragment template",
      "A custom process step is implemented as a package filter definition",
      "A custom process step is implemented as a workflow inbox group mapping",
      "A custom process step is implemented as an AND Split transition rule only",
      "A custom process step is implemented as a Cloud Manager environment variable",
      "A custom process step is implemented as an editable template policy",
    ],
    explanation:
      "Section 7 says a custom process step is implemented as an OSGi service that implements the WorkflowProcess interface.",
  },
  {
    id: "wf-046",
    topic: "Custom Process Steps in Java",
    question: "What is the execute method signature conceptually required by WorkflowProcess?",
    correctAnswers: [
      "The execute method receives a WorkItem, a WorkflowSession, and a MetaDataMap, and may throw a WorkflowException",
      "WorkflowProcess.execute takes WorkItem, WorkflowSession, and MetaDataMap and may throw WorkflowException",
      "Its single execute method is passed WorkItem, WorkflowSession, and MetaDataMap, with WorkflowException possible",
      "The required execute method accepts WorkItem, WorkflowSession, and MetaDataMap and can throw WorkflowException",
    ],
    incorrectAnswers: [
      "The execute method receives only a ResourceResolver and never throws exceptions",
      "The execute method receives a Page, a SlingRequest, and a ValueMap",
      "The execute method receives a Fragment, a Template, and a Selector string",
      "The execute method receives only a JCR Session and a launcher path",
      "The execute method receives a ModelEditor, a Transition, and a Timeout alert",
      "The execute method receives a WorkflowModel and returns the synced runtime model",
      "The execute method receives only PROCESS_ARGS as a plain string array",
      "The execute method receives a Package and deploys it through Cloud Manager",
    ],
    explanation:
      "The speech says WorkflowProcess has a single execute method that receives a WorkItem, a WorkflowSession, and a MetaDataMap, and may throw a WorkflowException.",
  },
  {
    id: "wf-047",
    topic: "Custom Process Steps in Java",
    question: "How is the Java service registered so authors see a friendly step name in the Process Step dialog?",
    correctAnswers: [
      "Register it as an OSGi Declarative Services component and set process.label for the display name",
      "Use the OSGi Declarative Services annotation and provide a process.label property",
      "The service is registered as a WorkflowProcess component, and process.label supplies the dialog name",
      "A friendly Process Step name comes from registering the DS component with the process.label property",
    ],
    incorrectAnswers: [
      "Register it only in /libs and set jcr:title on the runtime model node",
      "Register it as a launcher and use the event type as the dialog name",
      "Register it in Cloud Manager and use the pipeline name as the step label",
      "Register it as an Experience Fragment component and use Allowed Templates",
      "Register it as a Content Fragment model and use the model title",
      "Register it only through cq:editConfig and omit any OSGi component",
      "Register it as a participant group and use the inbox user ID as the label",
      "Register it with a package filter and use the filter root as the display name",
    ],
    explanation:
      "Section 7 says the service is registered with the OSGi Declarative Services annotation as a component with service WorkflowProcess, and process.label gives the step a display name.",
  },
  {
    id: "wf-048",
    topic: "Custom Process Steps in Java",
    question: "What information does the WorkItem give a custom Java process step?",
    correctAnswers: [
      "The WorkItem gives access to the workflow instance and its WorkflowData, which holds the payload",
      "WorkItem provides the workflow instance and WorkflowData containing the payload",
      "A custom step gets the workflow instance and payload-bearing WorkflowData from the WorkItem",
      "Through WorkItem, the step can access the instance and the WorkflowData that holds the payload",
    ],
    incorrectAnswers: [
      "The WorkItem gives only the Cloud Manager pipeline ID and deployment status",
      "The WorkItem gives only the fragment layout and responsive grid settings",
      "The WorkItem gives only the launcher regex and no payload information",
      "The WorkItem gives only the process.label property and no instance reference",
      "The WorkItem gives only package filter roots and installation paths",
      "The WorkItem gives only the GraphQL schema and persisted query list",
      "The WorkItem gives only the Experience Fragment folder permissions",
      "The WorkItem gives only the Sync button state in the model editor",
    ],
    explanation:
      "The speech says the WorkItem gives you the workflow instance and its WorkflowData, and that the WorkflowData holds the payload.",
  },
  {
    id: "wf-049",
    topic: "Custom Process Steps in Java",
    question: "How do you work with repository content from a custom Java process step?",
    correctAnswers: [
      "Use the WorkflowSession and adapt the session to a ResourceResolver or JCR Session",
      "To work with repository content, adapt the session to a ResourceResolver or JCR Session",
      "Repository access comes by using WorkflowSession and adapting it to a ResourceResolver or JCR Session",
      "A custom step works with repository content by adapting the session for a ResourceResolver or JCR Session",
    ],
    incorrectAnswers: [
      "Use only process.label because it exposes repository nodes directly",
      "Use only the launcher path because it becomes a writable JCR session",
      "Use only the workflow inbox because inbox items are repository sessions",
      "Use only the stage name because stages resolve content automatically",
      "Use only the Sync operation because synced models include content handles",
      "Use only the payload URL because AEM forbids session adaptation",
      "Use only Cloud Manager because repository access is unavailable in steps",
      "Use only fragment variations because they replace JCR sessions in workflows",
    ],
    explanation:
      "Section 7 says the WorkflowSession gives access to workflow operations, and for repository content the session can be adapted to a ResourceResolver or JCR Session.",
  },
  {
    id: "wf-050",
    topic: "Custom Process Steps in Java",
    question: "Where do Process Step arguments go, and what are the ECMA script variables for the current work item and arguments?",
    correctAnswers: [
      "Process Step arguments are carried in the MetaDataMap under PROCESS_ARGS, and ECMA scripts use graniteWorkItem and args",
      "Arguments are stored under PROCESS_ARGS in the MetaDataMap, while ECMA scripts use graniteWorkItem for the WorkItem and args for the arguments",
      "The Arguments field ends up under PROCESS_ARGS, and ECMA scripts read graniteWorkItem and args",
      "Step arguments are passed through MetaDataMap with PROCESS_ARGS, and in ECMA the variables are graniteWorkItem and args",
    ],
    incorrectAnswers: [
      "Process Step arguments are stored only in process.label, and ECMA scripts use workflowModel and params",
      "Arguments are written only to /libs, and ECMA scripts use currentNode and options",
      "Arguments go only into the launcher path, and ECMA scripts use workItemId and formData",
      "Arguments are stored only in the workflow inbox, and ECMA scripts use assignee and timeout",
      "Arguments are saved only in the runtime model title, and ECMA scripts use payloadPath and labels",
      "Arguments are stored only in Cloud Manager variables, and ECMA scripts use pipeline and stage",
      "Arguments go only into the start node metadata, and ECMA scripts use resolver and sessionUser",
      "Arguments are stored only as fragment variation names, and ECMA scripts use master and variationArgs",
    ],
    explanation:
      "Section 7 says the MetaDataMap passed to execute carries the step arguments, that Process Step Arguments are stored under the PROCESS_ARGS key, and that ECMA scripts use graniteWorkItem and args.",
  },
]
