import type { TriviaQuestion } from "./trivia-types"

export const dispatcherQuestionsPartB: TriviaQuestion[] = [
  {
    id: "disp-051",
    topic: "Cache Invalidation",
    question: "How does Dispatcher mark cached content as invalid after activation?",
    correctAnswers: [
      "Dispatcher invalidates cached files by touching a .stat file",
      "Cache invalidation works by updating the modification time of a .stat file",
      "Dispatcher marks cache entries stale by touching the relevant .stat file",
      "It invalidates cache through the .stat file timestamp rather than deleting every file immediately",
    ],
    incorrectAnswers: [
      "Dispatcher invalidates cache by renaming every cached file with a .old suffix",
      "It flushes cache only by restarting Apache after each activation",
      "Dispatcher deletes the entire docroot on every page activation",
      "It invalidates content by changing the farm name in dispatcher.any",
      "Dispatcher rewrites activated pages directly into the CDN cache",
      "It updates the Last-Modified header in the browser to invalidate Publish",
      "Dispatcher marks pages stale by editing the virtualhosts list",
      "It invalidates cache only when the render port number changes",
    ],
    explanation:
      "The speech says Dispatcher invalidates files by touching a .stat file and then compares that file's modification date with the cached document's modification date.",
  },
  {
    id: "disp-052",
    topic: "Cache Invalidation",
    question: "What does /statfileslevel control in Dispatcher cache invalidation?",
    correctAnswers: [
      "/statfileslevel limits .stat touching to the docroot-to-resource path depth",
      "It controls how many folder levels receive .stat files for invalidation",
      "The property defines how deep Dispatcher touches .stat files along the resource path",
      "It sets the maximum directory depth used for .stat-based invalidation",
    ],
    incorrectAnswers: [
      "It sets how many publish instances can receive flush requests",
      "It controls the number of farms loaded from enabled_farms",
      "It defines the maximum age of CDN entries in seconds",
      "It limits how many query parameters may be ignored for caching",
      "It chooses the number of rewrite rules allowed in flexible mode",
      "It sets the number of retry attempts for failed render connections",
      "It controls how many client headers Dispatcher forwards",
      "It defines the number of invalidation requests an allowed client may send per minute",
    ],
    explanation:
      "The speech explains that /statfileslevel controls how many folder levels get a .stat file and that only .stat files from docroot down to the file's level, or the configured depth, are touched.",
  },
  {
    id: "disp-053",
    topic: "Cache Invalidation",
    question: "A team configured a custom /statfile name, but Dispatcher still uses .stat files. Why?",
    correctAnswers: [
      "When /statfileslevel is set, Dispatcher ignores /statfile and uses .stat",
      "A configured /statfileslevel makes the /statfile setting irrelevant because .stat is used",
      "Dispatcher falls back to .stat whenever /statfileslevel is configured",
      "The presence of /statfileslevel causes Dispatcher to ignore the custom /statfile property",
    ],
    incorrectAnswers: [
      "Because /statfile is used only in author instances and never in cache docroots",
      "Because /statfile works only when /enableTTL is set to 1",
      "Because custom stat files are allowed only in legacy mode",
      "Because /statfile is overridden only when /allowAuthorized is 1",
      "Because /statfile applies only to CDN invalidation, not Dispatcher invalidation",
      "Because custom stat file names are supported only for POST requests",
      "Because /statfile is ignored whenever the farm includes default_renders.any",
      "Because the Dispatcher validator always rewrites custom stat file names to default.farm",
    ],
    explanation:
      "The source says that if /statfileslevel is set, the /statfile property is ignored and .stat is used.",
  },
  {
    id: "disp-054",
    topic: "Cache Invalidation",
    question: "What happens to auto-invalidated files defined by /invalidate?",
    correctAnswers: [
      "Auto-invalidated files stay on disk and are revalidated on the next request",
      "Dispatcher does not delete auto-invalidated files immediately; it checks validity when requested again",
      "Files matched by /invalidate are marked for revalidation rather than removed at once",
      "An auto-invalidated cache entry remains until the next request triggers a freshness check",
    ],
    incorrectAnswers: [
      "Dispatcher immediately purges matched files and all siblings from disk",
      "The files are moved into enabled_farms until a new deployment restores them",
      "They are converted into vanity URLs until the next author activation",
      "Dispatcher compresses them and serves the archive copy until midnight",
      "They are cached permanently unless a manual POST removes them",
      "The render instance rewrites them in place without any request reaching Dispatcher",
      "They are turned into immutable files inside the SDK framework",
      "Dispatcher sends them directly to the CDN but removes them from the document root",
    ],
    explanation:
      "The speech says auto-invalidated files are not deleted right away; their validity is checked at the next request.",
  },
  {
    id: "disp-055",
    topic: "Cache Invalidation",
    question: "Which pattern is typically used in /invalidate for linked page content?",
    correctAnswers: [
      "A common /invalidate setup denies everything and allows *.html",
      "The usual /invalidate configuration is deny all, then allow HTML pages",
      "Dispatcher commonly auto-invalidates HTML by denying all and allowing *.html",
      "For linked pages, /invalidate is typically configured with a deny-all baseline and an allow for .html",
    ],
    incorrectAnswers: [
      "Allow every file type and deny only HTML so pages stay permanently cached",
      "Deny only ZIP files and allow all images, because pages never link to each other",
      "Allow only POST requests and deny GET so HTML can be invalidated",
      "Match only the CQ-Action header and never file extensions",
      "Deny the docroot and allow the farm name as a path glob",
      "Allow only rewrite.rules and deny dispatcher.any to invalidate page content",
      "Use /virtualhosts instead of /invalidate to decide which HTML pages are invalidated",
      "Allow .stat files only and deny cached documents themselves",
    ],
    explanation:
      "The speech says /invalidate is typically used for HTML pages because pages link to each other, and the usual configuration denies everything and allows *.html.",
  },
  {
    id: "disp-056",
    topic: "Cache Invalidation",
    question: "What is required for a manual Dispatcher flush request?",
    correctAnswers: [
      "A manual flush is an HTTP POST to /dispatcher/invalidate.cache with CQ-Action and CQ-Handle",
      "You flush manually by sending POST /dispatcher/invalidate.cache and the headers CQ-Action and CQ-Handle",
      "Dispatcher manual invalidation requires an HTTP POST plus CQ-Action and CQ-Handle headers",
      "The cache is flushed manually through /dispatcher/invalidate.cache using POST and the CQ-Action and CQ-Handle headers",
    ],
    incorrectAnswers: [
      "A manual flush is a GET to /system/console with Cache-Control and Host headers",
      "It requires a PUT to /dispatcher/flush.any with ETag and If-Modified-Since",
      "Manual invalidation is done by deleting default.vhost and restarting the container",
      "A HEAD request to /libs/granite/dispatcher/content/vanityUrls.html is sufficient",
      "It requires posting only the farm name to /dispatcher/validate.cache",
      "A manual flush is triggered by a browser refresh with the nocache query parameter",
      "It requires an authenticated PATCH request to /bin/replicate.json",
      "A POST to the publish root path without CQ headers performs the same invalidation",
    ],
    explanation:
      "The speech defines a manual flush as an HTTP POST to /dispatcher/invalidate.cache with headers including CQ-Action and CQ-Handle.",
  },
  {
    id: "disp-057",
    topic: "Cache Invalidation",
    question: "Which header value should be used when only the targeted resource should be flushed without invalidating other cache areas?",
    correctAnswers: [
      "CQ-Action-Scope: ResourceOnly flushes only the targeted resource",
      "Use CQ-Action-Scope with the value ResourceOnly to limit the flush to that resource",
      "The ResourceOnly action scope prevents broader cache invalidation",
      "To flush just one resource, set CQ-Action-Scope to ResourceOnly",
    ],
    incorrectAnswers: [
      "Set Cache-Control to no-store so Dispatcher invalidates related pages automatically",
      "Use CQ-Handle-Scope: FarmOnly to keep the invalidation local",
      "Set Surrogate-Control to ResourceOnly so only Dispatcher flushes one item",
      "Use the PATH header with the value ResourceOnly in /clientheaders",
      "Set CQ-Action to LocalOnly so no .stat files are touched",
      "Use Dispatcher-Scope: SingleFile to disable path-based invalidation",
      "Send CQ-Action-Scope: AuthorOnly so Publish nodes are skipped",
      "Use X-Dispatcher-Invalidate: False to avoid invalidating linked resources",
    ],
    explanation:
      "The speech states that the header CQ-Action-Scope with value ResourceOnly flushes a resource without invalidating other parts of the cache.",
  },
  {
    id: "disp-058",
    topic: "Cache Invalidation",
    question: "Why is defining /allowedClients recommended in the cache section?",
    correctAnswers: [
      "Without /allowedClients, any client can clear the cache",
      "The property should be defined so arbitrary clients cannot flush Dispatcher",
      "Defining /allowedClients restricts cache flushes by client IP",
      "It is recommended because otherwise any client can repeatedly clear the cache and hurt performance",
    ],
    incorrectAnswers: [
      "Because /allowedClients is the only place where render hostnames can be configured",
      "Because Dispatcher refuses to serve HTML unless /allowedClients lists localhost",
      "Because the CDN reads /allowedClients to build its cache key",
      "Because /allowedClients controls which browsers may receive Cache-Control headers",
      "Because /allowedClients is required before /ignoreUrlParams can function",
      "Because it determines which farms are loaded from available_farms",
      "Because invalidation requests always originate from anonymous website visitors",
      "Because /allowedClients changes file permissions under the docroot to 0755",
    ],
    explanation:
      "The speech recommends defining /allowedClients because, if it is not defined, any client can clear the cache and repeated flushes can severely hurt performance.",
  },
  {
    id: "disp-059",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "What is the recommended /ignoreUrlParams strategy when most query parameters should not prevent caching?",
    correctAnswers: [
      "Ignore all parameters first, then deny only the ones that must bypass the cache",
      "The recommended pattern is allow * in /ignoreUrlParams and deny only cache-bypassing parameters such as nocache",
      "Use an allowlist that ignores everything by default and blocks caching only for specific parameter names",
      "Start by ignoring all URL parameters, then deny only the parameter names that should prevent caching",
    ],
    incorrectAnswers: [
      "Deny every parameter first and allow only login-token so all pages are cached",
      "Match query parameters only in /filter because /ignoreUrlParams is for headers",
      "Disable /ignoreUrlParams and depend entirely on /virtualhosts for query strings",
      "Allow only the nocache parameter so all other parameters force caching",
      "Configure one rule per page path because wildcards are forbidden in /ignoreUrlParams",
      "Use /headers instead of /ignoreUrlParams to ignore query parameters",
      "Set /allowAuthorized to 1 so query parameters no longer affect caching",
      "Move parameter logic to default_renders.any because cache rules cannot inspect them",
    ],
    explanation:
      "The speech recommends an allowlist approach: ignore everything with an allow rule on *, then deny only parameters that must bypass the cache, such as nocache.",
  },
  {
    id: "disp-060",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "A request URL has three query parameters, and one of them is not ignored by /ignoreUrlParams. What happens?",
    correctAnswers: [
      "If any parameter is not ignored, the page is not cached",
      "One non-ignored query parameter is enough to prevent caching",
      "Dispatcher caches the page only when all URL parameters are ignored",
      "The presence of a single non-ignored parameter makes the request non-cacheable",
    ],
    incorrectAnswers: [
      "Dispatcher caches the page as long as most parameters are ignored",
      "Only the first query parameter matters for cacheability",
      "The page is cached, but only for authenticated users",
      "Dispatcher caches the HTML but not the response headers",
      "The page is cached only after a second identical request",
      "A non-ignored parameter affects only CDN caching, not Dispatcher caching",
      "Dispatcher ignores all parameters when /enableTTL is set to 1",
      "The request is routed to Author instead of Publish when one parameter is denied",
    ],
    explanation:
      "The source says that if all parameters are ignored, the page is cached, but if any parameter is not ignored, the page is not cached.",
  },
  {
    id: "disp-061",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "What is the purpose of the /headers property in the Dispatcher cache configuration?",
    correctAnswers: [
      "/headers tells Dispatcher which response headers to store with the cached file and add back later",
      "It defines the response headers Dispatcher persists next to cached content for later responses",
      "Dispatcher uses /headers to save selected backend response headers alongside cache entries",
      "The property controls which response headers are retained and reapplied when serving cached files",
    ],
    incorrectAnswers: [
      "It lists the only request headers allowed to reach Publish",
      "It defines which browser headers can trigger manual invalidation",
      "It chooses which Apache directives are immutable in Cloud Service",
      "It controls the order of farms evaluated for virtual host matching",
      "It specifies which query parameters are copied into the cache key",
      "It stores author replication credentials for flush agents",
      "It decides which .stat files are touched during activation",
      "It names the symbolic links allowed under enabled_vhosts",
    ],
    explanation:
      "The speech says /headers lists the response headers Dispatcher stores next to the cached file and adds on later responses.",
  },
  {
    id: "disp-062",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "What must be done if a project wants Dispatcher to store ETag values for cached responses?",
    correctAnswers: [
      "Add ETag to /headers and set the Apache directive FileETag none",
      "To store ETag, include it in /headers and configure FileETag none in Apache",
      "ETag persistence requires both a /headers entry for ETag and FileETag none",
      "Dispatcher stores ETag correctly only when ETag is listed in /headers and Apache uses FileETag none",
    ],
    incorrectAnswers: [
      "Enable /allowAuthorized and add ETag to /clientheaders",
      "Add ETag to /ignoreUrlParams and leave FileETag at its default",
      "Configure ETag in /virtualhosts and remove Cache-Control from /headers",
      "Use default_invalidate.any instead of FileETag so ETag is generated",
      "Set /mode to 0644 and ETag will be stored automatically",
      "Move ETag handling to the CDN because Dispatcher cannot persist it",
      "Add ETag to rewrite.rules and set FileETag all",
      "Store ETag in CQ-Action-Scope so it survives invalidation",
    ],
    explanation:
      "The speech explicitly says that to store ETag, you must add it to /headers and set the Apache directive FileETag none.",
  },
  {
    id: "disp-063",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "How does Dispatcher implement time-based invalidation when /enableTTL is set to 1?",
    correctAnswers: [
      "Dispatcher reads Cache-Control max-age or Expires and creates an auxiliary file whose mtime equals the expiry",
      "TTL caching works by deriving expiry from max-age or Expires and storing it in an empty helper file",
      "With /enableTTL, Dispatcher uses backend expiry headers and an auxiliary file timestamp to know when to refetch",
      "It enables time-based invalidation by creating an empty side file dated to the response expiry time",
    ],
    incorrectAnswers: [
      "Dispatcher rewrites every cached HTML page every second until it expires",
      "It stores TTL only in browser cookies and never in the cache docroot",
      "TTL mode works only when /statfileslevel is removed from the farm",
      "Dispatcher calculates expiry only from the request URL extension",
      "It uses the Apache process start time as the expiration timestamp",
      "TTL invalidation requires a manual POST to /dispatcher/invalidate.cache for each entry",
      "Dispatcher copies the expiry into the farm name and reloads httpd at that moment",
      "It reads only Surrogate-Control and ignores Cache-Control max-age and Expires",
    ],
    explanation:
      "The speech says /enableTTL reads Cache-Control max-age or Expires from the backend response and creates an empty auxiliary file whose modification time equals the expiry.",
  },
  {
    id: "disp-064",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "What does /allowAuthorized control?",
    correctAnswers: [
      "/allowAuthorized controls whether requests carrying authentication information may be cached",
      "It determines if requests with auth headers or auth cookies are cacheable",
      "The property decides whether authenticated traffic can be stored in Dispatcher cache",
      "It governs caching for requests containing Authorization, authorization, or login-token credentials",
    ],
    incorrectAnswers: [
      "It determines which administrators may edit immutable files in Cloud Service",
      "It controls whether Publish accepts HTTPS connections from Dispatcher",
      "It specifies which IP addresses may reach /dispatcher/invalidate.cache",
      "It chooses whether ETag headers are stored with cached files",
      "It enables relative symbolic links in enabled_vhosts",
      "It decides whether HTML receives Surrogate-Control at the CDN",
      "It sets the timeout for authenticated render connections",
      "It controls whether query parameters are part of the cache key",
    ],
    explanation:
      "The speech says /allowAuthorized controls whether requests with authentication information are cached, including the Authorization header and cookies named authorization or login-token.",
  },
  {
    id: "disp-065",
    topic: "URL Parameters, Headers, TTL and Authentication",
    question: "Why must /allowAuthorized remain 0 when Dispatcher session management is used?",
    correctAnswers: [
      "Session management requires /allowAuthorized to stay at 0",
      "When using session management, authenticated requests must not be cached, so /allowAuthorized must be 0",
      "The speech says session management depends on /allowAuthorized being disabled",
      "For Dispatcher session management, /allowAuthorized cannot be enabled",
    ],
    incorrectAnswers: [
      "Because session management works only when authenticated requests are cached forever",
      "Because session management requires FileETag none instead of auth checks",
      "Because session management is available only in legacy mode farms",
      "Because session management is implemented through default_virtualhosts.any",
      "Because the CDN refuses to cache any response unless /allowAuthorized is 1",
      "Because /allowAuthorized changes POST requests into GET requests",
      "Because sessions can exist only when /mode is set to 0600",
      "Because session management uses the same property as /gracePeriod",
    ],
    explanation:
      "The source explicitly states that session management requires /allowAuthorized to be 0.",
  },
  {
    id: "disp-066",
    topic: "Invalidating from Author or Publish",
    question: "What does the standard Dispatcher Flush agent do when it is configured on Author?",
    correctAnswers: [
      "On Author, the standard Dispatcher Flush agent sends an invalidation request when a page is activated",
      "The default flush agent on Author triggers Dispatcher cache invalidation during page activation",
      "It sends a Dispatcher invalidation request from Author whenever content is activated",
      "Configured on Author, the flush agent clears Dispatcher cache as part of activation",
    ],
    incorrectAnswers: [
      "It copies cached HTML from Publish back into Author after activation",
      "It creates virtual hosts automatically whenever a new site is activated",
      "It disables Dispatcher caching so Publish always renders fresh pages",
      "It pushes default_vhost files into enabled_vhosts during replication",
      "It updates the CDN cache key to match the activated page path",
      "It replaces the replication queue with /ignoreUrlParams rules",
      "It writes activation history directly into dispatcher.any",
      "It restarts each publish instance before cache can be invalidated",
    ],
    explanation:
      "The speech says the standard Dispatcher Flush agent is installed by default and, when configured on Author, sends an invalidation request to Dispatcher when a page is activated.",
  },
  {
    id: "disp-067",
    topic: "Invalidating from Author or Publish",
    question: "Where should the Transport URI of a standard Dispatcher Flush agent point?",
    correctAnswers: [
      "The Transport URI should point to /dispatcher/invalidate.cache on the Dispatcher host",
      "A standard flush agent posts to the Dispatcher host at /dispatcher/invalidate.cache",
      "Its transport target is the Dispatcher endpoint /dispatcher/invalidate.cache",
      "The correct Transport URI is the Dispatcher host plus /dispatcher/invalidate.cache",
    ],
    incorrectAnswers: [
      "It should point to /libs/granite/dispatcher/content/vanityUrls.html on Author",
      "It must target /system/console on each Publish instance",
      "It should use the CDN domain root without any path",
      "It must post to /content/site/en.html on the render host",
      "It should call /bin/replicate.json on the Author host",
      "It points to /dispatcher/validate.cache so Cloud Manager can approve the request",
      "It must always target /etc/httpd/conf.dispatcher.d/dispatcher.any",
      "It should send invalidations to the default_rewrite.rules file path",
    ],
    explanation:
      "The speech says the flush agent's Transport URI points to /dispatcher/invalidate.cache on the Dispatcher host.",
  },
  {
    id: "disp-068",
    topic: "Invalidating from Author or Publish",
    question: "When is the flush agent's URI property used to target a specific farm?",
    correctAnswers: [
      "The URI property is used only with path-based virtual hosts to target a specific farm",
      "Use the URI property for farm targeting only when virtual hosts are path-based",
      "The property matters for specific-farm targeting in path-based virtual host setups",
      "A flush agent uses its URI property to select a farm only in path-based virtual host configurations",
    ],
    incorrectAnswers: [
      "It is used only when multiple render ports share the same hostname",
      "It is required whenever a farm includes default_renders.any",
      "It applies only to Author-to-CDN invalidations in Cloud Service",
      "It is used only when /allowAuthorized is set to 1",
      "It is required for all hostname-based virtual host definitions",
      "It is used only by legacy mode because flexible mode removed farm targeting",
      "It selects the .stat file depth used by the target farm",
      "It is relevant only for vanity URL updates at startup",
    ],
    explanation:
      "The speech states that the URI property is used only with path-based virtual hosts, to target a specific farm.",
  },
  {
    id: "disp-069",
    topic: "Invalidating from Author or Publish",
    question: "What is the recommended credential practice for Dispatcher Flush agents?",
    correctAnswers: [
      "If credentials are used, create a dedicated replication user instead of using admin",
      "Use a dedicated user for replication agents rather than the admin account",
      "The recommended practice is to avoid admin and assign flush agents their own user",
      "When a flush agent needs authentication, it should use a dedicated replication user",
    ],
    incorrectAnswers: [
      "Always leave the user blank because flush agents cannot send authentication",
      "Reuse the admin account so all farms share one global credential",
      "Store the password in global.vars because Dispatcher validates it there",
      "Use the anonymous user because Dispatcher ignores basic authentication",
      "Create one user per farm inside default_virtualhosts.any",
      "Put the credentials in /clientheaders so Author can forward them",
      "Use the CDN service account because flush agents call only Adobe endpoints",
      "Configure credentials only on Publish because Author never sends invalidations",
    ],
    explanation:
      "The source says the agent does not need a user name and password, but if they are set they are sent with basic authentication, and it recommends creating a dedicated user instead of using admin.",
  },
  {
    id: "disp-070",
    topic: "Invalidating from Author or Publish",
    question: "Why can invalidating Dispatcher directly from Author be difficult in some network topologies?",
    correctAnswers: [
      "Author-side invalidation can fail because Dispatcher must be reachable from the Author instance",
      "A firewall may block Author from reaching Dispatcher, which breaks author-triggered invalidation",
      "One problem with invalidating from Author is that network reachability to Dispatcher is required",
      "Invalidation from Author depends on Dispatcher being accessible from Author, which firewalls may prevent",
    ],
    incorrectAnswers: [
      "Because Author is not allowed to know the Dispatcher hostname in any AEM version",
      "Because Dispatcher accepts invalidation only from CDN IP addresses",
      "Because path-based virtual hosts disable activation from Author",
      "Because Author cannot send HTTP POST requests after activation",
      "Because the default flush agent works only on Publish and never on Author",
      "Because Dispatcher invalidation requires WebSocket connections from Author",
      "Because /dispatcher/invalidate.cache is resolved only from localhost",
      "Because Author uses only GET replication and Dispatcher requires DELETE",
    ],
    explanation:
      "The speech lists reachability as one of the two issues with invalidating from Author: Dispatcher must be reachable from the Author instance, which a firewall may block.",
  },
  {
    id: "disp-071",
    topic: "Invalidating from Author or Publish",
    question: "What race condition can occur when invalidation and publication happen at the same time?",
    correctAnswers: [
      "Dispatcher can cache the old page again if a user requests it after invalidation but before the new publication arrives",
      "A user may hit Publish between cache removal and new content publication, causing the old page to be re-cached",
      "Simultaneous invalidation and publication can briefly let stale content be fetched from Publish and cached again",
      "The risk is that Dispatcher removes the cached page, then repopulates it with the old version before publication completes",
    ],
    incorrectAnswers: [
      "Dispatcher permanently disables caching for the entire farm after every activation",
      "The race condition causes default_renders.any to be deleted from the farm",
      "It forces the CDN to purge all query-parameter variants of every page",
      "Publish automatically serves a 404 until the next deployment finishes",
      "The agent overwrites dispatcher.any with the old page HTML",
      "AEM converts the page into a vanity URL during the activation window",
      "The cache docroot becomes read-only until the publication queue is empty",
      "The Author instance starts serving public traffic directly to avoid stale pages",
    ],
    explanation:
      "The speech explains that publication and invalidation happen at the same time, so a user can request the page after it is removed from cache but before the new page is published, leading Dispatcher to cache the old page again.",
  },
  {
    id: "disp-072",
    topic: "Invalidating from Author or Publish",
    question: "What changes when cache invalidation is moved from Author to Publish?",
    correctAnswers: [
      "With publish-side invalidation, each Publish instance sends the invalidation request when it receives the published page",
      "Cache management moves to Publish, which flushes Dispatcher upon receiving the publication",
      "Invalidating from Publish means the publish instance triggers the flush after it receives the published content",
      "The publish-side approach has Publish send invalidation requests instead of Author",
    ],
    incorrectAnswers: [
      "Author still sends every invalidation, but Publish rewrites the Transport URI",
      "Dispatcher no longer needs any invalidation requests because Publish deletes the docroot directly",
      "The CDN performs all invalidation and Publish does nothing differently",
      "Publication switches from HTTP to JMX so the cache can be purged asynchronously",
      "Only one Publish instance should send invalidations even in a multi-publish topology",
      "Publish-side invalidation works only when /allowAuthorized is set to 1",
      "Moving invalidation to Publish eliminates the need for activation entirely",
      "This approach is automatic in every AEM setup and needs no extra configuration",
    ],
    explanation:
      "The speech says invalidating from the publish instance moves cache management to Publish: the publish instance sends the invalidation request when it receives a published page. It also notes the agent must be configured on every affected Publish instance.",
  },
  {
    id: "disp-073",
    topic: "Dispatcher in Cloud Service",
    question: "What do the Dispatcher Tools in the AEM as a Cloud Service SDK provide?",
    correctAnswers: [
      "They provide a vanilla project file structure, validation tooling, and a Docker image for local Dispatcher",
      "The tools include the starter Dispatcher file structure, config validation, and local Docker-based execution",
      "Dispatcher Tools supply the Maven-ready layout, supported-directive validation, and a local Docker image",
      "In Cloud Service, Dispatcher Tools give you the baseline structure, validators, and local Dispatcher runtime in Docker",
    ],
    incorrectAnswers: [
      "They provide only browser-side cache warming scripts for authors",
      "They replace Apache and run all traffic directly in the AEM JVM",
      "They create replication agents automatically on every environment",
      "They convert dispatcher.any into OSGi configurations during deployment",
      "They expose /crx/de safely through default filters for local debugging",
      "They replace the need for Maven by deploying farms directly from the browser",
      "They generate CDN certificates and Author user accounts automatically",
      "They are limited to query-parameter testing and do not validate syntax",
    ],
    explanation:
      "The speech says the Dispatcher Tools are part of the Cloud Service SDK and provide a vanilla file structure, tooling to validate supported directives and syntax, and a Docker image that runs Dispatcher locally.",
  },
  {
    id: "disp-074",
    topic: "Dispatcher in Cloud Service",
    question: "Which Dispatcher mode is recommended in AEM as a Cloud Service, and how is it activated?",
    correctAnswers: [
      "Flexible mode is recommended and is activated by the file opt-in/USE_SOURCES_DIRECTLY",
      "The recommended mode is flexible mode, enabled through opt-in/USE_SOURCES_DIRECTLY",
      "Cloud Service recommends flexible mode, which is turned on by the opt-in file USE_SOURCES_DIRECTLY",
      "Use flexible mode, activated by placing the opt-in/USE_SOURCES_DIRECTLY file",
    ],
    incorrectAnswers: [
      "Legacy mode is recommended and is enabled by deleting rewrite.rules",
      "Flexible mode is enabled by changing dispatcher.any to default.any",
      "The recommended mode is CDN-only mode, activated through global.vars",
      "Flexible mode starts automatically only when /allowAuthorized is set to 1",
      "Legacy mode is activated by adding default_virtualhosts.any to every farm",
      "Flexible mode is turned on by changing the Publish port to 443",
      "The recommended mode is author-driven mode, enabled by a replication agent",
      "Flexible mode is activated by setting FileETag none in Apache",
    ],
    explanation:
      "The source says flexible mode is recommended, is the default for archetype 28 and higher, and is activated by the file opt-in/USE_SOURCES_DIRECTLY.",
  },
  {
    id: "disp-075",
    topic: "Dispatcher in Cloud Service",
    question: "What limitation applied in legacy mode that flexible mode removes?",
    correctAnswers: [
      "Legacy mode required a single rewrite.rules file",
      "The old limitation was having only one rewrite.rules file",
      "Flexible mode removes the legacy requirement for a single rewrite.rules file",
      "In legacy mode, rewrite rules had to live in one rewrite.rules file",
    ],
    incorrectAnswers: [
      "Legacy mode allowed no farms at all",
      "Flexible mode is the only mode that supports virtual hosts",
      "Legacy mode required all files to be immutable in local development",
      "Flexible mode is the only mode that permits Dispatcher validation",
      "Legacy mode prevented the use of clientheaders.any",
      "Flexible mode alone supports .stat files for invalidation",
      "Legacy mode required one publish instance per farm",
      "Flexible mode removed the need for enabled_vhosts symbolic links",
    ],
    explanation:
      "The speech states that legacy mode required a single rewrite.rules file, while flexible mode removes that limit.",
  },
  {
    id: "disp-076",
    topic: "Dispatcher in Cloud Service",
    question: "What is the main difference between conf.d and conf.dispatcher.d in a Cloud Service Dispatcher project?",
    correctAnswers: [
      "conf.d holds Apache configuration, while conf.dispatcher.d holds Dispatcher configuration",
      "Apache files live under conf.d and Dispatcher-specific files live under conf.dispatcher.d",
      "Use conf.d for vhosts, rewrites, and variables; use conf.dispatcher.d for farms, filters, cache, and related Dispatcher files",
      "The split is Apache settings in conf.d versus Dispatcher settings in conf.dispatcher.d",
    ],
    incorrectAnswers: [
      "conf.d is for Author and conf.dispatcher.d is for Publish only",
      "conf.d stores immutable files and conf.dispatcher.d stores all source code",
      "conf.d is for CDN headers only and conf.dispatcher.d is for query parameters only",
      "conf.d contains only Java classes, while conf.dispatcher.d contains HTML",
      "conf.d is for local Docker and conf.dispatcher.d is for production only",
      "conf.d lists allowed clients and conf.dispatcher.d lists author users",
      "conf.d stores vanity URLs and conf.dispatcher.d stores replication queues",
      "There is no difference; both folders contain the same interchangeable files",
    ],
    explanation:
      "The speech says the project Dispatcher folder has two main subfolders: conf.d for Apache configuration and conf.dispatcher.d for Dispatcher configuration.",
  },
  {
    id: "disp-077",
    topic: "Dispatcher in Cloud Service",
    question: "How should a virtual host or farm be enabled in Cloud Service Dispatcher configuration?",
    correctAnswers: [
      "Create it in the available folder and enable it with a relative symbolic link in the enabled folder",
      "A vhost or farm is enabled by a relative symlink from enabled_* to the file in available_*",
      "The correct pattern is available_vhosts or available_farms plus a relative symbolic link in the matching enabled folder",
      "In flexible mode, enable files through relative symbolic links rather than copying them",
    ],
    incorrectAnswers: [
      "Copy default.vhost directly into enabled_vhosts and edit it there",
      "Place every active file only in the enabled folder and leave available empty",
      "Rename dispatcher.any to match the site domain and Apache enables it automatically",
      "Enable a farm by adding its name to global.vars",
      "Move rewrite.rules into the cache folder to activate the configuration",
      "Create Windows shortcuts in the project root instead of symlinks",
      "Add the farm path to /virtualhosts and Dispatcher will auto-enable it",
      "Put the configuration under /libs so the SDK can discover it",
    ],
    explanation:
      "The source says a virtual host or farm is created in the available folder and enabled by a relative symbolic link in the enabled folder, and specifically warns not to copy default.vhost directly into enabled_vhosts.",
  },
  {
    id: "disp-078",
    topic: "Dispatcher in Cloud Service",
    question: "Which aliases must at least one virtual host match so Dispatcher invalidation works in Cloud Service local setups?",
    correctAnswers: [
      "At least one virtual host must match *.local, localhost, and 127.0.0.1",
      "Dispatcher invalidation needs a vhost whose ServerAlias covers *.local, localhost, and 127.0.0.1",
      "A required virtual host alias set for invalidation is *.local, localhost, and 127.0.0.1",
      "For invalidation support, include ServerAlias values *.local, localhost, and 127.0.0.1 in at least one vhost",
    ],
    incorrectAnswers: [
      "Only *.adobeaemcloud.net is required for local invalidation",
      "The required aliases are author.local, publish.local, and dispatcher.local only",
      "Only the production site hostname is needed because invalidation ignores local aliases",
      "You need *.internal, localhost6, and 0.0.0.0 instead",
      "No aliases are required as long as /allowedClients includes 127.0.0.1",
      "The invalidation requirement is limited to /content and not to ServerAlias values",
      "Dispatcher invalidation uses only IP addresses, so localhost must not be present",
      "Only *.local is allowed; localhost and 127.0.0.1 fail validation",
    ],
    explanation:
      "The speech says at least one virtual host must match the ServerAlias values *.local, localhost, and 127.0.0.1 because they are needed for Dispatcher invalidation.",
  },
  {
    id: "disp-079",
    topic: "Dispatcher in Cloud Service",
    question: "Why are the aliases *.adobeaemcloud.net and *.adobeaemcloud.com also required in Cloud Service?",
    correctAnswers: [
      "Those aliases are required for internal Adobe processes",
      "At least one vhost must also cover *.adobeaemcloud.net and *.adobeaemcloud.com because Adobe uses them internally",
      "The Adobe-managed internal processes depend on aliases for *.adobeaemcloud.net and *.adobeaemcloud.com",
      "They are required ServerAlias values so internal Adobe processes can reach the vhost",
    ],
    incorrectAnswers: [
      "They are needed only so browsers can bypass Dispatcher and reach Author directly",
      "They are the only aliases that allow query parameters to be ignored",
      "These aliases are required only in legacy mode because flexible mode removed internal routing",
      "They exist solely to enable ETag storage in the cache docroot",
      "They are required because the CDN cache key excludes the customer domain",
      "They let default_virtualhosts.any win every host match by design",
      "They are used only to expose /crx/de safely for Adobe support staff",
      "They are optional aliases that matter only for vanity URL loading",
    ],
    explanation:
      "The source says the aliases *.adobeaemcloud.net and *.adobeaemcloud.com are also required, for internal Adobe processes.",
  },
  {
    id: "disp-080",
    topic: "Customizable and Immutable Files",
    question: "What is the key difference between customizable and immutable Dispatcher files in Cloud Service?",
    correctAnswers: [
      "Customizable files are deployed to Cloud, while immutable files are part of the base framework and local edits to them are ignored",
      "Only customizable files are transferred on deployment; immutable files come from the framework and cannot be changed by local edits",
      "Cloud Service deploys customizable files, but immutable default files are not transferred from your local changes",
      "The important distinction is that customizable files are shipped to the environment and immutable ones are replaced by the platform version",
    ],
    incorrectAnswers: [
      "Customizable files run only on Author, while immutable files run only on Publish",
      "Immutable files are copied from enabled_vhosts during deployment, but customizable files are not",
      "Customizable files exist only in local Docker and never in Cloud environments",
      "Immutable files are the only files Cloud Manager allows you to edit in production",
      "Customizable files are cached by the CDN, while immutable files are not cached anywhere",
      "Immutable files are generated from query parameters at request time",
      "Customizable files are read-only, but immutable files are meant for customer overrides",
      "There is no deployment difference; the distinction applies only to local validation speed",
    ],
    explanation:
      "The speech says customizable files are transferred to the Cloud environment on deployment, while immutable files are part of the base framework and modifying them locally has no effect.",
  },
  {
    id: "disp-081",
    topic: "Customizable and Immutable Files",
    question: "Which file can be used to change the Dispatcher and rewrite log level in Cloud Service?",
    correctAnswers: [
      "global.vars is where you can change the Dispatcher and rewrite log level",
      "Use global.vars to adjust Dispatcher and rewrite logging",
      "The customizable file for Dispatcher and rewrite log levels is global.vars",
      "Log-level changes for Dispatcher and rewrites belong in global.vars",
    ],
    incorrectAnswers: [
      "default.vhost is the supported file for changing all Cloud log levels",
      "dispatcher.any is immutable and therefore the correct place for log-level edits",
      "rules.any controls only log levels, not cache rules",
      "default_filters.any is where rewrite logging must be turned on",
      "available_farms stores the log-level directives for all environments",
      "default_invalidate.any is used to configure trace logging",
      "The SDK Dockerfile is the only supported place to set Dispatcher log levels",
      "clientheaders.any is where Apache rewrite logging is configured",
    ],
    explanation:
      "The source says that in global.vars you can change the Dispatcher and rewrite log level.",
  },
  {
    id: "disp-082",
    topic: "Customizable and Immutable Files",
    question: "What happens to local modifications of immutable Dispatcher files when deploying to AEM as a Cloud Service?",
    correctAnswers: [
      "They have no effect because the latest immutable framework version is used on deployment",
      "Local edits to immutable files are ignored, and Cloud Service uses its current framework copy",
      "The deployment uses the latest immutable base files, not your local changes to them",
      "Changing an immutable file locally does nothing in Cloud because the platform supplies that file",
    ],
    incorrectAnswers: [
      "They are merged into dispatcher.any only after phase 3 validation",
      "They override customizable files because immutable files win deployment order",
      "They are applied only in non-production environments and skipped in production",
      "They are copied if you also change global.vars in the same commit",
      "Cloud Manager converts immutable changes into warnings and deploys them anyway",
      "They take effect only if you add the file to enabled_vhosts",
      "They are deployed to Author but not to Publish tiers",
      "They are accepted only in legacy mode and rejected in flexible mode",
    ],
    explanation:
      "The speech states that immutable files are part of the base framework, modifying them locally has no effect, and the latest version is always used on deployment.",
  },
  {
    id: "disp-083",
    topic: "Customizable and Immutable Files",
    question: "Which file must every farm include in its /renders section?",
    correctAnswers: [
      "Every farm must include default_renders.any in /renders",
      "The required /renders include is default_renders.any",
      "A valid farm includes default_renders.any under /renders",
      "In Cloud Service, each farm's /renders section must pull in default_renders.any",
    ],
    incorrectAnswers: [
      "Every farm must include default_virtualhosts.any in /renders",
      "The mandatory /renders include is rewrite.rules",
      "Each farm must include dispatcher.any directly inside /renders",
      "Every farm needs default_filters.any in /renders instead",
      "The /renders section must include clientheaders.any before it can define hosts",
      "Only legacy mode requires an include, and it must be default.vhost",
      "Each farm must include global.vars in /renders for host resolution",
      "default_invalidate.any is the required /renders include",
    ],
    explanation:
      "The speech explicitly says every farm must include default_renders.any in its /renders section.",
  },
  {
    id: "disp-084",
    topic: "Customizable and Immutable Files",
    question: "Which file must every farm include in the /allowedClients section of /cache?",
    correctAnswers: [
      "Every farm must include default_invalidate.any in /cache /allowedClients",
      "The required include for /allowedClients is default_invalidate.any",
      "A valid Cloud Service farm includes default_invalidate.any under /cache /allowedClients",
      "Each farm must pull in default_invalidate.any in the /allowedClients block of /cache",
    ],
    incorrectAnswers: [
      "Every farm must include default_clientheaders.any in /allowedClients",
      "The mandatory include is default_virtualhosts.any so invalidation can match every request",
      "Use rewrite.rules in /allowedClients because clients are matched by URL",
      "Add dispatcher.any inside /cache /allowedClients to satisfy validation",
      "Only Author farms need default_invalidate.any; Publish farms must omit it",
      "Each farm must include default_renders.any again inside /allowedClients",
      "The required file is global.vars because allowed clients are environment variables",
      "There is no required include under /allowedClients in Cloud Service",
    ],
    explanation:
      "The source says every farm must include default_invalidate.any in the /allowedClients section of /cache.",
  },
  {
    id: "disp-085",
    topic: "Customizable and Immutable Files",
    question: "Where are your own include files allowed in Cloud Service Dispatcher configuration, and what naming rule applies?",
    correctAnswers: [
      "Custom includes are allowed only in /clientheaders, /filters, /cache /rules, and /virtualhosts, using the names clientheaders.any, filters.any, rules.any, or virtualhosts.any",
      "Your own includes may appear only in clientheaders, filters, cache rules, and virtualhosts, and they must use the prescribed .any names",
      "Cloud validation allows custom includes only in those four sections and only with the standard filenames or their default_ versions",
      "You can include your own files only for client headers, filters, cache rules, and virtual hosts, and they must be named exactly as required",
    ],
    incorrectAnswers: [
      "You may include custom files anywhere as long as the filename starts with custom_",
      "Only /renders and /allowedClients permit customer include files",
      "Custom includes are allowed only in dispatcher.any because farm files must stay untouched",
      "Any filename is valid under flexible mode, so naming rules no longer apply",
      "Only .vhost files may include customer files; farms may not",
      "Custom files are allowed in immutable defaults as long as they are symlinked",
      "Cloud Service permits includes only in rewrite.rules and global.vars",
      "The validator requires every custom include to be named after the site domain",
    ],
    explanation:
      "The speech says customer files may be included only in /clientheaders, /filters, /rules in /cache, and /virtualhosts, and they must be named clientheaders.any, filters.any, rules.any, and virtualhosts.any, or the default_ version.",
  },
  {
    id: "disp-086",
    topic: "Customizable and Immutable Files",
    question: "Why should default_virtualhosts.any not be included in a custom Cloud Service configuration?",
    correctAnswers: [
      "Do not include default_virtualhosts.any because it matches every incoming request",
      "Including default_virtualhosts.any is wrong because it catches all requests",
      "The reason to avoid default_virtualhosts.any in customizations is that it matches every request",
      "default_virtualhosts.any should not be customized in because its match is too broad for all incoming requests",
    ],
    incorrectAnswers: [
      "Because it disables Dispatcher invalidation for localhost aliases",
      "Because it is the only immutable file that Cloud Manager deploys twice",
      "Because it changes /allowAuthorized to 1 for every farm",
      "Because it deletes the relative symlinks in enabled_vhosts",
      "Because it prevents default_renders.any from being loaded",
      "Because it forces legacy mode and a single rewrite.rules file",
      "Because it blocks Cache-Control and Expires headers from Publish",
      "Because it can be included only from Author and never from Publish",
    ],
    explanation:
      "The source says not to include default_virtualhosts.any in a customization because it matches every incoming request.",
  },
  {
    id: "disp-087",
    topic: "CDN and Cache Headers",
    question: "Which origin response headers control caching in the AEM as a Cloud Service CDN?",
    correctAnswers: [
      "The Cloud Service CDN is controlled by Cache-Control, Surrogate-Control, or Expires from the origin response",
      "CDN caching is driven by the origin headers Cache-Control, Surrogate-Control, and Expires",
      "Use origin response headers such as Cache-Control, Surrogate-Control, or Expires to control the CDN cache",
      "The Adobe CDN reads Cache-Control, Surrogate-Control, or Expires to decide caching behavior",
    ],
    incorrectAnswers: [
      "The CDN is controlled only by Dispatcher farm names and virtual host order",
      "Only ETag and Last-Modified control CDN caching in Cloud Service",
      "The CDN uses /allowedClients and /ignoreUrlParams instead of response headers",
      "CDN caching is controlled solely by query parameter names in the URL",
      "Only Set-Cookie and Authorization headers can make the CDN cache content",
      "The CDN ignores origin headers and depends only on FileETag none",
      "Cloud Service uses the PATH request header as the only CDN cache directive",
      "CDN caching is controlled exclusively through Cloud Manager deployment settings",
    ],
    explanation:
      "The speech says caching of HTTP responses in the Cloud Service CDN is controlled by the origin response headers Cache-Control, Surrogate-Control, or Expires.",
  },
  {
    id: "disp-088",
    topic: "CDN and Cache Headers",
    question: "How do query parameters affect the CDN cache key in AEM as a Cloud Service?",
    correctAnswers: [
      "The CDN cache key includes the full request URL, so different query parameters create different cache entries",
      "Each distinct query parameter combination becomes a separate CDN cache entry because the full URL is part of the key",
      "Cloud Service CDN caching varies by the entire request URL, including query parameters",
      "Different query strings lead to different CDN cache keys because the key includes the full URL",
    ],
    incorrectAnswers: [
      "The CDN strips all query parameters before generating its cache key",
      "Only the path and extension are in the CDN key; query strings never matter",
      "The CDN hashes only ignored URL parameters into one shared cache entry",
      "Query parameters affect Dispatcher only and are never seen by the CDN",
      "The CDN cache key contains only the host name and ignores the URI",
      "All query strings are normalized into alphabetical order and one common cache object",
      "The CDN uses only Surrogate-Control values as the cache key",
      "A query string changes the cache key only for authenticated users",
    ],
    explanation:
      "The source says the CDN cache key includes the full request URL, including query parameters, so each different query parameter produces a different cache entry.",
  },
  {
    id: "disp-089",
    topic: "CDN and Cache Headers",
    question: "Which responses will the Cloud Service CDN refuse to cache?",
    correctAnswers: [
      "Responses with Cache-Control private, no-cache, or no-store, or with a Set-Cookie header, are not cached by the CDN",
      "The CDN skips responses marked private, no-cache, or no-store, and also skips responses that set cookies",
      "Cloud Service CDN caching is prevented by private, no-cache, no-store, or Set-Cookie",
      "A response is not CDN-cached if it includes private, no-cache, no-store, or a Set-Cookie header",
    ],
    incorrectAnswers: [
      "Responses with Expires are never cached because only Surrogate-Control is honored",
      "The CDN refuses only 200 responses and caches all redirects and errors",
      "Any response with Content-Type text/html is automatically excluded from the CDN",
      "Responses without ETag are always rejected from the CDN cache",
      "The CDN refuses to cache only when the URL has no file extension",
      "Set-Cookie forces the response into shared CDN caching for better reuse",
      "Responses with Cache-Control public are explicitly excluded from CDN caching",
      "The CDN caches private content automatically if Dispatcher can cache it",
    ],
    explanation:
      "The speech states that responses containing private, no-cache, or no-store in Cache-Control, or a Set-Cookie header, are not cached by the CDN.",
  },
  {
    id: "disp-090",
    topic: "CDN and Cache Headers",
    question: "What is the default caching behavior for text and HTML responses in Cloud Service Dispatcher setups?",
    correctAnswers: [
      "By default, browsers cache text and HTML for five minutes, and the CDN respects that",
      "Dispatcher sets default headers so text and HTML are browser-cached for five minutes, which the CDN also follows",
      "The default text and HTML behavior is a five-minute browser cache respected by the CDN",
      "Unless changed, HTML and text get default headers that cache them for five minutes in browsers and the CDN",
    ],
    incorrectAnswers: [
      "HTML and text are never cached unless Surrogate-Control is set manually",
      "The default is a one-day browser cache and a one-hour CDN cache",
      "Text and HTML are cached only at Dispatcher and never in browsers",
      "The default is zero caching because AEM strips all cache headers from text responses",
      "Browsers cache for five seconds while the CDN caches for five days",
      "The default behavior applies only to JSON and excludes HTML",
      "Only authenticated text responses receive the five-minute default",
      "The CDN ignores Dispatcher defaults and always uses thirty days for HTML",
    ],
    explanation:
      "The source says that for text and HTML, Dispatcher sets default headers so the browser caches for five minutes, and the CDN respects this.",
  },
  {
    id: "disp-091",
    topic: "CDN and Cache Headers",
    question: "How can the default text and HTML caching behavior be disabled or overridden globally in Cloud Service?",
    correctAnswers: [
      "Define DISABLE_DEFAULT_CACHING in global.vars to disable it, or use EXPIRATION_TIME in global.vars to override it",
      "The default can be turned off with DISABLE_DEFAULT_CACHING and globally changed with EXPIRATION_TIME, both in global.vars",
      "Use global.vars: DISABLE_DEFAULT_CACHING removes the default, while EXPIRATION_TIME overrides it for HTML and text",
      "Cloud Service global control comes from DISABLE_DEFAULT_CACHING or EXPIRATION_TIME in global.vars",
    ],
    incorrectAnswers: [
      "Change default_virtualhosts.any because global.vars cannot affect caching",
      "Set /mode to 0000 to disable browser caching and /allowAuthorized to override it",
      "Delete rewrite.rules so Apache falls back to zero-cache mode",
      "Use only /ignoreUrlParams because caching headers cannot be globally changed",
      "Enable flexible mode and the default caching behavior disappears automatically",
      "Modify immutable default_rewrite.rules because global overrides are unsupported",
      "Set FileETag all to disable the five-minute HTML cache",
      "Add Set-Cookie to every response because that is the documented global override",
    ],
    explanation:
      "The speech says you can disable the default by defining DISABLE_DEFAULT_CACHING in global.vars and override it for all HTML and text with the EXPIRATION_TIME variable in global.vars.",
  },
  {
    id: "disp-092",
    topic: "CDN and Cache Headers",
    question: "Which header should be used when you want to control Adobe-managed CDN caching independently of browser caching?",
    correctAnswers: [
      "Use Surrogate-Control to control the Adobe-managed CDN independently of the browser",
      "The header for CDN-only cache control is Surrogate-Control",
      "Surrogate-Control lets you set Adobe CDN caching separately from browser caching",
      "To decouple CDN behavior from browser behavior, set Surrogate-Control",
    ],
    incorrectAnswers: [
      "Use X-Content-Type-Options because it overrides browser cache duration only at the CDN",
      "Set Content-Disposition because the CDN reads it before Cache-Control",
      "Use CQ-Action-Scope since it controls shared cache lifetimes",
      "Set Authorization because authenticated headers have higher CDN precedence",
      "Use FileETag none because it is the browser-independent CDN directive",
      "Set PATH because Surrogate-Control is only for Dispatcher",
      "Use Last-Modified because Adobe-managed CDN ignores Surrogate-Control",
      "Set login-token to control shared CDN cache without affecting the browser",
    ],
    explanation:
      "The source says Surrogate-Control applies to the Adobe managed CDN and lets you control the CDN cache independently of the browser.",
  },
  {
    id: "disp-093",
    topic: "CDN and Cache Headers",
    question: "How should a response be marked when it must stay out of the CDN cache?",
    correctAnswers: [
      "Set Cache-Control to private to keep the response out of the CDN",
      "Use Cache-Control: private when the content must not be cached by the CDN",
      "The CDN exclusion header in this case is Cache-Control private",
      "Mark the response private in Cache-Control so the Cloud Service CDN will not cache it",
    ],
    incorrectAnswers: [
      "Set Surrogate-Control to public so the CDN knows the response is sensitive",
      "Use Expires: 0 because that forces permanent CDN retention",
      "Add default_invalidate.any to the response headers for private delivery",
      "Set Cache-Control to immutable so the CDN avoids storing the object",
      "Return ETag only, because the CDN never caches responses that have validators",
      "Add the response to /headers and the CDN will skip it automatically",
      "Use CQ-Handle with the page path so the CDN treats it as uncached",
      "Set LocationMatch only on Author because Publish cannot influence the CDN",
    ],
    explanation:
      "The speech says that to keep content out of the CDN, set Cache-Control to private. It also notes that private HTML can still be cached at Dispatcher with permission-sensitive caching.",
  },
  {
    id: "disp-094",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "Why can browsers cache AEM client libraries for a very long time?",
    correctAnswers: [
      "Clientlibs can be cached indefinitely because a change produces a new file with a unique path",
      "AEM client libraries are generated so changes create a different URL, allowing very long browser caching",
      "Browsers may cache clientlibs for a long time because updated clientlibs get a new unique path",
      "The reason is that clientlib changes produce a new file path, so the old cached URL stays valid",
    ],
    incorrectAnswers: [
      "Because Dispatcher invalidates JavaScript only once per deployment and never again",
      "Because clientlibs are always served from Author and bypass Publish permissions",
      "Because their URLs stay constant, so browsers must poll every request",
      "Because they are excluded from Cache-Control and rely only on ETag",
      "Because the CDN rewrites all clientlibs into default.vhost automatically",
      "Because AEM stores clientlibs only inside immutable files in Cloud Service",
      "Because query parameters on clientlibs are ignored by every cache layer",
      "Because browsers ignore response headers for .css and .js files in AEM",
    ],
    explanation:
      "The speech says client libraries are generated so browsers can cache JavaScript and CSS indefinitely because any change produces a new file with a unique path.",
  },
  {
    id: "disp-095",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "Which Cloud Service programs cache blob content by default while still respecting authentication?",
    correctAnswers: [
      "Programs created after mid-May 2022 with program IDs above 65000 cache blob content by default while respecting authentication",
      "Blob caching is on by default for programs newer than mid-May 2022 whose program ID is above 65000",
      "Default blob caching applies to post-mid-May-2022 programs with IDs greater than 65000",
      "Newer programs, specifically those created after mid-May 2022 and above ID 65000, cache blobs by default with auth awareness",
    ],
    incorrectAnswers: [
      "All Cloud Service programs cache blob content by default regardless of age or ID",
      "Only programs created before 2022 with IDs below 65000 cache blobs by default",
      "Blob caching defaults only on Author preview environments and not on production programs",
      "Programs cache blobs by default only when /allowAuthorized is set to 1",
      "Default blob caching requires a custom rewrite.rules file instead of program age",
      "Only programs with IDs below 1000 are allowed to cache blobs automatically",
      "Blob caching defaults only after local SDK validation phase 3 passes",
      "Program creation date never matters; only CDN domain aliases do",
    ],
    explanation:
      "The source says that for blob content, programs created after mid-May 2022, with program IDs above 65000, cache by default while respecting authentication.",
  },
  {
    id: "disp-096",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "If no cache header is set on cacheable blob content in newer programs, what headers are applied by default?",
    correctAnswers: [
      "Public blob traffic gets public, max-age 600, immutable, while authenticated blob traffic gets private",
      "Without an explicit cache header, public blobs default to public, max-age 600, immutable and authenticated blobs default to private",
      "The default is public, max-age 600, immutable for public blob content and private for authenticated requests",
      "Newer programs apply public, max-age 600, immutable to public blobs, but private to authenticated blob responses when no cache header exists",
    ],
    incorrectAnswers: [
      "All blob responses default to no-store so authentication is always rechecked",
      "Public blobs default to private and authenticated blobs default to public",
      "Every blob gets max-age 0 and must be revalidated on every request",
      "Blob content always inherits the five-minute HTML default from Dispatcher",
      "Blobs receive Surrogate-Control only and never Cache-Control",
      "All blob traffic defaults to immutable for thirty days regardless of authentication",
      "Blob responses get public, max-age 31536000, and Set-Cookie by default",
      "The defaults are determined only by /ignoreUrlParams rules",
    ],
    explanation:
      "The speech says that when no cache header is set, public blob content gets public, max-age 600, immutable, and authenticated traffic gets private.",
  },
  {
    id: "disp-097",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "How do older Cloud Service programs behave for blob caching by default?",
    correctAnswers: [
      "Older programs do not cache blob content by default",
      "Blob caching is off by default for older programs",
      "Programs older than the newer threshold do not automatically cache blobs",
      "The default for older programs is no blob caching",
    ],
    incorrectAnswers: [
      "Older programs always cache blobs indefinitely with immutable headers",
      "Older programs cache blobs only for authenticated requests by default",
      "Older programs redirect all blobs to Author instead of caching them",
      "Older programs use the same default blob caching as newer ones without exceptions",
      "Older programs cache blobs only when clientlibs change path",
      "Older programs require Surrogate-Control private before they can skip caching",
      "Older programs cache only blobs smaller than 16 KB by default",
      "Older programs default to CDN-only caching but not Dispatcher caching",
    ],
    explanation:
      "The source explicitly says older programs do not cache blob content by default.",
  },
  {
    id: "disp-098",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "Which environment variable can change the default caching-header behavior for blob content?",
    correctAnswers: [
      "AEM_BLOB_ENABLE_CACHING_HEADERS can change the blob caching-header behavior",
      "Use the environment variable AEM_BLOB_ENABLE_CACHING_HEADERS to change this behavior",
      "The relevant variable is AEM_BLOB_ENABLE_CACHING_HEADERS",
      "Blob caching headers can be altered through AEM_BLOB_ENABLE_CACHING_HEADERS",
    ],
    incorrectAnswers: [
      "DISABLE_DEFAULT_CACHING is the blob-only switch for binaries",
      "EXPIRATION_TIME controls blob authentication behavior exclusively",
      "FILE_ETAG_BLOB_MODE changes blob cache headers",
      "AEM_DISPATCHER_BLOB_INVALIDATE enables automatic blob header changes",
      "USE_SOURCES_DIRECTLY toggles all blob caching semantics",
      "AEM_BLOB_REDIRECT_HEADERS is the documented cache-header variable",
      "AUTHOR_BLOB_PRIVATE_MODE is required for authenticated blob caching",
      "CQ_BLOB_MAXAGE_HEADERS is the supported environment variable",
    ],
    explanation:
      "The speech says the environment variable AEM_BLOB_ENABLE_CACHING_HEADERS can change the default blob caching-header behavior.",
  },
  {
    id: "disp-099",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "What special behavior applies to blob responses larger than 16 KB?",
    correctAnswers: [
      "Blobs larger than 16 KB are served as 302 redirects, and only a limited set of headers can be customized on them",
      "Large blobs over 16 KB are returned through 302 redirects with only limited header customization",
      "For blobs above 16 KB, AEM serves a 302 redirect and restricts which headers you can customize",
      "The rule is that blobs larger than 16 KB redirect with 302 and expose only limited customizable headers such as Content-Disposition and Cache-Control",
    ],
    incorrectAnswers: [
      "Blobs larger than 16 KB are always streamed inline from Author with all headers editable",
      "Any blob above 16 KB bypasses authentication and becomes public by default",
      "Large blobs are split into multiple .stat files so Dispatcher can cache chunks",
      "Blobs larger than 16 KB cannot be cached or redirected in Cloud Service",
      "AEM converts blobs over 16 KB into clientlibs with immutable caching",
      "Large blobs are always served with 301 redirects and unrestricted header editing",
      "The 16 KB rule applies only to HTML and never to binary content",
      "Blobs over 16 KB are stored only in the CDN and never requested from Publish",
    ],
    explanation:
      "The source says blobs larger than 16 KB are served as 302 redirects, and only a limited list of headers can be customized on them, such as Content-Disposition and Cache-Control.",
  },
  {
    id: "disp-100",
    topic: "Clientlibs, Blob Content and Exam Tips",
    question: "Which response directives are recommended to refresh cached content in the background and avoid cache misses?",
    correctAnswers: [
      "Use stale-while-revalidate and stale-if-error to refresh in the background and avoid cache misses",
      "The recommended directives are stale-while-revalidate and stale-if-error",
      "For background refresh and fewer cache misses, use stale-while-revalidate together with stale-if-error",
      "The speech recommends stale-while-revalidate plus stale-if-error as cache optimizations",
    ],
    incorrectAnswers: [
      "Use no-store and must-revalidate so the browser always bypasses the cache",
      "Set Vary: User-Agent and remove Cache-Control to improve reuse",
      "Use CQ-Action-Scope and CQ-Handle to refresh cached pages in the background",
      "Set private and Set-Cookie together so the CDN revalidates automatically",
      "Use only Expires with a past date so stale content refreshes silently",
      "Add default_virtualhosts.any so stale content is matched more broadly",
      "Use FileETag all and disable Surrogate-Control to avoid cache misses",
      "Set login-token and authorization cookies to immutable for background refresh",
    ],
    explanation:
      "The speech's optimization tips say to use stale-while-revalidate and stale-if-error to refresh in the background and avoid cache misses.",
  },
]
