import type { TriviaQuestion } from "./trivia-types"

export const mavenQuestionsPartB: TriviaQuestion[] = [
  {
    id: "mvn-051",
    topic: "Filters & Package Contents",
    question: "What does a package define in META-INF/vault/filter.xml according to the speech?",
    correctAnswers: [
      "Which repository paths the package owns",
      "The repository paths owned by that package",
      "Its owned repository roots and paths",
      "The set of repository paths that belong to the package",
    ],
    incorrectAnswers: [
      "The Java classes exported by the core bundle",
      "The Cloud Manager pipeline stages for the build",
      "The OSGi PID values for run-mode configs",
      "The list of Maven profiles enabled by default",
      "The Sling Models registered by the bundle",
      "The author users allowed to log in",
      "The editable template policies under /conf",
      "The Dispatcher cache rules for publish",
    ],
    explanation:
      "The speech says each package defines in META-INF/vault/filter.xml which repository paths it owns.",
  },
  {
    id: "mvn-052",
    topic: "Filters & Package Contents",
    question: "Given a scenario where content under a filter root exists in the repository but not in the package, which filter mode removes that extra content by default?",
    correctAnswers: [
      "replace",
      "The default mode is replace",
      "Use replace, which removes content under the filter root that is not in the package",
      "replace is the mode that deletes repository content not present in the package",
    ],
    incorrectAnswers: [
      "merge",
      "update",
      "append",
      "overlay",
      "preserve",
      "install",
      "container",
      "baseline",
    ],
    explanation:
      "The speech states that replace is the default mode and that it removes content in the filter root that is not in the package.",
  },
  {
    id: "mvn-053",
    topic: "Filters & Package Contents",
    question: "Which filter mode adds content and overwrites existing content but never removes anything?",
    correctAnswers: [
      "update",
      "Use update",
      "The mode is update",
      "update adds and overwrites but never removes",
    ],
    incorrectAnswers: [
      "replace",
      "merge",
      "sync",
      "author",
      "publish",
      "content",
      "application",
      "package",
    ],
    explanation:
      "The speech distinguishes the modes by saying update adds and overwrites but never removes.",
  },
  {
    id: "mvn-054",
    topic: "Filters & Package Contents",
    question: "What rule applies to a package that has /apps filters?",
    correctAnswers: [
      "It must not also have /content filters",
      "A package with /apps filters cannot also include /content filters",
      "Do not combine /apps and /content filters in the same package",
      "If /apps is filtered, /content must not be filtered in that same package",
    ],
    incorrectAnswers: [
      "It must always include /conf filters too",
      "It must be marked only as a content package",
      "It must store Repo Init scripts under /content",
      "It must use merge mode everywhere",
      "It must deploy only to publish instances",
      "It must exclude Oak index paths",
      "It must declare all templates under /apps and /content together",
      "It must embed Core Components examples",
    ],
    explanation:
      "The speech explicitly says a package that has /apps filters must not also have /content filters.",
  },
  {
    id: "mvn-055",
    topic: "Filters & Package Contents",
    question: "Why is mixing mutable and immutable roots in one package a problem in AEM as a Cloud Service?",
    correctAnswers: [
      "Because it violates the rules of AEM as a Cloud Service",
      "Because AEM as a Cloud Service forbids mixing mutable and immutable roots in one package",
      "Because a package cannot combine mutable and immutable roots under the cloud rules",
      "Because that mix breaks the AEM as a Cloud Service packaging rules",
    ],
    incorrectAnswers: [
      "Because it disables the Maven compiler parameters flag",
      "Because it forces cfg.json files to become invalid",
      "Because it changes the parent POM into a submodule",
      "Because it prevents Cloud Manager from using Git",
      "Because it converts ui.content into a bundle",
      "Because it removes the need for the all package",
      "Because it turns all filters into publish-only filters",
      "Because it requires JSP instead of HTL",
    ],
    explanation:
      "The speech says mixing mutable and immutable roots in one package violates the rules of AEM as a Cloud Service.",
  },
  {
    id: "mvn-056",
    topic: "Filters & Package Contents",
    question: "Given a scenario where you are packaging actual templates, where does the speech place them?",
    correctAnswers: [
      "Under /conf/<appId> in ui.content",
      "The actual templates belong in ui.content under /conf/<appId>",
      "Put actual templates in the ui.content module at /conf/<appId>",
      "Templates themselves live in /conf/<appId> inside ui.content",
    ],
    incorrectAnswers: [
      "Under /apps/<appId>/components in ui.apps",
      "Under /apps/<appId>/clientlibs in ui.apps",
      "Only in the parent POM modules section",
      "Under /apps/<appId>/osgiconfig in ui.config",
      "Inside the core bundle manifest",
      "Only under /content/dam/<appId>",
      "Under /var/workflow/models",
      "Inside Cloud Manager variables",
    ],
    explanation:
      "The speech says ui.content contains the actual templates under /conf/<appId>, while ui.apps contains template type and policy code under /apps/settings.",
  },
  {
    id: "mvn-057",
    topic: "Filters & Package Contents",
    question: "Where do legacy /etc nodes belong, according to the speech?",
    correctAnswers: [
      "In ui.content, with a goal of migrating them away from /etc",
      "Legacy /etc nodes belong in ui.content",
      "Place legacy /etc nodes in ui.content and ideally migrate them to non-/etc locations",
      "ui.content is where legacy /etc nodes belong",
    ],
    incorrectAnswers: [
      "In ui.apps because /etc is immutable",
      "In the core module because they are Java resources",
      "In ui.config as cfg.json files",
      "In the all module only",
      "In Cloud Manager environment variables",
      "In Dispatcher source folders only",
      "In the archetype command line as properties",
      "In dependencyManagement of the parent POM",
    ],
    explanation:
      "The speech says legacy /etc nodes belong in ui.content and ideally should be migrated to non-/etc locations.",
  },
  {
    id: "mvn-058",
    topic: "ui.config, Run Modes & Repo Init",
    question: "What does the ui.config package contain?",
    correctAnswers: [
      "OSGi configurations",
      "It contains the OSGi configurations",
      "The ui.config package holds OSGi config",
      "OSGi configuration files belong in ui.config",
    ],
    incorrectAnswers: [
      "Only editable template pages",
      "The embedded core bundle JAR",
      "The Java API dependency binaries",
      "The sample Selenium test reports",
      "Only Dispatcher farm files",
      "Author user home directories",
      "Core Components example pages for production",
      "The Maven wrapper distribution",
    ],
    explanation:
      "The speech says the ui.config package contains the OSGi configurations.",
  },
  {
    id: "mvn-059",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Why is ui.config considered code in the speech?",
    correctAnswers: [
      "Because the configurations belong to OSGi bundles and have no regular content nodes",
      "It is considered code because its configurations belong to OSGi bundles and are not regular content nodes",
      "Because OSGi configurations are code-oriented and do not have regular content nodes",
      "The speech treats ui.config as code since the configs belong to bundles rather than normal content",
    ],
    incorrectAnswers: [
      "Because it always contains Java classes and unit tests",
      "Because it stores pages under /content",
      "Because it is deployed only to publish",
      "Because it uses JSP tags instead of JSON",
      "Because it is the only module allowed in Cloud Manager",
      "Because it contains Core Components proxies",
      "Because it owns /dam filters by default",
      "Because it replaces the all module",
    ],
    explanation:
      "The speech explains that ui.config is considered code because the configurations belong to OSGi bundles and have no regular content nodes.",
  },
  {
    id: "mvn-060",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Where are the configurations stored inside the repository?",
    correctAnswers: [
      "In /apps/<appId>/osgiconfig",
      "The configurations live under /apps/<appId>/osgiconfig",
      "Store them in /apps/<appId>/osgiconfig",
      "OSGi configs are placed at /apps/<appId>/osgiconfig",
    ],
    incorrectAnswers: [
      "In /content/<appId>/osgiconfig",
      "In /conf/global/osgiconfig by default",
      "In /var/config only",
      "In /libs/<appId>/config",
      "In /etc/packages/osgiconfig",
      "In dependencyManagement",
      "In the all package filter root only",
      "In /content/dam/<appId>/configs",
    ],
    explanation:
      "The speech states that the configurations are in /apps/<appId>/osgiconfig.",
  },
  {
    id: "mvn-061",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Given a scenario where you need defaults that apply everywhere, which folder does the speech use?",
    correctAnswers: [
      "config",
      "Use the common config folder",
      "The defaults go in the config folder",
      "Place universal defaults in config",
    ],
    incorrectAnswers: [
      "config.defaults.global",
      "config.author.prod",
      "config.publish.stage",
      "install",
      "runmodes",
      "config.everywhere",
      "osgi.defaults",
      "config.shared.cloud",
    ],
    explanation:
      "The speech says a common folder named config holds defaults that apply everywhere.",
  },
  {
    id: "mvn-062",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Which folder name matches the run-mode naming pattern described in the speech?",
    correctAnswers: [
      "config.publish.prod",
      "config.publish.prod is a valid run-mode folder example",
      "Use a pattern like config.publish.prod",
      "A valid example is config.publish.prod",
    ],
    incorrectAnswers: [
      "config.production.publish",
      "publish.config.prod",
      "config.live.author",
      "config.qa.public",
      "config.author.production.eu",
      "osgiconfig.publish.default",
      "config.publish.uat",
      "config.editor.prod",
    ],
    explanation:
      "The speech gives examples such as config.author, config.publish.prod, and config.dev, and says the run-mode names are author and publish for the service plus dev, stage, and prod for the environment type.",
  },
  {
    id: "mvn-063",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Which format is best for Repo Init according to the speech, and why?",
    correctAnswers: [
      ".config because it supports multi-line values",
      "Use the .config format because Repo Init benefits from multi-line values",
      "Repo Init is best written as .config since that format supports multi-line values",
      "The speech recommends .config for Repo Init because of multi-line support",
    ],
    incorrectAnswers: [
      "cfg.json because Repo Init requires JSON arrays only",
      "xml because RepositoryInitializer only reads XML",
      "yaml because Cloud Manager converts it automatically",
      "properties because multi-line values are forbidden",
      "jsp because Repo Init runs in rendering",
      "jar because Repo Init is a bundle resource",
      "csv because ACLs are tabular",
      "htl because Repo Init is template-driven",
    ],
    explanation:
      "The speech says configuration files use cfg.json, with one exception: Repo Init is best written with the .config format because it supports multi-line values.",
  },
  {
    id: "mvn-064",
    topic: "ui.config, Run Modes & Repo Init",
    question: "Given a scenario where an application needs baseline content structures and service users before code runs, what is the recommended deployment mechanism?",
    correctAnswers: [
      "Repo Init",
      "Use Repo Init",
      "The recommended mechanism is Repo Init",
      "Deploy that baseline setup with Repo Init",
    ],
    incorrectAnswers: [
      "Editable templates only",
      "A Dispatcher flush agent",
      "A manual Package Manager upload after startup",
      "A Sling Model annotation",
      "A client library category",
      "DependencyManagement in the parent POM",
      "A Selenium suite in ui.tests",
      "A content policy under /apps/settings",
    ],
    explanation:
      "The speech says Repo Init is the recommended way to deploy mutable content that is logically part of the application, including baseline structures, users, service users, groups, and ACLs, and that it runs early in the deployment lifecycle.",
  },
  {
    id: "mvn-065",
    topic: "Parent POM",
    question: "What is the pom.xml at the root of the project?",
    correctAnswers: [
      "The parent POM",
      "It is the parent POM",
      "The root pom.xml serves as the parent POM",
      "The project root pom.xml is the parent POM",
    ],
    incorrectAnswers: [
      "The all package manifest",
      "The ui.apps content package definition",
      "The generated Dispatcher descriptor",
      "The OSGi bundle manifest",
      "The Repo Init script container",
      "The Selenium runner configuration",
      "The author run-mode folder",
      "The Core Components example site",
    ],
    explanation:
      "The speech says the pom.xml at the root of the project is the parent POM.",
  },
  {
    id: "mvn-066",
    topic: "Parent POM",
    question: "Which section of the parent POM manages dependency versions?",
    correctAnswers: [
      "dependencyManagement",
      "Use dependencyManagement",
      "Dependency versions are managed in dependencyManagement",
      "The parent POM manages versions in the dependencyManagement section",
    ],
    incorrectAnswers: [
      "modules",
      "repositories",
      "profiles",
      "buildExtensions",
      "reporting",
      "distributionManagement",
      "pluginRepositories",
      "scm",
    ],
    explanation:
      "The speech says the parent POM manages dependency versions in dependencyManagement.",
  },
  {
    id: "mvn-067",
    topic: "Parent POM",
    question: "What should submodules do about versions for managed dependencies?",
    correctAnswers: [
      "They must not include version information",
      "Submodules should omit versions for managed dependencies",
      "Do not specify versions in submodules for dependencies managed by the parent",
      "Managed dependency versions stay out of submodule POMs",
    ],
    incorrectAnswers: [
      "They must duplicate the parent versions in every module",
      "They must pin newer versions than the parent",
      "They must move versions into filter.xml",
      "They must set versions only in ui.apps",
      "They must define versions only for publish builds",
      "They must store versions in Repo Init",
      "They must use Cloud Manager variables for versions",
      "They must generate versions from cfg.json",
    ],
    explanation:
      "The speech explicitly says submodules must not include version information for managed dependencies because versions are managed in the parent.",
  },
  {
    id: "mvn-068",
    topic: "Parent POM",
    question: "Which defaults are used for local deployment in the global properties?",
    correctAnswers: [
      "localhost, 4502 for author, 4503 for publish, and the admin user",
      "The defaults are localhost with 4502 on author, 4503 on publish, and admin",
      "Local defaults use localhost, author 4502, publish 4503, and the admin user",
      "By default the POM targets localhost with ports 4502 and 4503 using admin",
    ],
    incorrectAnswers: [
      "127.0.0.1, 8080 for author, 8081 for publish, and anonymous",
      "localhost, 4503 for author, 4502 for publish, and deploy",
      "cloud.adobe.io, 443 for both, and admin",
      "localhost, 7502 for author, 7503 for publish, and workflow-user",
      "publish.local only, port 4503, and service-user",
      "localhost, 3000 for author, 3001 for publish, and root",
      "localhost, 4502 only, with no publish default",
      "author.local and publish.local with ports chosen by Repo Init",
    ],
    explanation:
      "The speech lists the defaults as localhost, 4502 for author, 4503 for publish, and the admin user.",
  },
  {
    id: "mvn-069",
    topic: "Parent POM",
    question: "Given a scenario where you need to deploy to a different host without editing the POM files, what does the speech recommend?",
    correctAnswers: [
      "Override the properties from the command line",
      "Pass deployment property overrides on the Maven command line",
      "Use command-line properties such as -Daem.host instead of changing the POM",
      "The POM should stay unchanged and the values should be overridden via Maven parameters",
    ],
    incorrectAnswers: [
      "Edit dependencyManagement for every deployment",
      "Rename the parent POM before each install",
      "Move the host settings into filter.xml",
      "Embed the production hostname in the core bundle",
      "Set the host only in ui.tests",
      "Convert the project to the older archetype groupId",
      "Store the host in /content/dam",
      "Delete the autoInstall profiles first",
    ],
    explanation:
      "The speech gives the example mvn -PautoInstallPackage clean install -Daem.host=production.hostname and says the POM files do not have to change.",
  },
  {
    id: "mvn-070",
    topic: "Parent POM",
    question: "For AEM as a Cloud Service, which dependency is the key AEM Java API entry?",
    correctAnswers: [
      "aem-sdk-api",
      "Use the aem-sdk-api dependency",
      "The key API dependency for AEM as a Cloud Service is aem-sdk-api",
      "AEM as a Cloud Service uses aem-sdk-api as the Java API dependency",
    ],
    incorrectAnswers: [
      "uber-jar",
      "core.wcm.components.examples",
      "aem-cloud-uber-jar",
      "sling-api-all",
      "granite-sdk-api",
      "oak-run-api",
      "dispatcher-sdk-api",
      "cq-quickstart-all",
    ],
    explanation:
      "The speech says that for AEM as a Cloud Service, the AEM Java API dependency is aem-sdk-api, while for AEM 6.5 it is the uber-jar.",
  },
  {
    id: "mvn-071",
    topic: "Parent POM",
    question: "What should happen to core.wcm.components.examples for production deployments?",
    correctAnswers: [
      "Remove it",
      "It should be removed for production deployments",
      "The sample package core.wcm.components.examples should not be kept in production",
      "For production, remove core.wcm.components.examples",
    ],
    incorrectAnswers: [
      "Embed it in every cloud deployment",
      "Promote it to the parent POM only",
      "Move it into ui.config",
      "Rename it to aem-sdk-api",
      "Deploy it only through Repo Init",
      "Convert it into an author run-mode folder",
      "Use it as the required package for ACLs",
      "Store it under /content/dam",
    ],
    explanation:
      "The speech describes core.wcm.components.examples as a set of sample pages and says to remove it for production deployments.",
  },
  {
    id: "mvn-072",
    topic: "Core Bundle & Testing",
    question: "What does the core module build?",
    correctAnswers: [
      "An OSGi bundle",
      "The core module builds an OSGi bundle",
      "It produces an OSGi bundle",
      "The output of the core module is an OSGi bundle",
    ],
    incorrectAnswers: [
      "A content package only",
      "A Dispatcher farm archive",
      "A Selenium browser profile",
      "A Repo Init-only configuration ZIP",
      "A language-master content tree",
      "A Cloud Manager pipeline JSON",
      "A cq:dialog definition package",
      "A client-side SPA bundle only",
    ],
    explanation:
      "The speech says the core module builds an OSGi bundle.",
  },
  {
    id: "mvn-073",
    topic: "Core Bundle & Testing",
    question: "What generates the bundle manifest, including the Sling-Model-Packages header?",
    correctAnswers: [
      "The bnd-maven-plugin",
      "Use the bnd-maven-plugin",
      "The bundle manifest is generated by the bnd-maven-plugin",
      "bnd-maven-plugin generates the manifest and Sling-Model-Packages header",
    ],
    incorrectAnswers: [
      "The maven-surefire-plugin",
      "The content-package-maven-plugin",
      "The frontend-maven-plugin",
      "The maven-archetype-plugin at runtime",
      "Cloud Manager automatically writing MANIFEST.MF",
      "Repo Init factory configs",
      "The ui.tests Selenium runner",
      "The Dispatcher SDK",
    ],
    explanation:
      "The speech says the bnd-maven-plugin generates the bundle manifest, including the Sling-Model-Packages header.",
  },
  {
    id: "mvn-074",
    topic: "Core Bundle & Testing",
    question: "According to the speech, what is the advantage of the generated Sling-Model-Packages header?",
    correctAnswers: [
      "You do not maintain it manually",
      "It means the header does not need manual maintenance",
      "The generated header avoids manual manifest maintenance",
      "Because it is generated, you do not edit that header by hand",
    ],
    incorrectAnswers: [
      "It forces every model to use request adaptable",
      "It stores ACLs for service users",
      "It replaces all unit tests in core",
      "It deploys templates under /conf",
      "It converts cfg.json into .config",
      "It installs the all package on publish",
      "It adds Core Components examples to production",
      "It changes the Java version in Cloud Manager automatically",
    ],
    explanation:
      "The speech specifically notes that the bnd-maven-plugin generates the Sling-Model-Packages header so you do not maintain it manually.",
  },
  {
    id: "mvn-075",
    topic: "Core Bundle & Testing",
    question: "Given a scenario with constructor injection, which Maven compiler option does the speech call out when needed?",
    correctAnswers: [
      "The parameters flag",
      "Use the parameters flag",
      "The Maven compiler options include the parameters flag when needed",
      "Constructor injection may require the parameters compiler flag",
    ],
    incorrectAnswers: [
      "The debug flag only",
      "The failOnWarning flag",
      "The reactor flag",
      "The profiles flag",
      "The offline flag",
      "The checksumPolicy flag",
      "The classifier flag",
      "The resources flag",
    ],
    explanation:
      "The speech says the Maven compiler options include the parameters flag when needed for constructor injection.",
  },
  {
    id: "mvn-076",
    topic: "Core Bundle & Testing",
    question: "What must the Java version of the build match?",
    correctAnswers: [
      "What Cloud Manager supports for the target AEM release",
      "The Java version supported by Cloud Manager for the target AEM release",
      "It must match Cloud Manager support for the target AEM release",
      "Use the Java version that Cloud Manager supports for that AEM target",
    ],
    incorrectAnswers: [
      "Whichever version the local browser uses",
      "The version embedded in /content",
      "Only the version used by Dispatcher tools",
      "The oldest Java version supported by Maven itself",
      "The version required by the com.adobe.granite.archetype groupId",
      "Whatever version is set in cfg.json",
      "The Node.js version in the front-end build",
      "The publish run-mode name",
    ],
    explanation:
      "The speech says the Java version of the build must match what Cloud Manager supports for the target AEM release.",
  },
  {
    id: "mvn-077",
    topic: "Core Bundle & Testing",
    question: "Where is the bundle embedded?",
    correctAnswers: [
      "In the all package",
      "The bundle is embedded in the all package",
      "Embed the bundle in all",
      "The all package contains the embedded bundle",
    ],
    incorrectAnswers: [
      "In ui.content only",
      "Directly under /conf",
      "In the ui.tests browser driver",
      "In the root README only",
      "In dependencyManagement only",
      "In config.publish.prod",
      "In the archetype command itself",
      "In /content/dam/<appId>",
    ],
    explanation:
      "The speech states that the bundle is embedded in the all package.",
  },
  {
    id: "mvn-078",
    topic: "Core Bundle & Testing",
    question: "What are the three testing levels described in the speech?",
    correctAnswers: [
      "Unit tests in core, integration tests in it.tests, and UI tests in ui.tests",
      "The three levels are unit in core, integration in it.tests, and UI in ui.tests",
      "Testing is split into core unit tests, server integration tests in it.tests, and browser UI tests in ui.tests",
      "There are unit, integration, and UI tests, mapped to core, it.tests, and ui.tests",
    ],
    incorrectAnswers: [
      "Unit tests in ui.apps, integration tests in ui.config, and UI tests in all",
      "Author tests, publish tests, and dispatcher tests only",
      "Manual tests, package tests, and Repo Init tests",
      "Sling tests, Oak tests, and CRX tests only",
      "JSP tests, HTL tests, and servlet tests",
      "POM tests, filter tests, and profile tests",
      "AEM tests, Maven tests, and Git tests",
      "Component tests, policy tests, and content tests only",
    ],
    explanation:
      "The speech lists three levels: unit tests in core, integration tests in it.tests running on the AEM server, and UI tests in ui.tests using Selenium in the browser.",
  },
  {
    id: "mvn-079",
    topic: "Generating with the Archetype",
    question: "What is the AEM Project Archetype?",
    correctAnswers: [
      "A Maven template that creates a minimal, best-practices-based AEM project",
      "It is a Maven template for a minimal AEM project based on best practices",
      "The archetype is a Maven project template for best-practices AEM setup",
      "A minimal best-practices AEM project is generated from this Maven archetype",
    ],
    incorrectAnswers: [
      "An OSGi bundle that replaces the core module",
      "A Repo Init script generator stored in ui.config",
      "A Dispatcher-only configuration package",
      "A browser plug-in for Selenium execution",
      "A content fragment model for exam preparation",
      "A filter.xml validator built into Oak",
      "A Cloud Manager environment variable set",
      "A cq:Page component under /apps",
    ],
    explanation:
      "The speech defines the AEM Project Archetype as a Maven template that creates a minimal, best-practices-based AEM project.",
  },
  {
    id: "mvn-080",
    topic: "Generating with the Archetype",
    question: "Which command-line tool is used to generate the project?",
    correctAnswers: [
      "The maven-archetype-plugin",
      "Use the maven-archetype-plugin",
      "Project generation is done with the maven-archetype-plugin",
      "The speech uses Maven's archetype plugin to generate the project",
    ],
    incorrectAnswers: [
      "The bnd-maven-plugin",
      "The maven-surefire-plugin",
      "The content-package-maven-plugin",
      "The Sling Model exporter plugin",
      "The Dispatcher SDK CLI",
      "The oak-run console",
      "The package manager install wizard",
      "The repository initializer factory",
    ],
    explanation:
      "The speech says to generate a project with the maven-archetype-plugin, version 3.3.1 or later.",
  },
  {
    id: "mvn-081",
    topic: "Generating with the Archetype",
    question: "What minimum archetype plugin version does the speech specify?",
    correctAnswers: [
      "3.3.1 or later",
      "Version 3.3.1 or newer",
      "At least 3.3.1",
      "Use maven-archetype-plugin 3.3.1 or later",
    ],
    incorrectAnswers: [
      "3.0.0 only",
      "3.1.0 exactly",
      "2.6 or later",
      "4.0.0 or later only",
      "1.0-SNAPSHOT",
      "6.5.8 or later",
      "4502 or later",
      "Latest only with no minimum stated",
    ],
    explanation:
      "The speech says to use the maven-archetype-plugin, version 3.3.1 or later.",
  },
  {
    id: "mvn-082",
    topic: "Generating with the Archetype",
    question: "According to the speech, when is the older archetype group ID com.adobe.granite.archetype needed?",
    correctAnswers: [
      "Only for older versions of the archetype",
      "It is needed only for older archetype versions",
      "Use the older group ID only when working with older archetype releases",
      "The speech says com.adobe.granite.archetype is only for older versions",
    ],
    incorrectAnswers: [
      "For every cloud project",
      "Whenever appId contains a hyphen",
      "Only for UI tests",
      "Only when generating Dispatcher config",
      "For all projects targeting 6.5.8 and later",
      "Whenever includeExamples is n",
      "Only when singleCountry is y",
      "For production deployments of Core Components examples",
    ],
    explanation:
      "The speech says the older archetype group ID, com.adobe.granite.archetype, is needed only for older versions of the archetype.",
  },
  {
    id: "mvn-083",
    topic: "Generating with the Archetype",
    question: "What does appTitle set?",
    correctAnswers: [
      "The website title and the component groups",
      "appTitle sets the website title and component groups",
      "It controls the site title plus component groups",
      "The speech says appTitle defines the website title and the component groups",
    ],
    incorrectAnswers: [
      "The Java package and artifact coordinates only",
      "The author and publish run modes",
      "The SDK version for cloud builds",
      "The Repo Init ACL definitions",
      "The /conf template root",
      "The Maven profile names",
      "The Oak index package type",
      "The Cloud Manager target",
    ],
    explanation:
      "The speech says appTitle sets the website title and the component groups.",
  },
  {
    id: "mvn-084",
    topic: "Generating with the Archetype",
    question: "Given a scenario where you need the technical name for component, config, and content folder names, which property does the speech use?",
    correctAnswers: [
      "appId",
      "Use appId",
      "The technical name property is appId",
      "appId is used for component, config, and content folder names",
    ],
    incorrectAnswers: [
      "appTitle",
      "sdkVersion",
      "singleCountry",
      "includeExamples",
      "country",
      "version",
      "aemVersion",
      "includeDispatcherConfig",
    ],
    explanation:
      "The speech says appId is the technical name used for the component, config, and content folder names, and the client library names.",
  },
  {
    id: "mvn-085",
    topic: "Generating with the Archetype",
    question: "What defaults does the speech give for artifactId, package, and version?",
    correctAnswers: [
      "artifactId defaults to appId, package defaults to groupId, and version defaults to 1.0-SNAPSHOT",
      "The defaults are artifactId = appId, package = groupId, and version = 1.0-SNAPSHOT",
      "artifactId uses appId by default, package uses groupId, and version is 1.0-SNAPSHOT",
      "By default the archetype sets artifactId from appId, package from groupId, and version to 1.0-SNAPSHOT",
    ],
    incorrectAnswers: [
      "artifactId defaults to appTitle, package defaults to appId, and version defaults to latest",
      "artifactId defaults to groupId, package defaults to appTitle, and version defaults to release",
      "artifactId defaults to core, package defaults to ui.apps, and version defaults to 6.5.8",
      "artifactId defaults to all, package defaults to cloud, and version defaults to 3.3.1",
      "artifactId defaults to mysite, package defaults to country, and version defaults to 4502",
      "artifactId defaults to publish, package defaults to author, and version defaults to admin",
      "artifactId defaults to archetypeVersion, package defaults to sdkVersion, and version defaults to none",
      "artifactId defaults to package, package defaults to artifactId, and version defaults to prod",
    ],
    explanation:
      "The speech lists the defaults directly: artifactId defaults to the appId, package defaults to the groupId, and version defaults to 1.0-SNAPSHOT.",
  },
  {
    id: "mvn-086",
    topic: "Archetype Options",
    question: "What does aemVersion select?",
    correctAnswers: [
      "The target AEM platform",
      "aemVersion selects the target",
      "It chooses which AEM target the project is generated for",
      "The speech says aemVersion determines the target environment type",
    ],
    incorrectAnswers: [
      "The Maven compiler flag set",
      "The bundle symbolic name",
      "The filter mode for ui.content",
      "The number of testing modules",
      "The Cloud Manager Git branch",
      "The Repo Init script language",
      "The packageType of the all module",
      "The workflow inbox group",
    ],
    explanation:
      "The speech says aemVersion selects the target.",
  },
  {
    id: "mvn-087",
    topic: "Archetype Options",
    question: "What is the default value of aemVersion?",
    correctAnswers: [
      "cloud",
      "The default is cloud",
      "aemVersion defaults to cloud",
      "By default the archetype targets cloud",
    ],
    incorrectAnswers: [
      "6.5.8",
      "latest",
      "general",
      "none",
      "publish",
      "author",
      "ams",
      "onprem",
    ],
    explanation:
      "The speech says the default for aemVersion is cloud for AEM as a Cloud Service.",
  },
  {
    id: "mvn-088",
    topic: "Archetype Options",
    question: "When is sdkVersion used, according to the speech?",
    correctAnswers: [
      "Only when aemVersion is cloud",
      "sdkVersion applies only if aemVersion is cloud",
      "Use sdkVersion only for cloud targets",
      "The speech says sdkVersion is relevant only when aemVersion equals cloud",
    ],
    incorrectAnswers: [
      "Only when includeExamples is y",
      "Only for on-premise 6.5.8",
      "Only for UI tests",
      "Only when singleCountry is n",
      "Only when packageType is container",
      "Only in the core module",
      "Only when using com.adobe.granite.archetype",
      "Only for publish run mode folders",
    ],
    explanation:
      "The speech says sdkVersion, only when aemVersion is cloud, picks a specific SDK version.",
  },
  {
    id: "mvn-089",
    topic: "Archetype Options",
    question: "What does includeDispatcherConfig do by default?",
    correctAnswers: [
      "It defaults to y and adds Dispatcher configuration",
      "The default is y, which adds Dispatcher config",
      "includeDispatcherConfig is y by default and includes Dispatcher configuration",
      "By default it adds Dispatcher configuration",
    ],
    incorrectAnswers: [
      "It defaults to n and removes Dispatcher files",
      "It forces Selenium UI tests to run",
      "It adds only Repo Init scripts",
      "It disables the front-end module",
      "It changes appId to dispatcher",
      "It embeds Core Components examples",
      "It converts all packages to container type",
      "It sets cloudManagerTarget to publish",
    ],
    explanation:
      "The speech says includeDispatcherConfig, default y, adds the Dispatcher configuration for cloud or for AMS and on-premise depending on aemVersion.",
  },
  {
    id: "mvn-090",
    topic: "Archetype Options",
    question: "Which values does the speech list for frontendModule in the standard options described there?",
    correctAnswers: [
      "general and none",
      "The values listed are general and none",
      "frontendModule defaults to general, and the other value mentioned is none",
      "The speech names general and none as the relevant frontendModule values",
    ],
    incorrectAnswers: [
      "author and publish",
      "cloud and 6.5.8",
      "react and angular only",
      "core and all",
      "style-system and editable-templates",
      "apps and content",
      "merge and replace",
      "latest and locked",
    ],
    explanation:
      "The speech says frontendModule, default general, includes the front-end build module, and the other value is none. It separately notes SPA options add React or Angular front-end modules.",
  },
  {
    id: "mvn-091",
    topic: "Archetype Options",
    question: "What do language and country set?",
    correctAnswers: [
      "The content structure",
      "They set the content structure",
      "language and country define the content structure, such as en and us",
      "The speech uses language and country to shape the content structure",
    ],
    incorrectAnswers: [
      "The Java compiler source and target",
      "The OSGi PID naming convention",
      "The repository filter modes",
      "The parent POM dependency versions",
      "The bundle manifest headers",
      "The admin credentials for local install",
      "The packageType values for packages",
      "The autoInstall Maven profile names",
    ],
    explanation:
      "The speech says language and country set the content structure, for example en and us.",
  },
  {
    id: "mvn-092",
    topic: "Archetype Options",
    question: "Given a scenario where you need a language-master content structure for multi-language and multi-region setups, how should singleCountry be set?",
    correctAnswers: [
      "Set singleCountry to n",
      "singleCountry should be n",
      "Use n for singleCountry so a language-master structure is created",
      "The speech implies singleCountry must not stay at the default y if you want language-master structure",
    ],
    incorrectAnswers: [
      "Set singleCountry to y",
      "Set singleCountry to cloud",
      "Set singleCountry to latest",
      "Set singleCountry to author",
      "Set singleCountry to general",
      "Set singleCountry to 6.5.8",
      "Set singleCountry to package",
      "Set singleCountry to config.publish.prod",
    ],
    explanation:
      "The speech says singleCountry, default y, controls whether a language-master content structure is created, and that structure is used for multi-language and multi-region setups. Therefore, wanting that structure means not keeping the single-country default.",
  },
  {
    id: "mvn-093",
    topic: "Build, Deploy & Best Practices",
    question: "What does mvn clean install do in this project?",
    correctAnswers: [
      "It builds all modules and produces the packages and the bundle",
      "mvn clean install builds every module and creates the packages and bundle",
      "The command builds all modules and outputs both the packages and the OSGi bundle",
      "Running mvn clean install produces the packages and bundle for the whole project",
    ],
    incorrectAnswers: [
      "It installs only ui.content on publish",
      "It runs only Selenium UI tests and skips builds",
      "It creates only Repo Init scripts without packages",
      "It deploys directly to Cloud Manager without Maven",
      "It edits the parent POM dependency versions automatically",
      "It rebuilds only the Dispatcher configuration",
      "It removes the all package from the reactor",
      "It converts filter modes to replace",
    ],
    explanation:
      "The speech says mvn clean install builds all modules and produces the packages and the bundle.",
  },
  {
    id: "mvn-094",
    topic: "Build, Deploy & Best Practices",
    question: "Which Maven profile installs the all package on the author instance from the project root?",
    correctAnswers: [
      "autoInstallSinglePackage",
      "Use autoInstallSinglePackage",
      "The author install profile is autoInstallSinglePackage",
      "At the project root, autoInstallSinglePackage installs the all package on author",
    ],
    incorrectAnswers: [
      "autoInstallSinglePackagePublish",
      "autoInstallBundle",
      "autoInstallPackage",
      "cleanInstallAuthor",
      "installAllToAuthorPublish",
      "autoInstallExamples",
      "cloudManagerDeploy",
      "publishInstallBundle",
    ],
    explanation:
      "The speech says autoInstallSinglePackage, at the project root, installs the all package on the author instance.",
  },
  {
    id: "mvn-095",
    topic: "Build, Deploy & Best Practices",
    question: "Which profile installs the all package on the publish instance?",
    correctAnswers: [
      "autoInstallSinglePackagePublish",
      "Use autoInstallSinglePackagePublish",
      "The publish install profile is autoInstallSinglePackagePublish",
      "autoInstallSinglePackagePublish installs the all package on publish",
    ],
    incorrectAnswers: [
      "autoInstallSinglePackage",
      "autoInstallBundle",
      "autoInstallPackage",
      "publishOnlyAllPackage",
      "installPublishBundle",
      "cloudPublishInstall",
      "packagePublishRoot",
      "uiPublishInstall",
    ],
    explanation:
      "The speech says autoInstallSinglePackagePublish installs the all package on the publish instance.",
  },
  {
    id: "mvn-096",
    topic: "Build, Deploy & Best Practices",
    question: "Given a scenario where you are actively developing Java code and want the fastest deployment option, which profile should you use?",
    correctAnswers: [
      "autoInstallBundle in the core module",
      "Use autoInstallBundle from the core module",
      "The fast Java-development option is autoInstallBundle in core",
      "For quick Java iteration, install only the OSGi bundle with autoInstallBundle",
    ],
    incorrectAnswers: [
      "autoInstallSinglePackagePublish from the project root",
      "autoInstallPackage in ui.content for every change",
      "includeDispatcherConfig with y",
      "maven-archetype-plugin generate",
      "singleCountry = y",
      "core.wcm.components.examples",
      "config.publish.prod",
      "dependencyManagement install",
    ],
    explanation:
      "The speech says autoInstallBundle in the core module installs only the OSGi bundle and is the fast option while developing Java code.",
  },
  {
    id: "mvn-097",
    topic: "Build, Deploy & Best Practices",
    question: "What does Cloud Manager deploy, according to the speech?",
    correctAnswers: [
      "Only the all package",
      "Cloud Manager deploys only the all package",
      "The deployed artifact in Cloud Manager is only the all package",
      "The speech says Cloud Manager builds with Maven and deploys only the all package",
    ],
    incorrectAnswers: [
      "Only ui.apps and never all",
      "Only the core bundle with no package",
      "Every package except all",
      "Only Repo Init factory configs",
      "Only the Dispatcher module",
      "Only ui.tests reports",
      "Only the parent POM",
      "Only /content filters",
    ],
    explanation:
      "The speech says Cloud Manager builds the project from Git with Maven and deploys only the all package.",
  },
  {
    id: "mvn-098",
    topic: "Build, Deploy & Best Practices",
    question: "According to the best practices list, where should Oak indexes be deployed?",
    correctAnswers: [
      "As code in ui.apps",
      "Deploy Oak indexes as code in ui.apps",
      "Oak indexes belong in ui.apps as code",
      "The speech says Oak indexes should be packaged as code in ui.apps",
    ],
    incorrectAnswers: [
      "As mutable content in ui.content",
      "Inside Repo Init scripts only",
      "Only in Cloud Manager variables",
      "Under /content/dam/<appId>",
      "As Selenium fixtures in ui.tests",
      "Inside the parent POM modules section",
      "In /conf/<appId> templates",
      "In the examples package for production",
    ],
    explanation:
      "The best practices section explicitly says to deploy Oak indexes as code in ui.apps.",
  },
  {
    id: "mvn-099",
    topic: "Build, Deploy & Best Practices",
    question: "What should cloudManagerTarget be set to on every package except all?",
    correctAnswers: [
      "none",
      "Set cloudManagerTarget to none",
      "Every package except all should use cloudManagerTarget = none",
      "The speech says cloudManagerTarget must be none for all packages except all",
    ],
    incorrectAnswers: [
      "all",
      "author",
      "publish",
      "cloud",
      "application",
      "content",
      "container",
      "latest",
    ],
    explanation:
      "The best practices list says to set cloudManagerTarget to none on every package except all.",
  },
  {
    id: "mvn-100",
    topic: "Build, Deploy & Best Practices",
    question: "Given a scenario where a team wants to store environment-specific values directly in Java code, what does the speech say instead?",
    correctAnswers: [
      "Put environment-specific values in run-mode folders and Cloud Manager variables, never in code",
      "Environment-specific values belong in run-mode folders and Cloud Manager variables, not in code",
      "Use run-mode folders plus Cloud Manager variables instead of hardcoding environment-specific values",
      "The speech says never place environment-specific values in code; use run-mode folders and Cloud Manager variables",
    ],
    incorrectAnswers: [
      "Hardcode them in the core bundle for faster deployment",
      "Store them only in /content/<appId> pages",
      "Place them in filter.xml so Cloud Manager can edit them",
      "Keep them in the parent POM and commit per environment",
      "Write them under /apps/settings as template policies",
      "Embed them in core.wcm.components.examples",
      "Put them only in Selenium test classes",
      "Define them only in the archetype generate command forever",
    ],
    explanation:
      "The best practices section says to put environment-specific values in run-mode folders and Cloud Manager variables, never in code.",
  },
]
