import type { TriviaQuestion } from "./trivia-types"

export const mavenQuestionsPartA: TriviaQuestion[] = [

  // ── INTRODUCTION (7) ─────────────────────────────────────────────────────

  {
    id: "mvn-001",
    topic: "Introduction",
    question: "What does this lesson focus on after component construction has already been covered?",
    correctAnswers: [
      "How everything is packaged and deployed",
      "It focuses on how the AEM project is packaged and deployed",
      "The lesson turns to packaging and deployment",
      "It covers the packaging and deployment side of the project",
    ],
    incorrectAnswers: [
      "How to author editable templates in the page editor",
      "How to configure workflow inbox delegation rules",
      "How to build GraphQL persisted queries for headless delivery",
      "How to migrate classic UI dialogs to Coral 2",
      "How to tune Dispatcher cache invalidation headers",
      "How to create IMS technical accounts manually",
      "How to administer users in Adobe Admin Console",
      "How to model commerce catalogs in CIF",
    ],
    explanation:
      "The introduction says the lesson now looks at how everything is packaged and deployed, including project structure, content package types, the container package, and the AEM Project Archetype.",
  },
  {
    id: "mvn-002",
    topic: "Introduction",
    question: "Which exam section does this lesson map to?",
    correctAnswers: [
      "Section 3: Build and Deployment",
      "It maps to Section 3, Build and Deployment",
      "The lesson is aligned to the Build and Deployment section of the exam",
      "Its exam mapping is Section 3 on Build and Deployment",
    ],
    incorrectAnswers: [
      "Section 1: Configurations",
      "Section 2: AEM Development",
      "Section 4: Dispatcher and CDN Rules",
      "Section 5: Security Administration",
      "Section 6: Content Fragment Modeling",
      "Section 7: Forms Integration",
      "Section 8: Workflow Authoring",
      "Section 9: Analytics Reporting",
    ],
    explanation:
      "The speech explicitly says the lesson maps to Section 3 of the exam: Build and Deployment.",
  },
  {
    id: "mvn-003",
    topic: "Introduction",
    question: "Which specific objective is called out for identifying the correct Maven project structure?",
    correctAnswers: [
      "Objective 3.1",
      "It is exam objective 3.1",
      "The correct objective is Section 3.1",
      "Identifying the Maven project structure is covered by 3.1",
    ],
    incorrectAnswers: [
      "Objective 1.1",
      "Objective 2.2",
      "Objective 3.3",
      "Objective 4.1",
      "Objective 5.2",
      "Objective 6.1",
      "Objective 7.3",
      "Objective 8.2",
    ],
    explanation:
      "The introduction says 3.1 is the objective for identifying the correct Maven project structure.",
  },
  {
    id: "mvn-004",
    topic: "Introduction",
    question: "Given a scenario, which objective covers identifying how to configure projects from archetypes?",
    correctAnswers: [
      "Objective 3.2",
      "That scenario maps to exam objective 3.2",
      "The archetype-configuration objective is 3.2",
      "Configuring projects from archetypes is covered by Section 3.2",
    ],
    incorrectAnswers: [
      "Objective 1.2",
      "Objective 2.1",
      "Objective 2.3",
      "Objective 3.1",
      "Objective 4.2",
      "Objective 5.1",
      "Objective 6.2",
      "Objective 9.1",
    ],
    explanation:
      "The speech states that 3.2 covers scenario-based identification of how to configure projects from archetypes.",
  },
  {
    id: "mvn-005",
    topic: "Introduction",
    question: "About what percentage of the exam is Build and Deployment?",
    correctAnswers: [
      "About 17 percent",
      "Roughly 17 percent of the exam",
      "It accounts for about 17% of the exam",
      "Build and Deployment is worth about seventeen percent",
    ],
    incorrectAnswers: [
      "About 5 percent",
      "About 10 percent",
      "About 25 percent",
      "About 33 percent",
      "About 40 percent",
      "About 50 percent",
      "About 60 percent",
      "About 75 percent",
    ],
    explanation:
      "The introduction says Build and Deployment is about 17 percent of the exam, making it worth careful study.",
  },
  {
    id: "mvn-006",
    topic: "Introduction",
    question: "What kind of exam questions should you expect for this topic?",
    correctAnswers: [
      "Scenario questions about modules, package types, deployment failures, and archetype properties",
      "Expect scenario-based questions about which module, which package type, why deployment failed, and which archetype property caused the result",
      "The exam style is scenario-based, focusing on module placement, package choice, deployment failure causes, and archetype settings",
      "You should expect scenarios involving the correct module, package type, deployment failure reason, and archetype property",
    ],
    incorrectAnswers: [
      "Only essay questions about Adobe company history",
      "Only command memorization for Git without scenarios",
      "Only UI click-path questions about the Sites console",
      "Only pricing questions about Cloud Manager licensing",
      "Only Java syntax trivia unrelated to AEM packaging",
      "Only design questions about color systems in component libraries",
      "Only translation workflow questions with no deployment content",
      "Only Dispatcher log interpretation with no project structure content",
    ],
    explanation:
      "The introduction says to expect scenario questions such as which module holds a file, which package type is correct, why deployment failed, and which Archetype property produced a result.",
  },
  {
    id: "mvn-007",
    topic: "Introduction",
    question: "Which set of subjects is explicitly named in the introduction as part of this lesson?",
    correctAnswers: [
      "Maven project structure, content package types, the container package, and the AEM Project Archetype",
      "The lesson covers the Maven project structure, package types, the container package, and the AEM Project Archetype",
      "It includes project structure, package types, the all container package, and the project archetype",
      "The named subjects are project structure, content package types, the container package, and the archetype",
    ],
    incorrectAnswers: [
      "Dispatcher farms, CDN headers, and vanity URL mappings",
      "Editable template policies, MSM rollouts, and translation jobs",
      "User sync, IMS organizations, and SSO trust stores",
      "Content Fragment Models, GraphQL schemas, and persisted queries",
      "Sling Jobs, workflow launchers, and inbox notifications",
      "Asset microservices, Smart Tags, and Dynamic Media profiles",
      "SPA Editor routing, React hydration, and SSR adapters",
      "Replication agents, reverse replication, and transport users",
    ],
    explanation:
      "The introduction names four study areas: the Maven project structure, the content package types, the container package, and the AEM Project Archetype.",
  },

  // ── MUTABLE VS IMMUTABLE AREAS (7) ───────────────────────────────────────

  {
    id: "mvn-008",
    topic: "Mutable vs Immutable Areas",
    question: "In AEM as a Cloud Service, which repository areas are immutable after startup?",
    correctAnswers: [
      "/apps and /libs",
      "The immutable areas are /apps and /libs",
      "AEM Cloud Service treats /apps and /libs as immutable",
      "After startup, /apps and /libs cannot be changed at runtime",
    ],
    incorrectAnswers: [
      "/content and /conf",
      "/var and /tmp",
      "/oak:index and /home",
      "/etc and /system",
      "/content and /apps",
      "/libs and /content",
      "/conf and /oak:index",
      "/dam and /var",
    ],
    explanation:
      "Section 2 says AEM as a Cloud Service requires strict separation of code and content, and specifically marks /apps and /libs as immutable.",
  },
  {
    id: "mvn-009",
    topic: "Mutable vs Immutable Areas",
    question: "What happens if code tries to create, update, or delete something in /apps at runtime after AEM starts?",
    correctAnswers: [
      "The attempt fails",
      "It fails because /apps is immutable at runtime",
      "A runtime write to /apps is rejected",
      "The operation cannot succeed because /apps cannot be modified after startup",
    ],
    incorrectAnswers: [
      "AEM moves the node automatically to /var",
      "The change succeeds only on author and replicates later",
      "The change succeeds if a service user has write permissions",
      "AEM converts the write into a Repo Init instruction",
      "Cloud Manager stores the change in ui.content automatically",
      "The write succeeds temporarily until the next deployment",
      "AEM redirects the update into /conf with the same path",
      "The node is created in /libs as a fallback",
    ],
    explanation:
      "The speech states that after AEM starts, you cannot create, update, or delete anything in /apps or /libs at runtime, and any attempt fails.",
  },
  {
    id: "mvn-010",
    topic: "Mutable vs Immutable Areas",
    question: "Which of these paths is listed as mutable in the speech?",
    correctAnswers: [
      "/conf",
      "/conf is one of the mutable areas",
      "The speech explicitly lists /conf as mutable",
      "A mutable example from the lesson is /conf",
    ],
    incorrectAnswers: [
      "/libs",
      "/apps",
      "/libs/settings",
      "/apps/install",
      "/libs/clientlibs",
      "/apps/components",
      "/libs/cq/gui",
      "/apps/cq/core",
    ],
    explanation:
      "The mutable list includes /content, /conf, /var, /etc, /system, /tmp, /home, and /oak:index.",
  },
  {
    id: "mvn-011",
    topic: "Mutable vs Immutable Areas",
    question: "Why can't a single content package deploy to both /apps and a mutable area in AEM as a Cloud Service?",
    correctAnswers: [
      "Because the application must split code and content into discrete packages",
      "Because Cloud Service requires code and content to be separated into different packages",
      "Because one package cannot mix immutable code roots with mutable content roots",
      "Because the strict code-versus-content separation requires separate packages",
    ],
    incorrectAnswers: [
      "Because Package Manager accepts only one filter root per package",
      "Because /apps can be deployed only through Replication agents",
      "Because mutable areas must always be installed from ZIP files by hand",
      "Because /content packages must be JSON, not Vault packages",
      "Because Cloud Manager deploys only packages without filters",
      "Because /apps content must always live inside the core bundle JAR",
      "Because AEM forbids packages with more than one subpackage",
      "Because /conf must always be installed from CRXDE Lite",
    ],
    explanation:
      "The speech says that due to the separation of immutable code and mutable content, a single package cannot deploy to both /apps and a mutable area, so the application must split them into discrete packages.",
  },
  {
    id: "mvn-012",
    topic: "Mutable vs Immutable Areas",
    question: "Which statement about /libs is correct?",
    correctAnswers: [
      "/libs must never be modified because only AEM product code is deployed there",
      "Only AEM product code belongs in /libs, so it must never be changed",
      "The rule is that /libs is reserved for AEM product code and must not be modified",
      "/libs is off-limits to application changes because it contains only product code",
    ],
    incorrectAnswers: [
      "/libs is the recommended location for project-specific client libraries",
      "/libs is mutable on author but immutable on publish",
      "/libs should hold tenant templates to keep /apps clean",
      "/libs is where Repo Init stores generated groups",
      "/libs is the required location for editable template policies",
      "/libs is intended for site content that authors update daily",
      "/libs is where Cloud Manager stores embedded subpackages",
      "/libs should be patched during runtime for emergency fixes",
    ],
    explanation:
      "The lesson says that, as in earlier versions, /libs must never be modified and only AEM product code is deployed there.",
  },
  {
    id: "mvn-013",
    topic: "Mutable vs Immutable Areas",
    question: "Given a scenario with Oak indexes in Cloud Service, how are index definitions treated for deployment?",
    correctAnswers: [
      "They are deployed as code in ui.apps",
      "Oak index definitions are treated as code and placed in ui.apps",
      "Even though /oak:index is mutable, index definitions deploy with the code package in ui.apps",
      "The correct treatment is to deploy Oak indexes as code through ui.apps",
    ],
    incorrectAnswers: [
      "They belong only in ui.content because /oak:index is mutable",
      "They must be authored live under /oak:index after deployment",
      "They go only inside ui.config with run-mode folders",
      "They are embedded only in the core bundle manifest",
      "They are installed from dispatcher.cloud during publish activation",
      "They should be created manually in /libs/oak:index",
      "They are stored only in the all package with no source module",
      "They must be delivered through install hooks in the container package",
    ],
    explanation:
      "The speech calls Oak indexes a special case: although /oak:index is mutable at runtime, Cloud Manager waits for reindexing before switching code, so index definitions are deployed as code in ui.apps.",
  },
  {
    id: "mvn-014",
    topic: "Mutable vs Immutable Areas",
    question: "Why are Oak index definitions not treated like ordinary mutable content?",
    correctAnswers: [
      "Because Cloud Manager waits for the new index to be deployed and fully reindexed before switching to the new code image",
      "Because code deployment in Cloud Service must wait until the new index is deployed and fully reindexed",
      "Because the switch to the new code image happens only after the new index is deployed and reindexed",
      "Because reindexing must complete before Cloud Manager moves to the new code image",
    ],
    incorrectAnswers: [
      "Because Oak indexes are stored only in /libs and cannot be packaged",
      "Because Oak indexes are never deployed in Cloud Service",
      "Because Cloud Manager ignores indexes and updates them lazily later",
      "Because index definitions can be changed only from the web console",
      "Because index changes are applied only during author replication",
      "Because indexes require classic package hooks to install",
      "Because Oak indexes are part of dispatcher.cloud and not repository code",
      "Because reindexing is disabled in Cloud Service environments",
    ],
    explanation:
      "The reason given is that Cloud Manager waits until a new index is deployed and fully reindexed before switching to the new code image.",
  },

  // ── PROJECT MODULES (7) ──────────────────────────────────────────────────

  {
    id: "mvn-015",
    topic: "Project Modules",
    question: "Which module is the Java OSGi bundle with Sling Models, servlets, listeners, schedulers, services, and request filters?",
    correctAnswers: [
      "core",
      "The core module",
      "That belongs in core",
      "The Java OSGi bundle module is core",
    ],
    incorrectAnswers: [
      "ui.apps",
      "ui.content",
      "ui.config",
      "all",
      "dispatcher.cloud",
      "ui.tests",
      "it.tests",
      "ui.frontend",
    ],
    explanation:
      "Section 3 says core is the Java OSGi bundle and lists OSGi services, listeners, schedulers, Sling Models, servlets, and request filters there.",
  },
  {
    id: "mvn-016",
    topic: "Project Modules",
    question: "Which module contains the /apps part of the project, including components, clientlibs, templates code, and Oak index definitions?",
    correctAnswers: [
      "ui.apps",
      "The ui.apps module",
      "That content belongs in ui.apps",
      "The /apps project area is housed in ui.apps",
    ],
    incorrectAnswers: [
      "ui.content",
      "ui.config",
      "core",
      "all",
      "it.tests",
      "ui.tests",
      "dispatcher.ams",
      "ui.frontend",
    ],
    explanation:
      "The speech says ui.apps contains the /apps part of the project: components, clientlibs, templates code, and Oak index definitions.",
  },
  {
    id: "mvn-017",
    topic: "Project Modules",
    question: "Given a scenario with OSGi configurations in run-mode folders and Repo Init scripts, which module should hold them?",
    correctAnswers: [
      "ui.config",
      "They belong in ui.config",
      "The correct module is ui.config",
      "OSGi run-mode configs and Repo Init scripts are stored in ui.config",
    ],
    incorrectAnswers: [
      "ui.content",
      "ui.apps",
      "core",
      "all",
      "ui.frontend",
      "dispatcher.cloud",
      "it.tests",
      "ui.tests",
    ],
    explanation:
      "Section 3 defines ui.config as the module containing OSGi configurations in run-mode specific folders plus the Repo Init scripts.",
  },
  {
    id: "mvn-018",
    topic: "Project Modules",
    question: "Which module contains mutable content and configuration such as /content, /conf, /content/dam, context-aware configurations, and governed tag taxonomies?",
    correctAnswers: [
      "ui.content",
      "The ui.content module",
      "Those mutable repository areas belong in ui.content",
      "The correct module for that mutable content is ui.content",
    ],
    incorrectAnswers: [
      "ui.apps",
      "ui.config",
      "core",
      "all",
      "dispatcher.cloud",
      "dispatcher.ams",
      "it.tests",
      "ui.tests",
    ],
    explanation:
      "The speech says ui.content contains mutable content and configuration such as /content, /conf, /content/dam, context-aware configurations, and governed tag taxonomies.",
  },
  {
    id: "mvn-019",
    topic: "Project Modules",
    question: "What is the role of the all module?",
    correctAnswers: [
      "It is the container package that embeds everything into one deployable artifact",
      "The all module is the container package for the full deployment artifact",
      "Its role is to embed the project deliverables into one deployable container",
      "all acts as the single container package that wraps the deployable pieces",
    ],
    incorrectAnswers: [
      "It is the Java bundle where Sling Models are compiled",
      "It is the Selenium test suite for authoring flows",
      "It is the module for mutable site content only",
      "It is the module that stores Dispatcher rewrite rules only",
      "It is the optional webpack front-end build",
      "It is the package where all OSGi configs must be authored directly",
      "It is the AMS-only project root for CRX package uploads",
      "It is the module that replaces the parent pom.xml",
    ],
    explanation:
      "Section 3 explicitly says all is the container package that embeds everything into one deployable artifact.",
  },
  {
    id: "mvn-020",
    topic: "Project Modules",
    question: "Which module is optional and contains the webpack-based front-end build that generates clientlibs?",
    correctAnswers: [
      "ui.frontend",
      "The optional module is ui.frontend",
      "That webpack-based clientlib build belongs in ui.frontend",
      "The front-end build module is ui.frontend",
    ],
    incorrectAnswers: [
      "ui.apps",
      "core",
      "ui.content",
      "all",
      "it.tests",
      "ui.tests",
      "dispatcher.cloud",
      "dispatcher.ams",
    ],
    explanation:
      "The speech says ui.frontend is optional and contains the webpack-based front-end build that generates the clientlibs.",
  },
  {
    id: "mvn-021",
    topic: "Project Modules",
    question: "Which statement about testing modules is correct?",
    correctAnswers: [
      "it.tests contains Java-based integration tests on the AEM server, ui.tests contains Selenium UI tests, and unit tests live in core",
      "Integration tests run in it.tests, UI tests run in ui.tests, and unit tests stay in core",
      "The project separates tests into core unit tests, it.tests integration tests, and ui.tests Selenium tests",
      "Unit tests are in core, Java integration tests are in it.tests, and Selenium tests are in ui.tests",
    ],
    incorrectAnswers: [
      "All tests belong in the all module because it is the deployment artifact",
      "Unit tests belong only in ui.content because they verify content structures",
      "Selenium tests belong in dispatcher.cloud because they exercise publish",
      "Java integration tests belong in ui.apps because they deploy to /apps",
      "There is only one test module and it replaces core tests entirely",
      "UI tests run from ui.config because they depend on run modes",
      "it.tests contains client libraries and no automated tests",
      "ui.tests contains only JAR manifests for OSGi bundles",
    ],
    explanation:
      "Section 3 says it.tests contains Java-based integration tests that run on the AEM server, ui.tests contains Selenium-based UI tests, and unit tests live in core.",
  },

  // ── PACKAGE TYPES (7) ────────────────────────────────────────────────────

  {
    id: "mvn-022",
    topic: "Package Types",
    question: "Where is the package type configured for an AEM package?",
    correctAnswers: [
      "In the packageType configuration of the filevault-package-maven-plugin",
      "It is set with packageType in the filevault-package-maven-plugin",
      "The package type is declared through the filevault-package-maven-plugin packageType setting",
      "You configure it in the FileVault package Maven plugin using packageType",
    ],
    incorrectAnswers: [
      "In the bundleSymbolicName of the bnd-maven-plugin",
      "In the artifactId of the parent pom.xml only",
      "In CRXDE Lite under /system/packageTypes",
      "In a Cloud Manager environment variable named PACKAGE_TYPE",
      "In the Dispatcher farm file under /virtualhosts",
      "In the Sling Model annotation on the package-info.java file",
      "In the OSGi web console configuration PID",
      "In the content.xml jcr:primaryType of the package root",
    ],
    explanation:
      "Section 4 says every package must declare a package type, and that the type is set with the packageType configuration of the filevault-package-maven-plugin.",
  },
  {
    id: "mvn-023",
    topic: "Package Types",
    question: "What packageType do code, immutable packages use?",
    correctAnswers: [
      "application",
      "They use packageType application",
      "The correct type for immutable code packages is application",
      "Code packages are marked as application",
    ],
    incorrectAnswers: [
      "content",
      "container",
      "bundle",
      "install",
      "repository",
      "structure",
      "author",
      "publish",
    ],
    explanation:
      "The speech says code, immutable packages set packageType to application, with ui.apps and ui.config given as examples.",
  },
  {
    id: "mvn-024",
    topic: "Package Types",
    question: "What packageType should ui.content use?",
    correctAnswers: [
      "content",
      "ui.content should use packageType content",
      "The mutable content package type is content",
      "ui.content is marked as a content package",
    ],
    incorrectAnswers: [
      "application",
      "container",
      "bundle",
      "subPackage",
      "install",
      "acl",
      "osgi",
      "repo-init",
    ],
    explanation:
      "Section 4 states that content, mutable packages set packageType to content, and ui.content is the example given.",
  },
  {
    id: "mvn-025",
    topic: "Package Types",
    question: "What packageType do container packages use?",
    correctAnswers: [
      "container",
      "Container packages use packageType container",
      "The correct container type is container",
      "A container package is marked with packageType container",
    ],
    incorrectAnswers: [
      "application",
      "content",
      "embedded",
      "install",
      "aggregate",
      "package",
      "bundle",
      "deployable",
    ],
    explanation:
      "The lesson says container packages set packageType to container, and that the all package is a container.",
  },
  {
    id: "mvn-026",
    topic: "Package Types",
    question: "Which statement about the all package is correct?",
    correctAnswers: [
      "The all package is a container package",
      "all is the project's container package",
      "The package type for all is container",
      "all serves as the container package in the project",
    ],
    incorrectAnswers: [
      "The all package is the mutable content package",
      "The all package is the Java OSGi bundle",
      "The all package is the run-mode configuration package",
      "The all package is the Selenium test package",
      "The all package is the Dispatcher configuration package",
      "The all package is an editable template package only",
      "The all package is an author-only ACL package",
      "The all package is the archetype generator itself",
    ],
    explanation:
      "Section 4 directly states that the all package is a container.",
  },
  {
    id: "mvn-027",
    topic: "Package Types",
    question: "Given a scenario with a container package, what may it hold according to the speech?",
    correctAnswers: [
      "Only OSGi bundles, configurations, and sub packages",
      "A container may hold only OSGi bundles, configurations, and subpackages",
      "Its allowed contents are OSGi bundles, configurations, and subpackages only",
      "Container packages are limited to bundles, configs, and subpackages",
    ],
    incorrectAnswers: [
      "Regular content nodes under /content and /conf",
      "Editable template pages for authors to modify directly",
      "Arbitrary component nodes under /apps/<appId>/components",
      "Repository users created as regular JCR content",
      "Dispatcher YAML files as repository nodes",
      "Client-side source files under /src for webpack compilation",
      "Any runtime-generated nodes under /var and /tmp",
      "Classic install hooks plus regular content nodes",
    ],
    explanation:
      "The speech says a container may hold only OSGi bundles, configurations, and sub packages, and must not contain regular nodes.",
  },
  {
    id: "mvn-028",
    topic: "Package Types",
    question: "What is the usual value mentioned for accessControlHandling when packages are installed?",
    correctAnswers: [
      "merge",
      "It is usually set to merge",
      "The common setting is accessControlHandling=merge",
      "Packages usually use merge for accessControlHandling",
    ],
    incorrectAnswers: [
      "replace",
      "ignore",
      "overwrite",
      "strict",
      "inherit",
      "append",
      "validate",
      "update",
    ],
    explanation:
      "Section 4 says another setting is accessControlHandling, usually set to merge, which keeps existing ACLs when the package is installed.",
  },

  // ── CLOUD MANAGER TARGET (7) ─────────────────────────────────────────────

  {
    id: "mvn-029",
    topic: "Cloud Manager Target",
    question: "By default, what does Cloud Manager harvest from the Maven build?",
    correctAnswers: [
      "Every package produced by the Maven build",
      "It harvests every package the build produces",
      "Cloud Manager picks up all packages generated by Maven by default",
      "The default behavior is to harvest every built package",
    ],
    incorrectAnswers: [
      "Only the core bundle JAR and nothing else",
      "Only packages whose artifactId ends with -cloud",
      "Only ui.apps and never the all package",
      "Only packages listed in Dispatcher configuration",
      "Only content packages and not code packages",
      "Only OSGi configurations from ui.config",
      "Only packages uploaded manually through Package Manager",
      "Only third-party packages from Adobe's repository",
    ],
    explanation:
      "Section 5 says that by default, Cloud Manager harvests every package produced by the Maven build.",
  },
  {
    id: "mvn-030",
    topic: "Cloud Manager Target",
    question: "Why must ui.apps or ui.content not be deployed individually by Cloud Manager when all already embeds them?",
    correctAnswers: [
      "Because they would be installed twice",
      "They must be excluded so they are not installed twice",
      "Deploying them individually would cause double installation",
      "If harvested separately, those packages would be installed twice",
    ],
    incorrectAnswers: [
      "Because Cloud Manager cannot read embedded packages",
      "Because ui.apps and ui.content are not valid Vault packages",
      "Because only mutable packages may be embedded",
      "Because AEM rejects any package that contains a filter.xml",
      "Because embedded packages must be converted to OSGi bundles first",
      "Because individual package deployment forces /libs writes",
      "Because Cloud Manager deploys only publish packages and skips author",
      "Because ui.apps and ui.content can run only from local Maven profiles",
    ],
    explanation:
      "The speech explains that the all package already embeds the other packages, so if ui.apps or ui.content were also deployed individually, they would be installed twice.",
  },
  {
    id: "mvn-031",
    topic: "Cloud Manager Target",
    question: "What property value should package-producing projects except all set in the filevault-package-maven-plugin?",
    correctAnswers: [
      "cloudManagerTarget set to none",
      "They set cloudManagerTarget to none",
      "The property should be cloudManagerTarget=none",
      "Every non-all package-producing project uses cloudManagerTarget none",
    ],
    incorrectAnswers: [
      "cloudManagerTarget set to all",
      "cloudManagerTarget set to publish",
      "cloudManagerTarget set to author",
      "cloudManagerTarget set to container",
      "cloudManagerTarget set to application",
      "cloudManagerTarget set to content",
      "cloudManagerTarget set to embed",
      "cloudManagerTarget set to install",
    ],
    explanation:
      "Section 5 says that every package-producing project except all adds properties with cloudManagerTarget set to none in the FileVault plugin configuration.",
  },
  {
    id: "mvn-032",
    topic: "Cloud Manager Target",
    question: "Which package is the only one Cloud Manager should deploy?",
    correctAnswers: [
      "all",
      "Only the all package",
      "Cloud Manager should deploy just all",
      "The single Cloud Manager deployment artifact is all",
    ],
    incorrectAnswers: [
      "ui.apps",
      "ui.content",
      "ui.config",
      "core",
      "dispatcher.cloud",
      "it.tests",
      "ui.tests",
      "ui.frontend",
    ],
    explanation:
      "The rule in the speech is explicit: all is the only package that Cloud Manager deploys.",
  },
  {
    id: "mvn-033",
    topic: "Cloud Manager Target",
    question: "Given an application deployment in Cloud Manager, how many AEM packages should compose that deployment artifact?",
    correctAnswers: [
      "A single AEM package",
      "The deployment must be composed of one AEM package",
      "It should be one AEM package only",
      "The application deployment is a single AEM package",
    ],
    incorrectAnswers: [
      "Exactly two AEM packages, one for author and one for publish",
      "At least three packages, one per repository root",
      "One package per module with no container package",
      "A separate package for each run mode",
      "One package for code and one JAR-only deployment for content",
      "No package at all, only bundle uploads",
      "A single ZIP for author and a second mandatory ZIP for publish",
      "Only a Dispatcher package plus a content package",
    ],
    explanation:
      "Section 5 says an application deployment must be composed of a single AEM package.",
  },
  {
    id: "mvn-034",
    topic: "Cloud Manager Target",
    question: "What should that single deployment package contain?",
    correctAnswers: [
      "Sub packages for code, configuration, and any baseline content the application needs",
      "It contains subpackages for code, configuration, and needed baseline content",
      "The single deployment package should wrap code, configuration, and baseline content as subpackages",
      "It should contain subpackages for all required code, config, and baseline content",
    ],
    incorrectAnswers: [
      "Only mutable content, because code ships separately",
      "Only the core bundle and no packages",
      "Only author-specific ACLs with no application code",
      "Only Dispatcher rules for publish delivery",
      "Only template pages under /content and nothing else",
      "Only OSGi configs, because content is authored later",
      "Only package filters with no embedded artifacts",
      "Only sample content and never baseline application code",
    ],
    explanation:
      "The speech says the single deployment package contains sub packages for everything the application needs: code, configuration, and any baseline content.",
  },
  {
    id: "mvn-035",
    topic: "Cloud Manager Target",
    question: "A deployment installed ui.apps once through all and then again directly. Which rule from the speech was violated?",
    correctAnswers: [
      "Every package except all should set cloudManagerTarget to none",
      "The non-all packages should have been marked with cloudManagerTarget none",
      "Only all should be deployed, so the other package should have targeted none",
      "The rule violated is that Cloud Manager deploys only all and all other packages set cloudManagerTarget to none",
    ],
    incorrectAnswers: [
      "The core bundle should have used packageType content",
      "ui.apps should have been moved under /content to avoid duplication",
      "The parent pom.xml should not list ui.apps as a module",
      "Cloud Manager should have used install hooks to deduplicate the package",
      "ui.content should have depended on core instead of ui.apps",
      "The deployment should have replaced all with dispatcher.cloud",
      "The fix is to add regular content nodes into the container package",
      "The package should have been installed from CRX Package Manager manually",
    ],
    explanation:
      "The lesson's rule is to deploy only all, while every other package-producing project sets cloudManagerTarget to none to avoid duplicate installation.",
  },

  // ── CONTAINER PACKAGE & EMBEDS (7) ──────────────────────────────────────

  {
    id: "mvn-036",
    topic: "Container Package & Embeds",
    question: "What should the all package include as embeds?",
    correctAnswers: [
      "Only deployable artifacts such as the core bundle JAR and the ui.apps, ui.config, and ui.content packages",
      "It should embed only deployable artifacts: the core JAR plus ui.apps, ui.config, and ui.content",
      "The all container embeds the core bundle and the ui.apps, ui.config, and ui.content packages",
      "Its embeds should be limited to deployable artifacts like the core bundle and the main packages",
    ],
    incorrectAnswers: [
      "Regular page content under /content/mysite as direct nodes",
      "Component source code written directly inside the all package",
      "Editable template instances as regular repository nodes",
      "Dispatcher farm files as JCR content",
      "Runtime-generated logs from /var and /tmp",
      "CRX Package Manager metadata copied from the target instance",
      "User profile nodes from /home as baseline content",
      "Manual hotfixes stored under /libs",
    ],
    explanation:
      "Section 6 says the all package is a container and includes only deployable artifacts as embeds: the core bundle JAR and the ui.apps, ui.config, and ui.content packages.",
  },
  {
    id: "mvn-037",
    topic: "Container Package & Embeds",
    question: "What must the all package not contain?",
    correctAnswers: [
      "Any content or code of its own",
      "It must not contain its own content or code",
      "The all package should have no content or code of its own",
      "No standalone code or content should live directly inside all",
    ],
    incorrectAnswers: [
      "Embedded packages from ui.apps or ui.content",
      "The core bundle JAR",
      "Package metadata such as its FileVault configuration",
      "Filters for the embedded-package target paths",
      "Third-party packages embedded the same way",
      "The application's deployable artifacts as embeds",
      "Author-only embedded packages when needed",
      "Publish-only embedded packages when needed",
    ],
    explanation:
      "The speech explicitly says the all package must not contain any content or code of its own.",
  },
  {
    id: "mvn-038",
    topic: "Container Package & Embeds",
    question: "Which FileVault plugin configuration should be used to include packages in the container?",
    correctAnswers: [
      "embeddeds",
      "Use the embeddeds configuration",
      "Packages are included with the embeddeds configuration",
      "The correct configuration is embeddeds, not the older alternative",
    ],
    incorrectAnswers: [
      "subPackages",
      "includes",
      "dependencies",
      "installHooks",
      "bundleEmbeds",
      "packageFilters",
      "artifactSets",
      "runModes",
    ],
    explanation:
      "Section 6 says packages are included with the embeddeds configuration of the FileVault package Maven plugin, and that the older subPackages configuration is not used.",
  },
  {
    id: "mvn-039",
    topic: "Container Package & Embeds",
    question: "Which older configuration does the speech say is not used for embedding packages?",
    correctAnswers: [
      "subPackages",
      "The older subPackages configuration",
      "It explicitly says not to use subPackages",
      "The outdated embedding configuration mentioned is subPackages",
    ],
    incorrectAnswers: [
      "embeddeds",
      "packageType",
      "accessControlHandling",
      "repositoryStructurePackage",
      "filterRoots",
      "cloudManagerTarget",
      "artifactId",
      "dependencyManagement",
    ],
    explanation:
      "The lesson contrasts embeddeds with the older subPackages configuration and says subPackages is not used.",
  },
  {
    id: "mvn-040",
    topic: "Container Package & Embeds",
    question: "Where are embedded packages placed inside the container package?",
    correctAnswers: [
      "/apps/<app-name>-packages/(content|application|container)/install(.author|.publish)?",
      "They go under /apps/<app-name>-packages with the package-type folder and install, install.author, or install.publish",
      "The target format is /apps/<app-name>-packages/(content|application|container)/install(.author|.publish)?",
      "Embedded packages are placed under /apps, then <app-name>-packages, then the package type, then install or the author/publish variant",
    ],
    incorrectAnswers: [
      "/content/<app-name>/packages/install",
      "/conf/<app-name>/packages/application/runmodes",
      "/libs/<app-name>-packages/install",
      "/oak:index/<app-name>/packages/content",
      "/apps/<app-name>/components/install",
      "/var/packages/<app-name>/author",
      "/system/<app-name>/subpackages",
      "/etc/packages/<app-name>/runtime",
    ],
    explanation:
      "Section 6 gives the exact target-path pattern for embedded packages: /apps/<app-name>-packages/(content|application|container)/install(.author|.publish)?.",
  },
  {
    id: "mvn-041",
    topic: "Container Package & Embeds",
    question: "Why does the second-level folder use the suffix -packages?",
    correctAnswers: [
      "To prevent embedded packages from being deployed into the application's own target folders under /apps/<app-name>",
      "The -packages suffix avoids deploying embedded packages into /apps/<app-name> and causing destructive or cyclic installation",
      "It is a convention that keeps embedded packages out of the application's normal /apps/<app-name> folders",
      "The suffix exists to prevent destructive or cyclic installation into the application's own target folders",
    ],
    incorrectAnswers: [
      "To make the package appear first in alphabetical CRXDE listings",
      "To force Cloud Manager to treat the package as mutable content",
      "To enable install hooks on author only",
      "To make Dispatcher automatically invalidate package caches",
      "To convert content packages into container packages at runtime",
      "To bypass filter.xml ownership rules for /apps",
      "To allow deployment into /libs instead of /apps",
      "To store Repo Init scripts beside editable template content",
    ],
    explanation:
      "The speech says the -packages suffix is a convention that prevents embedded packages from being deployed into the target folders of the application under /apps/<app-name>, which would cause destructive or cyclic installation.",
  },
  {
    id: "mvn-042",
    topic: "Container Package & Embeds",
    question: "Which run-mode-specific embedded package folders are supported?",
    correctAnswers: [
      "install.author and install.publish only",
      "Only install.author and install.publish are supported",
      "The supported run-mode-specific folders are install.author and install.publish",
      "Author-only and publish-only folders are allowed as install.author and install.publish",
    ],
    incorrectAnswers: [
      "install.dev and install.prod only",
      "install.stage and install.qa only",
      "install.author.dev and install.publish.prod",
      "install.cloud and install.local",
      "install.preview and install.live",
      "install.test and install.load",
      "install.integration and install.ui",
      "install.shared and install.global",
    ],
    explanation:
      "Section 6 says only install.author and install.publish are supported; other run modes are not.",
  },

  // ── DEPENDENCIES & REPOSITORY STRUCTURE (8) ─────────────────────────────

  {
    id: "mvn-043",
    topic: "Dependencies & Repository Structure",
    question: "What is the general dependency rule between ui.content and ui.apps?",
    correctAnswers: [
      "ui.content depends on ui.apps",
      "The mutable content package should depend on the supporting immutable code package ui.apps",
      "In the general case, ui.content declares a dependency on ui.apps",
      "The standard rule is that ui.content depends on ui.apps",
    ],
    incorrectAnswers: [
      "ui.apps depends on ui.content",
      "all depends on ui.content and ui.content depends on all",
      "ui.content depends only on ui.config",
      "ui.apps must depend on every content package",
      "core must depend on ui.content for page installation",
      "dispatcher.cloud depends on ui.apps for package order",
      "ui.tests depends on ui.content to resolve filters",
      "No package dependencies should ever be declared",
    ],
    explanation:
      "Section 7 gives the general rule that packages with mutable content, ui.content, depend on the immutable code, ui.apps, that supports them.",
  },
  {
    id: "mvn-044",
    topic: "Dependencies & Repository Structure",
    question: "In the simple case described by the speech, which package has no dependencies?",
    correctAnswers: [
      "ui.apps has no dependencies",
      "In the simple case, ui.apps does not depend on another package",
      "The speech says ui.apps has no dependencies in the simple case",
      "A no-dependency package in the simple example is ui.apps",
    ],
    incorrectAnswers: [
      "ui.content has no dependencies",
      "core depends on ui.content in the simple case",
      "all depends on ui.apps in the simple case",
      "ui.apps depends on all in the simple case",
      "ui.config always depends on ui.content in the simple case",
      "dispatcher.cloud depends on all in the simple case",
      "ui.tests has the only dependency in the simple case",
      "Every package must depend on core in the simple case",
    ],
    explanation:
      "The simple example in Section 7 says all has no dependencies, ui.apps has no dependencies, and ui.content depends on ui.apps.",
  },
  {
    id: "mvn-045",
    topic: "Dependencies & Repository Structure",
    question: "What is the exception involving a code package that contains only OSGi bundles?",
    correctAnswers: [
      "No AEM package should declare a dependency on it",
      "A package containing only OSGi bundles should not be depended on by other AEM packages",
      "If a code package has only OSGi bundles, other AEM packages must not declare dependencies on it",
      "The exception is to avoid declaring AEM package dependencies on a bundles-only code package",
    ],
    incorrectAnswers: [
      "Every content package must depend on it twice",
      "It must be converted into a content package before deployment",
      "It should always be embedded under /content rather than /apps",
      "It must declare a dependency on ui.content to register correctly",
      "It can be installed only with container install hooks",
      "It should replace the all container package entirely",
      "It belongs only in dispatcher.cloud and not in Maven modules",
      "It must be registered manually in /libs/package-manager",
    ],
    explanation:
      "Section 7 says that if a code package contains only OSGi bundles, no AEM package should declare a dependency on it.",
  },
  {
    id: "mvn-046",
    topic: "Dependencies & Repository Structure",
    question: "Why is depending on a package that contains only OSGi bundles a problem?",
    correctAnswers: [
      "Because it is not registered with Package Manager, so the dependency is unsatisfied and installation fails",
      "Because Package Manager does not register that package, leaving an unsatisfied dependency",
      "Because other packages see an unsatisfied dependency and fail to install",
      "Because a bundles-only package is not registered with Package Manager and dependent packages fail to install",
    ],
    incorrectAnswers: [
      "Because it forces Cloud Manager to deploy all packages twice",
      "Because it causes the package to install into /libs automatically",
      "Because it converts the dependency into a runtime Sling Model import",
      "Because it disables embeddeds and reverts to subPackages",
      "Because it moves the bundle into ui.content during installation",
      "Because it forces install.author and install.publish to run together",
      "Because it removes the container package's filter.xml entries",
      "Because it makes ui.apps mutable at runtime",
    ],
    explanation:
      "The lesson explains that such a package is not registered with Package Manager, so any AEM package that depends on it has an unsatisfied dependency and fails to install.",
  },
  {
    id: "mvn-047",
    topic: "Dependencies & Repository Structure",
    question: "In a complex deployment with several sites, what dependency chain does the speech give for site-specific packages?",
    correctAnswers: [
      "site-a.ui.apps depends on common.ui.apps, and site-a.ui.content depends on site-a.ui.apps",
      "The example chain is common.ui.apps -> site-a.ui.apps -> site-a.ui.content",
      "site-a.ui.apps should depend on common.ui.apps, while site-a.ui.content depends on site-a.ui.apps",
      "The speech's multi-site example has site-a.ui.apps depending on common.ui.apps and site-a.ui.content depending on site-a.ui.apps",
    ],
    incorrectAnswers: [
      "common.ui.apps depends on site-a.ui.apps, and ui.content depends on common.ui.content",
      "site-a.ui.content depends directly on common.ui.apps and nothing else",
      "site-a.ui.apps depends on site-a.ui.content so content installs first",
      "all must depend on every site package to determine installation order",
      "site-a.ui.apps and site-a.ui.content should never declare any dependencies",
      "site-a.ui.content depends on dispatcher.cloud for publish activation",
      "common.ui.apps depends on ui.content because mutable content owns shared code",
      "site-a.ui.apps depends only on the core bundle manifest",
    ],
    explanation:
      "Section 7 gives a multi-site example where site-a.ui.apps depends on common.ui.apps, and site-a.ui.content depends on site-a.ui.apps.",
  },
  {
    id: "mvn-048",
    topic: "Dependencies & Repository Structure",
    question: "What additional requirement applies to code packages with packageType application?",
    correctAnswers: [
      "They need a repository structure package",
      "Application code packages require a repository structure package",
      "A code package with packageType application must use a repository structure package",
      "The speech says application packages also need a repository structure package",
    ],
    incorrectAnswers: [
      "They must always be converted to content packages",
      "They require install hooks to validate folder ownership",
      "They must declare /content filters to accompany /apps filters",
      "They cannot be embedded in the all container package",
      "They require a second parent pom.xml under ui.apps",
      "They must disable dependencies on ui.content",
      "They can exist only in AMS projects and not Cloud Service",
      "They must store Repo Init scripts directly in core",
    ],
    explanation:
      "Section 7 says code packages, those with packageType application, also need a repository structure package.",
  },
  {
    id: "mvn-049",
    topic: "Dependencies & Repository Structure",
    question: "Which FileVault plugin element configures the repository structure package?",
    correctAnswers: [
      "repositoryStructurePackage",
      "It is configured with the repositoryStructurePackage element",
      "The correct plugin element is repositoryStructurePackage",
      "You configure it through the repositoryStructurePackage setting",
    ],
    incorrectAnswers: [
      "packageType",
      "cloudManagerTarget",
      "embeddeds",
      "subPackages",
      "accessControlHandling",
      "dependencyManagement",
      "installHooks",
      "filterRoots",
    ],
    explanation:
      "The speech says the repository structure package is configured with the repositoryStructurePackage element in the FileVault package Maven plugin.",
  },
  {
    id: "mvn-050",
    topic: "Dependencies & Repository Structure",
    question: "What does the repository structure package enforce, and which module does the archetype generate for it?",
    correctAnswers: [
      "It enforces structural dependency correctness so one code package does not install over another's folders, and the archetype generates ui.apps.structure",
      "It prevents one code package from installing over another package's folders, and the generated module is ui.apps.structure",
      "Its purpose is structural dependency correctness between code packages, and the archetype creates ui.apps.structure for that",
      "The repository structure package guards folder ownership between code packages, and the archetype-generated module is ui.apps.structure",
    ],
    incorrectAnswers: [
      "It enforces ACL inheritance rules, and the archetype generates ui.content.security",
      "It validates Dispatcher cache rules, and the archetype generates dispatcher.structure",
      "It forces author-only installation order, and the archetype generates ui.author.structure",
      "It registers OSGi bundles with Package Manager, and the archetype generates core.structure",
      "It merges mutable content trees, and the archetype generates ui.content.structure",
      "It compiles Sling Models, and the archetype generates sling.models.structure",
      "It embeds third-party packages automatically, and the archetype generates all.structure",
      "It defines run-mode folders for configs, and the archetype generates ui.config.structure",
    ],
    explanation:
      "Section 7 says the repository structure package enforces correctness of structural dependencies so one code package does not install over another's folders, and that the archetype generates a ui.apps.structure module for this.",
  },
]
