import type { TriviaQuestion } from "./trivia-types"

export const componentsQuestionsPartA: TriviaQuestion[] = [

  // ── INTRODUCTION (7) ─────────────────────────────────────────────────────

  {
    id: "comp-001",
    topic: "Introduction",
    question: "What do templates define before this lesson turns to the components themselves?",
    correctAnswers: [
      "Templates define where components can go",
      "They define the places where components are allowed to go",
      "Templates specify where components may be placed",
      "They determine where components can live on a page",
    ],
    incorrectAnswers: [
      "Templates define the Sling Model Java package",
      "Templates store authored content inside the component folder",
      "Templates replace sling:resourceType on content resources",
      "Templates decide the OSGi run mode for Publish",
      "Templates version Core Components automatically",
      "Templates remove the need for HTL scripts",
      "Templates compile client libraries into bundles",
      "Templates override /libs search paths at runtime",
    ],
    explanation:
      "The speech opens by saying that templates define where components can go, and the lesson then shifts to the internal structure and implementation of the components themselves.",
  },
  {
    id: "comp-002",
    topic: "Introduction",
    question: "What is the main focus of this lesson after templates?",
    correctAnswers: [
      "Looking inside components: their structure, extension, markup, logic, dialogs, and supporting services",
      "Understanding component internals, including HTL, Sling Models, dialogs, and supporting services",
      "Studying how components are structured, extended, rendered, and supported in AEM",
      "Examining component structure plus HTL markup, Sling Model logic, dialogs, and support from services and servlets",
    ],
    incorrectAnswers: [
      "Configuring only Dispatcher cache invalidation rules",
      "Managing users and groups in Adobe Admin Console",
      "Building only workflow models for content approval",
      "Designing only editable templates without components",
      "Creating only GraphQL schemas for headless delivery",
      "Migrating only DAM assets between environments",
      "Authoring only experience fragments without code",
      "Installing only package manager ZIP files",
    ],
    explanation:
      "According to the introduction, the lesson looks inside components themselves: their structure, extension, HTL markup, Sling Model logic, dialogs, and the way OSGi services and servlets support them.",
  },
  {
    id: "comp-003",
    topic: "Introduction",
    question: "Which exam section does this lesson primarily map to?",
    correctAnswers: [
      "Section 2 of the exam: AEM Development",
      "The lesson primarily maps to Section 2, AEM Development",
      "It is mainly aligned to the AEM Development section of the exam",
      "Its primary exam mapping is Section 2, which covers AEM Development",
    ],
    incorrectAnswers: [
      "Section 3: Dispatcher Configuration",
      "Section 4: User Administration",
      "Section 5: Asset Processing Pipelines",
      "Section 6: Adobe Analytics Integration",
      "Section 7: Commerce Catalog Import",
      "Section 8: Network Security Hardening",
      "Section 9: Front-End Build Tooling",
      "Section 10: Workflow Step Authoring",
    ],
    explanation:
      'The introduction explicitly states that the lesson maps to Section 2 of the exam: "AEM Development."',
  },
  {
    id: "comp-004",
    topic: "Introduction",
    question: "Which exam objective is explicitly called out in relation to proxy components?",
    correctAnswers: [
      "2.1, identifying how to implement a proxy of a core component",
      "Exam objective 2.1 about implementing a proxy of a Core Component",
      "Section 2.1, which asks how to implement a proxy of a core component",
      "The 2.1 objective on identifying proxy implementation for a Core Component",
    ],
    incorrectAnswers: [
      "1.1, identifying how to configure Dispatcher flush agents",
      "1.2, identifying how to create IMS organizations",
      "2.3, identifying how to write Oak index definitions",
      "3.1, identifying how to design content fragments",
      "3.2, identifying how to build CIF product importers",
      "4.1, identifying how to tune JVM garbage collection",
      "5.1, identifying how to author translation dictionaries",
      "6.1, identifying how to administer user sync",
    ],
    explanation:
      "The speech specifically says the lesson maps to exam objective 2.1, identifying how to implement a proxy of a core component.",
  },
  {
    id: "comp-005",
    topic: "Introduction",
    question: "Which exam objective is explicitly called out for creating component functionality?",
    correctAnswers: [
      "2.2, given a scenario, identifying how to create component functionality including HTL, models, and services",
      "Exam objective 2.2 about creating component functionality with HTL, models, and services",
      "Section 2.2, which focuses on scenario-based component functionality using HTL, models, and services",
      "The 2.2 objective on identifying component functionality for HTL, models, and services",
    ],
    incorrectAnswers: [
      "1.3, given a scenario, identifying how to configure replication agents",
      "2.4, given a scenario, identifying how to write Dispatcher farms",
      "3.3, given a scenario, identifying how to migrate tags with Groovy",
      "4.2, given a scenario, identifying how to enable SAML login",
      "5.2, given a scenario, identifying how to compress clientlibs",
      "6.2, given a scenario, identifying how to resize DAM renditions",
      "7.2, given a scenario, identifying how to build GraphQL persisted queries",
      "8.2, given a scenario, identifying how to patch Felix consoles",
    ],
    explanation:
      "The introduction says objective 2.2 covers scenario-based identification of how to create component functionality, including HTL, models, and services.",
  },
  {
    id: "comp-006",
    topic: "Introduction",
    question: "Besides Section 2, what other exam section does the lesson touch through OSGi configurations?",
    correctAnswers: [
      "Section 1, Configurations",
      "It also touches Section 1: Configurations",
      "The other section mentioned is Section 1, which covers configurations",
      "Section 1 on Configurations is touched through OSGi configurations",
    ],
    incorrectAnswers: [
      "Section 3, Dispatcher",
      "Section 4, Dispatcher Caching",
      "Section 5, Content Fragment Modeling",
      "Section 6, Admin Console Setup",
      "Section 7, Commerce Integration",
      "Section 8, Workflow Reporting",
      "Section 9, Translation Projects",
      "Section 10, Repository Modernization",
    ],
    explanation:
      "The speech says the lesson also touches Section 1, Configurations, specifically through OSGi configurations.",
  },
  {
    id: "comp-007",
    topic: "Introduction",
    question: "How does the speech describe the exam style you should expect?",
    correctAnswers: [
      "The exam is scenario-based and asks which file, property, annotation, or outcome applies",
      "Expect scenario-based questions about the right file, property, annotation, and what happens if you get it wrong",
      "It is a scenario-based exam focused on choosing the correct file, property, annotation, and resulting behavior",
      "You should expect scenario questions about what to change and what happens if it is wrong",
    ],
    incorrectAnswers: [
      "The exam is entirely essay-based with no implementation scenarios",
      "The exam is only multiple-select about licensing tiers",
      "The exam focuses only on memorizing product release dates",
      "The exam asks only command-line syntax for Cloud Manager",
      "The exam is based only on code compilation logs",
      "The exam tests only visual authoring shortcuts",
      "The exam avoids questions about properties and annotations",
      "The exam is purely about pricing and subscriptions",
    ],
    explanation:
      "The introduction says the exam is scenario-based and that you should expect questions such as which file to change, which property to set, which annotation to use, and what happens if you get it wrong.",
  },

  // ── ANATOMY OF A COMPONENT (7) ────────────────────────────────────────────

  {
    id: "comp-008",
    topic: "Anatomy of a Component",
    question: "What is an AEM component in repository terms?",
    correctAnswers: [
      "A node of type cq:Component stored under /apps",
      "A cq:Component node that lives in the repository under /apps",
      "A repository node of type cq:Component located beneath /apps",
      "It is a cq:Component node stored in /apps",
    ],
    incorrectAnswers: [
      "A cq:Page node stored under /content",
      "A sling:Folder node stored under /libs only",
      "An nt:file node stored in /var",
      "A rep:User node stored under /home",
      "An OSGi configuration PID stored under /conf",
      "A cq:Tag node stored under /content/cq:tags",
      "A dam:Asset node stored under /content/dam",
      "A workflow model node stored under /var/workflow",
    ],
    explanation:
      "The anatomy section defines a component as a node of type cq:Component stored in the repository under /apps.",
  },
  {
    id: "comp-009",
    topic: "Anatomy of a Component",
    question: "Where do a project's components typically live, and in which Maven module are they packaged?",
    correctAnswers: [
      "They live under /apps/<project>/components and are packaged in the ui.apps module",
      "Project components are stored in /apps/<project>/components and packaged through ui.apps",
      "The usual location is /apps/<project>/components, with packaging in ui.apps",
      "A project's components live in /apps/<project>/components, and the Maven module is ui.apps",
    ],
    incorrectAnswers: [
      "They live under /content/<project>/components and are packaged in ui.content",
      "They live under /conf/<project>/components and are packaged in core",
      "They live under /libs/<project>/components and are packaged in ui.frontend",
      "They live under /var/<project>/components and are packaged in all",
      "They live under /apps/<project>/pages and are packaged in dispatcher",
      "They live under /etc/<project>/components and are packaged in parent",
      "They live under /home/<project>/components and are packaged in integration-tests",
      "They live under /oak:index/<project>/components and are packaged in ui.tests",
    ],
    explanation:
      "The speech says a project's components live in /apps/<project>/components, and in the Maven project they are packaged in the ui.apps module.",
  },
  {
    id: "comp-010",
    topic: "Anatomy of a Component",
    question: "What file typically defines the cq:Component node and properties such as jcr:title, componentGroup, and sling:resourceSuperType?",
    correctAnswers: [
      "The .content.xml file in the component folder",
      "A .content.xml that defines the cq:Component node and its properties",
      "The component's .content.xml definition file",
      "The .content.xml stored with the component",
    ],
    incorrectAnswers: [
      "The pom.xml in the repository root",
      "The filter.xml in META-INF/vault only",
      "The package.json in ui.frontend",
      "The dispatcher.any file",
      "The jcr_root/.vltignore file",
      "The system console configuration page",
      "The archetype.properties file",
      "The Cloud Manager pipeline YAML",
    ],
    explanation:
      "The anatomy section lists .content.xml as the file that defines the cq:Component node and properties such as jcr:title, componentGroup, and sling:resourceSuperType.",
  },
  {
    id: "comp-011",
    topic: "Anatomy of a Component",
    question: "How is the main HTL script typically named in a component folder?",
    correctAnswers: [
      "It is named after the component, for example title.html",
      "The HTL script usually matches the component name, such as title.html",
      "Typically the component's HTL file is named after the component itself",
      "A common pattern is a component-named HTL file like title.html",
    ],
    incorrectAnswers: [
      "It must always be named component.jsp",
      "It is always named render.xml",
      "It must always be named dialog.html",
      "It is always named sling-model.java",
      "It must always be named content.html regardless of component",
      "It is always named cq_component.htl",
      "It must always be named resourceType.html",
      "It is always named index.jsp inside /content",
    ],
    explanation:
      "The speech says a component folder typically contains an HTL script named after the component, for example title.html.",
  },
  {
    id: "comp-012",
    topic: "Anatomy of a Component",
    question: "What does the jcr:title property represent on a component?",
    correctAnswers: [
      "The name shown to authors",
      "It is the author-facing name of the component",
      "jcr:title is the component name displayed to authors",
      "The property controls the name authors see",
    ],
    incorrectAnswers: [
      "The JCR primary type of the component",
      "The version number of the Core Component parent",
      "The only valid sling:resourceType for content nodes",
      "The client library category for Publish",
      "The OSGi PID for the component dialog",
      "The HTML tag name forced by data-sly-element",
      "The package name of the Sling Model implementation",
      "The default wcmmode for preview",
    ],
    explanation:
      "The anatomy section says jcr:title is the name shown to authors.",
  },
  {
    id: "comp-013",
    topic: "Anatomy of a Component",
    question: "What happens if a componentGroup value starts with a dot?",
    correctAnswers: [
      "The component group is hidden",
      "A dot-prefixed componentGroup hides the component from the browser grouping",
      "Starting the group with a dot makes that grouping hidden",
      "It causes the component group to be hidden from authors",
    ],
    incorrectAnswers: [
      "The component becomes a required policy component",
      "The component is promoted to the top of the browser",
      "The component can render only on Publish",
      "The component is treated as version 1 automatically",
      "The component skips dialog rendering entirely",
      "The component is moved from /apps to /libs",
      "The component becomes a Sling Model exporter",
      "The component is replicated immediately after build",
    ],
    explanation:
      "The speech explicitly says componentGroup controls grouping in the components browser, and a group starting with a dot is hidden.",
  },
  {
    id: "comp-014",
    topic: "Anatomy of a Component",
    question: "Given a scenario where authors need to place other components inside a component, which property marks it as a container?",
    correctAnswers: [
      "cq:isContainer",
      "Set cq:isContainer",
      "The property is cq:isContainer",
      "Use the cq:isContainer flag on the component",
    ],
    incorrectAnswers: [
      "jcr:isPage",
      "sling:isEditable",
      "cq:inheritsChildren",
      "granite:isContainer",
      "resource:isContainer",
      "cq:componentRoot",
      "jcr:containsComponents",
      "sling:allowChildren",
    ],
    explanation:
      "The anatomy section identifies cq:isContainer as the property that marks a component as a container for other components.",
  },

  // ── PROXY COMPONENT PATTERN (7) ───────────────────────────────────────────

  {
    id: "comp-015",
    topic: "Proxy Component Pattern",
    question: "According to best practice, what should a content resource's sling:resourceType point to?",
    correctAnswers: [
      "A site-specific component, not a component shared by multiple sites",
      "A project or site-specific component rather than a shared multi-site component",
      "Its own site's component, not a common component used directly by several sites",
      "A site-specific proxy component instead of a shared component",
    ],
    incorrectAnswers: [
      "Always directly to /libs/foundation/components/parsys",
      "Always to a versioned Core Component path in /apps/core/wcm/components",
      "Always to a content policy node under /conf",
      "Always to the component's clientlibs folder",
      "Always to a Sling Model class name",
      "Always to the editable template path",
      "Always to a servlet resource type in /bin",
      "Always to the current page template type",
    ],
    explanation:
      "The proxy pattern section says best practice is for sling:resourceType on content to point to a site-specific component, not one shared directly by multiple sites.",
  },
  {
    id: "comp-016",
    topic: "Proxy Component Pattern",
    question: "Why is it better for content to point to a site-specific component instead of a shared one?",
    correctAnswers: [
      "It lets one site customize behavior without affecting other sites",
      "It gives flexibility so site-specific changes do not impact other sites",
      "It isolates custom behavior per site instead of changing every site at once",
      "It allows one site to diverge safely while keeping other sites unchanged",
    ],
    incorrectAnswers: [
      "It forces all sites to share the exact same markup forever",
      "It automatically removes the need for sling:resourceSuperType",
      "It stores authored content inside the component folder",
      "It makes /libs writable at runtime",
      "It guarantees no HTL script is needed",
      "It converts dialogs into OSGi configurations",
      "It changes content policies into Java annotations",
      "It makes every component a container automatically",
    ],
    explanation:
      "The speech explains that site-specific components give flexibility: if one site needs different behavior, the customization happens on its own component without affecting other sites.",
  },
  {
    id: "comp-017",
    topic: "Proxy Component Pattern",
    question: "How does a project component avoid duplicating shared component code?",
    correctAnswers: [
      "It points to the shared parent with sling:resourceSuperType",
      "By setting sling:resourceSuperType to the shared parent component",
      "It inherits from the shared parent through sling:resourceSuperType",
      "It refers to the parent component with sling:resourceSuperType instead of copying code",
    ],
    incorrectAnswers: [
      "It copies the entire parent component into /content",
      "It sets sling:resourceType on the parent to the child",
      "It replaces HTL inheritance with Dispatcher rules",
      "It renames the componentGroup on every deployment",
      "It moves the shared component into /conf",
      "It packages the parent as a client library category",
      "It uses only OSGi service ranking for inheritance",
      "It switches the content node type to cq:Page",
    ],
    explanation:
      "The speech says the project component refers to the shared parent with sling:resourceSuperType so code does not have to be duplicated.",
  },
  {
    id: "comp-018",
    topic: "Proxy Component Pattern",
    question: "What is a proxy component?",
    correctAnswers: [
      "A project component that mostly refers to a parent through sling:resourceSuperType",
      "A component whose main role is to inherit from a parent component",
      "A site-specific component that primarily delegates to a parent component",
      "A component that acts as a thin inheriting layer over another component",
    ],
    incorrectAnswers: [
      "A servlet that proxies HTTP calls to Publish",
      "A client library folder that proxies CSS categories",
      "A workflow launcher that proxies DAM events",
      "A content policy node that proxies editable templates",
      "An OSGi factory config that proxies service users",
      "A package filter that proxies JCR installation paths",
      "A dispatcher farm that proxies CDN traffic",
      "A page component that stores content inline",
    ],
    explanation:
      "The proxy component pattern section says a project component that mostly just refers to a parent through sling:resourceSuperType is called a proxy component.",
  },
  {
    id: "comp-019",
    topic: "Proxy Component Pattern",
    question: "Can a proxy component be completely empty?",
    correctAnswers: [
      "Yes. It can be only a cq:Component node with a resourceSuperType when it fully inherits everything",
      "Yes. A proxy may contain just a cq:Component definition and sling:resourceSuperType",
      "Yes. If it fully inherits functionality, the proxy can be an otherwise empty cq:Component node",
      "Yes. A fully inherited proxy can be nothing more than a cq:Component with the parent reference",
    ],
    incorrectAnswers: [
      "No. A proxy must always copy every HTL file from the parent",
      "No. A proxy is valid only if it contains a custom Sling Model class",
      "No. A proxy must always define its own clientlibs folder",
      "No. A proxy must always include a servlet and OSGi configuration",
      "No. A proxy is required to have authored content below it",
      "No. A proxy must always override the dialog and design dialog",
      "No. A proxy must always be stored under /content",
      "No. A proxy requires a custom Dispatcher module",
    ],
    explanation:
      "The speech explicitly says a proxy can be entirely empty, only a cq:Component node with a resourceSuperType, if it fully inherits the functionality.",
  },
  {
    id: "comp-020",
    topic: "Proxy Component Pattern",
    question: "In the example from the speech, where does the Core Component parent for Title live?",
    correctAnswers: [
      "core/wcm/components/title/v3/title",
      "At the Core Components path core/wcm/components/title/v3/title",
      "The parent example is core/wcm/components/title/v3/title",
      "The example parent resource type is core/wcm/components/title/v3/title",
    ],
    incorrectAnswers: [
      "/libs/wcm/foundation/components/title",
      "wknd/components/title/v3/title",
      "/content/wknd/components/title",
      "core/wcm/components/title/v2/proxy",
      "/apps/wknd/components/title/v3/title",
      "core/wcm/components/page/v3/page",
      "/conf/wknd/settings/wcm/title",
      "wknd/core/components/title/v3/title",
    ],
    explanation:
      "The proxy example in the speech uses the Core Component parent path core/wcm/components/title/v3/title.",
  },
  {
    id: "comp-021",
    topic: "Proxy Component Pattern",
    question: "Why should you never modify Core Components code directly?",
    correctAnswers: [
      "Because it makes them unsupported and breaks upgrades",
      "Direct changes make Core Components unsupported and interfere with upgrades",
      "Adobe warns against modifying them directly because upgrades break and support is lost",
      "Changing Core Components directly creates unsupported code and upgrade problems",
    ],
    incorrectAnswers: [
      "Because Core Components render only on Author",
      "Because Core Components cannot use HTL",
      "Because Core Components are stored under /content",
      "Because Core Components must always be copied in full",
      "Because Core Components require JSP instead of HTL",
      "Because Core Components cannot have dialogs",
      "Because Core Components block sling:resourceType on content",
      "Because Core Components disable client libraries automatically",
    ],
    explanation:
      "The speech says never modify Core Components code directly because doing so makes them unsupported and breaks upgrades.",
  },

  // ── RESOURCE TYPE RESOLUTION & VERSIONING (7) ─────────────────────────────

  {
    id: "comp-022",
    topic: "Resource Type Resolution & Versioning",
    question: "How does Sling resolve the script for a request?",
    correctAnswers: [
      "It checks the resource's sling:resourceType first, then walks up sling:resourceSuperType until it finds a script",
      "Sling starts at sling:resourceType and climbs the sling:resourceSuperType chain if needed",
      "Resolution begins at the resource type and continues through super types until a matching script is found",
      "It looks at sling:resourceType first and falls back through inherited resource super types",
    ],
    incorrectAnswers: [
      "It starts at /content and ignores resource types entirely",
      "It checks only the page template and never the component type",
      "It resolves scripts only from OSGi service rankings",
      "It searches /libs first and stops even when nothing matches",
      "It uses only the Sling Model package name",
      "It resolves scripts from client library categories",
      "It always reads the dialog XML before the HTL script",
      "It picks the newest version number regardless of resource type",
    ],
    explanation:
      "The speech says Sling resolves a request by looking at the resource's sling:resourceType, and if the script is not found there, it walks up the sling:resourceSuperType chain until it finds one.",
  },
  {
    id: "comp-023",
    topic: "Resource Type Resolution & Versioning",
    question: "Through resourceSuperType inheritance, what can a proxy inherit from its parent according to the speech?",
    correctAnswers: [
      "HTL files, dialogs, and clientlibs",
      "It can inherit HTL scripts, dialogs, and client libraries",
      "A proxy inherits items such as HTL files, dialogs, and clientlibs",
      "The inheritance chain covers HTL, dialogs, and clientlibs",
    ],
    incorrectAnswers: [
      "Only Dispatcher filters and cache rules",
      "Only JMX beans and health checks",
      "Only Adobe IMS identities",
      "Only Maven dependencies from the parent POM",
      "Only oak:index definitions",
      "Only content fragment models",
      "Only workflow launchers and inbox items",
      "Only replication queues",
    ],
    explanation:
      "The resource type resolution section explicitly says this inheritance is how a proxy inherits HTL files, dialogs, and clientlibs from its parent.",
  },
  {
    id: "comp-024",
    topic: "Resource Type Resolution & Versioning",
    question: "What is the Sling search path order described in the speech?",
    correctAnswers: [
      "Sling searches /apps first and then /libs",
      "The search order is /apps before /libs",
      "It looks in /apps first, then falls back to /libs",
      "Custom code is checked in /apps before /libs is searched",
    ],
    incorrectAnswers: [
      "Sling searches /libs first and then /apps",
      "Sling searches /content first and then /apps",
      "Sling searches /conf first and then /content",
      "Sling searches only /apps and never /libs",
      "Sling searches only /libs in AEM as a Cloud Service",
      "Sling searches clientlibs before repository paths",
      "Sling searches package metadata before JCR paths",
      "Sling searches OSGi configs before repository nodes",
    ],
    explanation:
      "The speech says search paths matter and that Sling searches /apps first and then /libs.",
  },
  {
    id: "comp-025",
    topic: "Resource Type Resolution & Versioning",
    question: "Why must /libs never be modified?",
    correctAnswers: [
      "Because it is overlaid on every update in AEM as a Cloud Service and is immutable at runtime",
      "Because /libs is replaced on updates and cannot be modified at runtime in AEMaaCS",
      "Because AEM as a Cloud Service overlays /libs on update and treats it as immutable",
      "Because changes in /libs are not safe: updates overlay it and it is runtime-immutable",
    ],
    incorrectAnswers: [
      "Because /libs stores authored page content permanently",
      "Because /libs is writable only from client-side JavaScript",
      "Because /libs exists only on Publish and not on Author",
      "Because /libs is the required location for custom project code",
      "Because /libs is reserved only for editable templates",
      "Because /libs automatically versions custom components for you",
      "Because /libs cannot contain HTL scripts",
      "Because /libs is a transient cache folder under /var",
    ],
    explanation:
      "The speech says /libs must never be modified because it is overlaid on every update in AEM as a Cloud Service and is immutable at runtime.",
  },
  {
    id: "comp-026",
    topic: "Resource Type Resolution & Versioning",
    question: "What does the version number in a component path such as core/wcm/components/image/v3/image represent?",
    correctAnswers: [
      "A major version under semantic versioning for backward-incompatible changes",
      "The major semantic version, increased only for changes that are not backward compatible",
      "A semantic-version major number that signals incompatible changes",
      "The resource type's major version for non-backward-compatible changes",
    ],
    incorrectAnswers: [
      "The number of child resources authored under the component",
      "The AEM service pack installed on the environment",
      "The patch number for CSS-only changes",
      "The number of dialogs the component contains",
      "The default wcmmode level",
      "The number of client library categories attached",
      "The count of Sling Model exporters",
      "The Java class file version compiled by Maven",
    ],
    explanation:
      "The speech says component versioning adds a number to the resource type path and that the version represents a major version under semantic versioning, increasing only for non-backward-compatible changes.",
  },
  {
    id: "comp-027",
    topic: "Resource Type Resolution & Versioning",
    question: "Which kind of changes are named as backward-incompatible examples for component versioning?",
    correctAnswers: [
      "Changes to Sling Models, HTL scripts, HTML markup and CSS selectors, JSON representation, and dialogs",
      "Incompatible changes include Sling Models, HTL, HTML and CSS selectors, JSON output, and dialogs",
      "The speech lists model, HTL, markup and selector, JSON, and dialog changes as incompatible",
      "Examples include breaking changes in Sling Models, HTL scripts, HTML or CSS selectors, JSON, and dialogs",
    ],
    incorrectAnswers: [
      "Only changes to componentGroup labels",
      "Only moving content between folders under /content",
      "Only changing Author user permissions",
      "Only updating Cloud Manager environment variables",
      "Only renaming Maven modules",
      "Only adding package filters to filter.xml",
      "Only changing dispatcher cache TTL values",
      "Only updating image renditions in DAM",
    ],
    explanation:
      "The speech explicitly lists incompatible changes as including Sling Models, HTL scripts, HTML markup and CSS selectors, JSON representation, and dialogs.",
  },
  {
    id: "comp-028",
    topic: "Resource Type Resolution & Versioning",
    question: "Given a scenario where content points directly to a versioned component path, what rule from the speech is being violated?",
    correctAnswers: [
      "Content must never point to a versioned component",
      "A sling:resourceType in content must not include a version number",
      "The rule is that content should point to the proxy, not the versioned parent",
      "Version numbers do not belong in the content resource's sling:resourceType",
    ],
    incorrectAnswers: [
      "Content must always point directly to /libs for upgrades",
      "Content must always include the major version to be valid",
      "Versioned parents are required on all content resources",
      "The proxy must never use sling:resourceSuperType",
      "Content should always point to the design dialog resource type",
      "Versioning is allowed only when using data-sly-resource",
      "Version numbers belong only in componentGroup values",
      "The rule is to point content to the clientlibs folder",
    ],
    explanation:
      "The speech states the rule clearly: content must never point to a versioned component. Instead, content points to the proxy, and the proxy points to the versioned parent.",
  },

  // ── HTL FUNDAMENTALS (8) ──────────────────────────────────────────────────

  {
    id: "comp-029",
    topic: "HTL Fundamentals",
    question: "What is HTL in AEM?",
    correctAnswers: [
      "The server-side template language for AEM that replaces JSP",
      "HTL is AEM's server-side templating language and the replacement for JSP",
      "It is the HTML Template Language used on the server side instead of JSP",
      "AEM uses HTL as its server-side template language in place of JSP",
    ],
    incorrectAnswers: [
      "A client-side JavaScript framework for editable templates",
      "An OSGi service registry used for dependency injection",
      "A Dispatcher rule format for cache invalidation",
      "A DAM metadata schema language",
      "A Maven plugin for content package assembly",
      "A package manager replacement for pnpm",
      "A servlet-only API for binary streaming",
      "A JSON exporter annotation library",
    ],
    explanation:
      "The HTL fundamentals section says HTL, the HTML Template Language, is the server-side template language for AEM and that it replaces JSP.",
  },
  {
    id: "comp-030",
    topic: "HTL Fundamentals",
    question: "How does the speech describe the design goal of HTL regarding security?",
    correctAnswers: [
      "It was designed to be secure and simple, with automatic context-aware XSS protection",
      "HTL is designed to be secure and simple and automatically applies context-aware XSS protection",
      "The language aims for simplicity and security, including automatic context-aware XSS escaping",
      "HTL's design includes simplicity plus automatic context-aware XSS protection",
    ],
    incorrectAnswers: [
      "It requires manual XSS escaping in every expression",
      "It disables escaping by default so authors can see raw HTML",
      "It is designed mainly for client-side DOM manipulation",
      "It trusts every script and style context automatically",
      "It exists primarily to configure OSGi services",
      "It removes the need for any server-side rendering",
      "It secures output only when using JSP includes",
      "It protects only URI contexts and nothing else",
    ],
    explanation:
      "The speech says HTL was designed to be secure and simple and that it automatically applies context-aware XSS protection.",
  },
  {
    id: "comp-031",
    topic: "HTL Fundamentals",
    question: "What is the expression syntax used in HTL?",
    correctAnswers: [
      "A dollar sign and braces, like ${properties.jcr:title}",
      "Expressions use ${...} syntax, for example ${properties.jcr:title}",
      "HTL expressions are written with a dollar sign plus braces",
      "The language uses forms such as ${properties.jcr:title} for expressions",
    ],
    incorrectAnswers: [
      "Double curly syntax like {{properties.jcr:title}}",
      "JSP scriptlets like <% properties.jcr:title %>",
      "Mustache sections like #properties/jcr:title",
      "XML attributes like value=\"properties.jcr:title\" only",
      "Square bracket syntax like [properties.jcr:title]",
      "Sling EL syntax like #{properties.jcr:title}",
      "A colon syntax like properties:jcr:title",
      "Groovy interpolation only, like ${-> properties.jcr:title}",
    ],
    explanation:
      "The speech states that HTL expressions use a dollar sign and braces, like ${properties.jcr:title}.",
  },
  {
    id: "comp-032",
    topic: "HTL Fundamentals",
    question: "How are options added to an HTL expression?",
    correctAnswers: [
      "They follow an at sign, as in ${text @ context='html'}",
      "Options come after @ inside the expression, for example context='html'",
      "HTL options are written with an at sign after the expression target",
      "You add options by using @ syntax, such as ${text @ context='html'}",
    ],
    incorrectAnswers: [
      "They go in a second pair of braces after the expression",
      "They are defined only in the component's .content.xml",
      "They must be passed through data-sly-set and nowhere else",
      "They are appended as HTML comments after the element",
      "They require a Java annotation on the Sling Model",
      "They are written as URI query parameters after the value",
      "They are configured only in the design dialog",
      "They are specified only in client library categories",
    ],
    explanation:
      "The speech says HTL options follow an at sign, and the example given is ${text @ context='html'}.",
  },
  {
    id: "comp-033",
    topic: "HTL Fundamentals",
    question: "What does the or operator do in an expression such as ${properties.pageTitle || properties.jcr:title || resource.name}?",
    correctAnswers: [
      "It can provide defaults by falling back through values",
      "It is used to supply fallback values in order",
      "The operator lets HTL choose the first available default-style value",
      "It provides a fallback chain such as pageTitle, then jcr:title, then resource.name",
    ],
    incorrectAnswers: [
      "It concatenates all values into one string automatically",
      "It converts all values to numbers before comparison",
      "It forces HTML output context even inside scripts",
      "It loads a Sling Model from the Use-API",
      "It changes the current resource type at render time",
      "It repeats the host element for each non-empty value",
      "It disables XSS protection for fallback values",
      "It sorts the values alphabetically before output",
    ],
    explanation:
      "The HTL fundamentals section says the or operator can provide defaults, and gives a fallback example using pageTitle, jcr:title, and resource.name.",
  },
  {
    id: "comp-034",
    topic: "HTL Fundamentals",
    question: "How do equality comparisons behave in HTL?",
    correctAnswers: [
      "They are strict, like triple equals in JavaScript, with no type conversion",
      "HTL equality is strict and does not perform type coercion",
      "Comparison operators use JavaScript-style strict equality semantics without conversion",
      "The speech says equality works like JavaScript triple equals, not loose equality",
    ],
    incorrectAnswers: [
      "They always coerce strings and numbers automatically",
      "They compare only string length, not values",
      "They are case-insensitive by default",
      "They are available only inside data-sly-test variables",
      "They work only on authored content under /content",
      "They can be used only with Sling Models, not plain properties",
      "They require an explicit @ context='number' to compare",
      "They always treat null as an empty string",
    ],
    explanation:
      "The speech says comparison operators are strict and that the equality operators work like triple equals in JavaScript, with no type conversion.",
  },
  {
    id: "comp-035",
    topic: "HTL Fundamentals",
    question: "Which global objects are named as available in HTL?",
    correctAnswers: [
      "properties, pageProperties, inheritedPageProperties, currentPage, resource, request, and wcmmode",
      "Available global objects include properties, pageProperties, inheritedPageProperties, currentPage, resource, request, and wcmmode",
      "The speech lists properties, pageProperties, inheritedPageProperties, currentPage, resource, request, and wcmmode as global objects",
      "Those named globals are properties, pageProperties, inheritedPageProperties, currentPage, resource, request, and wcmmode",
    ],
    incorrectAnswers: [
      "dispatcher, cacheConfig, renderFarm, and flushAgent",
      "bundleContext, serviceRegistry, pid, and runModes only",
      "workflowSession, inboxItem, payload, and launcher",
      "asset, rendition, metadataSchema, and smartCrop",
      "cloudManager, pipeline, environment, and execution",
      "graphql, persistedQuery, endpoint, and schema",
      "adminUser, token, secret, and apiKey",
      "oakIndex, luceneConfig, checkpoint, and reindex",
    ],
    explanation:
      "The HTL fundamentals section explicitly names properties, pageProperties, inheritedPageProperties, currentPage, resource, request, and wcmmode as global objects available in HTL.",
  },
  {
    id: "comp-036",
    topic: "HTL Fundamentals",
    question: "What must you do for script and style contexts in HTL?",
    correctAnswers: [
      "Set a context explicitly, otherwise nothing is output",
      "You must declare the display context explicitly for script and style output",
      "Script and style contexts require an explicit context or HTL outputs nothing",
      "For script or style, HTL needs an explicit context setting to render output",
    ],
    incorrectAnswers: [
      "Use context='unsafe' because it is required there",
      "Switch to JSP because HTL cannot render script or style values",
      "Store the value in componentGroup first",
      "Wrap the expression in a normal HTML comment",
      "Move the script into /content to enable output",
      "Use only data-sly-repeat for script and style rendering",
      "Declare the context in .content.xml instead of HTL",
      "Set wcmmode='disabled' because that alone enables output",
    ],
    explanation:
      "The speech says that for script and style contexts you must set a context explicitly; otherwise nothing is output.",
  },

  // ── HTL BLOCK STATEMENTS (7) ──────────────────────────────────────────────

  {
    id: "comp-037",
    topic: "HTL Block Statements",
    question: "What are HTL block statements?",
    correctAnswers: [
      "data-sly attributes on HTML elements",
      "They are data-sly attributes applied to HTML elements",
      "HTL block statements are expressed as data-sly attributes",
      "They are the data-sly attributes you place on HTML elements",
    ],
    incorrectAnswers: [
      "JCR node types stored under /content",
      "OSGi annotations on Java classes",
      "Dialog fields inside _cq_dialog only",
      "Dispatcher configuration directives",
      "Client library categories in cq:ClientLibraryFolder",
      "Maven profiles used during package build",
      "Sling servlets registered under /bin",
      "Content policy properties in /conf",
    ],
    explanation:
      "The block statements section begins by defining block statements as data-sly attributes on HTML elements.",
  },
  {
    id: "comp-038",
    topic: "HTL Block Statements",
    question: "What is data-sly-use for?",
    correctAnswers: [
      "Initializing a helper object such as a Sling Model",
      "It loads a helper object, for example a Sling Model",
      "data-sly-use is used to initialize helper logic like a Sling Model",
      "Its purpose is to make a helper object available to the template",
    ],
    incorrectAnswers: [
      "Changing the current element name at runtime",
      "Repeating the host element for each list item",
      "Escaping all output as unsafe HTML",
      "Defining the component's JCR primary type",
      "Publishing content to the live environment",
      "Setting the componentGroup in .content.xml",
      "Registering a servlet path in OSGi",
      "Creating a child resource automatically under /content",
    ],
    explanation:
      "The speech says data-sly-use initializes a helper object such as a Sling Model.",
  },
  {
    id: "comp-039",
    topic: "HTL Block Statements",
    question: "What is the difference between data-sly-list and data-sly-repeat?",
    correctAnswers: [
      "data-sly-list keeps the host element and iterates over its content, while data-sly-repeat repeats the host element itself",
      "List iterates the inside content of the host element; repeat duplicates the host element",
      "With list the host element stays once and its content loops, but with repeat the whole host element is repeated",
      "The speech says list preserves the host element, whereas repeat reproduces that host element per item",
    ],
    incorrectAnswers: [
      "List is for Java classes and repeat is for JavaScript Use-API only",
      "List works only on Publish and repeat only on Author",
      "List changes the element name and repeat changes attributes",
      "List disables XSS protection and repeat enables it",
      "List renders child resources and repeat loads templates from another file",
      "List is deprecated and repeat is required in all new code",
      "List is only for numbers and repeat is only for strings",
      "List executes after attributes, while repeat executes before template priority",
    ],
    explanation:
      "The block statements section explicitly contrasts them: data-sly-list keeps the host element and iterates over its content, while data-sly-repeat repeats the host element itself.",
  },
  {
    id: "comp-040",
    topic: "HTL Block Statements",
    question: "What identifiers does data-sly-list expose by default?",
    correctAnswers: [
      "item and itemList",
      "By default it exposes item plus itemList",
      "The default identifiers are item and itemList",
      "You get item and itemList unless you rename them",
    ],
    incorrectAnswers: [
      "resource and currentPage",
      "entry and entryStatus",
      "model and modelList",
      "loop and loopInfo",
      "node and nodeMeta",
      "value and valueMap",
      "child and childCount",
      "page and pageStatus only",
    ],
    explanation:
      "The speech says data-sly-list exposes an item and itemList by default.",
  },
  {
    id: "comp-041",
    topic: "HTL Block Statements",
    question: "What information does itemList provide in a data-sly-list loop?",
    correctAnswers: [
      "index, count, first, middle, last, odd, and even",
      "It provides loop metadata such as index, count, first, middle, last, odd, and even",
      "The available itemList fields are index, count, first, middle, last, odd, and even",
      "itemList exposes position and parity values including index, count, first, middle, last, odd, and even",
    ],
    incorrectAnswers: [
      "Only author name and last replication date",
      "Only sling:resourceType and sling:resourceSuperType",
      "Only template name and policy path",
      "Only wcmmode and XSS context",
      "Only request method and status code",
      "Only page path and page depth",
      "Only clientlib category and embed list",
      "Only JSON exporter name and selector",
    ],
    explanation:
      "The block statements section lists the itemList properties as index, count, first, middle, last, odd, and even.",
  },
  {
    id: "comp-042",
    topic: "HTL Block Statements",
    question: "What useful pattern does data-sly-test support besides conditional rendering?",
    correctAnswers: [
      "It can store its result in a variable that can be reused later and is not scoped to the element",
      "data-sly-test can assign its result to a reusable variable",
      "You can capture the test result in a variable and use it later outside that element",
      "The test result may be stored for reuse, and the variable is not limited to the element scope",
    ],
    incorrectAnswers: [
      "It can rewrite sling:resourceType on the current content node",
      "It can create the _cq_dialog folder automatically",
      "It can change JSP imports for the component",
      "It can register an OSGi service on first render",
      "It can publish the page when the condition is true",
      "It can change the component's version number at runtime",
      "It can promote the componentGroup in the browser",
      "It can persist loop metadata back into JCR",
    ],
    explanation:
      'The speech gives the example data-sly-test.hasTitle="${properties.jcr:title}" and explains that the result can be stored in a variable, reused later, and is not scoped to the element.',
  },
  {
    id: "comp-043",
    topic: "HTL Block Statements",
    question: "Given a scenario where data-sly-test and data-sly-list are on the same element, when is the test evaluated?",
    correctAnswers: [
      "It is evaluated once before the loop starts",
      "Because list runs after test, the test executes once before iteration begins",
      "The test is evaluated a single time before the list loop starts",
      "On the same element, test runs first and only once before list processing",
    ],
    incorrectAnswers: [
      "It is evaluated after every attribute on every iteration only",
      "It is evaluated only after the final loop item renders",
      "It is skipped because list overrides test completely",
      "It is evaluated once per child resource type in /apps",
      "It is evaluated only on Publish, not Author",
      "It is evaluated twice because test and list have equal priority",
      "It is evaluated only if data-sly-repeat is also present",
      "It is evaluated by the Sling Model, not by HTL",
    ],
    explanation:
      "The speech explains that list runs after test in the priority order, so a data-sly-test on the same element as data-sly-list is evaluated once before the loop starts.",
  },

  // ── HTL TEMPLATES & USE-API (7) ───────────────────────────────────────────

  {
    id: "comp-044",
    topic: "HTL Templates & Use-API",
    question: "What do data-sly-template and data-sly-call do?",
    correctAnswers: [
      "data-sly-template defines a reusable template with parameters, and data-sly-call invokes it",
      "Template defines the reusable block; call executes it",
      "You define a parameterized reusable template with data-sly-template and invoke it with data-sly-call",
      "data-sly-template creates the reusable HTL template, while data-sly-call runs that template",
    ],
    incorrectAnswers: [
      "template creates a child resource and call publishes it",
      "template loads a Sling Model and call saves it to JCR",
      "template changes the componentGroup and call hides it",
      "template sets XSS context and call disables escaping",
      "template imports clientlibs and call compiles them",
      "template defines the dialog and call opens it for authors",
      "template sets sling:resourceType and call versions it",
      "template starts a workflow and call completes the step",
    ],
    explanation:
      "The speech says data-sly-template defines a reusable template with parameters in a file, and data-sly-call invokes it.",
  },
  {
    id: "comp-045",
    topic: "HTL Templates & Use-API",
    question: "How do you use templates from another file in HTL?",
    correctAnswers: [
      "Load the file with data-sly-use and then call the template with data-sly-call",
      "First use data-sly-use.templates=\"template.html\", then invoke templates.myTemplate with data-sly-call",
      "Templates from another file are loaded via data-sly-use and then executed with data-sly-call",
      "You import the template file through data-sly-use and call the named template afterward",
    ],
    incorrectAnswers: [
      "Move the other file into /content and reference it with sling:resourceType",
      "Set componentGroup to the file name and HTL imports it automatically",
      "Use only data-sly-include because templates cannot cross files",
      "Add the file path to .content.xml under jcr:title",
      "Register the template file as an OSGi service",
      "Put the template in a clientlibs category and call it from CSS",
      "Use data-sly-repeat on the file path directly",
      "Add the file under /libs and restart Author",
    ],
    explanation:
      "The speech says that to use templates from another file, you first load the file with data-sly-use.templates=\"template.html\" and then call it with data-sly-call.",
  },
  {
    id: "comp-046",
    topic: "HTL Templates & Use-API",
    question: "What is the difference between data-sly-include and data-sly-resource?",
    correctAnswers: [
      "data-sly-include includes the output of another script as markup, while data-sly-resource includes a resource rendered through its own component",
      "Include brings in script output as markup; resource renders another resource with its component",
      "data-sly-include does not change the processing context, whereas data-sly-resource renders a resource via its own component",
      "Include is script output inclusion, but resource is component-based resource rendering",
    ],
    incorrectAnswers: [
      "include is for Sling Models and resource is for OSGi configs",
      "include changes sling:resourceType on the current node, but resource cannot",
      "include is allowed only in JSP, while resource is HTL-only",
      "include renders only dialogs, while resource renders only templates",
      "include versions the parent component, while resource hides componentGroup",
      "include disables escaping, while resource forces unsafe context",
      "include runs only on Author, while resource runs only on Publish",
      "include creates content nodes, while resource deletes them after render",
    ],
    explanation:
      "The speech says data-sly-include includes the output of another script as markup and does not change the processing context, while data-sly-resource includes a resource rendered through its own component.",
  },
  {
    id: "comp-047",
    topic: "HTL Templates & Use-API",
    question: "Which options does the speech say you can pass to data-sly-resource?",
    correctAnswers: [
      "resourceType, selectors, wcmmode, prependPath, and appendPath",
      "The listed options are resourceType, selectors, wcmmode, plus prependPath and appendPath",
      "You can force a component with resourceType and also pass selectors, wcmmode, prependPath, and appendPath",
      "data-sly-resource supports options including resourceType, selectors, wcmmode, prependPath, and appendPath",
    ],
    incorrectAnswers: [
      "Only componentGroup, jcr:title, and cq:isContainer",
      "Only authorizableId, password, and groupMembership",
      "Only pid, service.ranking, and factoryPid",
      "Only cacheTtl, flushRules, and invalidationMode",
      "Only packageName, version, and bundleSymbolicName",
      "Only locale, timezone, and cronExpression",
      "Only policyPath, templateType, and rolloutConfig",
      "Only exporterName, modelClass, and servletPath",
    ],
    explanation:
      "The speech says data-sly-resource can take options such as resourceType to force a component, selectors, wcmmode, prependPath, and appendPath.",
  },
  {
    id: "comp-048",
    topic: "HTL Templates & Use-API",
    question: "What can data-sly-use load through the Use-API?",
    correctAnswers: [
      "A Java class, which can be a Sling Model, or a JavaScript Use-API file",
      "It can load either a Java class such as a Sling Model or a JavaScript Use-API file",
      "The Use-API lets data-sly-use reach logic in Java classes or JavaScript Use-API files",
      "data-sly-use can load Sling Model style Java classes as well as JavaScript Use-API helpers",
    ],
    incorrectAnswers: [
      "Only content policy nodes under /conf",
      "Only Dispatcher farm files",
      "Only editable templates and page policies",
      "Only client library categories from /etc.clientlibs",
      "Only JCR mixin definitions",
      "Only replication agents and transport handlers",
      "Only workflow inbox items",
      "Only package filters from META-INF/vault",
    ],
    explanation:
      "The speech says the Use-API is how HTL reaches logic and that data-sly-use can load a Java class, which may be a Sling Model, or a JavaScript Use-API file.",
  },
  {
    id: "comp-049",
    topic: "HTL Templates & Use-API",
    question: "What is the recommended modern approach for HTL logic according to the speech?",
    correctAnswers: [
      "Use Sling Models",
      "The recommended approach today is Sling Models",
      "HTL should typically reach logic through Sling Models",
      "The speech recommends Sling Models rather than older alternatives",
    ],
    incorrectAnswers: [
      "Prefer JSP scriptlets for all business logic",
      "Prefer copying Core Components into /libs",
      "Prefer only JavaScript Use-API and avoid models",
      "Prefer component logic inside .content.xml properties",
      "Prefer OSGi configurations as the template logic layer",
      "Prefer Dispatcher rules as the rendering logic source",
      "Prefer storing logic directly in authored content nodes",
      "Prefer only HTML comments to control rendering",
    ],
    explanation:
      "The speech says that while data-sly-use can load Java or JavaScript helpers, the recommended approach today is Sling Models.",
  },
  {
    id: "comp-050",
    topic: "HTL Templates & Use-API",
    question: "When a Sling Model is loaded through the Sling Models Use Provider, what adaptable does it receive first if supported?",
    correctAnswers: [
      "The request, and otherwise the resource",
      "It gets the request as adaptable if it supports it; otherwise it gets the resource",
      "The request is used first when supported, with the resource as fallback",
      "Loaded this way, the model adapts from the request when possible and the resource otherwise",
    ],
    incorrectAnswers: [
      "The current page, and otherwise the template policy",
      "The dialog node, and otherwise the design dialog",
      "The clientlib category, and otherwise the bundle context",
      "The OSGi config PID, and otherwise the service user",
      "The HTML element, and otherwise the componentGroup",
      "The versioned parent path, and otherwise the proxy path",
      "The authorizable user, and otherwise the workflow session",
      "The dispatcher rule set, and otherwise the replication queue",
    ],
    explanation:
      "The speech says that when loaded through the Sling Models Use Provider, the model gets the request as adaptable if it supports it, and the resource otherwise.",
  },
]
