import type { TriviaQuestion } from "./trivia-types"

export const workflowsQuestionsPartB: TriviaQuestion[] = [
  {
    id: "wf-051",
    topic: "MetaDataMaps and Persisting Data",
    question: "What is workflow metadata used for in AEM workflows?",
    correctAnswers: [
      "Workflow metadata persists information needed during the workflow and between steps",
      "It stores data that must remain available across the life of the workflow and later steps",
      "Its purpose is to persist workflow information from one step to another",
      "It keeps workflow data available during the workflow lifecycle",
    ],
    incorrectAnswers: [
      "It only stores the visual layout of the workflow model editor",
      "It is used only to version workflow models in /var/workflow/models",
      "It exists only to configure launcher path conditions",
      "It is the same thing as the workflow inbox assignment list",
      "It only stores archived instance history after completion",
      "It is used only for email server configuration",
      "It replaces the workflow payload itself",
      "It is limited to the start node and cannot be read later",
    ],
    explanation:
      "The speech says workflow metadata persists information needed during the life of the workflow and between steps, and that it is stored in MetaDataMap objects.",
  },
  {
    id: "wf-052",
    topic: "MetaDataMaps and Persisting Data",
    question: "Which MetaDataMap is recommended when you need data shared over the entire workflow?",
    correctAnswers: [
      "Use the WorkflowData MetaDataMap for shared workflow data",
      "The recommended shared map is the WorkflowData metadata map",
      "WorkflowData metadata is the map recommended for values used across the workflow",
      "Store cross-step shared values in the WorkflowData MetaDataMap",
    ],
    incorrectAnswers: [
      "Use only the WorkItem MetaDataMap for all long-lived values",
      "Store shared values only in the step component's cq:editConfig node",
      "Use the launcher configuration node as the shared data store",
      "Put the values only in the workflow model title property",
      "Use the participant inbox as the recommended data store",
      "Persist them only in the OR Split transition rules",
      "Store them only in the Experience Fragment folder properties",
      "Use only the workflow instance archive record after completion",
    ],
    explanation:
      "The speech lists MetaDataMaps for Workflow, WorkflowData, and WorkItem, then recommends using only the WorkflowData map for shared workflow data.",
  },
  {
    id: "wf-053",
    topic: "MetaDataMaps and Persisting Data",
    question: "In Java, where should a process step write a value if a later step must read it?",
    correctAnswers: [
      "Write it to workItem.getWorkflow().getWorkflowData().getMetaDataMap()",
      "Store it in the WorkflowData MetaDataMap obtained from the current WorkItem",
      "Persist it on the workflow's WorkflowData metadata map",
      "Use the WorkItem to reach WorkflowData and put the key there",
    ],
    incorrectAnswers: [
      "Write it only to the node name of the current WorkflowNode",
      "Store it only in the runtime model under /var/workflow/models",
      "Put it only in the PROCESS label of the step component",
      "Save it only in the participant's personal inbox item title",
      "Write it only into the launcher's node type condition",
      "Store it only in the editable template policy",
      "Persist it only in the page component dialog under /apps",
      "Put it only in the transition display name",
    ],
    explanation:
      "The speech says that to persist data for later steps in Java, you call getWorkflow().getWorkflowData().getMetaDataMap() on the WorkItem and put a key and value there.",
  },
  {
    id: "wf-054",
    topic: "MetaDataMaps and Persisting Data",
    question: "Which MetaDataMap is limited to the lifetime of the current step's work item?",
    correctAnswers: [
      "The WorkItem MetaDataMap only lasts while that work item is running",
      "The WorkItem map is usable only for the current running work item",
      "Only the WorkItem metadata map is limited to the current step execution",
      "The step-scoped map is the WorkItem MetaDataMap",
    ],
    incorrectAnswers: [
      "The WorkflowData MetaDataMap exists only for the current step",
      "The Workflow model definition map disappears after each transition",
      "The payload path itself is the only step-scoped map",
      "The archive record is the map that lasts only during a step",
      "The Content Fragment model map is the step-lifetime map",
      "The WorkflowSession is the only per-step metadata container",
      "The launcher event object is the workflow's official step map",
      "The process.label property is the temporary step map",
    ],
    explanation:
      'The speech says a WorkItem map can only be used while that work item, meaning that step, is running.',
  },
  {
    id: "wf-055",
    topic: "MetaDataMaps and Persisting Data",
    question: 'Values entered below a step component\'s "./metaData" node end up where at runtime?',
    correctAnswers: [
      "They are added to the workflow MetaDataMap",
      "Those dialog values are stored in the workflow metadata map",
      "They become entries in the workflow's MetaDataMap",
      "AEM adds them to the workflow metadata at runtime",
    ],
    incorrectAnswers: [
      "They are compiled into the Sling Rewriter configuration",
      "They are written only to the user's workflow inbox preferences",
      "They are stored only on the editable template content policy",
      "They go only into the launcher's path expression",
      "They are persisted only in the page component HTML",
      "They are stored only in the Content Fragment model definition",
      "They replace the workflow payload type automatically",
      "They are added only to the archived history after completion",
    ],
    explanation:
      'The speech states that dialog values stored below the "./metaData" node of a step component are added to the workflow MetaDataMap.',
  },
  {
    id: "wf-056",
    topic: "MetaDataMaps and Persisting Data",
    question: "When the metadata key is PROCESS_ARGS, how are those arguments exposed to implementations?",
    correctAnswers: [
      "PROCESS_ARGS is available as args in ECMA and through the MetaDataMap argument in Java",
      "ECMA scripts read PROCESS_ARGS as args, while Java receives it through the MetaDataMap parameter",
      "The PROCESS_ARGS value is exposed directly as args in ECMA and via MetaDataMap in Java",
      "AEM maps PROCESS_ARGS to args for scripts and to the execute MetaDataMap for Java steps",
    ],
    incorrectAnswers: [
      "PROCESS_ARGS is available only in the Workflow REST API response",
      "PROCESS_ARGS is exposed only as the payload path string",
      "PROCESS_ARGS can be read only from the workflow archive node",
      "PROCESS_ARGS is available only inside Content Fragment variations",
      "PROCESS_ARGS is mapped only to the participant assignee field",
      "PROCESS_ARGS is used only by launchers and not by steps",
      "PROCESS_ARGS is available only in the page request attributes",
      "PROCESS_ARGS is the property that enables Target export offers",
    ],
    explanation:
      "The speech says that when the key is PROCESS_ARGS, the value is available directly as args in ECMA scripts and as the MetaDataMap argument in Java.",
  },
  {
    id: "wf-057",
    topic: "MetaDataMaps and Persisting Data",
    question: 'In an ECMA workflow script, why should you not confuse "metaData" with workflow metadata?',
    correctAnswers: [
      "In ECMA, metaData refers to the step metadata, not the workflow metadata",
      "The metaData variable is step metadata rather than shared workflow metadata",
      "ECMA metaData points to the step's metadata, so it is different from workflow metadata",
      "The speech distinguishes ECMA metaData from the workflow metadata map",
    ],
    incorrectAnswers: [
      "Because metaData always means the payload binary stream",
      "Because metaData is the archived history of terminated instances",
      "Because metaData is only the workflow launcher's event object",
      "Because metaData is the Experience Fragment plain HTML rendition",
      "Because metaData is only the JCR node type of the payload",
      "Because metaData is the WorkflowSession adapted from the resolver",
      "Because metaData is the Content Fragment model title field",
      "Because metaData is the same as PROCESS_AUTO_ADVANCE",
    ],
    explanation:
      "The speech explicitly says that in ECMA scripts, the variable metaData is the metadata of the step, which is different from the workflow metadata.",
  },
  {
    id: "wf-058",
    topic: "Custom Step Components",
    question: "What does a workflow step component define for model authors?",
    correctAnswers: [
      "A workflow step component defines the step's authoring behavior, appearance, dialog, and runtime implementation",
      "It defines how the step looks, is categorized, is edited, and what runs at runtime",
      "It controls the step's category, name, appearance, edit dialog, and executing service or script",
      "It defines both the model-building experience and the runtime hook for the step",
    ],
    incorrectAnswers: [
      "It defines only the workflow archive retention period",
      "It is used only to sync runtime models under /var",
      "It defines only launcher event types and path conditions",
      "It replaces the need for WorkflowProcess implementations",
      "It exists only to manage GraphQL schemas for headless delivery",
      "It controls only mail server setup for participant notifications",
      "It defines only Target export credentials",
      "It is limited to naming the workflow instance after completion",
    ],
    explanation:
      "The speech says a workflow step component defines how a step looks and behaves when building models, including its category and name, appearance, edit dialog, and the service or script that runs at runtime.",
  },
  {
    id: "wf-059",
    topic: "Custom Step Components",
    question: "Which base step resource super type should a custom automatic process step inherit from?",
    correctAnswers: [
      "cq/workflow/components/model/process",
      "Use cq/workflow/components/model/process",
      "The correct process-step super type is cq/workflow/components/model/process",
      "A custom automatic process step inherits from cq/workflow/components/model/process",
    ],
    incorrectAnswers: [
      "cq/workflow/components/model/participant",
      "cq/workflow/components/model/dynamic_participant",
      "cq/experience-fragments/components/xfpage",
      "core/wcm/components/page/v3/page",
      "dam/cfm/models/console/components/model",
      "granite/ui/components/coral/foundation/form",
      "cq/workflow/components/model/container_only",
      "libs/foundation/components/parsys",
    ],
    explanation:
      "The speech lists the three base paths and says process steps inherit from cq/workflow/components/model/process.",
  },
  {
    id: "wf-060",
    topic: "Custom Step Components",
    question: "If a custom step should choose the assignee at runtime, which base step should it extend?",
    correctAnswers: [
      "cq/workflow/components/model/dynamic_participant",
      "Use the dynamic participant base step",
      "The correct super type is cq/workflow/components/model/dynamic_participant",
      "A runtime chooser step extends cq/workflow/components/model/dynamic_participant",
    ],
    incorrectAnswers: [
      "cq/workflow/components/model/process",
      "cq/workflow/components/model/participant",
      "cq/workflow/components/model/start",
      "cq/experience-fragments/components/xfpage",
      "dam/cfm/components/contentfragment",
      "cq/workflow/components/model/or_split",
      "wcm/foundation/components/responsivegrid",
      "granite/ui/components/coral/foundation/container",
    ],
    explanation:
      "The speech says the dynamic participant base path is cq/workflow/components/model/dynamic_participant.",
  },
  {
    id: "wf-061",
    topic: "Custom Step Components",
    question: "Why should custom workflow step components never be modified under /libs?",
    correctAnswers: [
      "Never change /libs; recreate the item under /apps and change it there",
      "Because the correct approach is to recreate the step under /apps instead of editing /libs",
      "Customizations belong under /apps, not as edits to /libs",
      "The speech says to avoid /libs and make the customized item under /apps",
    ],
    incorrectAnswers: [
      "Because /libs is where workflow runtime history must be persisted",
      "Because /libs is reserved only for Content Fragment models",
      "Because /libs can be used only for GraphQL persisted queries",
      "Because /libs automatically blocks all participant steps",
      "Because /libs is where launchers are always authored in Cloud Service",
      "Because /libs is required only for Experience Fragment folders",
      "Because /libs is the correct place for mail server credentials",
      "Because /libs can be used only for archived terminated instances",
    ],
    explanation:
      "The speech is explicit: never change anything in /libs; recreate the item under /apps and make the changes there.",
  },
  {
    id: "wf-062",
    topic: "Custom Step Components",
    question: "Where do design-time defaults for a workflow step component belong?",
    correctAnswers: [
      "In cq:editConfig with child cq:formParameters",
      "Put design-time defaults in a cq:editConfig node and its cq:formParameters child",
      "The defaults belong under cq:editConfig/cq:formParameters",
      "Use cq:editConfig of type cq:EditConfig with a cq:formParameters child",
    ],
    incorrectAnswers: [
      "In the workflow instance archive below /var/workflow/instances",
      "In the Sling Rewriter configuration for experience fragments",
      "In the Workflow REST API models URL response",
      "In the payload node's jcr:content/renditions path",
      "In the Content Fragment Main variation",
      "In the launcher event type property only",
      "In the WorkflowSession adaptation chain",
      "In the user's experience-fragments-editors group profile",
    ],
    explanation:
      "The speech says design-time defaults go in a cq:editConfig node of type cq:EditConfig, with a child node named cq:formParameters of type nt:unstructured.",
  },
  {
    id: "wf-063",
    topic: "Custom Step Components",
    question: "Which cq:formParameters property fixes the implementation of a process step so model authors cannot change it?",
    correctAnswers: [
      "PROCESS fixes the process implementation",
      "Use the PROCESS property",
      "The property is PROCESS",
      "Set PROCESS to lock the process implementation for authors",
    ],
    incorrectAnswers: [
      "FORM_PATH",
      "DIALOG_PATH",
      "DO_NOTIFY",
      "PROCESS_AUTO_ADVANCE",
      "jcr:description",
      "allowedCssClasses",
      "PARTICIPANT_STEP_MODE",
      "WORKFLOW_STATE",
    ],
    explanation:
      "The speech says properties on cq:formParameters include PROCESS, PARTICIPANT, and DYNAMIC_PARTICIPANT, and that setting them removes the model author's ability to change the value.",
  },
  {
    id: "wf-064",
    topic: "Custom Step Components",
    question: "For a participant step, which cq:formParameters property should be used to show a form when the user opens the work item?",
    correctAnswers: [
      "FORM_PATH shows a form when the user opens the work item",
      "Use FORM_PATH",
      "The property is FORM_PATH",
      "Set FORM_PATH to present the form on work-item open",
    ],
    incorrectAnswers: [
      "DIALOG_PATH",
      "PROCESS",
      "PROCESS_AUTO_ADVANCE",
      "DO_NOTIFY",
      "PARTICIPANT",
      "allowedTags",
      "plain",
      "RESOURCE_RESOLVER",
    ],
    explanation:
      "The speech says FORM_PATH is used to present a form when the user opens a work item, and that it applies to participant steps.",
  },
  {
    id: "wf-065",
    topic: "Custom Step Components",
    question: "For a participant step, which cq:formParameters property presents a custom dialog when the user completes the work item?",
    correctAnswers: [
      "DIALOG_PATH presents the completion dialog",
      "Use DIALOG_PATH",
      "The property is DIALOG_PATH",
      "Set DIALOG_PATH to show a custom dialog on completion",
    ],
    incorrectAnswers: [
      "FORM_PATH",
      "PROCESS",
      "PROCESS_AUTO_ADVANCE",
      "DO_NOTIFY",
      "PARTICIPANT",
      "allowedTemplates",
      "jsonExporter",
      "payloadType",
    ],
    explanation:
      "The speech says DIALOG_PATH is used to present a custom dialog when the user completes a participant step.",
  },
  {
    id: "wf-066",
    topic: "Programmatic Interaction",
    question: "In Java or an OSGi service, how do you obtain a WorkflowSession?",
    correctAnswers: [
      "Adapt a ResourceResolver to WorkflowSession",
      "Get a WorkflowSession by adapting the ResourceResolver",
      "The standard approach is ResourceResolver.adaptTo(WorkflowSession)",
      "Use the resource resolver adaptation to obtain WorkflowSession",
    ],
    incorrectAnswers: [
      "Adapt the WorkflowSession to a ResourceResolver first",
      "Read it from the Content Fragment model definition",
      "Create it from the Experience Fragment plain selector",
      "Fetch it only from the Workflow REST API JSON",
      "Read it from cq:formParameters on the step component",
      "Resolve it only from the mail server configuration",
      "Generate it by syncing the workflow model",
      "Read it from the archived instance node after completion",
    ],
    explanation:
      "The speech says that to start or manage workflows from code, you obtain a WorkflowSession by adapting a ResourceResolver to WorkflowSession.",
  },
  {
    id: "wf-067",
    topic: "Programmatic Interaction",
    question: "In an ECMA script, how do you reach a WorkflowSession?",
    correctAnswers: [
      "Use sling's resource resolver and adapt it to WorkflowSession",
      "In ECMA, the sling ScriptHelper provides a resolver that can be adapted to WorkflowSession",
      "Get the resource resolver from sling and adapt it to WorkflowSession",
      "The ECMA path is through the sling variable to a resolver, then to WorkflowSession",
    ],
    incorrectAnswers: [
      "Use the metaData variable because it already is a WorkflowSession",
      "Read WorkflowSession directly from PROCESS_ARGS",
      "Get it only from the Experience Fragment folder regex",
      "Use the Content Fragment Main variation as the session handle",
      "Read it only from the model sidekick category",
      "Create it from the .plain.html rendition URL",
      "Load it from the archived work item node",
      "Use allowedCssClasses to derive it automatically",
    ],
    explanation:
      "The speech says that in ECMA scripts, sling is a ScriptHelper that gives access to the request and its resource resolver, which can be adapted to WorkflowSession.",
  },
  {
    id: "wf-068",
    topic: "Programmatic Interaction",
    question: "Which API does the Workflow console itself use to manage workflows over HTTP?",
    correctAnswers: [
      "The Workflow REST API",
      "Use the Workflow REST API",
      "The console uses the Workflow REST API",
      "Workflow management over HTTP is done through the Workflow REST API",
    ],
    incorrectAnswers: [
      "The GraphQL fragments API",
      "The Experience Fragments Rewriter API",
      "The Content Services authoring API",
      "The Sling Models Exporter API only",
      "The Cloud Manager pipeline API",
      "The Repo Init endpoint",
      "The OSGi Web Console package API",
      "The editable templates REST endpoint",
    ],
    explanation:
      "The speech says workflows can also be managed through the Workflow REST API and that the Workflow console itself uses it.",
  },
  {
    id: "wf-069",
    topic: "Programmatic Interaction",
    question: "How do GET requests return JSON from the Workflow REST API?",
    correctAnswers: [
      "Add the .json extension to the URL",
      "Use a URL with the .json extension",
      "Workflow REST GET responses return JSON when the URL ends in .json",
      "Request the resource with a .json extension",
    ],
    incorrectAnswers: [
      "Add the .plain selector to the URL",
      "Append .nocloudconfigs.html to the URL",
      "Use only POST because GET never returns JSON",
      "Add the PROCESS_ARGS query parameter",
      "Set the page template to editable mode",
      "Append .graphql to the URL",
      "Use only the publish instance host name",
      "Set allowedTags on the rewriter configuration",
    ],
    explanation:
      "The speech states that GET requests return JSON when the Workflow REST API URL has the .json extension.",
  },
  {
    id: "wf-070",
    topic: "Programmatic Interaction",
    question: "Which states are used when listing workflow instances by state through the Workflow REST API?",
    correctAnswers: [
      "Workflow instance states are RUNNING, SUSPENDED, ABORTED, and COMPLETED",
      "The states are RUNNING, SUSPENDED, ABORTED, and COMPLETED",
      "Use the four REST states RUNNING, SUSPENDED, ABORTED, and COMPLETED",
      "Workflow instances are listed by the states RUNNING, SUSPENDED, ABORTED, and COMPLETED",
    ],
    incorrectAnswers: [
      "DRAFT, REVIEW, APPROVED, and PUBLISHED",
      "ACTIVE, PAUSED, CANCELLED, and ARCHIVED",
      "AUTHOR, PUBLISH, DEV, and PROD",
      "START, PARTICIPANT, PROCESS, and END",
      "OPEN, BLOCKED, DONE, and REOPENED",
      "DEFAULT, CUSTOM, LEGACY, and TRANSIENT",
      "MASTER, VARIATION, SYNCED, and UNSYNCED",
      "HTML, JSON, XML, and PLAIN",
    ],
    explanation:
      "The speech says workflow instances are listed by state and names the states as RUNNING, SUSPENDED, ABORTED, and COMPLETED.",
  },
  {
    id: "wf-071",
    topic: "Programmatic Interaction",
    question: "Where are workflow models listed in the Workflow REST API?",
    correctAnswers: [
      "Workflow models are listed under the models URL",
      "Use the models URL",
      "The REST API lists models under its models URL",
      "Model discovery is under the models URL",
    ],
    incorrectAnswers: [
      "Under the launchers-only URL",
      "Under the GraphQL schema endpoint",
      "Under the Experience Fragment folder URL",
      "Under the .plain.html rendition path",
      "Under the Template Editor policy URL",
      "Only under /libs/settings/wcm/templates",
      "Only under the Content Services export path",
      "Only under the /etc/packages manager URL",
    ],
    explanation:
      "The speech says models are listed under the models URL, and that a specific model returns its id, title, version, description, nodes, and transitions.",
  },
  {
    id: "wf-072",
    topic: "Programmatic Interaction",
    question: "When you inspect a model through the REST API, what kind of values appear in a node's metaData?",
    correctAnswers: [
      "A node's metaData can contain properties such as PARTICIPANT, PROCESS, and PROCESS_AUTO_ADVANCE",
      "Node metadata includes step properties like PARTICIPANT, PROCESS, and PROCESS_AUTO_ADVANCE",
      "The model node metaData holds values such as PARTICIPANT, PROCESS, and PROCESS_AUTO_ADVANCE",
      "Expect REST node metaData to expose properties like PARTICIPANT, PROCESS, and PROCESS_AUTO_ADVANCE",
    ],
    incorrectAnswers: [
      "Only GraphQL persisted query hashes",
      "Only Experience Fragment folder regular expressions",
      "Only Link Externalizer publish mappings",
      "Only bnd manifest headers",
      "Only Content Fragment rich text policy settings",
      "Only Target offer impression counts",
      "Only JUnit test selectors",
      "Only Oak index cache paths",
    ],
    explanation:
      "The speech says that in a model, each node has a type and its metaData holds properties like PARTICIPANT, PROCESS, and PROCESS_AUTO_ADVANCE.",
  },
  {
    id: "wf-073",
    topic: "Content Fragments Concepts",
    question: "What best describes a Content Fragment?",
    correctAnswers: [
      "A Content Fragment is channel-neutral structured content independent of a page",
      "It is structured, channel-neutral content managed independently from any page",
      "A Content Fragment is page-independent structured content that can be reused across channels",
      "It is structured content managed as an asset rather than as page layout",
    ],
    incorrectAnswers: [
      "A page-only layout container tied to one template",
      "A workflow launcher that starts on DAM events",
      "A participant step with a custom completion dialog",
      "A Sling Rewriter pipeline for HTML cleanup",
      "An immutable /libs component for reusable page chrome",
      "A publish-only archive of completed workflows",
      "A fixed set of OSGi configurations for fragments",
      "A folder-level permission group for authors",
    ],
    explanation:
      "The speech defines Content Fragments as channel-neutral, structured content that is managed as assets and is independent of any page.",
  },
  {
    id: "wf-074",
    topic: "Content Fragments Concepts",
    question: "What must exist before authors can create a Content Fragment?",
    correctAnswers: [
      "A Content Fragment Model must exist first",
      "You need a Content Fragment Model before creating the fragment",
      "Content Fragment creation requires a Content Fragment Model",
      "Authors can create a fragment only after its model exists",
    ],
    incorrectAnswers: [
      "An Experience Fragment folder with Allowed Templates",
      "A workflow runtime model synced under /var",
      "A custom process step component under /apps",
      "A Target configuration and Link Externalizer",
      "A participant step inbox assignment",
      "A launcher configured for node creation events",
      "A Sling Rewriter overlay under /libs",
      "A Repo Init script for GraphQL export",
    ],
    explanation:
      "The speech says that to create a fragment you need a Content Fragment Model, which is enabled with the Configuration Browser and created in the Content Fragment console.",
  },
  {
    id: "wf-075",
    topic: "Content Fragments Concepts",
    question: "What is the minimum required structure for a Content Fragment Model according to the speech?",
    correctAnswers: [
      "A Content Fragment Model requires a title and one data element",
      "The model must have a title and at least one data element",
      "Its minimum requirement is a title plus one data element",
      "A valid model needs a title and one data field",
    ],
    incorrectAnswers: [
      "A title, ten variations, and a paragraph system",
      "Only a template name that starts with experience-fragment",
      "At least one page component and one layout container",
      "A model title plus a publish-only Link Externalizer",
      "An editable template, a workflow stage, and a tag root",
      "A title, a Target config, and two rich text fields",
      "A GraphQL endpoint and a workflow launcher",
      "Only a main variation with no data elements",
    ],
    explanation:
      "The speech says a Content Fragment Model defines the structure and that a model requires a title and one data element.",
  },
  {
    id: "wf-076",
    topic: "Content Fragments Concepts",
    question: "Why can't authors change a fragment's structure while authoring?",
    correctAnswers: [
      "Authors cannot change the structure because the Content Fragment Model defines it",
      "The model fixes the fragment structure for authors",
      "Structure is controlled by the model, not by fragment authors during authoring",
      "AEM keeps authors from changing the structure because it comes from the model definition",
    ],
    incorrectAnswers: [
      "Because structure can be changed only in Adobe Target offers",
      "Because fragment structure is always generated from the workflow payload path",
      "Because paragraph systems lock all field definitions at publish time",
      "Because only archived workflow instances may store field definitions",
      "Because Allowed Templates on folders replace model structure",
      "Because the Sling Rewriter pipeline owns all field definitions",
      "Because structure must be changed in the workflow inbox",
      "Because fragment authors are required to edit /libs directly",
    ],
    explanation:
      "The speech says the model defines the structure of a fragment and that authors cannot change the structure while authoring.",
  },
  {
    id: "wf-077",
    topic: "Content Fragments Concepts",
    question: "What are the main parts of a Content Fragment?",
    correctAnswers: [
      "A Content Fragment is made of elements, paragraphs, and metadata",
      "Its main parts are elements, paragraphs, and metadata",
      "The fragment consists of elements, paragraphs, and metadata",
      "Elements, paragraphs, and metadata make up a Content Fragment",
    ],
    incorrectAnswers: [
      "Templates, policies, and launchers",
      "Pages, paragraph systems, and design dialogs",
      "Bundles, run modes, and Repo Init scripts",
      "Models, services, and workflow stages only",
      "Offers, activities, and impressions",
      "Selectors, rewriters, and externalizers",
      "Nodes, transitions, and work items",
      "Folders, inboxes, and assignees",
    ],
    explanation:
      "The speech says a fragment is made of elements, paragraphs, and metadata.",
  },
  {
    id: "wf-078",
    topic: "Content Fragments Concepts",
    question: "What is true about the Main variation of a Content Fragment?",
    correctAnswers: [
      "Main is the basis of all variations and cannot be deleted",
      "Every fragment has one Main variation that all other variations are based on",
      "The Main variation is mandatory and undeletable",
      "Main, labeled Master in the Assets editor, is the source for other variations",
    ],
    incorrectAnswers: [
      "Main can be deleted after the first named variation is created",
      "Main exists only for Experience Fragments, not Content Fragments",
      "Main is the HTML export rendition for third-party apps",
      "Main is a workflow state listed by the REST API",
      "Main is the only place where images are forbidden",
      "Main is created only on publish instances",
      "Main is the folder regex for allowed templates",
      "Main is a participant step property under cq:formParameters",
    ],
    explanation:
      "The speech says every fragment has one Main, that Main is the basis of all variations, and that Main cannot be deleted. In the Assets console editor, Main is labeled Master.",
  },
  {
    id: "wf-079",
    topic: "Content Fragments Concepts",
    question: "How can images be used with a Content Fragment according to the speech?",
    correctAnswers: [
      "Images can be used as a Content Reference or inside a Multi line text field",
      "Use images either as a Content Reference or within Multi line text",
      "A fragment can use images through a Content Reference or in Multi line text",
      "The speech allows images as referenced content and inside Multi line text fields",
    ],
    incorrectAnswers: [
      "Images can be used only as workflow payload URLs",
      "Images are allowed only in Experience Fragment .plain renditions",
      "Images must be embedded only through cq:formParameters",
      "Images belong only in GraphQL schema definitions",
      "Images can be used only in the Main variation title",
      "Images must be stored only under /libs",
      "Images are supported only by participant step dialogs",
      "Images can appear only through the Target HTML offer selector",
    ],
    explanation:
      "The speech says images can be used with a fragment as a Content Reference, or inside a Multi line text field.",
  },
  {
    id: "wf-080",
    topic: "Content Fragments Delivery and Best Practices",
    question: "For page authoring, which component references a Content Fragment on a page?",
    correctAnswers: [
      "The Content Fragment Component references the fragment on the page",
      "Use the core Content Fragment Component",
      "Page authors reference fragments with the Content Fragment Component",
      "The correct page component is the Content Fragment Component",
    ],
    incorrectAnswers: [
      "The Experience Fragment plain renderer",
      "The Workflow Process Step component",
      "The Dynamic Participant chooser component",
      "The Sling Rewriter configuration node",
      "The GraphQL schema editor component",
      "The Launchers console component",
      "The Content Fragment Model editor page template",
      "The Repo Init bootstrap component",
    ],
    explanation:
      "The speech says that for page authoring, a fragment is referenced on a page with the Content Fragment Component, which is a core component.",
  },
  {
    id: "wf-081",
    topic: "Content Fragments Delivery and Best Practices",
    question: "For headless delivery, in what format are Content Fragments delivered?",
    correctAnswers: [
      "Content Fragments are delivered as JSON for headless use",
      "Headless delivery uses JSON",
      "For headless channels, fragments are delivered as JSON",
      "The speech says headless fragment delivery is JSON-based",
    ],
    incorrectAnswers: [
      "Only as plain HTML with the .plain selector",
      "Only as workflow archive XML",
      "Only as Java serialized objects",
      "Only as editable template policies",
      "Only as package filter definitions",
      "Only as email notifications to assignees",
      "Only as JCR node type exports",
      "Only as Sling Model annotations",
    ],
    explanation:
      "The speech says that for headless delivery, fragments are delivered as JSON.",
  },
  {
    id: "wf-082",
    topic: "Content Fragments Delivery and Best Practices",
    question: "Which query mechanism is used for headless delivery of Content Fragments?",
    correctAnswers: [
      "GraphQL is the query mechanism for headless delivery of Content Fragments",
      "Use GraphQL",
      "Headless fragment queries are done with GraphQL",
      "The speech names GraphQL as the headless query mechanism",
    ],
    incorrectAnswers: [
      "The Workflow REST API",
      "The Experience Fragment Rewriter pipeline",
      "The participant inbox API",
      "The Package Manager service",
      "The Repo Init parser",
      "The Link Externalizer admin console",
      "The cq:formParameters dialog API",
      "The bnd manifest generator",
    ],
    explanation:
      "The speech says GraphQL is the query mechanism for headless delivery of fragments.",
  },
  {
    id: "wf-083",
    topic: "Content Fragments Delivery and Best Practices",
    question: "What is true about the Content Fragments console mentioned in the speech?",
    correctAnswers: [
      "The Content Fragments console is optimized for headless use and exists only in AEM as a Cloud Service",
      "It is headless-optimized and available only in AEM as a Cloud Service",
      "The speech says the console is a Cloud Service-only, headless-optimized console",
      "Content Fragments console availability is limited to AEM as a Cloud Service",
    ],
    incorrectAnswers: [
      "It is available only on publish and not on author",
      "It is used only for Experience Fragment template restriction",
      "It exists only for managing workflow runtime models",
      "It is the same as the Workflow inbox console",
      "It is required only for Repo Init authoring",
      "It works only with classic UI dialog definitions",
      "It is available only when DO_NOTIFY is false",
      "It is limited to Adobe Target offer exports",
    ],
    explanation:
      "The speech says the Content Fragments console is optimized for headless use and is available only in AEM as a Cloud Service.",
  },
  {
    id: "wf-084",
    topic: "Content Fragments Delivery and Best Practices",
    question: "Why does Adobe recommend keeping the number of Content Fragment models to a small set, usually at most low tens?",
    correctAnswers: [
      "Too many models slow GraphQL queries and complicate governance",
      "A small set is recommended because excess models hurt GraphQL performance and governance",
      "Keeping model counts low avoids slower GraphQL queries and governance complexity",
      "The speech warns that too many models make GraphQL slower and governance harder",
    ],
    incorrectAnswers: [
      "Because AEM allows only ten models total in all environments",
      "Because more models automatically disable JSON export",
      "Because each model forces a workflow instance to become transient",
      "Because additional models are stored only under /libs",
      "Because models above ten can no longer have tags",
      "Because more models prevent editable templates from loading",
      "Because model count is tied to the number of participant inboxes",
      "Because GraphQL requires exactly one model per project",
    ],
    explanation:
      "The speech says to create as many models as needed but no more, and that too many slows GraphQL queries and complicates governance.",
  },
  {
    id: "wf-085",
    topic: "Content Fragments Delivery and Best Practices",
    question: "What is the recommended limit for deep nesting of Content Fragment References?",
    correctAnswers: [
      "Keep Content Fragment Reference nesting to no more than ten levels",
      "The recommendation is a maximum nesting depth of ten",
      "Avoid going beyond ten levels of nested Content Fragment References",
      "Content Fragment Reference nesting should stay at ten levels or fewer",
    ],
    incorrectAnswers: [
      "At least twenty levels are recommended for reuse",
      "Nesting is forbidden entirely in all models",
      "Only one level is allowed by AEM",
      "Use unlimited nesting because GraphQL flattens it automatically",
      "The speech limits nesting to three because of workflow history",
      "References must always point to Experience Fragments instead",
      "Nesting is controlled only by the mail server settings",
      "The recommendation applies only to the Main variation title field",
    ],
    explanation:
      "The speech says to avoid deep nesting of Content Fragment References and to keep nesting to no more than ten levels.",
  },
  {
    id: "wf-086",
    topic: "Content Fragments Delivery and Best Practices",
    question: "Why should a Content Fragment avoid having more than ten variations?",
    correctAnswers: [
      "More than ten variations add processing time on author and on delivery",
      "The speech limits variations because they increase processing time in author and delivery",
      "Too many variations are discouraged because they add processing overhead to authoring and delivery",
      "AEM best practice is to keep variations at ten or fewer to avoid extra processing time",
    ],
    incorrectAnswers: [
      "Because the Assets console deletes variation eleven automatically",
      "Because GraphQL can query only one variation per model",
      "Because variations are supported only in Experience Fragments",
      "Because more than ten variations disable the Main variation",
      "Because extra variations can exist only under /libs",
      "Because variations must match workflow stage names exactly",
      "Because publish instances accept only five variations",
      "Because the JSON Exporter strips all variations after the tenth paragraph",
    ],
    explanation:
      "The speech says not to exceed ten variations per fragment because variations add processing time on author and on delivery.",
  },
  {
    id: "wf-087",
    topic: "Experience Fragments Concepts",
    question: "What is an Experience Fragment?",
    correctAnswers: [
      "An Experience Fragment is a reusable group of components with content and layout that can be referenced within pages",
      "It is a group of one or more components, including content and layout, referenced within pages",
      "An Experience Fragment packages reusable page experience as components plus layout",
      "It is reusable page experience made from components and layout",
    ],
    incorrectAnswers: [
      "A channel-neutral data model with no layout",
      "A workflow runtime model generated by Sync",
      "A repository event definition that starts workflows",
      "A MetaDataMap limited to one work item",
      "An OSGi service that implements WorkflowProcess",
      "A GraphQL query document for headless export",
      "A package filter definition under META-INF/vault",
      "A repo-init script for fragment permissions",
    ],
    explanation:
      "The speech defines an Experience Fragment as a group of one or more components, including content and layout, that can be referenced within pages.",
  },
  {
    id: "wf-088",
    topic: "Experience Fragments Concepts",
    question: "Which statement about nesting is true for Experience Fragments?",
    correctAnswers: [
      "An Experience Fragment can contain other Experience Fragments",
      "Experience Fragments may contain other Experience Fragments",
      "The speech allows an Experience Fragment to include another Experience Fragment",
      "Nested Experience Fragments are supported",
    ],
    incorrectAnswers: [
      "Experience Fragments can contain only Content Fragments and nothing else",
      "Experience Fragments cannot contain any other components",
      "Only Content Fragments may contain Experience Fragments",
      "Experience Fragments may contain only workflow participant steps",
      "Nesting is supported only for launchers and runtime models",
      "Experience Fragments can contain only editable templates",
      "Nested fragments are forbidden unless they are archived",
      "Only the .plain rendition may contain nested fragments",
    ],
    explanation:
      "The speech says an Experience Fragment can contain any component, and it can contain other Experience Fragments.",
  },
  {
    id: "wf-089",
    topic: "Experience Fragments Concepts",
    question: "What is the foundation used to create the root page of an Experience Fragment?",
    correctAnswers: [
      "An Experience Fragment is based on an editable template that creates its root page",
      "The root page comes from an editable template",
      "Editable templates are the basis for Experience Fragment root pages",
      "The speech says the template is used to create the fragment's root page",
    ],
    incorrectAnswers: [
      "A Content Fragment Model creates the root page",
      "A Workflow launcher creates the root page",
      "A runtime model under /var creates the root page",
      "A Repo Init script is the required page foundation",
      "A fixed /libs page with no template is required",
      "Only the Workflow REST API can generate the root page",
      "The mail server configuration determines the root page",
      "The Target offer export selector creates the root page",
    ],
    explanation:
      "The speech says an Experience Fragment is based on an editable template and that the template is used to create the root page of the fragment.",
  },
  {
    id: "wf-090",
    topic: "Experience Fragments Concepts",
    question: "Why would an exam scenario choose an Experience Fragment instead of copying page sections manually?",
    correctAnswers: [
      "Because Experience Fragments let you reuse parts of a page without copy and paste",
      "They are used to reuse page sections instead of duplicating them manually",
      "The speech recommends Experience Fragments for reusable page parts without copy-paste",
      "Choose an Experience Fragment when you need reusable page experience across pages or channels",
    ],
    incorrectAnswers: [
      "Because they are the only way to store structured text fields",
      "Because they automatically create workflow launchers for page changes",
      "Because they are required for all GraphQL fragment queries",
      "Because they replace editable templates entirely",
      "Because they are the only way to persist MetaDataMap values",
      "Because they convert participant steps into process steps",
      "Because they can be created only on publish instances",
      "Because they prevent all content policies from being used",
    ],
    explanation:
      "The speech says Experience Fragments are used to reuse parts of a page without copy and paste, and also for headless use and omnichannel scenarios.",
  },
  {
    id: "wf-091",
    topic: "Experience Fragments Concepts",
    question: "What template requirement applies to pages that use Experience Fragments?",
    correctAnswers: [
      "Experience Fragments can be used only on pages based on editable templates",
      "Only pages built from editable templates can use Experience Fragments",
      "The speech says Experience Fragments require pages based on editable templates",
      "Editable templates are mandatory for pages using Experience Fragments",
    ],
    incorrectAnswers: [
      "They can be used only on static templates from /libs",
      "They require pages based on Content Fragment models",
      "They can be used only on workflow inbox pages",
      "They require a page with no paragraph system",
      "They are limited to pages under /content/dam",
      "They work only on pages created by launchers",
      "They require the page to be transient",
      "They can be used only on pages with Target export enabled",
    ],
    explanation:
      "The speech explicitly says Experience Fragments can only be used on pages that are based on editable templates.",
  },
  {
    id: "wf-092",
    topic: "Experience Fragments Concepts",
    question: "What is the recommended way to restrict which templates can be used for Experience Fragments?",
    correctAnswers: [
      "Set the folder's Allowed Templates property, typically with a regular expression",
      "Use Allowed Templates on the Experience Fragment folder",
      "The recommended restriction point is the folder-level Allowed Templates property",
      "Restrict templates with the folder's Allowed Templates regex rather than at instance level",
    ],
    incorrectAnswers: [
      "Edit the instance-level /libs template list directly",
      "Set the restriction only in the workflow model editor",
      "Use PROCESS_AUTO_ADVANCE on the step component",
      "Set the restriction only in the publish dispatcher config",
      "Use the Workflow REST API states list",
      "Place the restriction only in the fragment variation title",
      "Configure it only in the mail server settings",
      "Set it only through the Content Fragment console",
    ],
    explanation:
      "The speech says the recommended way to restrict templates is the Allowed Templates property of the folder, often using a regular expression, and says instance-level setting is not recommended.",
  },
  {
    id: "wf-093",
    topic: "Experience Fragments Concepts",
    question: "Which group grants write access for Experience Fragments?",
    correctAnswers: [
      "Users need the experience-fragments-editors group for write access",
      "Write access requires membership in experience-fragments-editors",
      "The required group is experience-fragments-editors",
      "Experience Fragment write access is granted through the experience-fragments-editors group",
    ],
    incorrectAnswers: [
      "content-fragments-editors",
      "workflow-participants",
      "target-offer-authors",
      "repo-init-administrators",
      "template-policy-managers",
      "graphQL-query-users",
      "dam-reviewers",
      "xf-plain-renderers",
    ],
    explanation:
      "The speech says write access requires the user to be in the group experience-fragments-editors.",
  },
  {
    id: "wf-094",
    topic: "Experience Fragments Development and Tips",
    question: "Which sling:resourceType is used by an Experience Fragment master or variation?",
    correctAnswers: [
      "Experience Fragment masters and variations use sling:resourceType cq/experience-fragments/components/xfpage",
      "The resource type is cq/experience-fragments/components/xfpage",
      "Use cq/experience-fragments/components/xfpage for an Experience Fragment master or variation",
      "The speech names cq/experience-fragments/components/xfpage as the fragment page resource type",
    ],
    incorrectAnswers: [
      "dam/cfm/components/contentfragment",
      "cq/workflow/components/model/process",
      "core/wcm/components/page/v3/page",
      "cq/workflow/components/model/participant",
      "granite/ui/components/coral/foundation/page",
      "cq/experience-fragments/components/rootxf",
      "wcm/foundation/components/basicpage",
      "libs/cq/experience-fragments/components/xfpageonly",
    ],
    explanation:
      "The speech says a fragment master or variation uses the sling:resourceType cq/experience-fragments/components/xfpage, which falls back to the core page component through sling:resourceSuperType.",
  },
  {
    id: "wf-095",
    topic: "Experience Fragments Development and Tips",
    question: "Which selector requests the plain HTML rendition of an Experience Fragment for third-party consumption?",
    correctAnswers: [
      "Use the .plain. selector to request the plain HTML rendition",
      "The selector is .plain.",
      "Request plain HTML with .plain.html",
      "The speech says third-party plain HTML is requested with the .plain selector",
    ],
    incorrectAnswers: [
      "Use the .json exporter selector",
      "Use the .nocloudconfigs.json selector",
      "Use the .workflow selector",
      "Use the .targetoffer selector",
      "Use the .rewriter selector",
      "Use the .cfm selector",
      "Use the .editable selector",
      "Use the .args selector",
    ],
    explanation:
      "The speech says the plain HTML rendition is requested with the .plain. selector, for example master.plain.html, so third-party applications can read the fragment by URL.",
  },
  {
    id: "wf-096",
    topic: "Experience Fragments Development and Tips",
    question: "What does the plain HTML rendition rewrite in links and resource attributes?",
    correctAnswers: [
      "It adds protocol, host, and context path, and its links point to the publish instance",
      "The plain rendition rewrites resource attributes with protocol, host, and context path and points links to publish",
      "It rewrites src, href, action, and similar attributes so published URLs are absolute",
      "The speech says the plain HTML rendition makes rewritten links reference publish with full URL parts",
    ],
    incorrectAnswers: [
      "It strips all links and removes every src attribute",
      "It rewrites all links to the author instance only",
      "It converts every link into a GraphQL query reference",
      "It stores link values only in MetaDataMap entries",
      "It changes links only inside workflow inbox notifications",
      "It rewrites links only for Content Fragment JSON export",
      "It blocks all action attributes by default",
      "It leaves all resource URLs untouched and relative",
    ],
    explanation:
      "The speech says the plain HTML rendition adds protocol, host, and context path to src, href, and action attributes and attributes ending in -src or -href, and that links always reference the publish instance.",
  },
  {
    id: "wf-097",
    topic: "Experience Fragments Development and Tips",
    question: "How is the plain Experience Fragment rendition built, and what customization rule accompanies it?",
    correctAnswers: [
      "It is built by the Sling Rewriter pipeline, and you should overlay the configuration instead of editing /libs",
      "The plain rendition comes from the Sling Rewriter pipeline and its config should be overlaid, not edited in /libs",
      "Use the experience-fragments rewriter configuration and overlay it rather than changing /libs",
      "The speech ties the plain rendition to the Sling Rewriter pipeline and says to overlay the config",
    ],
    incorrectAnswers: [
      "It is built only by GraphQL and must be edited directly in /libs",
      "It is produced by Workflow REST API states and customized in /var",
      "It is generated by Repo Init scripts inside the core bundle",
      "It is created only by the Content Fragment Component exporter",
      "It is assembled by participant step dialogs in /apps",
      "It is generated by the mail server and modified in /etc",
      "It is a dispatcher-only feature with no AEM configuration",
      "It is built by Target and cannot be customized",
    ],
    explanation:
      "The speech says the plain rendition is built by the Sling Rewriter pipeline under the experience-fragments rewriter configuration and says to overlay the configuration rather than editing it in /libs.",
  },
  {
    id: "wf-098",
    topic: "Experience Fragments Development and Tips",
    question: "How can an Experience Fragment template be recognized by the Create wizard?",
    correctAnswers: [
      "Its resource type must inherit from cq/experience-fragments/components/xfpage and its name begin with experience-fragment, or Allowed Templates must be configured",
      "Recognition comes from xfpage inheritance plus an experience-fragment name, or from configured Allowed Templates",
      "The Create wizard recognizes the template by xfpage inheritance and naming, unless Allowed Templates are configured",
      "Use an xfpage-inheriting template named with the experience-fragment prefix, or configure Allowed Templates",
    ],
    incorrectAnswers: [
      "It is recognized only if the template lives under /libs and has no folder restrictions",
      "It must inherit from the workflow process component and have a name starting with participant",
      "It is recognized only after a runtime model Sync creates it under /var",
      "It must be exported to Target before the wizard can see it",
      "It requires a GraphQL schema name that starts with content-fragment",
      "It is recognized only when mail notifications are enabled",
      "It must be created from the Content Fragments console first",
      "It is recognized only if its folder matches /content/dam",
    ],
    explanation:
      "The speech says an Experience Fragment template must either inherit from cq/experience-fragments/components/xfpage and have a name beginning with experience-fragment, or Allowed Templates must be configured in the console.",
  },
  {
    id: "wf-099",
    topic: "Experience Fragments Development and Tips",
    question: "What extra development step applies to components that will be used inside Experience Fragments?",
    correctAnswers: [
      "Allow the components on the template with the content policy",
      "The extra step is enabling the components through the template's content policy",
      "Components follow normal practices, but they still must be allowed by the content policy",
      "For Experience Fragments, components need template permission through content policy",
    ],
    incorrectAnswers: [
      "They must be registered as WorkflowProcess services",
      "They must be added to the Workflow REST API models URL",
      "They must live only under /libs to render correctly",
      "They must be exported to Target before authors can use them",
      "They require a Content Fragment Model with one data element",
      "They must be added to the participant inbox group",
      "They are allowed automatically and never use content policies",
      "They require GraphQL persisted queries on the folder",
    ],
    explanation:
      "The speech says components used in fragments follow standard component practices, and the only extra step is allowing them on the template with the content policy.",
  },
  {
    id: "wf-100",
    topic: "Experience Fragments Development and Tips",
    question: "What does Export to Target do for an Experience Fragment?",
    correctAnswers: [
      "Export to Target sends the Experience Fragment to Adobe Target as an offer in HTML or JSON",
      "It exports the fragment to Adobe Target as an HTML or JSON offer",
      "The feature sends an Experience Fragment to Target as an offer",
      "The speech says Export to Target turns the fragment into a Target offer in HTML or JSON",
    ],
    incorrectAnswers: [
      "It converts the fragment into a Content Fragment Model",
      "It syncs the workflow runtime model under /var",
      "It stores the fragment only as a participant step dialog",
      "It publishes the fragment only as GraphQL schema metadata",
      "It turns the fragment into a launcher that watches repository events",
      "It replaces editable templates with static templates",
      "It persists all fragment data only in the WorkflowData MetaDataMap",
      "It creates a package filter.xml entry for the fragment paths",
    ],
    explanation:
      "The speech says Export to Target sends a fragment to Adobe Target as an offer, in HTML or JSON format.",
  },
]
