import type { TriviaQuestion } from "./trivia-types"

export const oakOpsQuestionsPartB: TriviaQuestion[] = [
  {
    id: "oak-051",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "Which three extra logs exist only for the Publish tier in AEM as a Cloud Service?",
    correctAnswers: [
      "The Publish-only logs are the Apache HTTPD access log, the Apache HTTPD error log, and the Dispatcher log",
      "Publish has three additional logs: Apache access, Apache error, and Dispatcher",
      "Those extra Publish-tier logs are Apache HTTPD access, Apache HTTPD error, and Dispatcher",
      "The speech lists Apache access log, Apache error log, and Dispatcher log as the three extra Publish logs",
    ],
    incorrectAnswers: [
      "The extra Publish logs are error.log, request.log, and access.log",
      "Only the CDN log, the request log, and the audit log exist on Publish",
      "Publish adds replication.log, workflow.log, and cache.log",
      "The three Publish-only logs are stdout.log, stderr.log, and gc.log",
      "The extra logs are Author access, Author error, and MongoDB logs",
      "Publish provides query.log, indexing.log, and package.log",
      "The additional logs are traffic.log, security.log, and dispatcher.any",
      "Only Apache rewrite.log, replication.log, and vanity.log are added on Publish",
    ],
    explanation:
      "Section 8 says the Publish tier has three more logs before AEM application logging: the Apache HTTPD access log, the Apache HTTPD error log, and the Dispatcher log.",
  },
  {
    id: "oak-052",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "How is the mod_rewrite error log level configured in Cloud Service Dispatcher?",
    correctAnswers: [
      "Set REWRITE_LOG_LEVEL in conf.d/variables/global.var",
      "The mod_rewrite log level is controlled by the REWRITE_LOG_LEVEL variable in conf.d/variables/global.var",
      "Use REWRITE_LOG_LEVEL inside global.var under conf.d/variables to set rewrite logging",
      "Rewrite logging is configured with REWRITE_LOG_LEVEL in conf.d/variables/global.var",
    ],
    incorrectAnswers: [
      "Set DISP_LOG_LEVEL in conf.dispatcher.d/enabled_farms/default.farm",
      "Change org.apache.sling.commons.log.level in logs/error.log",
      "Edit the CDN JSON schema to set rewrite verbosity",
      "Set REWRITE_TRACE in dispatcher.any",
      "Configure mod_rewrite only from the Cloud Manager UI, not from source",
      "Add RewriteLogLevel to /oak:index/diff.index",
      "Use CQ-Action-Scope in the flush agent transport",
      "Place the rewrite level in ui.apps under /etc/map",
    ],
    explanation:
      "The source states that the Apache error log level for mod_rewrite is set with REWRITE_LOG_LEVEL in conf.d/variables/global.var.",
  },
  {
    id: "oak-053",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "What is the maximum mod_rewrite log level supported in the cloud?",
    correctAnswers: [
      "debug",
      "The maximum rewrite log level in the cloud is debug",
      "Cloud Service allows mod_rewrite up to debug",
      "For rewrite logging in the cloud, debug is the highest supported level",
    ],
    incorrectAnswers: [
      "trace8",
      "trace1",
      "info",
      "warn",
      "error",
      "fatal",
      "verbose",
      "notice",
    ],
    explanation:
      "Section 8 says REWRITE_LOG_LEVEL values run from error through trace8, but the maximum supported in the cloud is debug.",
  },
  {
    id: "oak-054",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "Which variable sets the Dispatcher log level in Cloud Service?",
    correctAnswers: [
      "DISP_LOG_LEVEL",
      "The Dispatcher log level is set with DISP_LOG_LEVEL",
      "Use DISP_LOG_LEVEL to control Dispatcher logging",
      "Dispatcher logging is configured through the DISP_LOG_LEVEL variable",
    ],
    incorrectAnswers: [
      "REWRITE_LOG_LEVEL",
      "AEM_LOG_LEVEL",
      "CDN_LOG_LEVEL",
      "HTTP_ACCESS_LEVEL",
      "OAK_LOG_LEVEL",
      "REPLICATION_LOG_LEVEL",
      "TRACE_LOG_LEVEL",
      "LOG_MANAGER_LEVEL",
    ],
    explanation:
      "The speech explicitly says the Dispatcher log level is set with DISP_LOG_LEVEL in the same global.var file.",
  },
  {
    id: "oak-055",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "What helpful details do Dispatcher log lines show for a request?",
    correctAnswers: [
      "They show the farm and an action such as miss or none",
      "Dispatcher log lines identify the farm plus an action like miss or none",
      "The log includes the farm name and an action, for example miss or none",
      "You can see the farm and actions such as miss or none in Dispatcher log entries",
    ],
    incorrectAnswers: [
      "They show the MongoDB replica set and journal sequence number",
      "They list only the Java package name and thread dump",
      "They contain only the CDN cache key and browser cookie values",
      "They show Author permissions and workflow launcher IDs only",
      "They include only the Oak query plan without request details",
      "They list replication agent passwords and SSL certificates",
      "They show only dispatcher.any line numbers with no request context",
      "They contain only CRX package install timestamps",
    ],
    explanation:
      "Section 8 says Dispatcher log lines show the farm and an action such as miss or none, which helps explain why a request reached AEM.",
  },
  {
    id: "oak-056",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "What values can appear in the CDN log cache field?",
    correctAnswers: [
      "HIT, MISS, or PASS",
      "The CDN cache field uses HIT, MISS, and PASS",
      "Possible cache values in the CDN log are HIT, MISS, and PASS",
      "The speech says the CDN log cache field can be HIT, MISS, or PASS",
    ],
    incorrectAnswers: [
      "STALE, FRESH, or PURGED",
      "CACHE, BYPASS, or STORE",
      "ALLOW, DENY, or SKIP",
      "AUTHOR, PUBLISH, or PREVIEW",
      "SYNC, ASYNC, or NRT",
      "ACTIVE, IDLE, or BLOCKED",
      "OPEN, CLOSED, or RETRY",
      "READ, WRITE, or EXECUTE",
    ],
    explanation:
      "The CDN log is described as JSON with fields such as timestamp, ttfb, status, url, and cache, where cache is HIT, MISS, or PASS.",
  },
  {
    id: "oak-057",
    topic: "Apache, Dispatcher and CDN Logs",
    question: "How are cloud logs made available to engineers?",
    correctAnswers: [
      "They can be downloaded through Cloud Manager or tailed with the Adobe I/O CLI",
      "Logs are available by Cloud Manager download and Adobe I/O command-line tailing",
      "Use Cloud Manager to download logs, or tail them with the Adobe I/O CLI",
      "The speech says logs are exposed through Cloud Manager downloads and Adobe I/O CLI tailing",
    ],
    incorrectAnswers: [
      "They are available only from CRX DE Lite on Publish",
      "They can be read only by attaching directly to the pod file system",
      "They are sent only by email once per day from Author",
      "They are accessible only from the Dispatcher SDK Docker container",
      "They are exposed only as OSGi console attachments",
      "They can be viewed only by editing org.apache.sling.commons.log.LogManager",
      "They are available only from MongoDB oplog tailing",
      "They require package installation through the Package Manager first",
    ],
    explanation:
      "Section 8 says logs are available either by downloading them through Cloud Manager or by tailing them with the Adobe I/O command line interface.",
  },
  {
    id: "oak-058",
    topic: "Replication Fundamentals",
    question: "What are replication agents used for according to the speech?",
    correctAnswers: [
      "They publish content from Author to Publish, flush Dispatcher cache, and return user input from Publish to Author",
      "Replication agents handle Author-to-Publish delivery, Dispatcher cache flushes, and reverse user-input flow back to Author",
      "The speech says replication agents are used for publishing content, flushing Dispatcher, and returning user data from Publish to Author",
      "They move content to Publish, invalidate Dispatcher cache, and support reverse replication of user input",
    ],
    incorrectAnswers: [
      "They choose whether Oak uses TarMK or MongoMK at startup",
      "They compile Lucene indexes during Cloud Manager builds",
      "They replace Apache and Dispatcher with direct CDN publishing",
      "They synchronize user data between all environments by default",
      "They store all binaries in MongoDB replica sets",
      "They rotate logs and change Sling log formats per request",
      "They generate vanity URLs and virtual host aliases automatically",
      "They create OSGi run modes for stage and production",
    ],
    explanation:
      "Section 9 defines replication agents as the mechanism for publishing content from Author to Publish, flushing Dispatcher cache, and returning user input from Publish to Author.",
  },
  {
    id: "oak-059",
    topic: "Replication Fundamentals",
    question: "In Author-to-Publish replication, what does the default replication agent do before content reaches Publish?",
    correctAnswers: [
      "It packages the content and places it in the replication queue",
      "The default agent bundles the content and enqueues it",
      "Before transport, the agent packages the content and puts it into the replication queue",
      "It prepares the content as a package and stores it in the queue for delivery",
    ],
    incorrectAnswers: [
      "It edits the Publish repository directly without a queue",
      "It converts the page into a MongoDB oplog entry",
      "It writes the content straight into the CDN cache and skips Publish",
      "It disables the page status indicator until a restart",
      "It replicates users and groups ahead of the page content",
      "It stores the page as a static file in Dispatcher before Author sends it",
      "It renames the content path to bin/receive before transport",
      "It changes all queries to SQL-2 so Publish can accept the package",
    ],
    explanation:
      "The speech says a publish request is passed to the default replication agent, which packages the content and places it in the replication queue.",
  },
  {
    id: "oak-060",
    topic: "Replication Fundamentals",
    question: "Which servlet receives replicated content on Publish by default?",
    correctAnswers: [
      "bin/receive",
      "The default servlet is bin/receive",
      "Replicated content is received by the Publish servlet at bin/receive",
      "On Publish, the default replication receiver endpoint is bin/receive",
    ],
    incorrectAnswers: [
      "dispatcher/invalidate.cache",
      "bin/replicate",
      "system/console",
      "libs/granite/dispatcher/content/vanityUrls.html",
      "oak:index",
      "bin/querybuilder.json",
      "content/dam/receive",
      "crx/de/index.jsp",
    ],
    explanation:
      "Section 9 states that a servlet on Publish receives the content and that the default servlet is bin/receive.",
  },
  {
    id: "oak-061",
    topic: "Replication Fundamentals",
    question: "Which data is explicitly not replicated between Author and Publish?",
    correctAnswers: [
      "User data such as users, groups, and profiles",
      "Users, groups, and profiles are not replicated",
      "The speech says user data like users, groups, and profiles is not replicated between Author and Publish",
      "Replication does not transfer users, groups, or profile data between Author and Publish",
    ],
    incorrectAnswers: [
      "Page content under /content",
      "Dispatcher flush requests",
      "Workflow models",
      "Replication queue metadata",
      "Binary assets in DAM",
      "OSGi run mode folders",
      "Lucene index definitions",
      "Apache virtual host aliases",
    ],
    explanation:
      "The source explicitly says that user data such as users, groups, and profiles is not replicated between Author and Publish.",
  },
  {
    id: "oak-062",
    topic: "Replication Fundamentals",
    question: "How does reverse replication return data from Publish to Author?",
    correctAnswers: [
      "The Publish agent puts data in an outbox, and Author listeners poll the outboxes",
      "Reverse replication uses an outbox on Publish and polling listeners on Author",
      "Data is placed into a Publish outbox, then replication listeners on Author poll it",
      "Author controls the reverse flow by polling outboxes created on Publish",
    ],
    incorrectAnswers: [
      "Publish opens inbound connections to Author and pushes data directly",
      "Dispatcher writes reverse replication into .stat files for Author to read",
      "MongoDB secondaries stream reverse data into TarMK standby nodes",
      "The CDN posts reverse data to /dispatcher/invalidate.cache",
      "Author sends all reverse data through the preview agent automatically",
      "Reverse replication is done by copying request.log to Author every minute",
      "Publish sends reverse data only through AEM Communities common store",
      "Apache mod_rewrite rewrites reverse data into request headers",
    ],
    explanation:
      "Section 9 says reverse replication works by having the agent on Publish place data in an outbox, while replication listeners on Author poll the outboxes.",
  },
  {
    id: "oak-063",
    topic: "Replication Fundamentals",
    question: "What is the default state of reverse replication since AEM 6.1?",
    correctAnswers: [
      "It is effectively disabled by default",
      "Since AEM 6.1, reverse replication is effectively disabled by default",
      "The default is that reverse replication is disabled in practice",
      "Reverse replication has been effectively off by default since 6.1",
    ],
    incorrectAnswers: [
      "It is the only replication mode enabled by default",
      "It is mandatory for all Publish tiers and cannot be turned off",
      "It is supported only for preview and never for publish",
      "It automatically replaces Dispatcher flush agents",
      "It is enabled only when MongoMK is chosen",
      "It runs only on Author and never touches Publish",
      "It is required for all user and group synchronization",
      "It is configured only through Cloud Manager pipelines",
    ],
    explanation:
      "The speech says reverse replication is effectively disabled by default since AEM 6.1.",
  },
  {
    id: "oak-064",
    topic: "Replication Fundamentals",
    question: "How is AEM Communities user-generated content handled?",
    correctAnswers: [
      "It is never replicated; a common store is used instead",
      "For AEM Communities, user-generated content uses a common store rather than replication",
      "The speech says Communities content is not replicated and relies on a common store",
      "UGC in AEM Communities is kept in a shared common store, not replicated between instances",
    ],
    incorrectAnswers: [
      "It is replicated only through the Static Agent into the file system",
      "It is always reverse-replicated from Author to Publish first",
      "It is copied to the CDN log so authors can replay it",
      "It is pushed into Dispatcher cache and becomes the source of truth",
      "It is synchronized only by Cold Standby repository replication",
      "It is stored only in request.log and re-imported nightly",
      "It is packaged into /oak:index during deployment",
      "It is replicated only when the preview agent is enabled",
    ],
    explanation:
      "Section 9 explicitly says that for AEM Communities, user-generated content is never replicated and a common store is used instead.",
  },
  {
    id: "oak-065",
    topic: "Replication Agents and Queues in 6.5",
    question: "Which agents are part of a standard AEM 6.5 installation?",
    correctAnswers: [
      "The Default Agent, Dispatcher Flush, Reverse Replication, and the Static Agent",
      "A standard 6.5 setup includes Default Agent, Dispatcher Flush, Reverse Replication, and Static Agent",
      "The speech lists four standard agents: Default Agent, Dispatcher Flush, Reverse Replication, and Static Agent",
      "In 6.5, the out-of-the-box agents are Default Agent, Dispatcher Flush, Reverse Replication, and Static Agent",
    ],
    incorrectAnswers: [
      "Publish Agent, Preview Agent, CDN Flush Agent, and Query Agent",
      "TarMK Agent, MongoMK Agent, Lucene Agent, and Solr Agent",
      "Workflow Agent, Package Manager Agent, Oak Run Agent, and Outbox Agent",
      "Author Agent, Publish Agent, Stage Agent, and Production Agent",
      "HTTP Agent, HTTPS Agent, WebSocket Agent, and S3 Agent",
      "Replication Listener, Cluster Sync, Index Sync, and Log Sync",
      "Default Agent, Search Agent, OSGi Agent, and Vault Agent",
      "Dispatcher Flush, Preview Agent, Mongo Agent, and WAF Agent",
    ],
    explanation:
      "Section 10 says a standard 6.5 installation has the Default Agent for Author to Publish, Dispatcher Flush, Reverse Replication, and the Static Agent.",
  },
  {
    id: "oak-066",
    topic: "Replication Agents and Queues in 6.5",
    question: "What do the queue states Active, Idle, and Blocked mean?",
    correctAnswers: [
      "Active means items are being processed, Idle means the queue is empty, and Blocked means items are queued but cannot be processed",
      "A queue is Active while processing, Idle when empty, and Blocked when items cannot be processed",
      "The speech defines Active as processing, Idle as empty, and Blocked as queued but not processable",
      "Active, Idle, and Blocked map to processing work, no work, and queued work that cannot move forward",
    ],
    incorrectAnswers: [
      "Active means the agent is disabled, Idle means the agent is deleted, and Blocked means SSL is optional",
      "Active means Publish is down, Idle means Author is down, and Blocked means CDN is down",
      "Active means the queue uses MongoMK, Idle means TarMK, and Blocked means Lucene",
      "Active means request logging is on, Idle means access logging is on, and Blocked means error logging is on",
      "Active means cache hit, Idle means cache miss, and Blocked means cache pass",
      "Active means the queue is persisted, Idle means fully published, and Blocked means preview-only",
      "Active means fewer than 100 paths, Idle means 500 paths, and Blocked means above 10 MB",
      "Active means path-based vhosts, Idle means host-based, and Blocked means no rewrite rules",
    ],
    explanation:
      "The source defines Active, Idle, and Blocked exactly in terms of processing items, emptiness, and queued items that cannot be processed.",
  },
  {
    id: "oak-067",
    topic: "Replication Agents and Queues in 6.5",
    question: "What is the default Retry Delay for a replication agent in AEM 6.5?",
    correctAnswers: [
      "60000 milliseconds",
      "The default Retry Delay is 60000 ms",
      "By default, Retry Delay is set to 60000 milliseconds",
      "The speech gives 60000 milliseconds as the default Retry Delay",
    ],
    incorrectAnswers: [
      "6000 milliseconds",
      "15000 milliseconds",
      "30000 milliseconds",
      "90000 milliseconds",
      "120000 milliseconds",
      "500 milliseconds",
      "10 milliseconds",
      "60000 seconds",
    ],
    explanation:
      "Section 10 says agent settings include Retry Delay with a default of 60000 milliseconds.",
  },
  {
    id: "oak-068",
    topic: "Replication Agents and Queues in 6.5",
    question: "What access must the Agent User Id have, and what happens if it is left empty?",
    correctAnswers: [
      "It needs read access to all replicated paths on Author and create/write access on Publish; if empty, the system user is used",
      "The agent user must read replicated paths on Author and create plus write on Publish, or else AEM falls back to the system user when the field is empty",
      "Required permissions are read on Author and create/write on Publish, and an empty Agent User Id means the system user is used",
      "The speech says the Agent User Id needs Author read rights and Publish create/write rights, and if blank the system user is used",
    ],
    incorrectAnswers: [
      "It needs only administrator rights on Cloud Manager, and empty means anonymous",
      "It needs write access only on Author, and empty means the preview agent is selected",
      "It requires MongoDB primary access, and empty disables retries",
      "It needs no repository permissions if Dispatcher Flush serialization is chosen",
      "It must have read access only on Publish, and empty uses the CDN service account",
      "It requires package install permissions under /etc/packages, and empty blocks the queue",
      "It needs only Apache file-system access, and empty uses localhost",
      "It must be a named end user account, and empty throws ReplicationException immediately",
    ],
    explanation:
      "The source specifies that the Agent User Id must have read access to all replicated paths on Author and create/write access on Publish, and if it is empty the system user is used.",
  },
  {
    id: "oak-069",
    topic: "Replication Agents and Queues in 6.5",
    question: "Which log levels are available for a replication agent, and what is the default?",
    correctAnswers: [
      "Error, Info, and Debug, with Info as the default",
      "The available agent log levels are Error, Info, and Debug, and the default is Info",
      "Replication agents support Error, Info, and Debug; Info is the default",
      "Info is the default among the agent log levels Error, Info, and Debug",
    ],
    incorrectAnswers: [
      "Trace, Warn, and Fatal, with Warn as the default",
      "Only Debug and Trace are available, with Trace as the default",
      "Error, Warn, Info, Debug, and Trace8, with Error as the default",
      "Only Info is allowed and it cannot be changed",
      "Pass, Miss, and None, with Miss as the default",
      "Active, Idle, and Blocked, with Idle as the default",
      "Low, Medium, and High, with Medium as the default",
      "Author, Publish, and Preview, with Publish as the default",
    ],
    explanation:
      "Section 10 states that the agent Log Level options are Error, Info, and Debug, and that Info is the default.",
  },
  {
    id: "oak-070",
    topic: "Replication Agents and Queues in 6.5",
    question: "What endpoint does the Default Agent's URI point to?",
    correctAnswers: [
      "bin/receive",
      "For a Default Agent, the URI points to bin/receive",
      "The Default Agent transport URI targets bin/receive",
      "A Default Agent sends to the bin/receive endpoint",
    ],
    incorrectAnswers: [
      "dispatcher/invalidate.cache",
      "bin/querybuilder.json",
      "crx/de/index.jsp",
      "system/console/configMgr",
      "oak:index/diff.index",
      "content/dam",
      "libs/granite/ui/content",
      "bin/distribute",
    ],
    explanation:
      "The speech says the Transport tab holds the URI, and for a Default Agent that URI points to bin/receive.",
  },
  {
    id: "oak-071",
    topic: "Replication Agents and Queues in 6.5",
    question: "When do path-based virtual hosts affect the Dispatcher Flush agent URI?",
    correctAnswers: [
      "With path-based virtual hosts, the URI chooses which farm is invalidated",
      "The flush agent URI selects the invalidated farm when virtual hosts are path-based",
      "In path-based virtual host setups, the URI determines which farm gets invalidated",
      "The speech says the URI matters for farm selection only when path-based virtual hosts are used",
    ],
    incorrectAnswers: [
      "Whenever the queue is Active, the URI changes the retry delay",
      "Only with hostname-based virtual hosts does the URI pick the farm",
      "The URI never affects farm selection and is just documentation",
      "Path-based virtual hosts make the URI choose the Author cluster",
      "The URI is used only to set the Apache rewrite log level",
      "The URI selects the MongoDB secondary node for replication",
      "Path-based virtual hosts make the URI define the agent user permissions",
      "The URI matters only for reverse replication outboxes",
    ],
    explanation:
      "Section 10 says that with path-based virtual hosts, the Dispatcher Flush agent URI chooses which farm is invalidated.",
  },
  {
    id: "oak-072",
    topic: "Replication in Cloud Service",
    question: "What mechanism does AEM as a Cloud Service use to move content for replication?",
    correctAnswers: [
      "Sling Content Distribution to a pipeline service outside the AEM runtime",
      "Cloud Service uses Sling Content Distribution and sends content to a pipeline service outside runtime",
      "The speech says replication in Cloud Service goes through Sling Content Distribution to an external pipeline service",
      "Content is moved by Sling Content Distribution rather than classic in-runtime replication delivery",
    ],
    incorrectAnswers: [
      "Direct TarMK repository copying between Author and Publish pods",
      "MongoDB oplog streaming into each Publish container",
      "A static file sync from Dispatcher docroot back to Author",
      "CRX package installation on every Publish pod by hand",
      "A CDN webhook that writes directly into /content",
      "Oak Traversal Index walking nodes across instances",
      "Apache mod_rewrite posting pages to bin/receive",
      "A reverse replication outbox as the primary Cloud Service transport",
    ],
    explanation:
      "Section 11 says AEM as a Cloud Service uses Sling Content Distribution to move content to a pipeline service outside the AEM runtime.",
  },
  {
    id: "oak-073",
    topic: "Replication in Cloud Service",
    question: "What are the two predefined Cloud Service distribution agents and their default state?",
    correctAnswers: [
      "The publish agent is enabled by default, and the preview agent exists but is not enabled by default",
      "Cloud Service has a default-enabled publish agent and a preview agent that is off by default",
      "The two predefined agents are publish and preview; only publish is enabled by default",
      "The speech says publish is on by default, while preview is predefined but not enabled by default",
    ],
    incorrectAnswers: [
      "The predefined agents are author and stage, and both are enabled by default",
      "The predefined agents are default and static, and both are disabled by default",
      "Cloud Service has only a preview agent, which is always enabled",
      "The predefined agents are replication and invalidation, and neither can be disabled",
      "The agents are TarMK and MongoMK, and one is selected at deployment time",
      "The predefined agents are Dispatcher Flush and Reverse Replication, both enabled by default",
      "The only built-in agent is publish, and preview must be installed from Package Manager",
      "The publish and preview agents are both enabled only in production",
    ],
    explanation:
      "Section 11 says there are two predefined agents: publish, which is enabled by default, and preview, which is not enabled by default.",
  },
  {
    id: "oak-074",
    topic: "Replication in Cloud Service",
    question: "Where are Cloud Service distribution agents monitored?",
    correctAnswers: [
      "Tools, Deployment, Distribution",
      "They are monitored from Tools > Deployment > Distribution",
      "Use the Tools, Deployment, Distribution area to monitor the agents",
      "The speech points to Tools, Deployment, Distribution for monitoring",
    ],
    incorrectAnswers: [
      "CRX DE Lite under /var/distribution",
      "The Dispatcher SDK validator output only",
      "The Apache access log viewer in Cloud Manager",
      "The MongoDB replica set dashboard",
      "Tools, Operations, Indexes",
      "Package Manager under /etc/packages",
      "The CDN JSON log schema editor",
      "OSGi Web Console Agents tab",
    ],
    explanation:
      "The source says the publish and preview agents are monitored from Tools, Deployment, Distribution.",
  },
  {
    id: "oak-075",
    topic: "Replication in Cloud Service",
    question: "What is the recommended way to handle bulk publishing in Cloud Service?",
    correctAnswers: [
      "Use a workflow with the Tree Activation step",
      "For bulk publishing, the speech recommends a workflow that uses Tree Activation",
      "Bulk activation should use Tree Activation in a workflow instead of custom bulk code",
      "The recommended bulk-publish approach is a workflow containing the Tree Activation step",
    ],
    incorrectAnswers: [
      "Write custom code that loops over every path one by one as the preferred approach",
      "Use the deprecated Publish Content Tree workflow because it is the recommended option",
      "Enable reverse replication and let Publish send content back to Author for activation",
      "Deploy content only by changing Dispatcher rules, not by workflow",
      "Use package installation through CRX Package Manager as the main bulk publishing method",
      "Create a custom CDN invalidation job instead of publishing content",
      "Use TarMK Cold Standby replication for bulk publication",
      "Place all paths into the request log so AEM can auto-activate them",
    ],
    explanation:
      "Section 11 says that for bulk publishing you should use a workflow with the Tree Activation step and that building your own bulk code is not recommended.",
  },
  {
    id: "oak-076",
    topic: "Replication in Cloud Service",
    question: "What happens when the Replication API is used without an agent filter?",
    correctAnswers: [
      "It uses only the agents enabled by default, which means publish",
      "Without a filter, replication targets the default-enabled agents, so it goes to publish",
      "The speech says no filter means only default-enabled agents are used, namely publish",
      "Replicating without an AgentFilter sends content through the default-enabled publish agent",
    ],
    incorrectAnswers: [
      "It always targets preview first and publish second",
      "It broadcasts to every possible agent, including disabled ones",
      "It disables status updates until Tree Activation finishes",
      "It chooses Reverse Replication as the default transport",
      "It sends content directly to the CDN instead of the publish tier",
      "It uses only the static agent from classic 6.5",
      "It throws a ReplicationException unless preview is enabled",
      "It targets Author itself so the queue can be persisted locally",
    ],
    explanation:
      "The source states that replicating without a filter uses only the agents enabled by default, which means the publish agent.",
  },
  {
    id: "oak-077",
    topic: "Replication in Cloud Service",
    question: "How do you target the preview tier with the Replication API?",
    correctAnswers: [
      "Pass ReplicationOptions with an AgentFilter",
      "To target preview, provide ReplicationOptions and set an AgentFilter",
      "Preview replication requires ReplicationOptions with an AgentFilter instead of the default behavior",
      "The speech says preview is targeted by passing ReplicationOptions that include an AgentFilter",
    ],
    incorrectAnswers: [
      "Set the action type to DEACTIVATE and the API will infer preview",
      "Omit ReplicationOptions so preview is picked automatically",
      "Change the servlet path from bin/receive to dispatcher/invalidate.cache",
      "Target preview by editing org.apache.sling.commons.log.LogManager",
      "Use only the request log pair ID to route to preview",
      "Add preview paths to /oak:index and AEM will publish them to preview",
      "Switch the Author persistence from TarMK to MongoMK first",
      "Enable reverse replication and preview is selected automatically",
    ],
    explanation:
      "Section 11 explains that to target preview you pass ReplicationOptions with an AgentFilter.",
  },
  {
    id: "oak-078",
    topic: "Replication in Cloud Service",
    question: "What do the two Cloud Service agent queues mean?",
    correctAnswers: [
      "Persisted means the change is durably stored on the publish tier, and Fully published means it is live on all publish pods and Dispatcher cache has been cleared",
      "The Persisted queue means durable storage on publish, while Fully published means all publish pods are live and Dispatcher invalidation is complete",
      "Persisted is durable publish-tier storage; Fully published means all pods have the change and the relevant Dispatcher cache paths were cleared",
      "The speech defines Persisted as safely stored on publish and Fully published as live everywhere on publish with cache cleared",
    ],
    incorrectAnswers: [
      "Persisted means the change is stored on Author, and Fully published means it reached preview only",
      "Persisted means the queue is idle, and Fully published means it is blocked",
      "Persisted means the CDN returned HIT, and Fully published means it returned MISS",
      "Persisted means the content was written to MongoDB, and Fully published means TarMK copied it",
      "Persisted means the Dispatcher log level is saved, and Fully published means rewrite debug is enabled",
      "Persisted means binaries exceeded 10 MB, and Fully published means fewer than 100 paths were sent",
      "Persisted means a replication listener polled an outbox, and Fully published means reverse replication finished",
      "Persisted means the preview agent is enabled, and Fully published means the publish agent is disabled",
    ],
    explanation:
      "The source says each Cloud Service agent shows two queues: Persisted for durable storage on the publish tier, and Fully published for content live on all publish pods with Dispatcher cache cleared for the paths.",
  },
  {
    id: "oak-079",
    topic: "Persistence and Topologies in 6.5",
    question: "What is Adobe's default persistence recommendation starting with AEM 6.2?",
    correctAnswers: [
      "Use TarMK as the default in all deployments except specific cases",
      "Adobe recommends TarMK by default for both Author and Publish unless there is a specific exception",
      "The speech says TarMK is the default recommendation across deployments, with exceptions for special cases",
      "TarMK is the recommended default persistence choice, not MongoMK, in normal deployments",
    ],
    incorrectAnswers: [
      "Always choose MongoMK for both Author and Publish",
      "Use Cold Standby as the default persistence manager",
      "Select Solr as the default repository backend",
      "Use a common store on Publish as the standard persistence choice",
      "Pick MongoMK for Publish and TarMK for Author in every deployment",
      "Use Elasticsearch directly as the default persistence layer",
      "Always deploy active-active Authors on MongoDB regardless of load",
      "Use the Traversal Index instead of a persistence manager",
    ],
    explanation:
      "Section 12 says that starting with AEM 6.2, Adobe recommends TarMK as the default in all deployments for both Author and Publish, except for specific cases.",
  },
  {
    id: "oak-080",
    topic: "Persistence and Topologies in 6.5",
    question: "Which statement best describes a single TarMK instance?",
    correctAnswers: [
      "It is one instance on one server, simple and fast, but not scalable beyond that server and without failover",
      "A single TarMK is a one-server setup that is simple and performant but offers no failover and no horizontal scalability",
      "The speech describes single TarMK as the default for Author: one instance, fast and simple, yet not scalable beyond the server and with no failover",
      "Single TarMK means one server hosting one instance, with simplicity and speed but no failover or scale beyond that machine",
    ],
    incorrectAnswers: [
      "It is several active Authors sharing a MongoDB replica set",
      "It is the default Publish topology with multiple independent Oak nodes",
      "It provides automatic failover through a standby promoted by Sling",
      "It requires two licenses because every instance must have a standby pair",
      "It is a cloud-only topology managed exclusively through preview agents",
      "It scales reads by having Author publish to multiple Publish members",
      "It stores all binaries directly in MongoDB for performance",
      "It is the same as Cold Standby except both nodes are active",
    ],
    explanation:
      "The source says a single TarMK instance is one instance on a single server, is the default for Author, and is simple and fast but has no failover and cannot scale beyond that server.",
  },
  {
    id: "oak-081",
    topic: "Persistence and Topologies in 6.5",
    question: "What is true about TarMK Cold Standby?",
    correctAnswers: [
      "A primary replicates its repository to a standby, failover is not automatic, and both instances need a license",
      "Cold Standby uses a primary and a standby, but failover must be detected externally and both nodes require licensing",
      "The speech says TarMK Cold Standby replicates to a standby with only the HTTP receiver running and does not provide automatic failover",
      "In Cold Standby, the repository is copied from primary to standby; failover is external and each instance needs a license",
    ],
    incorrectAnswers: [
      "Both nodes are active-active authors writing to the same MongoDB replica set",
      "The standby handles all incoming HTTP traffic while the primary is passive",
      "Cold Standby is the default Publish farm in 6.5",
      "It eliminates the need for a backup because the standby cannot store repository data",
      "Failover is automatic and managed by the replication queue",
      "Only the primary needs a license because the standby is free",
      "Cold Standby sends user-generated content to a common store instead of replicating",
      "The standby node runs all authoring services except the HTTP receiver",
    ],
    explanation:
      "Section 12 says TarMK Cold Standby replicates the primary repository to a standby, the standby runs only the HTTP receiver, failover is not automatic, and both instances need a license.",
  },
  {
    id: "oak-082",
    topic: "Persistence and Topologies in 6.5",
    question: "Why is a TarMK Farm the default for Publish?",
    correctAnswers: [
      "It uses several independent TarMK Oak instances, scales reads, and provides failover",
      "A TarMK Farm is multiple independent TarMK-based Oak instances kept in sync by Author publishing to each member, which gives read scaling and failover",
      "The speech says TarMK Farm is the default Publish topology because it scales reads and provides failover",
      "Publish defaults to a TarMK Farm because independent TarMK nodes can be synchronized through Author publication and serve traffic resiliently",
    ],
    incorrectAnswers: [
      "It gives active-active Author editing across a shared MongoDB cluster",
      "It removes the need for replication because Publish writes back to Author",
      "It works only with reverse replication enabled by default",
      "It requires a single server and therefore scales vertically only",
      "It depends on the CDN storing repository segments",
      "It uses one standby node with only the HTTP receiver running",
      "It is chosen because TarMK cannot be used for Publish otherwise",
      "It stores the entire repository in Apache log files for faster reads",
    ],
    explanation:
      "The source says a TarMK Farm consists of several independent Oak instances with TarMK, kept in sync because Author publishes the same content to each member, and that it scales reads and gives failover.",
  },
  {
    id: "oak-083",
    topic: "Persistence and Topologies in 6.5",
    question: "How is an Oak cluster with MongoMK characterized?",
    correctAnswers: [
      "Several Author instances access a MongoDB replica set in an active-active topology that scales Author horizontally and provides high availability",
      "MongoMK clustering means multiple active Authors share a MongoDB replica set for horizontal scaling and HA",
      "The speech describes MongoMK as an active-active Author cluster backed by a MongoDB replica set",
      "With MongoMK, several Author nodes use one MongoDB replica set, gaining Author scale and high availability",
    ],
    incorrectAnswers: [
      "One Publish instance writes directly to a TarMK standby over HTTP",
      "Several Publish nodes share a single Tar segment store on the CDN",
      "It is the default persistence setup for every small Author environment",
      "MongoMK is a cache invalidation protocol for Dispatcher farms",
      "It disables failover because only one Author may be active",
      "It uses Lucene analyzers as the repository backend",
      "It is a Publish-only topology and cannot be used on Author",
      "It stores the data store inside MongoDB as the recommended default",
    ],
    explanation:
      "Section 12 says an Oak cluster with MongoMK has several Author instances accessing a MongoDB replica set, works active-active, scales Author horizontally, and provides high availability.",
  },
  {
    id: "oak-084",
    topic: "Persistence and Topologies in 6.5",
    question: "When does the speech say MongoMK on Author should be considered?",
    correctAnswers: [
      "When Author load is very high, such as thousands of named users a day, hundreds of concurrent users, or very large daily asset ingestion, edits, or searches",
      "Choose MongoMK on Author for high-scale scenarios like thousands of named users, hundreds of concurrent users, or hundreds of thousands of ingestions or edits per day",
      "The speech recommends MongoMK for Author when the usage profile reaches large numbers of users, concurrent activity, ingestions, edits, or searches",
      "MongoMK is for scalability cases with very high daily user, edit, ingestion, or search volumes on Author",
    ],
    incorrectAnswers: [
      "Whenever there is a single simple Author server with low traffic",
      "Only when you want better Publish cache hit ratio",
      "For any site that uses Dispatcher Flush agents",
      "Only when reverse replication is enabled by default",
      "When the main need is faster mod_rewrite debugging",
      "Any time the repository includes Lucene indexes",
      "Only when the CDN log cache field returns PASS",
      "As soon as you need one custom index under /oak:index",
    ],
    explanation:
      "The source gives MongoMK selection criteria as large-scale Author demands, including thousands of named users a day, hundreds of concurrent users, hundreds of thousands of ingestions or edits a day, and tens of thousands of searches a day.",
  },
  {
    id: "oak-085",
    topic: "Persistence and Topologies in 6.5",
    question: "What minimal MongoDB topology is recommended for a MongoMK Author setup?",
    correctAnswers: [
      "A replica set with one primary and two secondaries under 15 ms latency, plus an Author cluster with two active nodes",
      "The minimal topology is one MongoDB primary, two MongoDB secondaries, latency under 15 milliseconds, and two active Author nodes",
      "The speech calls for a MongoDB replica set of one primary and two secondaries with sub-15 ms latency and an Author cluster of two active nodes",
      "For MongoMK, use a one-primary/two-secondary replica set with latency below 15 ms and two active Authors",
    ],
    incorrectAnswers: [
      "A single standalone MongoDB node with one passive Author and no latency target",
      "Two TarMK Publish nodes and one CDN worker under 50 ms latency",
      "One primary and one secondary MongoDB node with a Cold Standby Author",
      "Three primary MongoDB nodes and one Author server with no shared data store",
      "A replica set with one primary and five secondaries, but only one inactive Author",
      "One MongoDB primary with Author and Publish both mounted on the same local disk only",
      "Two primary nodes, no secondaries, and latency under 150 ms",
      "A Solr cluster with two active Authors and no MongoDB replica set",
    ],
    explanation:
      "Section 12 says the minimal MongoDB topology is a replica set with one primary and two secondaries with latency under 15 milliseconds, along with an Author cluster of two active nodes.",
  },
  {
    id: "oak-086",
    topic: "Cloud Service Architecture and Operations",
    question: "What architectural shift does AEM as a Cloud Service make?",
    correctAnswers: [
      "It moves from instance-centric to service-based, using n-x AEM containers driven by Cloud Manager CI/CD pipelines",
      "Cloud Service shifts from named instances to a service-based model with n-x AEM containers managed by Cloud Manager pipelines",
      "The speech says AEM goes from instance-centric to service-based architecture with n-x containers and Cloud Manager CI/CD",
      "AEM as a Cloud Service replaces instance-centric thinking with service-based n-x containers under Cloud Manager",
    ],
    incorrectAnswers: [
      "It moves from cloud services back to a single fixed on-premise TarMK server",
      "It replaces Cloud Manager with manual CRX Package Manager deployments",
      "It changes from service-based to instance-centric so each pod is hand-managed",
      "It eliminates containers and runs only as a monolithic JVM on the CDN",
      "It requires every customer to choose MongoMK or TarMK for each environment",
      "It replaces CI/CD with manual Dispatcher cache invalidation only",
      "It shifts all traffic directly from browser to AEM without Apache or Dispatcher",
      "It stores all code changes only in the request log rather than in Git",
    ],
    explanation:
      "Section 13 says AEM as a Cloud Service moves from an instance-centric model to a service-based one with n-x AEM containers driven by Cloud Manager CI/CD pipelines.",
  },
  {
    id: "oak-087",
    topic: "Cloud Service Architecture and Operations",
    question: "What platform choices are no longer managed directly by customers in Cloud Service?",
    correctAnswers: [
      "Customers do not choose TarMK or MongoMK, do not manage Author clusters or Publish farms themselves, and the publish tier scales automatically",
      "In Cloud Service you no longer pick TarMK versus MongoMK or manage Author and Publish topologies yourself",
      "The speech says customers do not manage Author clusters or Publish farms and do not choose the persistence model; Publish auto-scales",
      "Cloud Service removes direct control over TarMK/MongoMK selection and manual cluster or farm management, while Publish scales automatically",
    ],
    incorrectAnswers: [
      "Customers must manually choose the microkernel and size every Publish farm by hand",
      "Customers manage only MongoDB but Adobe manages TarMK",
      "Customers still hand-build Cold Standby failover and preview agents for each pod",
      "Persistence selection moves into dispatcher.any and is edited per farm",
      "Customers must manually scale publish pods through CRX DE Lite",
      "Author clusters are still required to be configured in OSGi run modes",
      "The CDN chooses TarMK or MongoMK based on cache HIT ratio",
      "Only log levels are platform-managed; all topologies remain fully customer-managed",
    ],
    explanation:
      "Section 13 says customers do not choose TarMK or MongoMK and do not manage Author clusters or Publish farms themselves; the publish tier scales automatically.",
  },
  {
    id: "oak-088",
    topic: "Cloud Service Architecture and Operations",
    question: "Which kinds of changes must be deployed through Cloud Manager in AEM as a Cloud Service?",
    correctAnswers: [
      "Code, OSGi configurations, Dispatcher configuration, log configuration, and index definitions",
      "Cloud Manager deploys code plus OSGi, Dispatcher, log, and index-definition changes",
      "The speech lists code, OSGi configs, Dispatcher config, log config, and index definitions as pipeline-deployed artifacts",
      "Those platform-managed changes all go through Cloud Manager: code, OSGi config, Dispatcher config, log config, and index definitions",
    ],
    incorrectAnswers: [
      "Only Java classes; OSGi, Dispatcher, logs, and indexes are edited live in production",
      "Only CDN log schemas and browser cookies",
      "Only replication queue content and user profiles",
      "Only MongoDB replica set members and TarMK segment files",
      "Only request.log and access.log retention settings",
      "Only Dispatcher Flush agent passwords and outboxes",
      "Only preview content and reverse replication listeners",
      "Only Author page content, because configuration is never source-controlled",
    ],
    explanation:
      "The source says code, OSGi configurations, Dispatcher configuration, log configuration, and index definitions are all deployed through Cloud Manager.",
  },
  {
    id: "oak-089",
    topic: "Cloud Service Architecture and Operations",
    question: "Why are production configuration changes outside the pipeline a problem in Cloud Service?",
    correctAnswers: [
      "Because configuration changes in production that bypass the pipeline break the CI/CD policy",
      "Bypassing Cloud Manager for production configuration changes violates the CI/CD policy",
      "The speech says direct production config edits are a problem because they break CI/CD policy",
      "Cloud Service expects production configuration to go through the pipeline, so bypassing it breaks policy",
    ],
    incorrectAnswers: [
      "Because the CDN immediately deletes all cached content after any production change",
      "Because Author can no longer save content after a manual config update",
      "Because manual changes automatically convert TarMK into MongoMK",
      "Because the only effect is losing access to preview, not policy compliance",
      "Because Cloud Service allows only request.log changes to bypass the pipeline",
      "Because pipeline bypasses are required to update Lucene indexes",
      "Because the Dispatcher SDK validator refuses to run in local development afterward",
      "Because reverse replication depends on live production edits outside Git",
    ],
    explanation:
      "Section 13 explicitly says that configuration changes in production that bypass the pipeline break the CI/CD policy.",
  },
  {
    id: "oak-090",
    topic: "Cloud Service Architecture and Operations",
    question: "What is true about indexes during a rolling deployment in Cloud Service?",
    correctAnswers: [
      "Old and new versions run side by side for a time, so two sets of indexes exist, and the new version is built and reindexed before the traffic switch",
      "Rolling deployment means two versions coexist temporarily, two index sets exist, and the new indexes are built before traffic switches",
      "The speech says rolling deployments keep old and new versions side by side, with the new index built and repositories reindexed before cutover",
      "During rolling deployment, there are separate old and new indexes until the new version is ready and traffic is switched",
    ],
    incorrectAnswers: [
      "There is always only one index set, and it is edited live in place during the cutover",
      "Indexes are ignored during rolling deployments because only CDN changes matter",
      "Rolling deployments require customers to rebuild Elasticsearch indexes manually",
      "Traffic switches first, and the new indexes are built afterward on demand",
      "Old indexes are deleted before the new deployment starts to save time",
      "Only preview receives new indexes; publish keeps the old ones indefinitely",
      "Rolling deployments apply only to TarMK Author, not to Cloud Service",
      "The request log, not Cloud Manager, shows index status during deployment",
    ],
    explanation:
      "The source says rolling deployments run the old and new version side by side, so two index sets exist, and the new version's indexes are built and repositories reindexed before the traffic switch.",
  },
  {
    id: "oak-091",
    topic: "Cloud Service Architecture and Operations",
    question: "Why can checking only AEM logs miss a request in Cloud Service?",
    correctAnswers: [
      "Because traffic flows from the CDN to Apache and Dispatcher on Publish and then to AEM, and a request may be answered earlier in that chain",
      "A request can be handled by the CDN or Apache/Dispatcher before it reaches AEM, so AEM logs alone may miss it",
      "The speech says each layer in the chain has its own log, so earlier handling by CDN or Dispatcher may keep the request out of AEM logs",
      "Since traffic passes through CDN and Apache/Dispatcher first, only checking AEM logs can miss requests resolved upstream",
    ],
    incorrectAnswers: [
      "Because AEM logs are disabled whenever the CDN returns MISS",
      "Because requests go directly from browser to AEM with no other layers involved",
      "Because AEM logs record only Author traffic and never Publish traffic",
      "Because request IDs are stored only in MongoDB and not in logs",
      "Because Apache and Dispatcher write into the same logs/error.log file as AEM",
      "Because AEM deletes logs after every successful response",
      "Because only preview requests appear in AEM logs",
      "Because Cloud Manager blocks AEM logging during rolling deployments",
    ],
    explanation:
      "Section 13 says traffic flows CDN to Apache and Dispatcher to AEM, and each layer has its own log, so AEM logs alone can miss a request answered earlier in the chain.",
  },
  {
    id: "oak-092",
    topic: "Cloud Service Architecture and Operations",
    question: "What runtime operational support does the speech mention for Cloud Service customers?",
    correctAnswers: [
      "SREs monitor system health around the clock, and customers can set up alerts and see metrics including search performance",
      "The platform is watched 24/7 by SREs, while customers can configure alerts and view runtime metrics such as search performance",
      "The speech says SREs monitor health continuously and customers get alerts and metrics, including search performance",
      "Cloud Service operations include round-the-clock SRE monitoring plus customer-visible alerts and runtime metrics",
    ],
    incorrectAnswers: [
      "Customers must monitor every pod manually because Adobe provides no metrics",
      "Only the CDN is monitored; AEM itself has no health coverage",
      "Metrics are available only during local Dispatcher SDK runs",
      "Search performance cannot be monitored at runtime in Cloud Service",
      "Only reverse replication queues are monitored by SREs",
      "Customers can set alerts only for Cold Standby failover, not for search performance",
      "Runtime monitoring is limited to request.log downloads once per week",
      "SREs monitor only stage environments and not production",
    ],
    explanation:
      "The source says SREs monitor system health around the clock, and customers can set up alerts and see runtime metrics, including search performance.",
  },
  {
    id: "oak-093",
    topic: "Troubleshooting and Exam Tips",
    question: "What log clue should make you suspect a slow Oak query?",
    correctAnswers: [
      "A WARN message saying Oak traversed nodes and suggesting an index or query change",
      "Look for the WARN about traversed nodes, which indicates the query ran without a suitable index",
      "The speech says a slow query clue is the WARN log that many nodes were traversed",
      "A traversed-nodes WARN message is the sign that a suitable index is missing or the query should change",
    ],
    incorrectAnswers: [
      "A HIT entry in the CDN cache field",
      "An Apache access log line with status 200",
      "An Active replication queue on Author",
      "A Fully published status in Cloud Service",
      "A warning that the preview agent is enabled",
      "A mod_rewrite debug line in global.var",
      "An access.log entry showing response size",
      "A message that request and response IDs were paired successfully",
    ],
    explanation:
      "Section 14 says that for a slow query, you should look for the WARN message about traversed nodes and then create a suitable Lucene index.",
  },
  {
    id: "oak-094",
    topic: "Troubleshooting and Exam Tips",
    question: "How should a slow-query index fix be handled in AEM as a Cloud Service?",
    correctAnswers: [
      "Deploy a suitable Lucene index through the pipeline with the correct custom name instead of editing the repository by hand",
      "In the cloud, fix it by deploying the Lucene index via Cloud Manager using the proper custom naming pattern",
      "The speech says to create the right Lucene index and deploy it through the pipeline, not by hand on the repository",
      "For Cloud Service, use a correctly named custom Lucene index delivered through the pipeline rather than live repository edits",
    ],
    incorrectAnswers: [
      "Open the repository on the running instance and edit oak:index directly by hand",
      "Switch the environment from TarMK to MongoMK to speed up the query immediately",
      "Raise the default Sling root logger to DEBUG permanently and leave the query unchanged",
      "Delete all existing indexes so Oak is forced to rebuild them in place",
      "Convert the index to elasticsearch and configure it directly as a customer",
      "Only clear the Dispatcher cache because indexing does not affect query speed",
      "Move the query into the CDN so it no longer needs an index",
      "Use the request log pair ID to suppress the traversal warning",
    ],
    explanation:
      "The troubleshooting section says that in the cloud you deploy the suitable Lucene index through the pipeline with the correct custom name and do not edit the repository by hand.",
  },
  {
    id: "oak-095",
    topic: "Troubleshooting and Exam Tips",
    question: "If a custom index is not being used in the cloud, what broad checklist does the speech recommend?",
    correctAnswers: [
      "Check the custom naming pattern and prefix, confirm type lucene and async, verify includedPaths and tags, and verify allowIndexDefinitions, noIntermediateSaves, and the vault filter",
      "The checklist covers the name pattern, lucene type, async value, includedPaths, tags, deployment flags like allowIndexDefinitions and noIntermediateSaves, and the vault filter",
      "You should verify naming, lucene plus async settings, includedPaths and tags, and the packaging settings such as allowIndexDefinitions, noIntermediateSaves, and the vault filter",
      "The speech says to inspect the custom/versioned name and prefix, lucene and async configuration, path and tag settings, and the relevant project packaging flags and filter",
    ],
    incorrectAnswers: [
      "Check only whether the CDN cache field shows HIT and ignore the index definition itself",
      "Verify only the replication agent password because indexing depends on bin/receive",
      "Inspect only MongoDB replica set latency because index usage is unrelated to configuration",
      "Look only at request.log IDs because Cloud Service always ignores index names",
      "Confirm the Author license count and Cold Standby state first",
      "Check only Apache ServerAlias values and rewrite rules",
      "Edit org.apache.sling.commons.log.LogManager and set it to DEBUG permanently",
      "Delete Dispatcher cache files because index usage depends on .stat timestamps only",
    ],
    explanation:
      "Section 14 lists a checklist for unused custom indexes that includes naming, type and async, includedPaths and tags, allowIndexDefinitions and noIntermediateSaves, and the vault filter.",
  },
  {
    id: "oak-096",
    topic: "Troubleshooting and Exam Tips",
    question: "Where should you look in the cloud to troubleshoot specific request and cache behaviors?",
    correctAnswers: [
      "Use the AEM Java log for application code, the request log to pair requests and responses, the access log to follow a user, the Dispatcher log for miss or none, the Apache error log for rewrite rules, and the CDN log for HIT, MISS, and PASS",
      "The speech maps logs as follows: Java log for application code, request log for request-response pairing, access log for following a user, Dispatcher log for miss or none, Apache error log for rewrites, and CDN log for HIT/MISS/PASS",
      "Check Java log for app code, request log for paired request/response IDs, access log for user flow, Dispatcher for miss or none, Apache error for rewrite rules, and CDN for cache HIT, MISS, or PASS",
      "For cloud troubleshooting, use the six-way mapping from the speech: Java, request, access, Dispatcher, Apache error, and CDN logs for their respective roles",
    ],
    incorrectAnswers: [
      "Use only error.log because all cloud request, cache, and rewrite information is merged there",
      "Look only at the CDN log because AEM and Dispatcher logs are not useful in Cloud Service",
      "Use the MongoDB replica set logs for cache hits and Apache rewrite analysis",
      "Check only CRX Package Manager because request and response pairing is stored there",
      "Use the replication queue screen to find rewrite-rule matches and CDN cache status",
      "Check the Author OSGi console for HIT, MISS, PASS, and request-response IDs",
      "Use only the Dispatcher SDK validator because runtime logs do not show these details",
      "Look at the preview agent monitor because it replaces access and request logs",
    ],
    explanation:
      "The troubleshooting section gives an explicit log map: Java log for app code, request log for paired requests and responses, access log to follow a user, Dispatcher for miss or none, Apache error for rewrites, and CDN for HIT/MISS/PASS.",
  },
  {
    id: "oak-097",
    topic: "Troubleshooting and Exam Tips",
    question: "What cloud logging defaults should not be changed, and how should DEBUG be used?",
    correctAnswers: [
      "Do not change the default INFO level, the log format, or the logs/error.log destination; raise a package to DEBUG only temporarily",
      "The speech says to keep default INFO, keep the default format and logs/error.log target, and use DEBUG for a package only for a short time",
      "Never change the root INFO setting, the format, or the logs/error.log file in the cloud, and restore any temporary DEBUG increase afterward",
      "Cloud logging rules are to preserve INFO, format, and logs/error.log, while using package-level DEBUG sparingly and temporarily",
    ],
    incorrectAnswers: [
      "Switch the default root level to DEBUG in production and keep it there for troubleshooting",
      "Change the main log destination from logs/error.log to request.log whenever a bug appears",
      "Rewrite the log pattern in org.apache.sling.commons.log.LogManager during every deployment",
      "Use DEBUG globally because package-level logging is not supported",
      "Disable INFO logs entirely and log only rewrites in the CDN log",
      "Move all AEM logging into the Apache access log for consistency",
      "Change the format in production so request IDs are easier to read",
      "Keep DEBUG permanently on all product packages after an incident",
    ],
    explanation:
      "Section 14 repeats the cloud logging guidance: never change the default INFO level, the format, or the logs/error.log destination, and use DEBUG only temporarily for a package.",
  },
  {
    id: "oak-098",
    topic: "Troubleshooting and Exam Tips",
    question: "What are common reasons for a blocked publish queue, and what should you inspect?",
    correctAnswers: [
      "The receiving instance may be disabled or unreachable, or the agent user may lack permissions; check the agent log and the Retry Delay",
      "A blocked publish queue usually means the receiver is down or unreachable, or permissions are missing; inspect the agent log and Retry Delay",
      "The speech says blocked queues come from an unreachable or disabled receiver or insufficient agent-user rights, and you should review the agent log plus Retry Delay",
      "Typical blocked-queue causes are connectivity or permission problems, and the things to check are the agent log and Retry Delay",
    ],
    incorrectAnswers: [
      "It always means the CDN returned HIT and no content can be published",
      "It happens only when TarMK is used instead of MongoMK",
      "A blocked queue proves the preview agent is enabled by default",
      "The only cause is that the Java log level is still INFO",
      "It means the request log is not configurable in the cloud",
      "A blocked queue occurs only when fewer than 100 paths are replicated",
      "It shows that reverse replication is active and healthy",
      "The fix is always to delete the Apache access log first",
    ],
    explanation:
      "The troubleshooting section says a blocked publish queue means the receiving instance is disabled or unreachable, or the agent user lacks permissions, and it tells you to check the agent log and Retry Delay.",
  },
  {
    id: "oak-099",
    topic: "Troubleshooting and Exam Tips",
    question: "What replication call limits does the speech ask you to remember for Cloud Service?",
    correctAnswers: [
      "Replicate fewer than 100 paths at a time, 500 is the hard limit, and content per call must not exceed 10 MB",
      "The remembered limits are under 100 paths per call, 500 maximum paths, and 10 MB of content per call",
      "Cloud Service replication guidance is fewer than 100 paths ideally, 500 absolute max, and no more than 10 MB per call",
      "The speech highlights three numbers: less than 100 paths per call, a 500-path cap, and a 10 MB content limit",
    ],
    incorrectAnswers: [
      "Use at least 1000 paths per call, with no size limit if binaries are excluded",
      "The key numbers are 15 paths, 60 paths, and 600 MB",
      "There is no path limit as long as the preview agent is disabled",
      "The limits are 10 paths, 50 paths, and 1 MB",
      "Only latency under 15 ms matters; there are no path or size limits",
      "You must send exactly 100 paths and exactly 10 MB every time",
      "The hard limit is 50 paths and 100 MB per call",
      "The limits apply only to Dispatcher invalidation, not to replication",
    ],
    explanation:
      "Section 14 repeats the Cloud Service replication numbers: fewer than 100 paths at a time, a limit of 500, and 10 MB of content per call.",
  },
  {
    id: "oak-100",
    topic: "Troubleshooting and Exam Tips",
    question: "Which defaults does the speech tell you to remember for topology, replication, and logging?",
    correctAnswers: [
      "Author is a single TarMK, Publish is a TarMK farm, TarMK is for performance, MongoMK is for scalability, only the publish agent is on by default in the cloud, and Dispatcher plus rewrite logs default to warn",
      "Remember these defaults: single-TarMK Author, TarMK-farm Publish, TarMK for performance, MongoMK for scalability, publish agent enabled by default in the cloud, and warn as the Dispatcher and rewrite log default",
      "The speech's defaults summary is Author single TarMK, Publish TarMK farm, TarMK equals performance, MongoMK equals scalability, cloud publish agent on by default, and warn for Dispatcher and rewrite logs",
      "You should remember the baseline defaults for Author, Publish, persistence tradeoff, cloud publish-agent behavior, and warn-level Dispatcher/rewrite logging",
    ],
    incorrectAnswers: [
      "Author defaults to MongoMK, Publish defaults to Cold Standby, preview is enabled by default, and rewrite logs default to debug",
      "Both Author and Publish default to active-active MongoMK, with reverse replication enabled and log defaults at error",
      "Author defaults to TarMK farm, Publish to a single TarMK, and Dispatcher logs default to trace8",
      "The defaults are preview-only publishing, Solr for scalability, and INFO disabled in the cloud",
      "Publish defaults to single TarMK with no auto-scaling, and rewrite logs default to trace1",
      "Author defaults to a CDN-managed repository, Publish to MongoDB, and Dispatcher defaults to pass",
      "The default is static-agent publishing only, with Apache error logs at debug in production",
      "TarMK is for scalability, MongoMK is for performance, and both publish and preview agents are enabled by default",
    ],
    explanation:
      "The final exam-tips section tells you to remember those defaults: single TarMK for Author, TarMK farm for Publish, TarMK for performance, MongoMK for scalability, only publish enabled by default in the cloud, and warn as the default for Dispatcher and rewrite logs.",
  },
]
