import type { TriviaQuestion } from "./trivia-types"

export const oakOpsQuestionsPartA: TriviaQuestion[] = [

  // ── 1 INTRODUCTION (7) ───────────────────────────────────────────────────

  {
    id: "oak-001",
    topic: "Introduction",
    question: "What four operational areas does the introduction say this lesson covers?",
    correctAnswers: [
      "It covers how Oak finds content with indexes, how AEM writes logs, how content moves from Author to Publish with replication, and how AEM instances are arranged in a topology",
      "The four areas are Oak indexes, AEM logging, replication from Author to Publish, and AEM topology",
      "The introduction says the lesson covers indexes, logs, replication, and topologies",
      "It is about how Oak finds content with indexes, how AEM writes logs, how content moves with replication, and how instances are arranged in a topology",
    ],
    incorrectAnswers: [
      "It covers editable templates, content fragments, translation projects, and MSM live copies",
      "The four areas are package installation, user synchronization, SPA Editor, and GraphQL persisted queries",
      "The introduction says the lesson covers workflows, launch promotion, XF localization, and user administration",
      "It is about Dispatcher flush rules, SSL certificates, IMS login, and CRX package replication only",
      "The four areas are Sling Models, HTL, client libraries, and component dialogs",
      "It covers tag management, permissions inheritance, content policies, and style systems",
      "The introduction says the lesson covers asset microservices, Dynamic Media, Smart Tags, and metadata schemas",
      "It is about servlet resolution, OSGi bundles, unit testing, and dispatcher cache invalidation only",
    ],
    explanation:
      "Section 1 says the lesson covers four operational areas: indexes, logs, replication, and topology.",
  },
  {
    id: "oak-002",
    topic: "Introduction",
    question: "Which exam area does this topic map to, and about what percentage does the speech assign to it?",
    correctAnswers: [
      "It maps to Analyzing and Debugging, about 18 percent of the exam",
      "The speech maps it to Analyzing and Debugging at roughly 18%",
      "The main exam area is Analyzing and Debugging, around eighteen percent",
      "It belongs to Analyzing and Debugging, about 18 percent of the exam",
    ],
    incorrectAnswers: [
      "It maps to Build and Deployment, about 18 percent of the exam",
      "The speech maps it to Environment Maintenance at roughly 18%",
      "The main exam area is Authoring, around eighteen percent",
      "It belongs to Security Administration, about 18 percent of the exam",
      "It maps to Analyzing and Debugging, about 13 percent of the exam",
      "The speech maps it to Components at roughly 25%",
      "The main exam area is Templates, around thirty percent",
      "It belongs to Workflows, about 8 percent of the exam",
    ],
    explanation:
      "The introduction explicitly says the topic maps to Analyzing and Debugging, about 18 percent of the exam.",
  },
  {
    id: "oak-003",
    topic: "Introduction",
    question: "Which second exam area is also named in the introduction, and at about what percentage?",
    correctAnswers: [
      "It also maps to Environment Maintenance, about 13 percent",
      "The second area named is Environment Maintenance at roughly 13%",
      "The speech also mentions Environment Maintenance, around thirteen percent",
      "Besides Analyzing and Debugging, it names Environment Maintenance at about 13 percent",
    ],
    incorrectAnswers: [
      "It also maps to Build and Deployment, about 13 percent",
      "The second area named is Authoring at roughly 13%",
      "The speech also mentions Environment Maintenance, around eighteen percent",
      "Besides Analyzing and Debugging, it names Components at about 13 percent",
      "It also maps to Configuration Browser, about 13 percent",
      "The second area named is Translation at roughly 13%",
      "The speech also mentions Editable Templates, around thirteen percent",
      "Besides Analyzing and Debugging, it names MSM at about 13 percent",
    ],
    explanation:
      "Section 1 says the topic also maps to Environment Maintenance, about 13 percent of the exam.",
  },
  {
    id: "oak-004",
    topic: "Introduction",
    question: "Why does the introduction say this lesson also supports Build and Deployment?",
    correctAnswers: [
      "Because index definitions and log configurations are deployed as code",
      "It supports Build and Deployment because index definitions and log settings are deployed as code",
      "The reason given is that index definitions and log configurations go through code deployment",
      "The speech says it supports Build and Deployment since index definitions and log configurations are deployed as code",
    ],
    incorrectAnswers: [
      "Because replication queues are edited manually on production publish nodes",
      "It supports Build and Deployment because topology choices are changed from the Touch UI",
      "The reason given is that user profiles are replicated as code packages",
      "The speech says it supports Build and Deployment since query statements are compiled into Java classes",
      "Because full-text analyzers can only be configured from CRXDE Lite in production",
      "It supports Build and Deployment because TarMK compaction is part of every pipeline",
      "The reason given is that CDN logs are generated by Cloud Manager build containers",
      "The speech says it supports Build and Deployment since reverse replication writes Maven POM files",
    ],
    explanation:
      "The introduction ties the lesson to Build and Deployment because index definitions and log configurations are deployed as code.",
  },
  {
    id: "oak-005",
    topic: "Introduction",
    question: "What kind of exam questions should you expect according to the introduction?",
    correctAnswers: [
      "Expect scenario questions",
      "The introduction says to expect scenario-based questions",
      "You should expect scenarios rather than only pure definitions",
      "The speech explicitly says to expect scenario questions",
    ],
    incorrectAnswers: [
      "Expect only coding exercises in Java",
      "The introduction says to expect only UI memorization questions",
      "You should expect only Maven command syntax questions",
      "The speech explicitly says to expect only essay questions",
      "Expect only regular-expression writing tasks",
      "The introduction says to expect only package manager walkthrough questions",
      "You should expect only OSGi PID copy-paste questions",
      "The speech explicitly says to expect only diagram labeling questions",
    ],
    explanation:
      "Section 1 warns that exam items in this area are scenario questions.",
  },
  {
    id: "oak-006",
    topic: "Introduction",
    question: "Which of these is one of the example scenario questions named in the introduction?",
    correctAnswers: [
      "Why is this query slow",
      "One example is: why is this query slow",
      "The speech includes a scenario asking why a query is slow",
      "An example given is the question, why is this query slow",
    ],
    incorrectAnswers: [
      "How do you create a content fragment model variation",
      "One example is: how do you author a live copy rollout config",
      "The speech includes a scenario asking how to add a Sling Model exporter annotation",
      "An example given is the question, how do you style a core component dialog",
      "How do you make a workflow participant step assign to a group",
      "One example is: how do you enable GraphQL persisted queries",
      "The speech includes a scenario asking how to create an XF localization root",
      "An example given is the question, how do you configure SPA Editor routing",
    ],
    explanation:
      "The introduction gives example scenario questions including why a query is slow.",
  },
  {
    id: "oak-007",
    topic: "Introduction",
    question: "When Experience Manager 6.5 documentation and Cloud Service documentation differ, what does the lesson say it will do?",
    correctAnswers: [
      "It will say which one applies",
      "The lesson says it will state which documentation applies",
      "It will explicitly tell you whether 6.5 or Cloud Service applies",
      "The speech says it will say which documentation applies when they differ",
    ],
    incorrectAnswers: [
      "It will always prefer the 6.5 documentation without comment",
      "The lesson says it will merge both versions into a single unsupported approach",
      "It will ignore the difference and focus only on on-premise deployments",
      "The speech says it will ask Cloud Manager to choose automatically",
      "It will always prefer the oldest documentation version available",
      "The lesson says it will replace both sets of docs with CRX package screenshots",
      "It will ignore both documents and use dispatcher.any comments instead",
      "The speech says it will default to Author behavior regardless of platform",
    ],
    explanation:
      "Section 1 says that where the 6.5 and Cloud Service documentation differ, the lesson will say which one applies.",
  },

  // ── 2 OAK QUERY ENGINE AND INDEXERS (7) ─────────────────────────────────

  {
    id: "oak-008",
    topic: "Oak Query Engine and Indexers",
    question: "Compared with Jackrabbit 2, what does the speech say about Oak indexing by default?",
    correctAnswers: [
      "Unlike Jackrabbit 2, Oak does not index content by default",
      "Oak does not index content by default, unlike Jackrabbit 2",
      "The speech says Oak is different from Jackrabbit 2 because it does not index content by default",
      "By default, Oak has no automatic content indexing in the way Jackrabbit 2 did",
    ],
    incorrectAnswers: [
      "Unlike Jackrabbit 2, Oak automatically creates Lucene indexes for all content by default",
      "Oak indexes every property and every full-text field by default",
      "The speech says Oak is different from Jackrabbit 2 because it always prefers Solr indexes out of the box",
      "By default, Oak enables custom indexing only for publish and not author",
      "Unlike Jackrabbit 2, Oak creates only traversal indexes and stores them on disk by default",
      "Oak indexes only cq:Page nodes by default and ignores everything else",
      "The speech says Oak behaves the same as Jackrabbit 2 and indexes content by default",
      "By default, Oak indexes content only after a manual Cloud Manager job",
    ],
    explanation:
      "Section 2 explicitly says Oak does not index content by default, unlike Jackrabbit 2.",
  },
  {
    id: "oak-009",
    topic: "Oak Query Engine and Indexers",
    question: "When should custom indexes be created according to the speech?",
    correctAnswers: [
      "Custom indexes must be created when necessary",
      "The speech says to create custom indexes when necessary",
      "They should be created only as needed",
      "Oak custom indexes are created when necessary, much like in a relational database",
    ],
    incorrectAnswers: [
      "Custom indexes must be created for every node type before any content is added",
      "The speech says to create custom indexes only after replication is blocked",
      "They should be created automatically by the request log",
      "Oak custom indexes are created only when Cloud Manager edits a running instance",
      "Custom indexes must be created for every query language whether needed or not",
      "The speech says to create custom indexes only for TarMK and never for Cloud Service",
      "They should be created only after enabling reverse replication",
      "Oak custom indexes are created automatically when request URIs contain a question mark",
    ],
    explanation:
      "Section 2 says custom indexes must be created when necessary, much like in a relational database.",
  },
  {
    id: "oak-010",
    topic: "Oak Query Engine and Indexers",
    question: "What happens if a query has no index?",
    correctAnswers: [
      "Many nodes may be traversed, and the query still works but is likely slow",
      "Without an index, Oak may traverse many nodes and the query still works, but it is likely slow",
      "The speech says a query without an index can still run, but many nodes may be traversed and it will likely be slow",
      "If there is no index, the query still works while Oak traverses many nodes and likely performs slowly",
    ],
    incorrectAnswers: [
      "The query is rejected immediately because Oak refuses to run queries without indexes",
      "Without an index, Oak automatically creates a property index before running the query",
      "The speech says a query without an index becomes a replication exception",
      "If there is no index, only full-text conditions keep working and property constraints fail",
      "The query is routed to the CDN log until a Lucene index appears",
      "Without an index, Oak uses reverse replication to fetch the results",
      "The speech says a query without an index runs only on publish and never on author",
      "If there is no index, the query is converted into JQOM and then cancelled",
    ],
    explanation:
      "Section 2 says a query without an index still works, but many nodes may be traversed so it is likely slow.",
  },
  {
    id: "oak-011",
    topic: "Oak Query Engine and Indexers",
    question: "What WARN message behavior does Oak show when it runs a query without an index?",
    correctAnswers: [
      "It logs a WARN saying it traversed a number of nodes and suggests creating an index or changing the query",
      "Oak prints a WARN that it traversed many nodes and suggests creating an index or changing the query",
      "The speech says the WARN message reports traversed nodes and recommends an index or a query change",
      "Without an index, Oak logs a WARN about traversed nodes and suggests creating an index or changing the query",
    ],
    incorrectAnswers: [
      "It logs a WARN saying the replication queue is blocked and suggests increasing Retry Delay",
      "Oak prints a WARN that the Dispatcher cache is stale and suggests a flush",
      "The speech says the WARN message reports missing binaries and recommends reverse replication",
      "Without an index, Oak logs a WARN about CDN traffic and suggests changing the WAF",
      "It logs a WARN saying the request log is not configurable and suggests editing access.log",
      "Oak prints a WARN that the root logger is DEBUG and suggests changing LogManager",
      "The speech says the WARN message reports MongoDB latency and recommends TarMK compaction",
      "Without an index, Oak logs a WARN about missing run modes and suggests changing config.prod",
    ],
    explanation:
      "Section 2 says Oak prints a WARN about traversed nodes and suggests creating an index or changing the query.",
  },
  {
    id: "oak-012",
    topic: "Oak Query Engine and Indexers",
    question: "Which query languages does the speech say the query engine supports, and which one is recommended?",
    correctAnswers: [
      "It supports XPath, SQL-2, the deprecated SQL, and JQOM, and XPath is recommended",
      "The supported languages named are XPath, SQL-2, deprecated SQL, and JQOM, with XPath recommended",
      "The speech lists XPath, SQL-2, deprecated SQL, and JQOM, and recommends XPath",
      "Oak supports XPath, SQL-2, deprecated SQL, and JQOM, and the recommended one is XPath",
    ],
    incorrectAnswers: [
      "It supports GraphQL, HTL, JSP, and JCR-SQL, and GraphQL is recommended",
      "The supported languages named are XPath, SQL-2, JavaScript, and Groovy, with SQL-2 recommended",
      "The speech lists only SQL-2 and Lucene syntax, and Lucene is recommended",
      "Oak supports REST queries, QueryBuilder JSON, and JSP EL, and REST is recommended",
      "It supports XPath, SQL-2, and GraphQL only, and JQOM is deprecated but recommended",
      "The supported languages named are XQuery, SQL-92, and QueryBuilder XML, with SQL recommended",
      "The speech lists only XPath and JQOM, and deprecated SQL is recommended",
      "Oak supports HTL expressions, Sling selectors, and SQL-2, and HTL is recommended",
    ],
    explanation:
      "Section 2 says the query engine supports XPath, SQL-2, deprecated SQL, and JQOM, and that XPath is recommended.",
  },
  {
    id: "oak-013",
    topic: "Oak Query Engine and Indexers",
    question: "Into what native language are queries ultimately transformed in Oak?",
    correctAnswers: [
      "They are transformed into SQL-2",
      "Oak transforms them into SQL-2, which is the native language",
      "The speech says SQL-2 is the native language that queries end up in",
      "Queries are parsed and then transformed into SQL-2",
    ],
    incorrectAnswers: [
      "They are transformed into XPath because it is the native language",
      "Oak transforms them into Lucene syntax, which is the native language",
      "The speech says JQOM is the native language that queries end up in",
      "Queries are parsed and then transformed into GraphQL",
      "They are transformed into dispatcher.any filter rules",
      "Oak transforms them into OSGi factory configurations",
      "The speech says deprecated SQL is the native language that queries end up in",
      "Queries are parsed and then transformed into MongoDB replica-set commands",
    ],
    explanation:
      "Section 2 says a query is parsed into an abstract syntax tree and then transformed into SQL-2, the native language of Oak.",
  },
  {
    id: "oak-014",
    topic: "Oak Query Engine and Indexers",
    question: "How does Oak choose among several indexers that can answer a query?",
    correctAnswers: [
      "Each indexer estimates cost, Oak picks the lowest-cost one, retrieves results, and then filters them for read access and full-query match",
      "Oak compares estimated cost, chooses the lowest-cost indexer, gets its results, and filters them for permissions and query correctness",
      "The speech says each indexer estimates cost, the lowest estimate wins, and the results are then filtered for access and full-query matching",
      "When multiple indexers apply, Oak selects the one with the lowest estimated cost and then filters the results for read access and complete query matching",
    ],
    incorrectAnswers: [
      "Oak always chooses Lucene first, then falls back to property indexes only if Lucene throws an error",
      "Oak selects the newest index definition alphabetically and never applies permission filtering afterward",
      "The speech says Oak picks the indexer with the largest repository footprint and skips access checks for speed",
      "When multiple indexers apply, Oak runs all of them and merges results without filtering",
      "Oak always chooses Traversal Index first because it guarantees exact matches",
      "Oak selects the indexer based only on the current run mode folder and not on cost",
      "The speech says Oak picks the indexer with the highest estimated cost because it is more complete",
      "When multiple indexers apply, Oak selects the one with the most analyzers and ignores read permissions",
    ],
    explanation:
      "Section 2 says each applicable indexer estimates cost, Oak picks the lowest estimated cost, and then filters results for read access and complete query matching.",
  },

  // ── 3 PROPERTY AND LUCENE INDEXES (7) ───────────────────────────────────

  {
    id: "oak-015",
    topic: "Property and Lucene Indexes",
    question: "Where are indexes configured, and what node type must an index definition use?",
    correctAnswers: [
      "Indexes are configured as nodes under oak:index, and the node type must be oak:QueryIndexDefinition",
      "They live under oak:index and must use the node type oak:QueryIndexDefinition",
      "The speech says index definitions are nodes under oak:index with node type oak:QueryIndexDefinition",
      "Index configuration goes under oak:index, and the required node type is oak:QueryIndexDefinition",
    ],
    incorrectAnswers: [
      "Indexes are configured under /apps, and the node type must be cq:PageContent",
      "They live under /var/index, and must use the node type nt:unstructured",
      "The speech says index definitions are nodes under /content with node type dam:Asset",
      "Index configuration goes under /libs, and the required node type is sling:Folder",
      "Indexes are configured under /conf, and the node type must be rep:Policy",
      "They live under /etc/indexes, and must use the node type oak:AsyncIndex",
      "The speech says index definitions are nodes under /oak:index but must use cq:Component",
      "Index configuration goes under /system/console, and the required node type is sling:OsgiConfig",
    ],
    explanation:
      "Section 3 says indexes are configured as nodes under oak:index, using node type oak:QueryIndexDefinition.",
  },
  {
    id: "oak-016",
    topic: "Property and Lucene Indexes",
    question: "What kind of queries does the Property Index suit, and which two properties define it?",
    correctAnswers: [
      "It suits property constraints that are not full-text, and it uses type set to property with propertyNames listing the properties",
      "The Property Index is for non-full-text property constraints, using type property and propertyNames",
      "The speech says Property Index fits property constraints rather than full-text, with type property and propertyNames",
      "For non-full-text property constraints, use a Property Index with type property and propertyNames",
    ],
    incorrectAnswers: [
      "It suits only full-text search, and it uses type lucene with async set to nrt",
      "The Property Index is for query traversal, using type traversal and costPerEntry",
      "The speech says Property Index fits CDN logs, with type json and propertyNames",
      "For non-full-text property constraints, use a Property Index with type elasticsearch and analyzers",
      "It suits only similarity search, and it uses useInSimilarity with feature vectors",
      "The Property Index is for replication queues, using type queue and propertyPaths",
      "The speech says Property Index fits only ordered sorting, with type ordered and docroot",
      "For non-full-text property constraints, use a Property Index with type property but no propertyNames",
    ],
    explanation:
      "Section 3 says the Property Index suits property constraints that are not full-text and uses type property with propertyNames.",
  },
  {
    id: "oak-017",
    topic: "Property and Lucene Indexes",
    question: "What do the unique flag, declaringNodeTypes, and reindex=true do on a Property Index?",
    correctAnswers: [
      "The unique flag adds a uniqueness constraint, declaringNodeTypes restricts the index to a node type, and reindex=true triggers a full reindex",
      "Unique enforces uniqueness, declaringNodeTypes narrows the node type, and reindex set to true starts a full reindex",
      "The speech says unique adds a uniqueness constraint, declaringNodeTypes restricts by node type, and reindex true triggers full reindexing",
      "On a Property Index, unique means uniqueness, declaringNodeTypes limits the node type, and reindex=true causes a full reindex",
    ],
    incorrectAnswers: [
      "The unique flag enables async updates, declaringNodeTypes chooses a run mode, and reindex=true enables CDN logging",
      "Unique controls request deduplication, declaringNodeTypes sets the document root, and reindex=true rotates logs",
      "The speech says unique adds full-text stemming, declaringNodeTypes enables Solr, and reindex true disables traversal",
      "On a Property Index, unique means use Elasticsearch, declaringNodeTypes limits access.log, and reindex=true clears dispatcher cache",
      "The unique flag adds a retry delay, declaringNodeTypes picks publish pods, and reindex=true pairs request IDs",
      "Unique configures virtual hosts, declaringNodeTypes selects farms, and reindex=true reloads vanity URLs",
      "The speech says unique disables full-text search, declaringNodeTypes adds a prefix, and reindex true makes the index synchronous",
      "On a Property Index, unique means lower cost, declaringNodeTypes sets analyzers, and reindex=true updates only changed nodes",
    ],
    explanation:
      "Section 3 defines these directly: unique adds a uniqueness constraint, declaringNodeTypes restricts the node type, and reindex=true triggers a full reindex.",
  },
  {
    id: "oak-018",
    topic: "Property and Lucene Indexes",
    question: "What does the speech say about the Ordered index?",
    correctAnswers: [
      "The Ordered index is deprecated and should be replaced with a Lucene Property Index",
      "It says the Ordered index is deprecated and should be replaced by Lucene Property Index",
      "The speech recommends replacing the deprecated Ordered index with a Lucene Property Index",
      "Ordered is deprecated, and the replacement named is Lucene Property Index",
    ],
    incorrectAnswers: [
      "The Ordered index is required in Cloud Service and should replace Lucene",
      "It says the Ordered index is the preferred index for full-text search",
      "The speech recommends replacing the Ordered index with Traversal Index",
      "Ordered is deprecated only on publish, but required on author",
      "The Ordered index is required for cqPageLucene customizations",
      "It says the Ordered index should be replaced by MongoMK",
      "The speech recommends keeping the Ordered index because Lucene cannot index properties",
      "Ordered is deprecated only when request logs are disabled",
    ],
    explanation:
      "Section 3 says the Ordered index is deprecated and should be replaced with a Lucene Property Index.",
  },
  {
    id: "oak-019",
    topic: "Property and Lucene Indexes",
    question: "Which two main settings does the Lucene full-text index use, and what delay tradeoff does the speech mention?",
    correctAnswers: [
      "It uses type lucene and async set to async, so some full-text results can be unavailable briefly after a change",
      "The Lucene full-text index uses type lucene with async=async, and updates happen on a background thread so results can lag briefly",
      "The speech says Lucene full-text uses type lucene and async async, which means a short window where fresh results may be unavailable",
      "Use type lucene and async set to async; because it is asynchronous, full-text results may not reflect a change immediately",
    ],
    incorrectAnswers: [
      "It uses type property and async set to sync, so results are always immediately visible",
      "The Lucene full-text index uses type elasticsearch with async disabled, and updates require manual rotation",
      "The speech says Lucene full-text uses type traversal and async warn, so results appear only after replication",
      "Use type lucene and async set to fulltext-async on 6.5, which guarantees no delay after a change",
      "It uses type property and propertyNames, so full-text conditions are routed to access.log",
      "The Lucene full-text index uses type lucene with async false, and all updates require a restart",
      "The speech says Lucene full-text uses type solr and async stage, so results appear only on publish",
      "Use type ordered and async async, which prevents any result lag after content changes",
    ],
    explanation:
      "Section 3 says the Lucene full-text index uses type lucene and async set to async, so some results can be briefly unavailable after changes.",
  },
  {
    id: "oak-020",
    topic: "Property and Lucene Indexes",
    question: "What does the speech say happens when a full-text index is configured, and what if none is configured?",
    correctAnswers: [
      "If a full-text index is configured, all queries with a full-text condition use it; if none is configured, full-text conditions do not work as expected",
      "Configured full-text queries use the full-text index, and without one full-text conditions do not work as expected",
      "The speech says every query with a full-text condition uses the configured full-text index, and without one those conditions do not behave as expected",
      "With a full-text index present, full-text conditions use it; without one, full-text conditions do not work as expected",
    ],
    incorrectAnswers: [
      "If a full-text index is configured, only SQL-2 queries use it; if none is configured, XPath still works the same",
      "Configured full-text queries use Traversal Index first, and without one Oak switches to replication queues",
      "The speech says every query with a full-text condition uses Property Index, and without one Lucene is auto-created",
      "With a full-text index present, only access log entries use it; without one request.log takes over",
      "If a full-text index is configured, only author uses it; if none is configured, publish uses Solr automatically",
      "Configured full-text queries are ignored by cost estimation, and without one they are routed to CDN logs",
      "The speech says every query with a full-text condition uses Ordered index, and without one they become unique constraints",
      "With a full-text index present, propertyNames are ignored; without one declaringNodeTypes fixes full-text behavior",
    ],
    explanation:
      "Section 3 says a configured full-text index is used for all queries with a full-text condition, and without one those conditions do not work as expected.",
  },
  {
    id: "oak-021",
    topic: "Property and Lucene Indexes",
    question: "How do you configure Lucene to index non-full-text property constraints, and what consistency note comes with it?",
    correctAnswers: [
      "Set fulltextEnabled to false and list the properties in includePropertyNames; a Lucene Property Index is always async, so results may lag behind the latest state",
      "For Lucene property constraints, use fulltextEnabled=false with includePropertyNames, and remember it is always async",
      "The speech says non-full-text Lucene property indexing uses fulltextEnabled false plus includePropertyNames, and because it is async the newest state may not be reflected immediately",
      "Configure Lucene property indexing with fulltextEnabled set to false and includePropertyNames, and expect asynchronous result lag",
    ],
    incorrectAnswers: [
      "Set fulltextEnabled to true and remove includePropertyNames; a Lucene Property Index is always synchronous",
      "For Lucene property constraints, use type property with no other flags, and it updates only during deployment",
      "The speech says non-full-text Lucene property indexing uses analyzers only, and results are always fully current",
      "Configure Lucene property indexing with useInSimilarity and feature vectors, and expect no async behavior",
      "Set fulltextEnabled to false and use propertyNames only; a Lucene Property Index is always traversal-based",
      "For Lucene property constraints, use declaringNodeTypes only, and it updates through reverse replication",
      "The speech says non-full-text Lucene property indexing uses async nrt on 6.5 only, and results are immediately current",
      "Configure Lucene property indexing with fulltextEnabled false and excludePropertyNames only, and expect synchronous writes",
    ],
    explanation:
      "Section 3 says Lucene can index non-full-text property constraints with fulltextEnabled=false and includePropertyNames, but it remains async.",
  },

  // ── 4 INDEX DEFINITIONS IN CLOUD SERVICE (7) ────────────────────────────

  {
    id: "oak-022",
    topic: "Index Definitions in Cloud Service",
    question: "How does the Cloud Service model change index configuration compared with single-instance thinking?",
    correctAnswers: [
      "In Cloud Service, index configuration is specified before deployment and not changed on a running instance",
      "The speech says Cloud Service moves index configuration to pre-deployment rather than editing a running instance",
      "You specify index configuration before a deployment instead of changing it on a live instance",
      "Cloud Service handles indexes as deployment-time configuration, not runtime instance edits",
    ],
    incorrectAnswers: [
      "In Cloud Service, indexes are configured only from the Index Manager on each running publish pod",
      "The speech says Cloud Service requires manual repository edits after every deployment",
      "You specify index configuration only after the deployment finishes and traffic switches",
      "Cloud Service handles indexes as browser-side configuration downloaded from the CDN",
      "In Cloud Service, indexes are configured by changing request.log on the active author node",
      "The speech says Cloud Service disables index deployment and uses only traversal",
      "You specify index configuration by editing MongoDB directly during runtime",
      "Cloud Service handles indexes as temporary files outside the pipeline",
    ],
    explanation:
      "Section 4 says index configuration in Cloud Service is specified before a deployment, not changed on a running instance.",
  },
  {
    id: "oak-023",
    topic: "Index Definitions in Cloud Service",
    question: "What does the speech say about user access to the Index Manager in Cloud Service?",
    correctAnswers: [
      "Users do not have access to the Index Manager of a single instance in the cloud",
      "In the cloud, users do not get access to a single-instance Index Manager",
      "The speech says the Index Manager is not available to users on Cloud Service instances",
      "Cloud Service users do not have access to the Index Manager on a running instance",
    ],
    incorrectAnswers: [
      "Users have full access to the Index Manager on every cloud publish pod",
      "In the cloud, users must use the Index Manager daily to finish deployments",
      "The speech says the Index Manager is the primary way customers customize Elasticsearch indexes directly",
      "Cloud Service users get access to the Index Manager only for preview tiers",
      "Users have full access to the Index Manager after enabling request.log debug",
      "In the cloud, users must use the Index Manager because Git deployment is not supported",
      "The speech says the Index Manager replaces Cloud Manager for index changes",
      "Cloud Service users get access to the Index Manager only when traversal warnings occur",
    ],
    explanation:
      "Section 4 says users do not have access to the Index Manager of a single instance in Cloud Service.",
  },
  {
    id: "oak-024",
    topic: "Index Definitions in Cloud Service",
    question: "What happens to indexes during a rolling deployment, and where can you see job completion?",
    correctAnswers: [
      "Two sets of indexes exist, one for the old version and one for the new version, and the Cloud Manager build page shows whether indexing is complete",
      "During rolling deployment there are old-version and new-version index sets, and completion is shown on the Cloud Manager build page",
      "The speech says rolling deployment keeps two index sets and the Cloud Manager build page reports indexing completion",
      "Cloud Service uses two sets of indexes during rolling deployment, and you check the Cloud Manager build page for completion",
    ],
    incorrectAnswers: [
      "A single shared index is edited in place, and completion appears only in error.log",
      "During rolling deployment all indexes are disabled, and completion is shown only in access.log",
      "The speech says rolling deployment deletes the old indexes first and completion appears in CRXDE Lite",
      "Cloud Service uses one set of indexes during rolling deployment, and you check request.log for completion",
      "Two sets of indexes exist only on author 6.5, and completion is shown in the replication queue",
      "A single shared index is rebuilt after the traffic switch, and completion appears in dispatcher.log",
      "The speech says rolling deployment merges indexes only on publish and completion appears in CDN logs",
      "Cloud Service uses no index build jobs, and you check the Sling LogManager factory config for completion",
    ],
    explanation:
      "Section 4 says that rolling deployments use two index sets and that the Cloud Manager build page shows whether the indexing job is complete.",
  },
  {
    id: "oak-025",
    topic: "Index Definitions in Cloud Service",
    question: "Which index type is supported for customer customization in Cloud Service?",
    correctAnswers: [
      "Only indexes of type lucene are supported for customization",
      "Cloud Service customization supports only lucene indexes",
      "The speech says only type lucene can be customized",
      "For customization in Cloud Service, the supported type is lucene only",
    ],
    incorrectAnswers: [
      "Only indexes of type property are supported for customization",
      "Cloud Service customization supports only elasticsearch indexes directly",
      "The speech says only type solr can be customized",
      "For customization in Cloud Service, the supported type is traversal only",
      "Only indexes of type ordered are supported for customization",
      "Cloud Service customization supports only ntBaseLucene indexes directly under /libs",
      "The speech says only type mongo can be customized",
      "For customization in Cloud Service, the supported type is property and ordered only",
    ],
    explanation:
      "Section 4 states that only indexes of type lucene are supported for customization in Cloud Service.",
  },
  {
    id: "oak-026",
    topic: "Index Definitions in Cloud Service",
    question: "Which async values are allowed for customized Cloud Service indexes?",
    correctAnswers: [
      "The async property can be async, async and nrt, or fulltext-async",
      "Allowed async values are async, async and nrt, and fulltext-async",
      "The speech lists async, async and nrt, and fulltext-async as the allowed values",
      "For Cloud Service customized indexes, async may be set to async, async and nrt, or fulltext-async",
    ],
    incorrectAnswers: [
      "The async property can be sync, immediate, or realtime",
      "Allowed async values are author, publish, and preview",
      "The speech lists warn, info, and debug as the allowed async values",
      "For Cloud Service customized indexes, async may be set to elastic, solr, or property",
      "The async property can be nrt only and never async",
      "Allowed async values are true, false, and auto",
      "The speech lists stage, prod, and dev as the allowed async values",
      "For Cloud Service customized indexes, async may be set to indexed, merged, or switched",
    ],
    explanation:
      "Section 4 names the allowed async values: async, async and nrt, or fulltext-async.",
  },
  {
    id: "oak-027",
    topic: "Index Definitions in Cloud Service",
    question: "Which two customization limitations does the speech call out about analyzers and similarity?",
    correctAnswers: [
      "Only standard product analyzers are supported, so custom analyzers are not, and useInSimilarity is not supported",
      "Cloud Service supports only standard shipped analyzers, not custom analyzers, and it does not support useInSimilarity",
      "The speech says custom analyzers are unsupported and useInSimilarity is also unsupported",
      "You can use only the standard analyzers that ship with the product, and useInSimilarity is not supported",
    ],
    incorrectAnswers: [
      "Only custom analyzers are supported, and useInSimilarity is required",
      "Cloud Service supports any analyzer from Lucene, including custom analyzers, and similarity is mandatory",
      "The speech says custom analyzers are supported only on preview and useInSimilarity only on author",
      "You can use only Elasticsearch analyzers configured directly by customers, and similarity search is the default",
      "Only stopword analyzers are supported, and useInSimilarity must be set to true",
      "Cloud Service supports custom analyzers after editing the Index Manager, and similarity is enabled by default",
      "The speech says analyzers are unsupported entirely and every query must use traversal",
      "You can use only deprecated SQL analyzers, and useInSimilarity controls request logging",
    ],
    explanation:
      "Section 4 says only standard shipped analyzers are supported, not custom analyzers, and useInSimilarity is not supported.",
  },
  {
    id: "oak-028",
    topic: "Index Definitions in Cloud Service",
    question: "Which project setup steps does the speech require for Cloud Service index definitions?",
    correctAnswers: [
      "Use filevault-package-maven-plugin 1.3.2 or later, add oak:index to immutableRootNodeNames, enable allowIndexDefinitions and noIntermediateSaves in ui.apps and ui.apps.structure, and add a filter for /oak:index in ui.apps.structure",
      "The setup includes filevault-package-maven-plugin version 1.3.2+, oak:index in immutableRootNodeNames, allowIndexDefinitions and noIntermediateSaves enabled, and a /oak:index filter in ui.apps.structure",
      "The speech requires plugin version 1.3.2 or later, oak:index added next to apps and libs in immutableRootNodeNames, allowIndexDefinitions and noIntermediateSaves enabled, plus a /oak:index filter",
      "Project setup for cloud indexes includes filevault-package-maven-plugin 1.3.2+, immutableRootNodeNames containing oak:index, allowIndexDefinitions and noIntermediateSaves, and a filter for /oak:index",
    ],
    incorrectAnswers: [
      "Use maven-bundle-plugin 1.0, add oak:index to clientlibs, disable allowIndexDefinitions, and remove every /oak:index filter",
      "The setup includes editing a running instance, using CRXDE Lite only, and omitting immutableRootNodeNames",
      "The speech requires plugin version 1.0, oak:index under /var only, and no filter in ui.apps.structure",
      "Project setup for cloud indexes includes Solr jars, reverse replication, and Dispatcher flush rules",
      "Use filevault-package-maven-plugin 1.2.0, add oak:index to access.log, and disable noIntermediateSaves",
      "The setup includes only request.log debug, no Maven plugin requirement, and editing Index Manager by hand",
      "The speech requires plugin version 1.3.2 or later but says never add a /oak:index filter",
      "Project setup for cloud indexes includes property indexes only, no immutableRootNodeNames, and no atomic landing",
    ],
    explanation:
      "Section 4 lists these setup requirements directly, including filevault-package-maven-plugin 1.3.2+, immutableRootNodeNames, allowIndexDefinitions, noIntermediateSaves, and the /oak:index filter.",
  },

  // ── 5 INDEX NAMES AND SIMPLIFIED INDEX MANAGEMENT (7) ───────────────────

  {
    id: "oak-029",
    topic: "Index Names and Simplified Index Management",
    question: "What three categories of indexes does the speech define?",
    correctAnswers: [
      "An out-of-the-box index, a customization of an out-of-the-box index, and a fully custom index",
      "The three categories are out-of-the-box, customized out-of-the-box, and fully custom indexes",
      "The speech groups indexes into out-of-the-box, OOTB customization, and fully custom",
      "It defines three categories: OOTB index, OOTB customization, and fully custom index",
    ],
    incorrectAnswers: [
      "A property index, a traversal index, and a replication index",
      "The three categories are author, publish, and preview indexes",
      "The speech groups indexes into Lucene, SQL-2, and XPath",
      "It defines three categories: request, access, and Java indexes",
      "A MongoMK index, a TarMK index, and a CDN index",
      "The three categories are cqPageLucene, request.log, and dispatcher.log",
      "The speech groups indexes into mutable, immutable, and transient runtime indexes",
      "It defines three categories: elasticsearch, Solr, and OSGi indexes",
    ],
    explanation:
      "Section 5 says an index falls into three categories: out-of-the-box, customization of an out-of-the-box index, and fully custom.",
  },
  {
    id: "oak-030",
    topic: "Index Names and Simplified Index Management",
    question: "What naming pattern does the speech show for customizing an out-of-the-box index?",
    correctAnswers: [
      "It appends -custom- and a number, as in damAssetLucene-8-custom-1",
      "An OOTB customization ends with -custom- and a version number, for example damAssetLucene-8-custom-1",
      "The speech says a customization name appends -custom- plus a number to the out-of-the-box index",
      "For an out-of-the-box customization, use the base index name with -custom- and a number",
    ],
    incorrectAnswers: [
      "It prefixes custom. and removes the product version, as in custom.damAssetLucene",
      "An OOTB customization ends with -lucene-async and a run mode",
      "The speech says a customization name must replace the base name with request.log",
      "For an out-of-the-box customization, use the base index name with -property-only and no version",
      "It appends -copy- and a date, as in damAssetLucene-copy-2026",
      "An OOTB customization ends with -preview only and no custom suffix",
      "The speech says a customization name must always start with a company prefix and omit the original index name",
      "For an out-of-the-box customization, use the base index name with -elastic-direct",
    ],
    explanation:
      "Section 5 says a customization of an out-of-the-box index appends -custom- and a number, for example damAssetLucene-8-custom-1.",
  },
  {
    id: "oak-031",
    topic: "Index Names and Simplified Index Management",
    question: "How should a fully custom index be named according to the speech?",
    correctAnswers: [
      "It should use a prefix and a dot before the name, and end with -custom- and a version number, such as acme.product-1-custom-2",
      "A fully custom index starts with a prefix plus dot and ends with -custom- and a version number",
      "The speech says fully custom indexes use a prefix to avoid conflicts and still end with -custom- and a version number",
      "For a fully custom index, put a prefix and dot first, then use a name that ends with -custom- and a version number",
    ],
    incorrectAnswers: [
      "It should never use a prefix and should always end with -lucene-async",
      "A fully custom index starts with /oak:index/ and ends with .json only",
      "The speech says fully custom indexes must reuse the exact out-of-the-box name with no suffix",
      "For a fully custom index, put the run mode first and omit any custom version",
      "It should always be named ntBaseLucene-custom with no company prefix",
      "A fully custom index starts with preview. and ends with -receive only",
      "The speech says fully custom indexes must begin with logs. and use no dots afterward",
      "For a fully custom index, put cqPageLucene first and remove all version numbers entirely",
    ],
    explanation:
      "Section 5 says a fully custom index should use a prefix and dot to avoid conflicts and end with -custom- plus a version number.",
  },
  {
    id: "oak-032",
    topic: "Index Names and Simplified Index Management",
    question: "How do you customize an out-of-the-box index in Cloud Service according to the speech?",
    correctAnswers: [
      "Copy its latest definition from a Cloud Service environment using the CRX DE Package Manager, rename it with the custom suffix, and add your changes",
      "The speech says to export the latest definition from Cloud Service with CRX DE Package Manager, rename it with the custom suffix, and then modify it",
      "To customize an OOTB index, copy the latest cloud definition, rename it with -custom-..., and apply your changes",
      "You customize an out-of-the-box index by copying the latest definition from a Cloud Service environment, renaming it with the custom suffix, and adding the required changes",
    ],
    incorrectAnswers: [
      "Edit the running cloud repository directly in Index Manager and save over the original index",
      "The speech says to create a brand-new property index with an unrelated name and ignore the current OOTB definition",
      "To customize an OOTB index, copy request.log into ui.config and change its level",
      "You customize an out-of-the-box index by deleting the original and letting traversal handle the queries",
      "Edit the running cloud repository directly through /system/console and save over the original index",
      "The speech says to create a preview agent filter and that automatically customizes the index",
      "To customize an OOTB index, export the Dispatcher cache docroot and rename it",
      "You customize an out-of-the-box index by copying an author replication agent and changing Retry Delay",
    ],
    explanation:
      "Section 5 says to copy the latest definition from a Cloud Service environment using CRX DE Package Manager, rename it with the custom suffix, and add changes.",
  },
  {
    id: "oak-033",
    topic: "Index Names and Simplified Index Management",
    question: "If the cloud index you copied is of type elasticsearch, what two changes does the speech require?",
    correctAnswers: [
      "Change type to lucene and change async to async and nrt",
      "The speech says convert elasticsearch copies by setting type=lucene and async='async and nrt'",
      "For a copied elasticsearch cloud index, switch the type to lucene and set async to async and nrt",
      "You must change the copied index from elasticsearch to lucene and update async to async and nrt",
    ],
    incorrectAnswers: [
      "Change type to property and change async to sync",
      "The speech says convert elasticsearch copies by setting type=solr and async='fulltext-async only'",
      "For a copied elasticsearch cloud index, switch the type to traversal and remove async entirely",
      "You must change the copied index from elasticsearch to MongoMK and update async to warn",
      "Change type to lucene and change async to false",
      "The speech says convert elasticsearch copies by setting type=request-log and async='debug'",
      "For a copied elasticsearch cloud index, switch the type to property and set async to 'author and publish'",
      "You must change the copied index from elasticsearch to ordered and update async to nrt only",
    ],
    explanation:
      "Section 5 says that if the cloud index is of type elasticsearch, change type to lucene and async to async and nrt.",
  },
  {
    id: "oak-034",
    topic: "Index Names and Simplified Index Management",
    question: "What does the speech say about introducing new full-text indexes on dam:Asset?",
    correctAnswers: [
      "It is strongly discouraged; instead customize damAssetLucene",
      "The speech strongly discourages new full-text indexes on dam:Asset and says to customize damAssetLucene instead",
      "Rather than creating a new full-text index on dam:Asset, customize damAssetLucene",
      "The guidance is to avoid new full-text indexes on dam:Asset and use damAssetLucene customization instead",
    ],
    incorrectAnswers: [
      "It is the recommended first step for every asset customization",
      "The speech strongly encourages a new full-text index on dam:Asset before touching damAssetLucene",
      "Rather than creating a new full-text index on dam:Asset, delete damAssetLucene",
      "The guidance is to create a property index on dam:Asset and ignore Lucene",
      "It is required whenever access.log grows too large",
      "The speech strongly encourages a new full-text index on dam:Asset only for preview",
      "Rather than creating a new full-text index on dam:Asset, switch assets to Traversal Index",
      "The guidance is to create a new full-text index on dam:Asset and name it without any custom suffix",
    ],
    explanation:
      "Section 5 says introducing new full-text indexes on dam:Asset is strongly discouraged and recommends customizing damAssetLucene instead.",
  },
  {
    id: "oak-035",
    topic: "Index Names and Simplified Index Management",
    question: "What is Simplified Index Management, and where does its diff-based configuration live?",
    correctAnswers: [
      "It uses a diff.index so out-of-the-box customizations and custom indexes can be defined with a single diff.json file, stored under _oak_index/diff.index with a placeholder .content.xml and a diff.json file",
      "Simplified Index Management is the diff.index approach, with configuration in _oak_index/diff.index using .content.xml and diff.json",
      "The speech says Simplified Index Management customizes and defines indexes through diff.index, where _oak_index/diff.index contains a placeholder .content.xml and diff.json",
      "It is the single-diff-file approach: _oak_index/diff.index contains the placeholder .content.xml and the diff.json used for merged index definitions",
    ],
    incorrectAnswers: [
      "It stores every index directly in /libs with no diff file and no merging",
      "Simplified Index Management is the request.log rotation model, with configuration in /logs/diff.index",
      "The speech says Simplified Index Management customizes indexes only through OSGi factory configs under /apps",
      "It is the single-diff-file approach in _oak_index/cqPageLucene using only .yaml files",
      "It stores every index directly in /oak:index on the running instance and never uses source control",
      "Simplified Index Management is the CDN JSON logging model, with configuration in /conf/diff.index",
      "The speech says Simplified Index Management customizes indexes only through MongoDB replica commands",
      "It is the single-diff-file approach in _oak_index/diff.index but contains only dispatcher.any and global.var",
    ],
    explanation:
      "Section 5 says Simplified Index Management uses diff.index and a single diff.json under _oak_index/diff.index together with a placeholder .content.xml.",
  },

  // ── 6 LOGGING BASICS AND OSGI CONFIGURATION (7) ─────────────────────────

  {
    id: "oak-036",
    topic: "Logging Basics and OSGi Configuration",
    question: "What is logging in AEM based on, and how is it configured?",
    correctAnswers: [
      "Logging in AEM is based on Sling logging and is configured with OSGi configurations",
      "AEM logging is based on Sling logging and configured through OSGi",
      "The speech says logging in AEM uses Sling logging with OSGi configurations",
      "It is Sling-based logging configured by OSGi configurations",
    ],
    incorrectAnswers: [
      "Logging in AEM is based on Apache access.log only and configured from CRXDE Lite",
      "AEM logging is based on MongoDB journaling and configured through Dispatcher farms",
      "The speech says logging in AEM uses CDN JSON logs with no OSGi configuration",
      "It is TarMK-based logging configured by replication agents",
      "Logging in AEM is based on Lucene analyzers and configured from oak:index nodes",
      "AEM logging is based on Cloud Manager pipelines only and cannot use OSGi",
      "The speech says logging in AEM uses request filters and virtual hosts only",
      "It is Solr-based logging configured by Sling Content Distribution",
    ],
    explanation:
      "Section 6 says logging in AEM is based on Sling logging and configured with OSGi configurations.",
  },
  {
    id: "oak-037",
    topic: "Logging Basics and OSGi Configuration",
    question: "What three logging areas does the speech list?",
    correctAnswers: [
      "Global parameters for the central logging service, request data logging, and settings for individual services",
      "The three areas are central logging service global parameters, request data logging, and individual-service settings",
      "The speech divides logging into global central logging parameters, request data logging, and per-service settings",
      "It lists three areas: central logging service globals, request data logging, and settings for individual services",
    ],
    incorrectAnswers: [
      "Global Dispatcher cache rules, CDN traffic filters, and replication listeners",
      "The three areas are author topology, publish topology, and preview topology",
      "The speech divides logging into Lucene analyzers, property constraints, and traversal warnings",
      "It lists three areas: package filters, Repo Init, and Cloud Manager variables",
      "Global MongoDB settings, Oak segment storage, and TarMK compaction",
      "The three areas are templates, components, and client libraries",
      "The speech divides logging into JQOM, XPath, and SQL-2",
      "It lists three areas: vanity URLs, filters, and render timeouts",
    ],
    explanation:
      "Section 6 names three logging areas: global parameters, request data logging, and settings for individual services.",
  },
  {
    id: "oak-038",
    topic: "Logging Basics and OSGi Configuration",
    question: "What does the Apache Sling Logging Configuration set on the root logger?",
    correctAnswers: [
      "It configures the log level, the location of the central log file, the number of versions to keep, rotation by size or time interval, and the message format",
      "The root logger configuration covers level, central log file location, versions kept, size or time rotation, and message format",
      "The speech says Apache Sling Logging Configuration sets log level, file location, retained versions, rotation, and format",
      "It configures the root logger's level, central file location, number of versions, size-or-time rotation, and message format",
    ],
    incorrectAnswers: [
      "It configures only Lucene tokenization, analyzers, and stemming",
      "The root logger configuration covers only virtual hosts and render hostnames",
      "The speech says Apache Sling Logging Configuration sets replication URI, user, and password",
      "It configures the root logger's queue status, retry delay, and agent user ID",
      "It configures only MongoDB replica members and Author cluster size",
      "The root logger configuration covers only Dispatcher cache docroot and invalidation rules",
      "The speech says Apache Sling Logging Configuration sets only WAF flags and CDN HIT/MISS/PASS values",
      "It configures the root logger's immutableRootNodeNames and vault filters",
    ],
    explanation:
      "Section 6 says the Apache Sling Logging Configuration sets the root logger's level, file location, retained versions, rotation, and message format.",
  },
  {
    id: "oak-039",
    topic: "Logging Basics and OSGi Configuration",
    question: "What three elements does AEM use for logging an individual service?",
    correctAnswers: [
      "An OSGi service writes a message, a Logging Logger formats it, and a Logging Writer writes it to the physical file",
      "The three elements are the OSGi service, the Logging Logger, and the Logging Writer",
      "The speech says an OSGi service emits the message, a Logging Logger formats it, and a Logging Writer writes it",
      "For an individual service, AEM uses an OSGi service, a Logging Logger, and a Logging Writer",
    ],
    incorrectAnswers: [
      "A replication agent writes a message, a Dispatcher farm formats it, and a CDN edge writes it to disk",
      "The three elements are the Index Manager, CRX Package Manager, and Cloud Manager build page",
      "The speech says an Author instance emits the message, a Publish instance formats it, and Preview writes it",
      "For an individual service, AEM uses a QueryBuilder servlet, a Lucene analyzer, and a property index",
      "A workflow launcher writes a message, a Tree Activation step formats it, and Dispatcher writes it to disk",
      "The three elements are request.log, access.log, and error.log only",
      "The speech says a TarMK segment emits the message, MongoMK formats it, and Oak-run writes it",
      "For an individual service, AEM uses a virtual host, a render, and a filter rule",
    ],
    explanation:
      "Section 6 describes three elements for service logging: the OSGi service, the Logging Logger, and the Logging Writer.",
  },
  {
    id: "oak-040",
    topic: "Logging Basics and OSGi Configuration",
    question: "How are a Logger and a Writer linked, and what happens if there is no match?",
    correctAnswers: [
      "The Log File parameter links them and the values must be identical; if there is no match, an implicit writer is created with default configuration and daily rotation",
      "Logger and Writer are linked by matching Log File values, and a mismatch creates an implicit writer with default settings and daily rotation",
      "The speech says the Log File value must be identical on Logger and Writer; otherwise AEM creates an implicit writer with defaults and daily rotation",
      "They are connected through the Log File parameter, and if the values do not match an implicit default writer with daily rotation is created",
    ],
    incorrectAnswers: [
      "They are linked by Retry Delay, and a mismatch creates a blocked replication queue",
      "Logger and Writer are linked by the /docroot path, and a mismatch disables request logging",
      "The speech says the Log File value may differ intentionally, and otherwise Lucene full-text search stops working",
      "They are connected through the virtual host, and if the values do not match Dispatcher creates a farm",
      "They are linked by the node type oak:QueryIndexDefinition, and a mismatch starts reindexing",
      "Logger and Writer are linked by the CDN cache status, and a mismatch creates PASS responses",
      "The speech says the Log File value must be blank, and otherwise a Solr writer is created",
      "They are connected through org.apache.sling.commons.log.level only, and if the values do not match nothing is written",
    ],
    explanation:
      "Section 6 says the Log File parameter links Logger and Writer, the values must match, and otherwise an implicit default writer with daily rotation is created.",
  },
  {
    id: "oak-041",
    topic: "Logging Basics and OSGi Configuration",
    question: "Why might you route one service's messages into a separate log file?",
    correctAnswers: [
      "It helps during development when you need a higher log level for a single service",
      "The speech says a separate file is useful when one service needs a higher log level during development",
      "You route one service into its own file to isolate it, for example to raise only that service's log level during development",
      "A separate service log helps during development when only one service needs more verbose logging",
    ],
    incorrectAnswers: [
      "It is required because request.log can store only one message per hour",
      "The speech says a separate file is useful only for changing MongoMK topology",
      "You route one service into its own file so Cloud Manager can bypass the pipeline",
      "A separate service log is needed only to enable reverse replication",
      "It is required because access.log cannot exist together with error.log",
      "The speech says a separate file is useful only for configuring custom analyzers",
      "You route one service into its own file so Dispatcher can choose the farm",
      "A separate service log is needed only to make XPath queries run natively",
    ],
    explanation:
      "Section 6 says separate service log files help during development, for example when only one service needs a higher log level.",
  },
  {
    id: "oak-042",
    topic: "Logging Basics and OSGi Configuration",
    question: "On the AEM 6.5 side, which three main log files does the speech name?",
    correctAnswers: [
      "error.log, request.log, and access.log",
      "The three main 6.5 log files named are error.log, request.log, and access.log",
      "The speech names error.log, request.log, and access.log on the 6.5 side",
      "On 6.5, the main files listed are error.log, request.log, and access.log",
    ],
    incorrectAnswers: [
      "dispatcher.log, cdn.log, and rewrite.log",
      "The three main 6.5 log files named are package.log, author.log, and publish.log",
      "The speech names oak.log, mongo.log, and tarmk.log on the 6.5 side",
      "On 6.5, the main files listed are logs/error.log, logs/request.log, and logs/access.log only in the cloud section",
      "global.var, dispatcher.any, and httpd.conf",
      "The three main 6.5 log files named are preview.log, traffic.log, and queue.log",
      "The speech names cqPageLucene.log, damAssetLucene.log, and ntBaseLucene.log on the 6.5 side",
      "On 6.5, the main files listed are waf.log, miss.log, and pass.log",
    ],
    explanation:
      "Section 6 says the main AEM 6.5 files are error.log, request.log, and access.log.",
  },

  // ── 7 CLOUD SERVICE LOGS (8) ────────────────────────────────────────────

  {
    id: "oak-043",
    topic: "Cloud Service Logs",
    question: "How are log settings and levels managed in AEM as a Cloud Service?",
    correctAnswers: [
      "They are configuration files stored in Git and deployed by Cloud Manager",
      "Cloud Service log settings and levels live in configuration files in Git and are deployed through Cloud Manager",
      "The speech says logging configuration is stored in Git and deployed by Cloud Manager",
      "In Cloud Service, log levels and settings are managed as Git-based configuration deployed by Cloud Manager",
    ],
    incorrectAnswers: [
      "They are changed directly on running instances through the Index Manager",
      "Cloud Service log settings and levels live only in access.log comments and are deployed through Dispatcher",
      "The speech says logging configuration is stored only in MongoDB and not in Git",
      "In Cloud Service, log levels and settings are managed from the Author page editor",
      "They are changed only by tailing logs through Adobe I/O CLI",
      "Cloud Service log settings and levels live only in CRXDE Lite packages on production nodes",
      "The speech says logging configuration is stored in CDN headers and not deployed",
      "In Cloud Service, log levels and settings are managed only by SREs with no code files",
    ],
    explanation:
      "Section 7 says Cloud Service log settings and levels are configuration files stored in Git and deployed by Cloud Manager.",
  },
  {
    id: "oak-044",
    topic: "Cloud Service Logs",
    question: "What three logging sets does the speech say Cloud Service breaks into?",
    correctAnswers: [
      "AEM application logging, Apache HTTPD web server and Dispatcher logging, and CDN logging",
      "The three sets are AEM application logs, Apache HTTPD plus Dispatcher logs, and CDN logs",
      "The speech breaks Cloud Service logging into AEM application logging, Apache HTTPD/Dispatcher logging, and CDN logging",
      "Cloud Service logging is divided into AEM application, Apache HTTPD and Dispatcher, and CDN",
    ],
    incorrectAnswers: [
      "Authoring logs, translation logs, and content fragment logs",
      "The three sets are Oak indexes, replication queues, and TarMK compaction logs",
      "The speech breaks Cloud Service logging into only request.log and access.log",
      "Cloud Service logging is divided into Lucene logs, SQL-2 logs, and XPath logs",
      "Dispatcher filters, virtual hosts, and renders",
      "The three sets are preview, stage, and prod logs only",
      "The speech breaks Cloud Service logging into OSGi configs, Maven POMs, and package filters",
      "Cloud Service logging is divided into CRXDE logs, Package Manager logs, and Repo Init logs",
    ],
    explanation:
      "Section 7 says Cloud Service logging breaks into AEM application logging, Apache HTTPD plus Dispatcher logging, and CDN logging.",
  },
  {
    id: "oak-045",
    topic: "Cloud Service Logs",
    question: "Which three AEM application logs are named, and what requests do not appear in them?",
    correctAnswers: [
      "The AEM Java log, the HTTP request log, and the HTTP access log; requests served from the Dispatcher cache or an upstream CDN do not appear in them",
      "The three AEM application logs are Java, HTTP request, and HTTP access, and cache- or CDN-served requests do not show up there",
      "The speech names the AEM Java log, HTTP request log, and HTTP access log, and says Dispatcher-cache or upstream-CDN hits are absent from them",
      "AEM application logging includes the Java log, request log, and access log, and requests answered by Dispatcher cache or an upstream CDN are not in those logs",
    ],
    incorrectAnswers: [
      "The AEM Java log, the Dispatcher log, and the CDN log; requests served from the cache always appear in all three",
      "The three AEM application logs are Java, request, and access, and they also include every CDN HIT automatically",
      "The speech names the AEM Java log, Apache error log, and rewrite log, and says cache-served requests appear only there",
      "AEM application logging includes the Java log, request log, and access log, and requests answered by Dispatcher cache are duplicated in them",
      "The AEM Java log, the preview log, and the publish queue log; requests served from cache appear with PASS only",
      "The three AEM application logs are Lucene, Property, and Traversal, and cache-served requests are indexed there",
      "The speech names the AEM Java log, Tree Activation log, and replication status log, and says CDN requests appear with node traversal counts",
      "AEM application logging includes the Java log, request log, and access log, and requests answered earlier in the chain always appear there first",
    ],
    explanation:
      "Section 7 names the AEM Java, HTTP request, and HTTP access logs and says Dispatcher-cache or upstream-CDN-served requests do not appear in them.",
  },
  {
    id: "oak-046",
    topic: "Cloud Service Logs",
    question: "How are Java log levels configured per environment type in Cloud Service?",
    correctAnswers: [
      "Through OSGi configuration in run mode folders: config for development, config.stage, and config.prod, using the Sling LogManager factory configuration",
      "The speech says Java log levels are set by OSGi configs in config, config.stage, and config.prod via the Sling LogManager factory configuration",
      "Use run mode folders config, config.stage, and config.prod with Sling LogManager factory configuration to set Java log levels",
      "Per-environment Java log levels are configured in OSGi run mode folders named config, config.stage, and config.prod using Sling LogManager factory config",
    ],
    incorrectAnswers: [
      "Through Dispatcher variables in global.var: config.dev, config.qa, and config.live",
      "The speech says Java log levels are set only from Cloud Manager UI toggles and not by OSGi configs",
      "Use run mode folders author, publish, and preview with replication agents to set Java log levels",
      "Per-environment Java log levels are configured in oak:index through diff.json only",
      "Through CDN rules in waf.json: config, config.stage, and config.prod",
      "The speech says Java log levels are set only by editing logs/error.log on each pod",
      "Use run mode folders config.debug, config.warn, and config.error with Lucene analyzers to set Java log levels",
      "Per-environment Java log levels are configured in request.log through bracket IDs",
    ],
    explanation:
      "Section 7 says Java log levels are configured through OSGi configuration in config, config.stage, and config.prod using the Sling LogManager factory configuration.",
  },
  {
    id: "oak-047",
    topic: "Cloud Service Logs",
    question: "Which Sling LogManager factory properties does the speech say to use for package names and level, and what levels are recommended by environment?",
    correctAnswers: [
      "Use org.apache.sling.commons.log.names for the Java packages and org.apache.sling.commons.log.level for the level; recommended levels are debug on development, warn on stage, and error on production",
      "The speech says package names go in org.apache.sling.commons.log.names and the level in org.apache.sling.commons.log.level, with debug for dev, warn for stage, and error for prod",
      "Use org.apache.sling.commons.log.names plus org.apache.sling.commons.log.level, and set debug in development, warn in stage, and error in production",
      "For Cloud Service Java logging, use org.apache.sling.commons.log.names and org.apache.sling.commons.log.level, with recommended levels debug, warn, and error for development, stage, and production respectively",
    ],
    incorrectAnswers: [
      "Use org.apache.sling.commons.log.file for the Java packages and org.apache.sling.commons.log.pattern for the level; recommended levels are info everywhere",
      "The speech says package names go in org.apache.sling.commons.log.level and the level in org.apache.sling.commons.log.names, with warn for dev, debug for stage, and error for prod",
      "Use org.apache.sling.commons.log.names plus org.apache.sling.commons.log.pattern, and set trace8 in development, info in stage, and debug in production",
      "For Cloud Service Java logging, use org.apache.sling.commons.log.file and org.apache.sling.commons.log.names, with recommended levels pass, miss, and hit",
      "Use dispatcher.log.level for the Java packages and REWRITE_LOG_LEVEL for the level; recommended levels are debug everywhere",
      "The speech says package names go in org.apache.sling.commons.log.writer and the level in org.apache.sling.commons.log.reader, with error for dev, warn for stage, and debug for prod",
      "Use org.apache.sling.commons.log.names plus org.apache.sling.commons.log.level, and set error in development, warn in stage, and debug in production",
      "For Cloud Service Java logging, use org.apache.sling.commons.log.pattern and org.apache.sling.commons.log.file, with recommended levels info, info, and info",
    ],
    explanation:
      "Section 7 names org.apache.sling.commons.log.names and org.apache.sling.commons.log.level and recommends debug for development, warn for stage, and error for production.",
  },
  {
    id: "oak-048",
    topic: "Cloud Service Logs",
    question: "What must you not change on the default Apache Sling Logging Configuration in Cloud Service?",
    correctAnswers: [
      "Do not change its default INFO level, its format, or the default file destination logs/error.log",
      "The speech says not to change the default INFO level, not to change the format, and not to move output from logs/error.log",
      "You must leave the default INFO level, the format, and the logs/error.log destination unchanged",
      "Cloud Service guidance says the root logging configuration must keep INFO, keep the format, and keep writing to logs/error.log",
    ],
    incorrectAnswers: [
      "Do not change the request log bracket IDs, the access log size field, or the CDN JSON schema",
      "The speech says to change the default INFO level to DEBUG in production and move output to logs/request.log",
      "You must leave the replication retry delay, dispatcher farm name, and MongoDB latency unchanged",
      "Cloud Service guidance says the root logging configuration must change to WARN, use a custom pattern, and write to a new file",
      "Do not change the Lucene analyzers, oak:index node type, or custom suffix naming",
      "The speech says to change the default INFO level to ERROR everywhere and move output to access.log",
      "You must leave only the request log configurable and freely change the Java log destination",
      "Cloud Service guidance says the root logging configuration must move output to dispatcher.log and enable daily custom patterns",
    ],
    explanation:
      "Section 7 says not to change the default INFO level, not to change the format, and not to change the logs/error.log destination.",
  },
  {
    id: "oak-049",
    topic: "Cloud Service Logs",
    question: "How does the HTTP request log differ from the HTTP access log in the speech?",
    correctAnswers: [
      "The request log pairs requests and responses by the numeric ID in brackets, while the access log shows requests in time order with status code and size and helps follow a specific user",
      "Request log entries are paired by bracketed numeric ID, whereas access log entries are time-ordered with status and size for following a user",
      "The speech says the request log uses the numeric ID in brackets to pair request and response, while the access log lists requests chronologically with status code and size",
      "The request log is for pairing request and response by bracket ID, and the access log is for time order, status code, size, and following a user",
    ],
    incorrectAnswers: [
      "The request log is configurable in the cloud, while the access log is where custom analyzers are defined",
      "Request log entries contain only CDN HIT/MISS/PASS, whereas access log entries contain Lucene token streams",
      "The speech says the request log lists farm miss/none actions, while the access log stores replication queue states",
      "The request log is for topology licensing, and the access log is for TarMK standby status",
      "The request log is the Apache web server error log, while the access log is the Dispatcher log",
      "Request log entries are paired by custom prefixes, whereas access log entries store only rewrite trace levels",
      "The speech says the request log follows a specific user, while the access log pairs requests and responses by bracket ID",
      "The request log is configurable through global.var, while the access log is configurable through diff.index",
    ],
    explanation:
      "Section 7 says the request log pairs requests and responses by the numeric bracket ID, while the access log shows requests in time order with status and size and helps follow a user.",
  },
  {
    id: "oak-050",
    topic: "Cloud Service Logs",
    question: "What does the speech say about CDN logs in Cloud Service?",
    correctAnswers: [
      "The CDN log is JSON, cannot be customized or set to different modes, shows fields such as timestamp, ttfb, status, url, and cache with HIT, MISS, or PASS, and is useful for cache-hit optimization and seeing matched traffic filter and WAF flags",
      "CDN logs are in JSON format, are not customizable, include fields like timestamp, ttfb, status, url, and cache values HIT, MISS, and PASS, and help with cache-hit optimization plus matched traffic filter and WAF flags",
      "The speech says the CDN log cannot be customized, is JSON, records fields such as timestamp, ttfb, status, url, and cache HIT/MISS/PASS, and also records matched traffic filter rules and WAF flags",
      "In Cloud Service, the CDN log is a non-customizable JSON log showing timestamp, ttfb, status, url, cache as HIT/MISS/PASS, and matched traffic-filter and WAF information",
    ],
    incorrectAnswers: [
      "The CDN log is plain text, fully customizable, and is where Java package levels are configured",
      "CDN logs are stored only in request.log format, include node traversal counts, and cannot show cache outcomes",
      "The speech says the CDN log is an OSGi factory config file that writes only to logs/error.log",
      "In Cloud Service, the CDN log is a Lucene index definition used for full-text search",
      "The CDN log is plain text, fully customizable per environment, and stores only rewrite rule trace output",
      "CDN logs are stored only in access.log format, include replication queue states, and cannot show WAF flags",
      "The speech says the CDN log is a CRX package export used to rename out-of-the-box indexes",
      "In Cloud Service, the CDN log is a MongoDB replica-set report for Author clusters",
    ],
    explanation:
      "Section 7 says the CDN log is JSON, not customizable, shows fields like timestamp, ttfb, status, url, and cache HIT/MISS/PASS, and records matched traffic filter rules and WAF flags.",
  },
]
